import type { IntentTemplate } from "./meeting-scheduler-types";

export const AGENDA_CATEGORIES = [
  { value: "economic", label: "Economic affairs", color: "bg-green" },
  { value: "social", label: "Social policy", color: "bg-blue" },
  { value: "infrastructure", label: "Infrastructure", color: "bg-yellow" },
  { value: "diplomatic", label: "Diplomatic relations", color: "bg-cyan" },
  { value: "governance", label: "Governance and administration", color: "bg-indigo" },
  { value: "other", label: "Other", color: "bg-fill" },
];

export const INTENT_TEMPLATES: IntentTemplate[] = [
  {
    id: "crisis",
    name: "Resolve crisis",
    description: "Convene to address an urgent national issue or emergency.",
    meetingType: "cabinet",
    defaultTitle: "Emergency cabinet session",
    defaultDuration: 45,
    recommendedRoles: ["chief", "security", "defense", "interior", "prime"],
    agenda: [
      {
        title: "Situation briefing",
        description: "Assess the immediate threat and core parameters of the crisis.",
        duration: 15,
        category: "governance",
        tags: ["urgent", "crisis"],
        presenter: "Ruler",
      },
      {
        title: "Mitigation options evaluation",
        description: "Review proposed response strategies and public impact projections.",
        duration: 20,
        category: "governance",
        tags: ["strategic"],
        presenter: "Cabinet Chief",
      },
      {
        title: "Executive action declaration",
        description: "Final vote on crisis response and communication strategy.",
        duration: 10,
        category: "governance",
        tags: ["reform"],
        presenter: "Ruler",
      },
    ],
  },
  {
    id: "economic",
    name: "Economic policy briefing",
    description: "Draft policies, review budget status, and tax reform proposals.",
    meetingType: "cabinet",
    defaultTitle: "Economic planning summit",
    defaultDuration: 60,
    recommendedRoles: ["finance", "treasury", "commerce", "economy"],
    agenda: [
      {
        title: "Treasury and reserves audit",
        description: "Review active policy maintenance costs and national liquidity.",
        duration: 20,
        category: "economic",
        tags: ["budget", "quarterly"],
        presenter: "Finance Minister",
      },
      {
        title: "Reform proposal review",
        description: "Evaluate target economic sector indicators and draft policies.",
        duration: 30,
        category: "economic",
        tags: ["policy", "reform"],
        presenter: "Commerce Minister",
      },
      {
        title: "Implementation timeline",
        description: "Authorize next-step resource disbursements.",
        duration: 10,
        category: "economic",
        tags: ["strategic"],
        presenter: "Ruler",
      },
    ],
  },
  {
    id: "social",
    name: "Social welfare policy",
    description: "Discuss education, healthcare, and demographic/population growth programs.",
    meetingType: "cabinet",
    defaultTitle: "Social policy review",
    defaultDuration: 60,
    recommendedRoles: ["health", "education", "social", "labor"],
    agenda: [
      {
        title: "Demographic trends assessment",
        description: "Examine birth rates, demographic health stats, and growth programs.",
        duration: 15,
        category: "social",
        tags: ["quarterly", "review"],
        presenter: "Health Minister",
      },
      {
        title: "Welfare and education budget allocation",
        description: "Determine education and healthcare grants and system funding.",
        duration: 25,
        category: "social",
        tags: ["budget", "policy"],
        presenter: "Education Minister",
      },
      {
        title: "Social wellbeing targets",
        description: "Set timeline for national approval and wellbeing objectives.",
        duration: 10,
        category: "social",
        tags: ["strategic"],
        presenter: "Ruler",
      },
    ],
  },
  {
    id: "infrastructure",
    name: "Infrastructure and development",
    description: "Plan national transport, energy grids, and environmental preservation.",
    meetingType: "cabinet",
    defaultTitle: "Infrastructure council session",
    defaultDuration: 60,
    recommendedRoles: ["infrastructure", "transport", "environment", "energy"],
    agenda: [
      {
        title: "Capital project audits",
        description: "Evaluate pipeline, transit network, and public utilities efficiency.",
        duration: 20,
        category: "infrastructure",
        tags: ["operational", "budget"],
        presenter: "Infrastructure Minister",
      },
      {
        title: "Environmental preservation initiatives",
        description: "Implement climate compliance guidelines and clean energy transitions.",
        duration: 20,
        category: "infrastructure",
        tags: ["policy", "reform"],
        presenter: "Environment Minister",
      },
      {
        title: "Treasury funding clearances",
        description: "Approve long-term infrastructural investment funds.",
        duration: 10,
        category: "economic",
        tags: ["budget"],
        presenter: "Finance Minister",
      },
    ],
  },
  {
    id: "governance",
    name: "Legislative and civil strategy",
    description: "Appoint cabinet positions, prepare elections, and review civil efficiency.",
    meetingType: "cabinet",
    defaultTitle: "Governance strategy briefing",
    defaultDuration: 60,
    recommendedRoles: ["chief", "interior", "prime", "justice"],
    agenda: [
      {
        title: "Ministerial coordination review",
        description: "Review cabinet minister performance metrics and departmental efficiency.",
        duration: 20,
        category: "governance",
        tags: ["review", "operational"],
        presenter: "Cabinet Chief",
      },
      {
        title: "Legislative calendar alignment",
        description: "Plan draft law rollouts and parliament/senate coordination.",
        duration: 15,
        category: "governance",
        tags: ["policy"],
        presenter: "Interior Minister",
      },
      {
        title: "Election security and prep",
        description: "Confirm constituency boundaries, voting logs, and security protocols.",
        duration: 15,
        category: "governance",
        tags: ["strategic"],
        presenter: "Interior Minister",
      },
    ],
  },
  {
    id: "bilateral",
    name: "Bilateral trade and diplomacy",
    description: "Request a summit with another nation's leadership.",
    meetingType: "bilateral",
    defaultTitle: "Bilateral summit",
    defaultDuration: 90,
    recommendedRoles: ["foreign", "diplomacy", "ambassador"],
    agenda: [
      {
        title: "Bilateral alignment review",
        description: "Assess diplomatic stance, embassy statuses, and treaty records.",
        duration: 30,
        category: "diplomatic",
        tags: ["strategic", "review"],
        presenter: "Foreign Minister",
      },
      {
        title: "Joint venture proposals",
        description: "Negotiate trade corridors, security pacts, or territorial access.",
        duration: 45,
        category: "diplomatic",
        tags: ["strategic"],
        presenter: "Guest Delegate",
      },
      {
        title: "Treaty approvals",
        description: "Execute treaty drafts and plan public press releases.",
        duration: 15,
        category: "diplomatic",
        tags: ["urgent"],
        presenter: "Ruler",
      },
    ],
  },
  {
    id: "routine",
    name: "Routine cabinet review",
    description: "General administration review and progress synchronization.",
    meetingType: "cabinet",
    defaultTitle: "Weekly cabinet review",
    defaultDuration: 30,
    recommendedRoles: [],
    agenda: [
      {
        title: "Department status reports",
        description: "Brief updates from all active ministries.",
        duration: 15,
        category: "governance",
        tags: ["operational"],
        presenter: "Cabinet Chief",
      },
      {
        title: "Agenda priorities alignment",
        description: "Identify next target issues and schedule future proceedings.",
        duration: 15,
        category: "governance",
        tags: ["strategic"],
        presenter: "Ruler",
      },
    ],
  },
];
