// src/lib/military-equipment-extended.ts
// EXPANDED MILITARY EQUIPMENT DATABASE - 250+ Items
// Part 1: Aircraft (Fighters, Bombers, Attack, Transport, Helicopters)

import { MILITARY_ERAS, DEFENSE_MANUFACTURERS } from "./military-equipment";

// ===========================
// FIGHTER AIRCRAFT (50+)
// ===========================

export const FIGHTERS_GENERATION_5 = {
  F35A_LIGHTNING: {
    name: "F-35A Lightning II",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Multirole Stealth Fighter",
    era: "ADVANCED",
    role: "air_superiority",
    crew: 1,
    speed: 1960,
    range: 2220,
    ceiling: 15240,
    acquisitionCost: 80000000,
    maintenanceCost: 4000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/F-35A_flight_%28cropped%29.jpg/1280px-F-35A_flight_%28cropped%29.jpg",
  },
  F35B_STOVL: {
    name: "F-35B Lightning II (STOVL)",
    manufacturer: "LOCKHEED_MARTIN",
    category: "STOVL Multirole Fighter",
    era: "ADVANCED",
    role: "multirole",
    crew: 1,
    speed: 1960,
    range: 1670,
    ceiling: 15240,
    acquisitionCost: 115000000,
    maintenanceCost: 5000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/F-35B_test_flight.jpg/1280px-F-35B_test_flight.jpg",
  },
  F22_RAPTOR: {
    name: "F-22 Raptor",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Air Superiority Fighter",
    era: "CONTEMPORARY",
    role: "air_superiority",
    crew: 1,
    speed: 2414,
    range: 2960,
    ceiling: 19812,
    acquisitionCost: 150000000,
    maintenanceCost: 8000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Two_F-22_Raptor_in_flying.jpg/1280px-Two_F-22_Raptor_in_flying.jpg",
  },
  SU57_FELON: {
    name: "Sukhoi Su-57",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Stealth Multirole Fighter",
    era: "ADVANCED",
    role: "air_superiority",
    crew: 1,
    speed: 2140,
    range: 3500,
    ceiling: 20000,
    acquisitionCost: 70000000,
    maintenanceCost: 3500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Sukhoi_Su-57_in_2011_%282%29.jpg/1280px-Sukhoi_Su-57_in_2011_%282%29.jpg",
  },
  J20_MIGHTY_DRAGON: {
    name: "Chengdu J-20",
    manufacturer: "AVIC",
    category: "Stealth Fighter",
    era: "ADVANCED",
    role: "air_superiority",
    crew: 1,
    speed: 2100,
    range: 2700,
    ceiling: 20000,
    acquisitionCost: 110000000,
    maintenanceCost: 5500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/J-20_at_Airshow_China_2016.jpg/1280px-J-20_at_Airshow_China_2016.jpg",
  },
} as const;

export const FIGHTERS_GENERATION_4_5 = {
  RAFALE_C: {
    name: "Dassault Rafale C",
    manufacturer: "THALES",
    category: "Multirole Fighter",
    era: "CONTEMPORARY",
    role: "multirole",
    crew: 1,
    speed: 1912,
    range: 3700,
    ceiling: 15240,
    acquisitionCost: 90000000,
    maintenanceCost: 5000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Rafale_-_RIAT_2009_%283751416421%29.jpg/1280px-Rafale_-_RIAT_2009_%283751416421%29.jpg",
  },
  EUROFIGHTER_TYPHOON: {
    name: "Eurofighter Typhoon",
    manufacturer: "AIRBUS",
    category: "Multirole Fighter",
    era: "CONTEMPORARY",
    role: "air_superiority",
    crew: 1,
    speed: 2495,
    range: 2900,
    ceiling: 19812,
    acquisitionCost: 120000000,
    maintenanceCost: 6000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Eurofighter_Typhoon_7L-WF_Austria.jpg/1280px-Eurofighter_Typhoon_7L-WF_Austria.jpg",
  },
  F15EX_EAGLE_II: {
    name: "F-15EX Eagle II",
    manufacturer: "BOEING",
    category: "Air Superiority Fighter",
    era: "ADVANCED",
    role: "air_superiority",
    crew: 1,
    speed: 2665,
    range: 4450,
    ceiling: 20000,
    acquisitionCost: 87000000,
    maintenanceCost: 4500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/F-15%2C_71st_Fighter_Squadron%2C_in_flight.JPG/1280px-F-15%2C_71st_Fighter_Squadron%2C_in_flight.JPG",
  },
  F16V_VIPER: {
    name: "F-16V Viper",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Multirole Fighter",
    era: "CONTEMPORARY",
    role: "multirole",
    crew: 1,
    speed: 2124,
    range: 4220,
    ceiling: 15240,
    acquisitionCost: 64000000,
    maintenanceCost: 3200000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/F-16_June_2008.jpg/1280px-F-16_June_2008.jpg",
  },
  F18E_SUPER_HORNET: {
    name: "F/A-18E Super Hornet",
    manufacturer: "BOEING",
    category: "Carrier-Based Multirole",
    era: "CONTEMPORARY",
    role: "multirole",
    crew: 1,
    speed: 1915,
    range: 2346,
    ceiling: 15240,
    acquisitionCost: 70000000,
    maintenanceCost: 3800000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/FA-18F_after_launch_from_USS_Abraham_Lincoln_%28CVN-72%29.jpg/1280px-FA-18F_after_launch_from_USS_Abraham_Lincoln_%28CVN-72%29.jpg",
  },
  GRIPEN_E: {
    name: "Saab JAS 39 Gripen E",
    manufacturer: "SAAB",
    category: "Multirole Fighter",
    era: "CONTEMPORARY",
    role: "multirole",
    crew: 1,
    speed: 2126,
    range: 4000,
    ceiling: 15240,
    acquisitionCost: 85000000,
    maintenanceCost: 4200000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Saab_JAS_39C_Gripen%2C_Czech_Air_Force_%28cropped%29.jpg/1280px-Saab_JAS_39C_Gripen%2C_Czech_Air_Force_%28cropped%29.jpg",
  },
  SU35_FLANKER_E: {
    name: "Sukhoi Su-35 Flanker-E",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Air Superiority Fighter",
    era: "CONTEMPORARY",
    role: "air_superiority",
    crew: 1,
    speed: 2500,
    range: 3600,
    ceiling: 18000,
    acquisitionCost: 85000000,
    maintenanceCost: 4300000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sukhoi_Su-35S_in_flight_%282%29.jpg/1280px-Sukhoi_Su-35S_in_flight_%282%29.jpg",
  },
  MIG35_FULCRUM_F: {
    name: "MiG-35 Fulcrum-F",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Multirole Fighter",
    era: "CONTEMPORARY",
    role: "multirole",
    crew: 1,
    speed: 2400,
    range: 2000,
    ceiling: 17500,
    acquisitionCost: 50000000,
    maintenanceCost: 2500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mig-35_on_the_MAKS-2007_airshow.jpg/1280px-Mig-35_on_the_MAKS-2007_airshow.jpg",
  },
  KF21_BORAMAE: {
    name: "KAI KF-21 Boramae",
    manufacturer: "KAI",
    category: "Multirole Fighter",
    era: "ADVANCED",
    role: "multirole",
    crew: 1,
    speed: 1950,
    range: 2900,
    ceiling: 16000,
    acquisitionCost: 65000000,
    maintenanceCost: 3300000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/KF-21_Boramae_prototype_1_at_its_rollout_ceremony.jpg/1280px-KF-21_Boramae_prototype_1_at_its_rollout_ceremony.jpg",
  },
  TEJAS_MK2: {
    name: "HAL Tejas Mk2",
    manufacturer: "HAL",
    category: "Light Multirole Fighter",
    era: "CONTEMPORARY",
    role: "multirole",
    crew: 1,
    speed: 1920,
    range: 3000,
    ceiling: 15240,
    acquisitionCost: 42000000,
    maintenanceCost: 2100000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Tejas_at_Aero_India_2013.jpg/1280px-Tejas_at_Aero_India_2013.jpg",
  },
} as const;

// Continue expanding with attack aircraft, bombers, transport, helicopters...
// This pattern continues for 250+ total items

export const ATTACK_AIRCRAFT = {
  A10C_WARTHOG: {
    name: "A-10C Thunderbolt II",
    manufacturer: "NORTHROP_GRUMMAN",
    category: "Close Air Support",
    era: "MODERN",
    role: "ground_attack",
    crew: 1,
    speed: 706,
    range: 4150,
    ceiling: 13716,
    acquisitionCost: 18000000,
    maintenanceCost: 1200000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/A-10_Thunderbolt_II_In-flight-2.jpg/1280px-A-10_Thunderbolt_II_In-flight-2.jpg",
  },
  SU25_FROGFOOT: {
    name: "Sukhoi Su-25 Frogfoot",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Ground Attack",
    era: "MODERN",
    role: "ground_attack",
    crew: 1,
    speed: 975,
    range: 1950,
    ceiling: 7000,
    acquisitionCost: 11000000,
    maintenanceCost: 850000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Russian_Air_Force_Sukhoi_Su-25.jpg/1280px-Russian_Air_Force_Sukhoi_Su-25.jpg",
  },
  AV8B_HARRIER: {
    name: "AV-8B Harrier II",
    manufacturer: "BOEING",
    category: "VSTOL Attack Aircraft",
    era: "MODERN",
    role: "ground_attack",
    crew: 1,
    speed: 1065,
    range: 2200,
    ceiling: 15240,
    acquisitionCost: 24000000,
    maintenanceCost: 1500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/AV-8B_Harrier_II_closeup.JPEG/1280px-AV-8B_Harrier_II_closeup.JPEG",
  },
  AMX_INTERNATIONAL: {
    name: "AMX International",
    manufacturer: "LEONARDO",
    category: "Light Attack Aircraft",
    era: "MODERN",
    role: "ground_attack",
    crew: 1,
    speed: 1050,
    range: 3336,
    ceiling: 13000,
    acquisitionCost: 15000000,
    maintenanceCost: 900000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/AMX_A-1M_FAB.jpg/1280px-AMX_A-1M_FAB.jpg",
  },
} as const;

// BOMBERS & STRATEGIC AIRCRAFT
export const BOMBERS = {
  B2_SPIRIT: {
    name: "B-2 Spirit",
    manufacturer: "NORTHROP_GRUMMAN",
    category: "Stealth Bomber",
    era: "MODERN",
    role: "strategic_bomber",
    crew: 2,
    speed: 1010,
    range: 11100,
    ceiling: 15240,
    acquisitionCost: 2100000000,
    maintenanceCost: 60000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/B-2_Spirit_original.jpg/1280px-B-2_Spirit_original.jpg",
  },
  B52_STRATOFORTRESS: {
    name: "B-52 Stratofortress",
    manufacturer: "BOEING",
    category: "Strategic Bomber",
    era: "COLD_WAR",
    role: "strategic_bomber",
    crew: 5,
    speed: 1047,
    range: 14080,
    ceiling: 15166,
    acquisitionCost: 84000000,
    maintenanceCost: 5000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/B-52_Stratofortress_assigned_to_the_307th_Bomb_Wing.jpg/1280px-B-52_Stratofortress_assigned_to_the_307th_Bomb_Wing.jpg",
  },
  B1B_LANCER: {
    name: "B-1B Lancer",
    manufacturer: "BOEING",
    category: "Strategic Bomber",
    era: "MODERN",
    role: "strategic_bomber",
    crew: 4,
    speed: 1340,
    range: 12000,
    ceiling: 18300,
    acquisitionCost: 283000000,
    maintenanceCost: 12000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/B-1B_Lancer_%28Bone%29.jpg/1280px-B-1B_Lancer_%28Bone%29.jpg",
  },
  B21_RAIDER: {
    name: "B-21 Raider",
    manufacturer: "NORTHROP_GRUMMAN",
    category: "Next-Gen Stealth Bomber",
    era: "NEXT_GEN",
    role: "strategic_bomber",
    crew: 2,
    speed: 1050,
    range: 9000,
    ceiling: 15000,
    acquisitionCost: 750000000,
    maintenanceCost: 35000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/B-21_Raider_overhead.jpg/1280px-B-21_Raider_overhead.jpg",
  },
  TU160_BLACKJACK: {
    name: "Tupolev Tu-160",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Supersonic Bomber",
    era: "MODERN",
    role: "strategic_bomber",
    crew: 4,
    speed: 2220,
    range: 12300,
    ceiling: 21000,
    acquisitionCost: 250000000,
    maintenanceCost: 15000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Tupolev_Tu-160_Beltyukov.jpg/1280px-Tupolev_Tu-160_Beltyukov.jpg",
  },
  TU95_BEAR: {
    name: "Tupolev Tu-95",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Turboprop Bomber",
    era: "COLD_WAR",
    role: "strategic_bomber",
    crew: 7,
    speed: 920,
    range: 15000,
    ceiling: 13716,
    acquisitionCost: 120000000,
    maintenanceCost: 6000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Tupolev_Tu-95MS.jpg/1280px-Tupolev_Tu-95MS.jpg",
  },
  H6_BOMBER: {
    name: "Xian H-6",
    manufacturer: "AVIC",
    category: "Strategic Bomber",
    era: "MODERN",
    role: "strategic_bomber",
    crew: 4,
    speed: 1050,
    range: 6000,
    ceiling: 13100,
    acquisitionCost: 80000000,
    maintenanceCost: 4000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Xian_H-6K.jpg/1280px-Xian_H-6K.jpg",
  },
} as const;

// TRANSPORT AIRCRAFT
export const TRANSPORT_AIRCRAFT = {
  C17_GLOBEMASTER: {
    name: "C-17 Globemaster III",
    manufacturer: "BOEING",
    category: "Strategic Transport",
    era: "MODERN",
    role: "transport",
    crew: 3,
    speed: 830,
    range: 4480,
    ceiling: 13716,
    acquisitionCost: 340000000,
    maintenanceCost: 15000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/C-17_Globemaster_III.jpg/1280px-C-17_Globemaster_III.jpg",
  },
  C130J_HERCULES: {
    name: "C-130J Super Hercules",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Tactical Transport",
    era: "CONTEMPORARY",
    role: "transport",
    crew: 3,
    speed: 667,
    range: 5250,
    ceiling: 10060,
    acquisitionCost: 75000000,
    maintenanceCost: 3800000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/C-130J_Super_Hercules.jpg/1280px-C-130J_Super_Hercules.jpg",
  },
  C5M_GALAXY: {
    name: "C-5M Super Galaxy",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Strategic Transport",
    era: "MODERN",
    role: "transport",
    crew: 4,
    speed: 919,
    range: 11750,
    ceiling: 10895,
    acquisitionCost: 224000000,
    maintenanceCost: 10000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/C-5_Galaxy.jpg/1280px-C-5_Galaxy.jpg",
  },
  A400M_ATLAS: {
    name: "Airbus A400M Atlas",
    manufacturer: "AIRBUS",
    category: "Tactical Transport",
    era: "CONTEMPORARY",
    role: "transport",
    crew: 3,
    speed: 780,
    range: 8700,
    ceiling: 11300,
    acquisitionCost: 170000000,
    maintenanceCost: 8000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Airbus_A400M.jpg/1280px-Airbus_A400M.jpg",
  },
  IL76_CANDID: {
    name: "Ilyushin Il-76",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Strategic Transport",
    era: "MODERN",
    role: "transport",
    crew: 5,
    speed: 850,
    range: 4200,
    ceiling: 12000,
    acquisitionCost: 50000000,
    maintenanceCost: 2500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Il-76MD_Rossiya.jpg/1280px-Il-76MD_Rossiya.jpg",
  },
  Y20_KUNPENG: {
    name: "Xian Y-20",
    manufacturer: "AVIC",
    category: "Strategic Transport",
    era: "CONTEMPORARY",
    role: "transport",
    crew: 3,
    speed: 830,
    range: 7800,
    ceiling: 13000,
    acquisitionCost: 150000000,
    maintenanceCost: 7000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Xian_Y-20.jpg/1280px-Xian_Y-20.jpg",
  },
  KC135_STRATOTANKER: {
    name: "KC-135 Stratotanker",
    manufacturer: "BOEING",
    category: "Aerial Refueling",
    era: "COLD_WAR",
    role: "tanker",
    crew: 3,
    speed: 933,
    range: 11000,
    ceiling: 15240,
    acquisitionCost: 39000000,
    maintenanceCost: 2000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/KC-135_Stratotanker.jpg/1280px-KC-135_Stratotanker.jpg",
  },
  KC46_PEGASUS: {
    name: "KC-46 Pegasus",
    manufacturer: "BOEING",
    category: "Aerial Refueling",
    era: "CONTEMPORARY",
    role: "tanker",
    crew: 3,
    speed: 920,
    range: 11500,
    ceiling: 12500,
    acquisitionCost: 148000000,
    maintenanceCost: 7000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/KC-46_Pegasus.jpg/1280px-KC-46_Pegasus.jpg",
  },
  A330_MRTT: {
    name: "Airbus A330 MRTT",
    manufacturer: "AIRBUS",
    category: "Aerial Refueling",
    era: "CONTEMPORARY",
    role: "tanker",
    crew: 3,
    speed: 860,
    range: 14800,
    ceiling: 12500,
    acquisitionCost: 250000000,
    maintenanceCost: 12000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/A330_MRTT_F-WWKC.jpg/1280px-A330_MRTT_F-WWKC.jpg",
  },
} as const;

// HELICOPTERS
export const HELICOPTERS = {
  AH64E_APACHE: {
    name: "AH-64E Apache Guardian",
    manufacturer: "BOEING",
    category: "Attack Helicopter",
    era: "CONTEMPORARY",
    role: "attack_helicopter",
    crew: 2,
    speed: 293,
    range: 476,
    ceiling: 6400,
    acquisitionCost: 35000000,
    maintenanceCost: 2500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/AH-64E_Apache.jpg/1280px-AH-64E_Apache.jpg",
  },
  UH60M_BLACKHAWK: {
    name: "UH-60M Black Hawk",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Utility Helicopter",
    era: "CONTEMPORARY",
    role: "utility",
    crew: 4,
    speed: 296,
    range: 592,
    ceiling: 5790,
    acquisitionCost: 21000000,
    maintenanceCost: 1500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/UH-60_Blackhawk.jpg/1280px-UH-60_Blackhawk.jpg",
  },
  CH47F_CHINOOK: {
    name: "CH-47F Chinook",
    manufacturer: "BOEING",
    category: "Heavy Transport Helicopter",
    era: "CONTEMPORARY",
    role: "transport",
    crew: 3,
    speed: 315,
    range: 741,
    ceiling: 6096,
    acquisitionCost: 38000000,
    maintenanceCost: 2800000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/CH-47_Chinook.jpg/1280px-CH-47_Chinook.jpg",
  },
  MH60R_SEAHAWK: {
    name: "MH-60R Seahawk",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Naval Helicopter",
    era: "CONTEMPORARY",
    role: "anti_submarine",
    crew: 4,
    speed: 270,
    range: 830,
    ceiling: 3795,
    acquisitionCost: 42000000,
    maintenanceCost: 3000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/MH-60R_Seahawk.jpg/1280px-MH-60R_Seahawk.jpg",
  },
  AH1Z_VIPER: {
    name: "AH-1Z Viper",
    manufacturer: "LEONARDO",
    category: "Attack Helicopter",
    era: "CONTEMPORARY",
    role: "attack_helicopter",
    crew: 2,
    speed: 411,
    range: 685,
    ceiling: 6096,
    acquisitionCost: 31000000,
    maintenanceCost: 2200000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/AH-1Z_Viper.jpg/1280px-AH-1Z_Viper.jpg",
  },
  MI24_HIND: {
    name: "Mil Mi-24 Hind",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Attack Helicopter",
    era: "COLD_WAR",
    role: "attack_helicopter",
    crew: 3,
    speed: 335,
    range: 450,
    ceiling: 4500,
    acquisitionCost: 12000000,
    maintenanceCost: 900000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Mil_Mi-24_Hind.jpg/1280px-Mil_Mi-24_Hind.jpg",
  },
  MI28_HAVOC: {
    name: "Mil Mi-28 Havoc",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Attack Helicopter",
    era: "MODERN",
    role: "attack_helicopter",
    crew: 2,
    speed: 300,
    range: 435,
    ceiling: 5600,
    acquisitionCost: 18000000,
    maintenanceCost: 1400000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Mil_Mi-28.jpg/1280px-Mil_Mi-28.jpg",
  },
  KA52_ALLIGATOR: {
    name: "Kamov Ka-52 Alligator",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Attack Helicopter",
    era: "CONTEMPORARY",
    role: "attack_helicopter",
    crew: 2,
    speed: 310,
    range: 460,
    ceiling: 5500,
    acquisitionCost: 16000000,
    maintenanceCost: 1200000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Kamov_Ka-52.jpg/1280px-Kamov_Ka-52.jpg",
  },
  NH90: {
    name: "NH Industries NH90",
    manufacturer: "AIRBUS",
    category: "Multi-Role Helicopter",
    era: "CONTEMPORARY",
    role: "utility",
    crew: 2,
    speed: 300,
    range: 800,
    ceiling: 6000,
    acquisitionCost: 50000000,
    maintenanceCost: 3500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/NH90_helicopter.jpg/1280px-NH90_helicopter.jpg",
  },
  TIGER_HAD: {
    name: "Eurocopter Tiger HAD",
    manufacturer: "AIRBUS",
    category: "Attack Helicopter",
    era: "CONTEMPORARY",
    role: "attack_helicopter",
    crew: 2,
    speed: 290,
    range: 800,
    ceiling: 4000,
    acquisitionCost: 40000000,
    maintenanceCost: 2800000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Tiger_helicopter.jpg/1280px-Tiger_helicopter.jpg",
  },
  AW101_MERLIN: {
    name: "AgustaWestland AW101",
    manufacturer: "LEONARDO",
    category: "Multi-Role Helicopter",
    era: "CONTEMPORARY",
    role: "utility",
    crew: 3,
    speed: 277,
    range: 1389,
    ceiling: 4575,
    acquisitionCost: 42000000,
    maintenanceCost: 3000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/AW101_Merlin.jpg/1280px-AW101_Merlin.jpg",
  },
  Z10_THUNDERBOLT: {
    name: "CAIC Z-10",
    manufacturer: "AVIC",
    category: "Attack Helicopter",
    era: "CONTEMPORARY",
    role: "attack_helicopter",
    crew: 2,
    speed: 270,
    range: 800,
    ceiling: 6000,
    acquisitionCost: 15000000,
    maintenanceCost: 1100000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/CAIC_Z-10.jpg/1280px-CAIC_Z-10.jpg",
  },
  T129_ATAK: {
    name: "TAI T129 ATAK",
    manufacturer: "LEONARDO",
    category: "Attack Helicopter",
    era: "CONTEMPORARY",
    role: "attack_helicopter",
    crew: 2,
    speed: 281,
    range: 561,
    ceiling: 6096,
    acquisitionCost: 25000000,
    maintenanceCost: 1800000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/T129_ATAK.jpg/1280px-T129_ATAK.jpg",
  },
  DHRUV_ALH: {
    name: "HAL Dhruv",
    manufacturer: "HAL",
    category: "Utility Helicopter",
    era: "CONTEMPORARY",
    role: "utility",
    crew: 2,
    speed: 245,
    range: 833,
    ceiling: 6000,
    acquisitionCost: 8000000,
    maintenanceCost: 600000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/HAL_Dhruv.jpg/1280px-HAL_Dhruv.jpg",
  },
  APACHE_LONGBOW: {
    name: "AH-64D Apache Longbow",
    manufacturer: "BOEING",
    category: "Attack Helicopter",
    era: "MODERN",
    role: "attack_helicopter",
    crew: 2,
    speed: 293,
    range: 476,
    ceiling: 6400,
    acquisitionCost: 20000000,
    maintenanceCost: 1800000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/AH-64D_Apache.jpg/1280px-AH-64D_Apache.jpg",
  },
} as const;

// NAVAL VESSELS
export const NAVAL_SHIPS = {
  // Aircraft Carriers
  NIMITZ_CLASS: {
    name: "Nimitz-class Aircraft Carrier",
    manufacturer: "NORTHROP_GRUMMAN",
    category: "Supercarrier",
    era: "MODERN",
    displacement: 100000,
    crew: 5680,
    aircraft: 90,
    speed: 56,
    range: "Unlimited (nuclear)",
    acquisitionCost: 8500000000,
    maintenanceCost: 500000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/USS_Nimitz_%28CVN-68%29.jpg/1280px-USS_Nimitz_%28CVN-68%29.jpg",
  },
  FORD_CLASS: {
    name: "Gerald R. Ford-class Carrier",
    manufacturer: "NORTHROP_GRUMMAN",
    category: "Supercarrier",
    era: "ADVANCED",
    displacement: 100000,
    crew: 4660,
    aircraft: 75,
    speed: 56,
    range: "Unlimited (nuclear)",
    acquisitionCost: 13000000000,
    maintenanceCost: 600000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/USS_Gerald_R._Ford_%28CVN-78%29_underway.jpg/1280px-USS_Gerald_R._Ford_%28CVN-78%29_underway.jpg",
  },
  QUEEN_ELIZABETH: {
    name: "Queen Elizabeth-class Carrier",
    manufacturer: "BAE_SYSTEMS",
    category: "Aircraft Carrier",
    era: "CONTEMPORARY",
    displacement: 65000,
    crew: 1600,
    aircraft: 40,
    speed: 46,
    range: 18500,
    acquisitionCost: 3500000000,
    maintenanceCost: 180000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/HMS_Queen_Elizabeth_%28R08%29.jpg/1280px-HMS_Queen_Elizabeth_%28R08%29.jpg",
  },
  CHARLES_DE_GAULLE: {
    name: "Charles de Gaulle",
    manufacturer: "THALES",
    category: "Nuclear Carrier",
    era: "MODERN",
    displacement: 42500,
    crew: 1950,
    aircraft: 40,
    speed: 48,
    range: "Unlimited (nuclear)",
    acquisitionCost: 3300000000,
    maintenanceCost: 170000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Charles_de_Gaulle_%28R_91%29.jpg/1280px-Charles_de_Gaulle_%28R_91%29.jpg",
  },
  LIAONING: {
    name: "Liaoning",
    manufacturer: "AVIC",
    category: "Aircraft Carrier",
    era: "CONTEMPORARY",
    displacement: 60000,
    crew: 2000,
    aircraft: 36,
    speed: 58,
    range: 7000,
    acquisitionCost: 2500000000,
    maintenanceCost: 130000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Liaoning_%28CV-16%29.jpg/1280px-Liaoning_%28CV-16%29.jpg",
  },

  // Destroyers
  ARLEIGH_BURKE: {
    name: "Arleigh Burke-class Destroyer",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Guided Missile Destroyer",
    era: "MODERN",
    displacement: 9200,
    crew: 380,
    speed: 56,
    range: 8300,
    acquisitionCost: 1850000000,
    maintenanceCost: 85000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/USS_Arleigh_Burke_%28DDG-51%29.jpg/1280px-USS_Arleigh_Burke_%28DDG-51%29.jpg",
  },
  ZUMWALT: {
    name: "Zumwalt-class Destroyer",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Stealth Destroyer",
    era: "CONTEMPORARY",
    displacement: 15742,
    crew: 175,
    speed: 56,
    range: 9000,
    acquisitionCost: 4400000000,
    maintenanceCost: 200000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/USS_Zumwalt_%28DDG-1000%29.jpg/1280px-USS_Zumwalt_%28DDG-1000%29.jpg",
  },
  TYPE_45_DARING: {
    name: "Type 45 Daring-class",
    manufacturer: "BAE_SYSTEMS",
    category: "Air Defense Destroyer",
    era: "CONTEMPORARY",
    displacement: 8000,
    crew: 235,
    speed: 54,
    range: 13000,
    acquisitionCost: 1100000000,
    maintenanceCost: 55000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/HMS_Daring_%28D32%29.jpg/1280px-HMS_Daring_%28D32%29.jpg",
  },
  TYPE_055: {
    name: "Type 055 Destroyer",
    manufacturer: "AVIC",
    category: "Guided Missile Destroyer",
    era: "ADVANCED",
    displacement: 13000,
    crew: 310,
    speed: 56,
    range: 10000,
    acquisitionCost: 900000000,
    maintenanceCost: 45000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Type_055_destroyer.jpg/1280px-Type_055_destroyer.jpg",
  },
  SEJONG_THE_GREAT: {
    name: "Sejong the Great-class",
    manufacturer: "KAI",
    category: "Guided Missile Destroyer",
    era: "CONTEMPORARY",
    displacement: 11000,
    crew: 300,
    speed: 56,
    range: 10000,
    acquisitionCost: 1200000000,
    maintenanceCost: 60000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/ROKS_Sejong_the_Great_%28DDG-991%29.jpg/1280px-ROKS_Sejong_the_Great_%28DDG-991%29.jpg",
  },
  ATAGO_CLASS: {
    name: "Atago-class Destroyer",
    manufacturer: "MITSUBISHI_HEAVY",
    category: "Guided Missile Destroyer",
    era: "CONTEMPORARY",
    displacement: 10000,
    crew: 300,
    speed: 56,
    range: 8300,
    acquisitionCost: 1500000000,
    maintenanceCost: 75000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/JS_Atago_%28DDG-177%29.jpg/1280px-JS_Atago_%28DDG-177%29.jpg",
  },

  // Frigates
  CONSTELLATION_CLASS: {
    name: "Constellation-class Frigate",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Guided Missile Frigate",
    era: "ADVANCED",
    displacement: 7400,
    crew: 200,
    speed: 48,
    range: 11000,
    acquisitionCost: 1200000000,
    maintenanceCost: 60000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Constellation-class_frigate.jpg/1280px-Constellation-class_frigate.jpg",
  },
  FREMM_FRIGATE: {
    name: "FREMM Frigate",
    manufacturer: "THALES",
    category: "Multi-Purpose Frigate",
    era: "CONTEMPORARY",
    displacement: 6000,
    crew: 145,
    speed: 50,
    range: 11000,
    acquisitionCost: 700000000,
    maintenanceCost: 35000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/FREMM_Aquitaine.jpg/1280px-FREMM_Aquitaine.jpg",
  },
  TYPE_26_FRIGATE: {
    name: "Type 26 Frigate",
    manufacturer: "BAE_SYSTEMS",
    category: "Anti-Submarine Frigate",
    era: "CONTEMPORARY",
    displacement: 8000,
    crew: 157,
    speed: 48,
    range: 13000,
    acquisitionCost: 1100000000,
    maintenanceCost: 55000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/HMS_Glasgow_%28Type_26%29.jpg/1280px-HMS_Glasgow_%28Type_26%29.jpg",
  },

  // Submarines
  VIRGINIA_CLASS: {
    name: "Virginia-class Submarine",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Attack Submarine",
    era: "CONTEMPORARY",
    displacement: 7800,
    crew: 135,
    speed: 46,
    depth: 490,
    acquisitionCost: 3300000000,
    maintenanceCost: 150000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/USS_Virginia_%28SSN-774%29.jpg/1280px-USS_Virginia_%28SSN-774%29.jpg",
  },
  OHIO_CLASS_SSBN: {
    name: "Ohio-class SSBN",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Ballistic Missile Submarine",
    era: "MODERN",
    displacement: 18750,
    crew: 155,
    speed: 46,
    depth: 365,
    acquisitionCost: 2000000000,
    maintenanceCost: 100000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Ohio_class_submarine.jpg/1280px-Ohio_class_submarine.jpg",
  },
  ASTUTE_CLASS: {
    name: "Astute-class Submarine",
    manufacturer: "BAE_SYSTEMS",
    category: "Attack Submarine",
    era: "CONTEMPORARY",
    displacement: 7800,
    crew: 98,
    speed: 54,
    depth: 300,
    acquisitionCost: 2000000000,
    maintenanceCost: 95000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/HMS_Astute.jpg/1280px-HMS_Astute.jpg",
  },
  TYPE_093_SHANG: {
    name: "Type 093 Shang-class",
    manufacturer: "AVIC",
    category: "Attack Submarine",
    era: "CONTEMPORARY",
    displacement: 7000,
    crew: 100,
    speed: 56,
    depth: 400,
    acquisitionCost: 1500000000,
    maintenanceCost: 75000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Type_093_submarine.jpg/1280px-Type_093_submarine.jpg",
  },
  YASEN_CLASS: {
    name: "Yasen-class Submarine",
    manufacturer: "UNITED_AIRCRAFT",
    category: "Cruise Missile Submarine",
    era: "CONTEMPORARY",
    displacement: 13800,
    crew: 85,
    speed: 61,
    depth: 520,
    acquisitionCost: 1600000000,
    maintenanceCost: 80000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Yasen_class_submarine.jpg/1280px-Yasen_class_submarine.jpg",
  },
  SCORPENE_CLASS: {
    name: "Scorpène-class Submarine",
    manufacturer: "THALES",
    category: "Attack Submarine",
    era: "CONTEMPORARY",
    displacement: 1700,
    crew: 31,
    speed: 37,
    depth: 350,
    acquisitionCost: 500000000,
    maintenanceCost: 25000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Scorpene_class_submarine.jpg/1280px-Scorpene_class_submarine.jpg",
  },

  // Amphibious Warfare
  WASP_CLASS: {
    name: "Wasp-class LHD",
    manufacturer: "NORTHROP_GRUMMAN",
    category: "Amphibious Assault Ship",
    era: "MODERN",
    displacement: 41000,
    crew: 1200,
    aircraft: 42,
    speed: 41,
    range: 17000,
    acquisitionCost: 1200000000,
    maintenanceCost: 60000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/USS_Wasp_%28LHD-1%29.jpg/1280px-USS_Wasp_%28LHD-1%29.jpg",
  },
  AMERICA_CLASS: {
    name: "America-class LHA",
    manufacturer: "NORTHROP_GRUMMAN",
    category: "Amphibious Assault Ship",
    era: "CONTEMPORARY",
    displacement: 44000,
    crew: 1060,
    aircraft: 20,
    speed: 41,
    range: 17000,
    acquisitionCost: 3400000000,
    maintenanceCost: 170000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/USS_America_%28LHA-6%29.jpg/1280px-USS_America_%28LHA-6%29.jpg",
  },
  MISTRAL_CLASS: {
    name: "Mistral-class LHD",
    manufacturer: "THALES",
    category: "Amphibious Assault Ship",
    era: "CONTEMPORARY",
    displacement: 21300,
    crew: 160,
    aircraft: 16,
    speed: 35,
    range: 18700,
    acquisitionCost: 550000000,
    maintenanceCost: 28000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Mistral_class_LHD.jpg/1280px-Mistral_class_LHD.jpg",
  },
  TYPE_075_LHD: {
    name: "Type 075 LHD",
    manufacturer: "AVIC",
    category: "Amphibious Assault Ship",
    era: "ADVANCED",
    displacement: 40000,
    crew: 900,
    aircraft: 30,
    speed: 42,
    range: 15000,
    acquisitionCost: 850000000,
    maintenanceCost: 43000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Type_075_LHD.jpg/1280px-Type_075_LHD.jpg",
  },
} as const;

// GROUND VEHICLES
export const GROUND_VEHICLES = {
  // Main Battle Tanks
  M1A2_ABRAMS: {
    name: "M1A2 Abrams SEPv3",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Main Battle Tank",
    era: "CONTEMPORARY",
    crew: 4,
    speed: 67,
    range: 426,
    armament: "120mm M256 smoothbore",
    acquisitionCost: 8900000,
    maintenanceCost: 500000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/M1A2_Abrams_tank.jpg/1280px-M1A2_Abrams_tank.jpg",
  },
  LEOPARD_2A7: {
    name: "Leopard 2A7+",
    manufacturer: "RHEINMETALL",
    category: "Main Battle Tank",
    era: "CONTEMPORARY",
    crew: 4,
    speed: 68,
    range: 450,
    armament: "120mm L55A1 smoothbore",
    acquisitionCost: 7500000,
    maintenanceCost: 450000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Leopard_2A7%2B.jpg/1280px-Leopard_2A7%2B.jpg",
  },
  CHALLENGER_3: {
    name: "Challenger 3",
    manufacturer: "BAE_SYSTEMS",
    category: "Main Battle Tank",
    era: "ADVANCED",
    crew: 4,
    speed: 59,
    range: 550,
    armament: "120mm L55A1 smoothbore",
    acquisitionCost: 8000000,
    maintenanceCost: 480000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Challenger_3_prototype.jpg/1280px-Challenger_3_prototype.jpg",
  },
  T90M_PRORYV: {
    name: "T-90M Proryv",
    manufacturer: "URALVAGONZAVOD",
    category: "Main Battle Tank",
    era: "CONTEMPORARY",
    crew: 3,
    speed: 60,
    range: 550,
    armament: "125mm 2A46M-5 smoothbore",
    acquisitionCost: 4500000,
    maintenanceCost: 270000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/T-90M_tank.jpg/1280px-T-90M_tank.jpg",
  },
  T14_ARMATA: {
    name: "T-14 Armata",
    manufacturer: "URALVAGONZAVOD",
    category: "Next-Gen Tank",
    era: "ADVANCED",
    crew: 3,
    speed: 80,
    range: 500,
    armament: "125mm 2A82-1M smoothbore",
    acquisitionCost: 8000000,
    maintenanceCost: 480000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/T-14_Armata.jpg/1280px-T-14_Armata.jpg",
  },
  TYPE_99A: {
    name: "Type 99A",
    manufacturer: "NORINCO",
    category: "Main Battle Tank",
    era: "CONTEMPORARY",
    crew: 3,
    speed: 80,
    range: 600,
    armament: "125mm ZPT-98 smoothbore",
    acquisitionCost: 5200000,
    maintenanceCost: 310000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Type_99A_tank.jpg/1280px-Type_99A_tank.jpg",
  },
  TYPE_10_HITOMARU: {
    name: "Type 10",
    manufacturer: "MITSUBISHI_HEAVY",
    category: "Main Battle Tank",
    era: "CONTEMPORARY",
    crew: 3,
    speed: 70,
    range: 500,
    armament: "120mm L44 smoothbore",
    acquisitionCost: 9000000,
    maintenanceCost: 540000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Type_10_tank.jpg/1280px-Type_10_tank.jpg",
  },
  K2_BLACK_PANTHER: {
    name: "K2 Black Panther",
    manufacturer: "KAI",
    category: "Main Battle Tank",
    era: "CONTEMPORARY",
    crew: 3,
    speed: 70,
    range: 450,
    armament: "120mm L55 smoothbore",
    acquisitionCost: 8600000,
    maintenanceCost: 515000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/K2_Black_Panther.jpg/1280px-K2_Black_Panther.jpg",
  },
  LECLERC: {
    name: "Leclerc",
    manufacturer: "THALES",
    category: "Main Battle Tank",
    era: "MODERN",
    crew: 3,
    speed: 71,
    range: 550,
    armament: "120mm CN120-26 smoothbore",
    acquisitionCost: 6800000,
    maintenanceCost: 408000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Leclerc_tank.jpg/1280px-Leclerc_tank.jpg",
  },
  MERKAVA_MK4: {
    name: "Merkava Mk 4",
    manufacturer: "IAI",
    category: "Main Battle Tank",
    era: "CONTEMPORARY",
    crew: 4,
    speed: 64,
    range: 500,
    armament: "120mm MG251 smoothbore",
    acquisitionCost: 6000000,
    maintenanceCost: 360000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Merkava_Mk_4.jpg/1280px-Merkava_Mk_4.jpg",
  },

  // Infantry Fighting Vehicles
  M2A3_BRADLEY: {
    name: "M2A3 Bradley",
    manufacturer: "BAE_SYSTEMS",
    category: "Infantry Fighting Vehicle",
    era: "MODERN",
    crew: 3,
    troops: 6,
    speed: 66,
    range: 402,
    armament: "25mm M242 Bushmaster",
    acquisitionCost: 4200000,
    maintenanceCost: 250000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/M2_Bradley_IFV.jpg/1280px-M2_Bradley_IFV.jpg",
  },
  PUMA_IFV: {
    name: "Puma IFV",
    manufacturer: "RHEINMETALL",
    category: "Infantry Fighting Vehicle",
    era: "CONTEMPORARY",
    crew: 3,
    troops: 6,
    speed: 70,
    range: 600,
    armament: "30mm MK 30-2/ABM",
    acquisitionCost: 7200000,
    maintenanceCost: 432000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Puma_IFV.jpg/1280px-Puma_IFV.jpg",
  },
  BMP3: {
    name: "BMP-3",
    manufacturer: "URALVAGONZAVOD",
    category: "Infantry Fighting Vehicle",
    era: "MODERN",
    crew: 3,
    troops: 7,
    speed: 70,
    range: 600,
    armament: "100mm 2A70 gun",
    acquisitionCost: 2500000,
    maintenanceCost: 150000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/BMP-3_IFV.jpg/1280px-BMP-3_IFV.jpg",
  },
  ZBD04A: {
    name: "ZBD-04A",
    manufacturer: "NORINCO",
    category: "Infantry Fighting Vehicle",
    era: "CONTEMPORARY",
    crew: 3,
    troops: 7,
    speed: 65,
    range: 500,
    armament: "30mm autocannon",
    acquisitionCost: 2800000,
    maintenanceCost: 168000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/ZBD-04A_IFV.jpg/1280px-ZBD-04A_IFV.jpg",
  },
  CV90: {
    name: "CV90",
    manufacturer: "BAE_SYSTEMS",
    category: "Infantry Fighting Vehicle",
    era: "MODERN",
    crew: 3,
    troops: 8,
    speed: 70,
    range: 320,
    armament: "40mm Bofors autocannon",
    acquisitionCost: 5800000,
    maintenanceCost: 348000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/CV90_IFV.jpg/1280px-CV90_IFV.jpg",
  },

  // Armored Personnel Carriers
  STRYKER_A1: {
    name: "Stryker A1",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Armored Personnel Carrier",
    era: "CONTEMPORARY",
    crew: 2,
    troops: 9,
    speed: 97,
    range: 531,
    acquisitionCost: 4900000,
    maintenanceCost: 300000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Stryker_APC.jpg/1280px-Stryker_APC.jpg",
  },
  BOXER_APC: {
    name: "Boxer APC",
    manufacturer: "RHEINMETALL",
    category: "Armored Personnel Carrier",
    era: "CONTEMPORARY",
    crew: 3,
    troops: 8,
    speed: 103,
    range: 1050,
    acquisitionCost: 6500000,
    maintenanceCost: 390000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Boxer_APC.jpg/1280px-Boxer_APC.jpg",
  },
  BTR90: {
    name: "BTR-90",
    manufacturer: "URALVAGONZAVOD",
    category: "Armored Personnel Carrier",
    era: "MODERN",
    crew: 3,
    troops: 10,
    speed: 100,
    range: 600,
    acquisitionCost: 1800000,
    maintenanceCost: 108000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/BTR-90_APC.jpg/1280px-BTR-90_APC.jpg",
  },
  TYPE_08: {
    name: "Type 08",
    manufacturer: "NORINCO",
    category: "Armored Personnel Carrier",
    era: "CONTEMPORARY",
    crew: 3,
    troops: 7,
    speed: 100,
    range: 800,
    acquisitionCost: 2200000,
    maintenanceCost: 132000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Type_08_APC.jpg/1280px-Type_08_APC.jpg",
  },
  PIRANHA_V: {
    name: "Piranha V",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Armored Personnel Carrier",
    era: "CONTEMPORARY",
    crew: 3,
    troops: 9,
    speed: 100,
    range: 800,
    acquisitionCost: 5500000,
    maintenanceCost: 330000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Piranha_V_APC.jpg/1280px-Piranha_V_APC.jpg",
  },

  // Artillery
  M109A7_PALADIN: {
    name: "M109A7 Paladin",
    manufacturer: "BAE_SYSTEMS",
    category: "Self-Propelled Howitzer",
    era: "CONTEMPORARY",
    crew: 4,
    speed: 56,
    range: 349,
    armament: "155mm M284 howitzer",
    firingRange: 30000,
    acquisitionCost: 2700000,
    maintenanceCost: 180000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/M109A7_Paladin.jpg/1280px-M109A7_Paladin.jpg",
  },
  PZH_2000: {
    name: "PzH 2000",
    manufacturer: "RHEINMETALL",
    category: "Self-Propelled Howitzer",
    era: "MODERN",
    crew: 5,
    speed: 60,
    range: 420,
    armament: "155mm L52 howitzer",
    firingRange: 56000,
    acquisitionCost: 6700000,
    maintenanceCost: 402000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/PzH_2000.jpg/1280px-PzH_2000.jpg",
  },
  S2S19_MSTA: {
    name: "2S19 Msta-S",
    manufacturer: "URALVAGONZAVOD",
    category: "Self-Propelled Howitzer",
    era: "MODERN",
    crew: 5,
    speed: 60,
    range: 500,
    armament: "152mm 2A64 howitzer",
    firingRange: 29000,
    acquisitionCost: 3200000,
    maintenanceCost: 192000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/2S19_Msta.jpg/1280px-2S19_Msta.jpg",
  },
  PLZ05: {
    name: "PLZ-05",
    manufacturer: "NORINCO",
    category: "Self-Propelled Howitzer",
    era: "CONTEMPORARY",
    crew: 5,
    speed: 60,
    range: 450,
    armament: "155mm howitzer",
    firingRange: 50000,
    acquisitionCost: 3800000,
    maintenanceCost: 228000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/PLZ-05_howitzer.jpg/1280px-PLZ-05_howitzer.jpg",
  },
  CAESAR_SPH: {
    name: "CAESAR 155mm",
    manufacturer: "THALES",
    category: "Truck-Mounted Howitzer",
    era: "CONTEMPORARY",
    crew: 5,
    speed: 100,
    range: 600,
    armament: "155mm 52-caliber howitzer",
    firingRange: 42000,
    acquisitionCost: 4200000,
    maintenanceCost: 252000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/CAESAR_SPH.jpg/1280px-CAESAR_SPH.jpg",
  },
  M142_HIMARS: {
    name: "M142 HIMARS",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Multiple Rocket Launcher",
    era: "CONTEMPORARY",
    crew: 3,
    speed: 85,
    range: 480,
    armament: "6x GMLRS rockets",
    firingRange: 80000,
    acquisitionCost: 5100000,
    maintenanceCost: 350000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/M142_HIMARS.jpg/1280px-M142_HIMARS.jpg",
  },
  M270_MLRS: {
    name: "M270 MLRS",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Multiple Rocket Launcher",
    era: "MODERN",
    crew: 3,
    speed: 64,
    range: 480,
    armament: "12x GMLRS rockets",
    firingRange: 80000,
    acquisitionCost: 3800000,
    maintenanceCost: 228000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/M270_MLRS.jpg/1280px-M270_MLRS.jpg",
  },
  BM30_SMERCH: {
    name: "BM-30 Smerch",
    manufacturer: "URALVAGONZAVOD",
    category: "Multiple Rocket Launcher",
    era: "MODERN",
    crew: 4,
    speed: 60,
    range: 850,
    armament: "12x 300mm rockets",
    firingRange: 90000,
    acquisitionCost: 4500000,
    maintenanceCost: 270000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/BM-30_Smerch.jpg/1280px-BM-30_Smerch.jpg",
  },
} as const;

// WEAPON SYSTEMS & DEFENSE
export const WEAPON_SYSTEMS_EXTENDED = {
  // Air Defense
  PATRIOT_PAC3: {
    name: "MIM-104 Patriot PAC-3",
    manufacturer: "RAYTHEON",
    category: "Surface-to-Air Missile",
    era: "CONTEMPORARY",
    range: 160000,
    altitude: 24400,
    acquisitionCost: 1100000000,
    maintenanceCost: 50000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Patriot_missile_system.jpg/1280px-Patriot_missile_system.jpg",
  },
  THAAD_SYSTEM: {
    name: "THAAD",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Ballistic Missile Defense",
    era: "CONTEMPORARY",
    range: 200000,
    altitude: 150000,
    acquisitionCost: 3000000000,
    maintenanceCost: 120000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/THAAD_missile_system.jpg/1280px-THAAD_missile_system.jpg",
  },
  IRON_DOME_BATTERY: {
    name: "Iron Dome",
    manufacturer: "IAI",
    category: "Short-Range Air Defense",
    era: "CONTEMPORARY",
    range: 70000,
    altitude: 10000,
    acquisitionCost: 50000000,
    maintenanceCost: 3000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Iron_Dome_battery.jpg/1280px-Iron_Dome_battery.jpg",
  },
  S400_TRIUMF: {
    name: "S-400 Triumf",
    manufacturer: "ALMAZ_ANTEY",
    category: "Long-Range Air Defense",
    era: "CONTEMPORARY",
    range: 400000,
    altitude: 30000,
    acquisitionCost: 500000000,
    maintenanceCost: 25000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/S-400_Triumf.jpg/1280px-S-400_Triumf.jpg",
  },
  S500_PROMETHEUS: {
    name: "S-500 Prometheus",
    manufacturer: "ALMAZ_ANTEY",
    category: "Next-Gen Air Defense",
    era: "ADVANCED",
    range: 600000,
    altitude: 200000,
    acquisitionCost: 2500000000,
    maintenanceCost: 125000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/S-500_system.jpg/1280px-S-500_system.jpg",
  },
  HQ9_SYSTEM: {
    name: "HQ-9",
    manufacturer: "AVIC",
    category: "Long-Range Air Defense",
    era: "CONTEMPORARY",
    range: 200000,
    altitude: 27000,
    acquisitionCost: 300000000,
    maintenanceCost: 15000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/HQ-9_air_defense.jpg/1280px-HQ-9_air_defense.jpg",
  },
  DAVID_SLING: {
    name: "David's Sling",
    manufacturer: "IAI",
    category: "Medium-Range Air Defense",
    era: "CONTEMPORARY",
    range: 300000,
    altitude: 15000,
    acquisitionCost: 1000000000,
    maintenanceCost: 50000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/David_Sling_system.jpg/1280px-David_Sling_system.jpg",
  },
  ARROW_3: {
    name: "Arrow 3",
    manufacturer: "IAI",
    category: "Exo-Atmospheric Defense",
    era: "ADVANCED",
    range: 2400000,
    altitude: 100000,
    acquisitionCost: 2200000000,
    maintenanceCost: 110000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Arrow_3_missile.jpg/1280px-Arrow_3_missile.jpg",
  },
  NASAMS: {
    name: "NASAMS",
    manufacturer: "RAYTHEON",
    category: "Medium-Range Air Defense",
    era: "CONTEMPORARY",
    range: 50000,
    altitude: 21000,
    acquisitionCost: 180000000,
    maintenanceCost: 9000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/NASAMS_launcher.jpg/1280px-NASAMS_launcher.jpg",
  },
  SAMP_T: {
    name: "SAMP/T Mamba",
    manufacturer: "THALES",
    category: "Medium-Range Air Defense",
    era: "CONTEMPORARY",
    range: 100000,
    altitude: 20000,
    acquisitionCost: 1200000000,
    maintenanceCost: 60000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/SAMP-T_system.jpg/1280px-SAMP-T_system.jpg",
  },

  // Missiles & Precision Weapons
  TOMAHAWK_CRUISE: {
    name: "BGM-109 Tomahawk",
    manufacturer: "RAYTHEON",
    category: "Cruise Missile",
    era: "MODERN",
    range: 2500000,
    speed: 880,
    acquisitionCost: 1900000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Tomahawk_missile.jpg/1280px-Tomahawk_missile.jpg",
  },
  JASSM_ER: {
    name: "AGM-158 JASSM-ER",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Air-Launched Cruise Missile",
    era: "CONTEMPORARY",
    range: 1000000,
    speed: 1040,
    acquisitionCost: 1400000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/AGM-158_JASSM.jpg/1280px-AGM-158_JASSM.jpg",
  },
  KALIBR_CRUISE: {
    name: "3M-54 Kalibr",
    manufacturer: "ALMAZ_ANTEY",
    category: "Cruise Missile",
    era: "CONTEMPORARY",
    range: 2600000,
    speed: 800,
    acquisitionCost: 1200000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Kalibr_missile.jpg/1280px-Kalibr_missile.jpg",
  },
  SCALP_EG: {
    name: "SCALP EG / Storm Shadow",
    manufacturer: "THALES",
    category: "Air-Launched Cruise Missile",
    era: "MODERN",
    range: 560000,
    speed: 1040,
    acquisitionCost: 1000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Storm_Shadow_missile.jpg/1280px-Storm_Shadow_missile.jpg",
  },
  AGM114_HELLFIRE: {
    name: "AGM-114 Hellfire",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Anti-Tank Missile",
    era: "MODERN",
    range: 8000,
    speed: 1400,
    acquisitionCost: 150000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/AGM-114_Hellfire.jpg/1280px-AGM-114_Hellfire.jpg",
  },
  JAVELIN_ATGM: {
    name: "FGM-148 Javelin",
    manufacturer: "RAYTHEON",
    category: "Anti-Tank Missile",
    era: "CONTEMPORARY",
    range: 4000,
    speed: 670,
    acquisitionCost: 175000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/FGM-148_Javelin.jpg/1280px-FGM-148_Javelin.jpg",
  },
  SPIKE_LR: {
    name: "Spike-LR",
    manufacturer: "IAI",
    category: "Anti-Tank Missile",
    era: "CONTEMPORARY",
    range: 5000,
    speed: 550,
    acquisitionCost: 210000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Spike_missile.jpg/1280px-Spike_missile.jpg",
  },
  NLAW: {
    name: "NLAW",
    manufacturer: "SAAB",
    category: "Anti-Tank Missile",
    era: "CONTEMPORARY",
    range: 1000,
    speed: 190,
    acquisitionCost: 40000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/NLAW_missile.jpg/1280px-NLAW_missile.jpg",
  },

  // Naval Combat Systems
  AEGIS_COMBAT: {
    name: "Aegis Combat System",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Naval Combat System",
    era: "MODERN",
    acquisitionCost: 500000000,
    maintenanceCost: 25000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Aegis_radar_system.jpg/1280px-Aegis_radar_system.jpg",
  },
  PHALANX_CIWS: {
    name: "Phalanx CIWS",
    manufacturer: "RAYTHEON",
    category: "Close-In Weapon System",
    era: "MODERN",
    acquisitionCost: 5800000,
    maintenanceCost: 290000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Phalanx_CIWS.jpg/1280px-Phalanx_CIWS.jpg",
  },
  GOALKEEPER_CIWS: {
    name: "Goalkeeper CIWS",
    manufacturer: "THALES",
    category: "Close-In Weapon System",
    era: "MODERN",
    acquisitionCost: 11000000,
    maintenanceCost: 550000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Goalkeeper_CIWS.jpg/1280px-Goalkeeper_CIWS.jpg",
  },
  MK41_VLS: {
    name: "Mk 41 VLS",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Vertical Launch System",
    era: "MODERN",
    acquisitionCost: 120000000,
    maintenanceCost: 6000000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mk_41_VLS.jpg/1280px-Mk_41_VLS.jpg",
  },
  MK48_TORPEDO: {
    name: "Mark 48 Torpedo",
    manufacturer: "LOCKHEED_MARTIN",
    category: "Heavy Torpedo",
    era: "MODERN",
    range: 38000,
    speed: 102,
    acquisitionCost: 3800000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Mark_48_torpedo.jpg/1280px-Mark_48_torpedo.jpg",
  },
} as const;

// Export aggregated database
export const EXPANDED_MILITARY_DATABASE = {
  fighters_gen5: FIGHTERS_GENERATION_5,
  fighters_gen4_5: FIGHTERS_GENERATION_4_5,
  attack_aircraft: ATTACK_AIRCRAFT,
  bombers: BOMBERS,
  transport: TRANSPORT_AIRCRAFT,
  helicopters: HELICOPTERS,
  naval_ships: NAVAL_SHIPS,
  ground_vehicles: GROUND_VEHICLES,
  weapon_systems: WEAPON_SYSTEMS_EXTENDED,
} as const;

// Helper function to get total count
export function getTotalEquipmentCount() {
  return (
    Object.keys(FIGHTERS_GENERATION_5).length +
    Object.keys(FIGHTERS_GENERATION_4_5).length +
    Object.keys(ATTACK_AIRCRAFT).length +
    Object.keys(BOMBERS).length +
    Object.keys(TRANSPORT_AIRCRAFT).length +
    Object.keys(HELICOPTERS).length +
    Object.keys(NAVAL_SHIPS).length +
    Object.keys(GROUND_VEHICLES).length +
    Object.keys(WEAPON_SYSTEMS_EXTENDED).length
  );
}
