// src/lib/small-arms-equipment.ts
// COMPREHENSIVE SMALL ARMS & TACTICAL EQUIPMENT DATABASE (370+ Items)
// For Unit Equipment Browser - Personal Weapons, Support Weapons, Tactical Gear

// ===========================
// SMALL ARMS MANUFACTURERS
// ===========================

export const SMALL_ARMS_MANUFACTURERS = {
  // United States
  COLT: { name: "Colt Defense", country: "USA", specialty: ["rifles", "pistols"] },
  FN_USA: {
    name: "FN America",
    country: "USA/Belgium",
    specialty: ["rifles", "machine_guns", "pistols"],
  },
  HECKLER_KOCH: {
    name: "Heckler & Koch",
    country: "Germany",
    specialty: ["rifles", "pistols", "submachine_guns"],
  },
  SIG_SAUER: { name: "SIG Sauer", country: "USA/Switzerland", specialty: ["pistols", "rifles"] },
  GLOCK: { name: "Glock", country: "Austria", specialty: ["pistols"] },
  BERETTA: { name: "Beretta", country: "Italy", specialty: ["pistols", "rifles", "shotguns"] },
  REMINGTON: { name: "Remington Arms", country: "USA", specialty: ["rifles", "shotguns"] },
  BARRETT: { name: "Barrett Firearms", country: "USA", specialty: ["sniper_rifles"] },
  SPRINGFIELD: { name: "Springfield Armory", country: "USA", specialty: ["pistols", "rifles"] },
  SMITH_WESSON: { name: "Smith & Wesson", country: "USA", specialty: ["pistols", "revolvers"] },
  RUGER: { name: "Sturm, Ruger & Co.", country: "USA", specialty: ["pistols", "rifles"] },
  MOSSBERG: { name: "O.F. Mossberg & Sons", country: "USA", specialty: ["shotguns"] },
  BENELLI: { name: "Benelli Armi", country: "Italy", specialty: ["shotguns"] },
  WINCHESTER: {
    name: "Winchester Repeating Arms",
    country: "USA",
    specialty: ["rifles", "shotguns"],
  },

  // European
  STEYR: { name: "Steyr Mannlicher", country: "Austria", specialty: ["rifles", "pistols"] },
  CZ: { name: "Česká zbrojovka", country: "Czech Republic", specialty: ["pistols", "rifles"] },
  ACCURACY_INT: { name: "Accuracy International", country: "UK", specialty: ["sniper_rifles"] },
  IWI: {
    name: "Israel Weapon Industries",
    country: "Israel",
    specialty: ["rifles", "submachine_guns"],
  },
  WALTHER: { name: "Carl Walther GmbH", country: "Germany", specialty: ["pistols"] },
  SAKO: { name: "Sako Ltd", country: "Finland", specialty: ["sniper_rifles"] },
  TIKKA: { name: "Tikka", country: "Finland", specialty: ["rifles"] },
  SIG_SWISS: { name: "SIG Switzerland", country: "Switzerland", specialty: ["rifles"] },
  BRUGGER_THOMET: {
    name: "Brügger & Thomet",
    country: "Switzerland",
    specialty: ["submachine_guns"],
  },

  // Russian/Eastern
  IZHMASH: {
    name: "Kalashnikov Concern",
    country: "Russia",
    specialty: ["rifles", "machine_guns"],
  },
  TULA: { name: "Tula Arms Plant", country: "Russia", specialty: ["pistols", "rifles"] },
  ZASTAVA: { name: "Zastava Arms", country: "Serbia", specialty: ["rifles", "pistols"] },

  // Asian
  NORINCO: { name: "NORINCO", country: "China", specialty: ["rifles", "pistols"] },
  DAEWOO: { name: "S&T Daewoo", country: "South Korea", specialty: ["rifles"] },
  HOWA: { name: "Howa Machinery", country: "Japan", specialty: ["rifles"] },

  // Other
  GENERAL_DYNAMICS: { name: "General Dynamics", country: "USA", specialty: ["equipment", "armor"] },
  RAYTHEON: { name: "Raytheon Technologies", country: "USA", specialty: ["optics", "missiles"] },
  ELBIT: { name: "Elbit Systems", country: "Israel", specialty: ["optics", "electronics"] },
  THALES: { name: "Thales Group", country: "France", specialty: ["electronics", "missiles"] },
  SAAB: { name: "Saab AB", country: "Sweden", specialty: ["weapons", "electronics"] },
} as const;

// ===========================
// TIME PERIODS / ERAS
// ===========================

export const WEAPON_ERAS = {
  WWII: { label: "World War II Era (1939-1945)", years: "1939-1945", reliability: 70 },
  COLD_WAR: { label: "Cold War Era (1946-1991)", years: "1946-1991", reliability: 80 },
  MODERN: { label: "Modern Era (1992-2010)", years: "1992-2010", reliability: 90 },
  CONTEMPORARY: { label: "Contemporary (2011-Present)", years: "2011-Present", reliability: 95 },
} as const;

// ===========================
// PISTOLS & SIDEARMS (40+ Items)
// ===========================

export const PISTOLS = {
  // Standard Service Pistols - USA
  M9_BERETTA: {
    name: "Beretta M9",
    manufacturer: "BERETTA",
    category: "Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 15,
    effectiveRange: 50, // meters
    fireRate: 0, // semi-auto
    weight: 0.97, // kg
    unitCost: 650,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/M9-pistolet.jpg/1280px-M9-pistolet.jpg",
  },
  M11_SIG: {
    name: "SIG Sauer P228/M11",
    manufacturer: "SIG_SAUER",
    category: "Compact Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 13,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.83,
    unitCost: 800,
    maintenanceCost: 25,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/SIG_Pro_by_Augustas_Didzgalvis.jpg/1280px-SIG_Pro_by_Augustas_Didzgalvis.jpg",
  },
  M17_M18: {
    name: "SIG Sauer M17/M18 (MHS)",
    manufacturer: "SIG_SAUER",
    category: "Modular Service Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 17,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.84,
    unitCost: 900,
    maintenanceCost: 30,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/SIG_Sauer_M17.jpg/1280px-SIG_Sauer_M17.jpg",
  },
  M1911_A1: {
    name: "Colt M1911A1",
    manufacturer: "COLT",
    category: "Classic Service Pistol",
    era: "WWII",
    caliber: ".45 ACP",
    capacity: 7,
    effectiveRange: 50,
    fireRate: 0,
    weight: 1.1,
    unitCost: 850,
    maintenanceCost: 25,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/M1911A1.png/1280px-M1911A1.png",
  },

  // Glock Series
  GLOCK_17: {
    name: "Glock 17",
    manufacturer: "GLOCK",
    category: "Polymer Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 17,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.71,
    unitCost: 600,
    maintenanceCost: 15,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Glock_17_4th_Gen.jpg/1280px-Glock_17_4th_Gen.jpg",
  },
  GLOCK_19: {
    name: "Glock 19",
    manufacturer: "GLOCK",
    category: "Compact Polymer Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 15,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.68,
    unitCost: 600,
    maintenanceCost: 15,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Glock19_wObLight.jpg/1280px-Glock19_wObLight.jpg",
  },
  GLOCK_22: {
    name: "Glock 22",
    manufacturer: "GLOCK",
    category: "Polymer Service Pistol",
    era: "MODERN",
    caliber: ".40 S&W",
    capacity: 15,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.75,
    unitCost: 620,
    maintenanceCost: 18,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Glock_22.jpg/1280px-Glock_22.jpg",
  },

  // European Pistols
  HK_USP: {
    name: "Heckler & Koch USP",
    manufacturer: "HECKLER_KOCH",
    category: "Service Pistol",
    era: "MODERN",
    caliber: "9x19mm / .45 ACP",
    capacity: 15,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.77,
    unitCost: 950,
    maintenanceCost: 28,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Heckler_%26_Koch_USP_9mm_Luger.jpg/1280px-Heckler_%26_Koch_USP_9mm_Luger.jpg",
  },
  HK_VP9: {
    name: "Heckler & Koch VP9",
    manufacturer: "HECKLER_KOCH",
    category: "Striker-Fired Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 15,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.72,
    unitCost: 800,
    maintenanceCost: 25,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/HK_VP9_Pistol.jpg/1280px-HK_VP9_Pistol.jpg",
  },
  CZ_75: {
    name: "CZ 75",
    manufacturer: "CZ",
    category: "Service Pistol",
    era: "COLD_WAR",
    caliber: "9x19mm Parabellum",
    capacity: 16,
    effectiveRange: 50,
    fireRate: 0,
    weight: 1.0,
    unitCost: 650,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/CZ_75_B.jpg/1280px-CZ_75_B.jpg",
  },

  // Russian/Eastern
  MAKAROV_PM: {
    name: "Makarov PM",
    manufacturer: "IZHMASH",
    category: "Compact Service Pistol",
    era: "COLD_WAR",
    caliber: "9x18mm Makarov",
    capacity: 8,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.73,
    unitCost: 300,
    maintenanceCost: 10,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Makarov_pm.jpg/1280px-Makarov_pm.jpg",
  },
  PSM: {
    name: "PSM Pistol",
    manufacturer: "TULA",
    category: "Compact Pistol",
    era: "COLD_WAR",
    caliber: "5.45x18mm",
    capacity: 8,
    effectiveRange: 25,
    fireRate: 0,
    weight: 0.46,
    unitCost: 250,
    maintenanceCost: 8,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/PSM_pistol.jpg/1280px-PSM_pistol.jpg",
  },
  MP443_GRACH: {
    name: "MP-443 Grach",
    manufacturer: "IZHMASH",
    category: "Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 17,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.95,
    unitCost: 500,
    maintenanceCost: 18,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/MP-443_Grach.jpg/1280px-MP-443_Grach.jpg",
  },

  // Specialized/Compact
  FN_FIVE_SEVEN: {
    name: "FN Five-seveN",
    manufacturer: "FN_USA",
    category: "PDW Pistol",
    era: "MODERN",
    caliber: "5.7x28mm",
    capacity: 20,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.74,
    unitCost: 1200,
    maintenanceCost: 35,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/FiveseveN_MK2_Pistol_USG_model.jpg/1280px-FiveseveN_MK2_Pistol_USG_model.jpg",
  },
  DESERT_EAGLE: {
    name: "Desert Eagle",
    manufacturer: "IWI",
    category: "Heavy Pistol",
    era: "MODERN",
    caliber: ".50 AE / .44 Magnum",
    capacity: 7,
    effectiveRange: 100,
    fireRate: 0,
    weight: 1.99,
    unitCost: 1800,
    maintenanceCost: 50,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Desert-Eagle-p1030134.jpg/1280px-Desert-Eagle-p1030134.jpg",
  },

  // Additional Pistols - Expanded Coverage
  WALTHER_P38: {
    name: "Walther P38",
    manufacturer: "WALTHER",
    category: "Service Pistol",
    era: "WWII",
    caliber: "9x19mm Parabellum",
    capacity: 8,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.96,
    unitCost: 700,
    maintenanceCost: 22,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Pistole_P38.jpg/1280px-Pistole_P38.jpg",
  },
  WALTHER_PPK: {
    name: "Walther PPK",
    manufacturer: "WALTHER",
    category: "Compact Pistol",
    era: "WWII",
    caliber: ".380 ACP",
    capacity: 7,
    effectiveRange: 25,
    fireRate: 0,
    weight: 0.59,
    unitCost: 650,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Walther_PPK.jpg/1280px-Walther_PPK.jpg",
  },
  WALTHER_P99: {
    name: "Walther P99",
    manufacturer: "WALTHER",
    category: "Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 15,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.71,
    unitCost: 750,
    maintenanceCost: 24,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Walther-P99-Pistol.jpg/1280px-Walther-P99-Pistol.jpg",
  },
  SPRINGFIELD_XD: {
    name: "Springfield XD",
    manufacturer: "SPRINGFIELD",
    category: "Polymer Service Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm / .40 S&W",
    capacity: 16,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.78,
    unitCost: 550,
    maintenanceCost: 18,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Springfield_Armory_XD.jpg/1280px-Springfield_Armory_XD.jpg",
  },
  SPRINGFIELD_1911: {
    name: "Springfield 1911",
    manufacturer: "SPRINGFIELD",
    category: "Classic Service Pistol",
    era: "MODERN",
    caliber: ".45 ACP",
    capacity: 7,
    effectiveRange: 50,
    fireRate: 0,
    weight: 1.08,
    unitCost: 900,
    maintenanceCost: 28,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Springfield_1911_Loaded.jpg/1280px-Springfield_1911_Loaded.jpg",
  },
  SW_MP: {
    name: "Smith & Wesson M&P",
    manufacturer: "SMITH_WESSON",
    category: "Polymer Service Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm / .40 S&W",
    capacity: 17,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.68,
    unitCost: 600,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Smith_%26_Wesson_M%26P.jpg/1280px-Smith_%26_Wesson_M%26P.jpg",
  },
  SW_686: {
    name: "Smith & Wesson 686",
    manufacturer: "SMITH_WESSON",
    category: "Revolver",
    era: "MODERN",
    caliber: ".357 Magnum",
    capacity: 6,
    effectiveRange: 50,
    fireRate: 0,
    weight: 1.13,
    unitCost: 850,
    maintenanceCost: 26,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Smith_%26_Wesson_686.jpg/1280px-Smith_%26_Wesson_686.jpg",
  },
  SW_500: {
    name: "Smith & Wesson Model 500",
    manufacturer: "SMITH_WESSON",
    category: "Heavy Revolver",
    era: "CONTEMPORARY",
    caliber: ".500 S&W Magnum",
    capacity: 5,
    effectiveRange: 100,
    fireRate: 0,
    weight: 2.04,
    unitCost: 1400,
    maintenanceCost: 42,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/S%26W_500_4inch.jpg/1280px-S%26W_500_4inch.jpg",
  },
  RUGER_SR9: {
    name: "Ruger SR9",
    manufacturer: "RUGER",
    category: "Service Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 17,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.75,
    unitCost: 500,
    maintenanceCost: 16,
  },
  RUGER_GP100: {
    name: "Ruger GP100",
    manufacturer: "RUGER",
    category: "Revolver",
    era: "MODERN",
    caliber: ".357 Magnum",
    capacity: 6,
    effectiveRange: 50,
    fireRate: 0,
    weight: 1.13,
    unitCost: 750,
    maintenanceCost: 24,
  },
  CZ_P10: {
    name: "CZ P-10",
    manufacturer: "CZ",
    category: "Striker-Fired Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 15,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.73,
    unitCost: 550,
    maintenanceCost: 18,
  },
  CZ_SHADOW_2: {
    name: "CZ Shadow 2",
    manufacturer: "CZ",
    category: "Competition Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 17,
    effectiveRange: 50,
    fireRate: 0,
    weight: 1.16,
    unitCost: 1200,
    maintenanceCost: 36,
  },
  TOKAREV_TT33: {
    name: "Tokarev TT-33",
    manufacturer: "TULA",
    category: "Service Pistol",
    era: "WWII",
    caliber: "7.62x25mm Tokarev",
    capacity: 8,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.85,
    unitCost: 250,
    maintenanceCost: 10,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/TT-33.jpg/1280px-TT-33.jpg",
  },
  STECHKIN_APS: {
    name: "Stechkin APS",
    manufacturer: "TULA",
    category: "Machine Pistol",
    era: "COLD_WAR",
    caliber: "9x18mm Makarov",
    capacity: 20,
    effectiveRange: 50,
    fireRate: 750,
    weight: 1.03,
    unitCost: 600,
    maintenanceCost: 22,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/APS_pistol.jpg/1280px-APS_pistol.jpg",
  },
  JERICHO_941: {
    name: "IWI Jericho 941",
    manufacturer: "IWI",
    category: "Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 16,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.99,
    unitCost: 700,
    maintenanceCost: 22,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Jericho_941.jpg/1280px-Jericho_941.jpg",
  },
  QSZ92: {
    name: "QSZ-92",
    manufacturer: "NORINCO",
    category: "Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 15,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.76,
    unitCost: 400,
    maintenanceCost: 14,
  },
  STEYR_M9: {
    name: "Steyr M9-A1",
    manufacturer: "STEYR",
    category: "Service Pistol",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 17,
    effectiveRange: 50,
    fireRate: 0,
    weight: 0.78,
    unitCost: 650,
    maintenanceCost: 20,
  },
} as const;

// ===========================
// ASSAULT RIFLES (50+ Items)
// ===========================

export const ASSAULT_RIFLES = {
  // M16/M4 Family - USA
  M16A4: {
    name: "M16A4 Rifle",
    manufacturer: "COLT",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 550,
    fireRate: 700, // rounds per minute
    weight: 3.4,
    unitCost: 1200,
    maintenanceCost: 60,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/M16A4_Rifle.jpg/1280px-M16A4_Rifle.jpg",
  },
  M4_CARBINE: {
    name: "M4 Carbine",
    manufacturer: "COLT",
    category: "Carbine",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 750,
    weight: 3.0,
    unitCost: 1500,
    maintenanceCost: 70,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/M4_Carbine_Flat_Dark_Earth.png/1280px-M4_Carbine_Flat_Dark_Earth.png",
  },
  M4A1_SOPMOD: {
    name: "M4A1 SOPMOD II",
    manufacturer: "COLT",
    category: "Special Operations Carbine",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 750,
    weight: 3.4,
    unitCost: 2500,
    maintenanceCost: 100,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PEO_M4_Carbine_RAS_M68_CCO.jpg/1280px-PEO_M4_Carbine_RAS_M68_CCO.jpg",
  },
  HK416: {
    name: "Heckler & Koch HK416",
    manufacturer: "HECKLER_KOCH",
    category: "Assault Rifle",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 600,
    fireRate: 850,
    weight: 3.6,
    unitCost: 3200,
    maintenanceCost: 120,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/HK416.svg/1280px-HK416.svg.png",
  },

  // AK Family - Russia/Eastern
  AK47: {
    name: "AK-47",
    manufacturer: "IZHMASH",
    category: "Assault Rifle",
    era: "COLD_WAR",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 380,
    fireRate: 600,
    weight: 3.5,
    unitCost: 400,
    maintenanceCost: 25,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/AK-47_type_II_Part_DM-ST-89-01131.jpg/1280px-AK-47_type_II_Part_DM-ST-89-01131.jpg",
  },
  AKM: {
    name: "AKM",
    manufacturer: "IZHMASH",
    category: "Assault Rifle",
    era: "COLD_WAR",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 600,
    weight: 3.1,
    unitCost: 450,
    maintenanceCost: 28,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/AKM_automatrifle.png/1280px-AKM_automatrifle.png",
  },
  AK74: {
    name: "AK-74",
    manufacturer: "IZHMASH",
    category: "Assault Rifle",
    era: "COLD_WAR",
    caliber: "5.45x39mm",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 650,
    weight: 3.3,
    unitCost: 500,
    maintenanceCost: 30,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/AK-74_assault_rifle.jpg/1280px-AK-74_assault_rifle.jpg",
  },
  AK74M: {
    name: "AK-74M",
    manufacturer: "IZHMASH",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "5.45x39mm",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 650,
    weight: 3.4,
    unitCost: 700,
    maintenanceCost: 40,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/AK-74M_bw.jpg/1280px-AK-74M_bw.jpg",
  },
  AK12: {
    name: "AK-12",
    manufacturer: "IZHMASH",
    category: "Assault Rifle",
    era: "CONTEMPORARY",
    caliber: "5.45x39mm / 7.62x39mm",
    capacity: 30,
    effectiveRange: 600,
    fireRate: 700,
    weight: 3.3,
    unitCost: 1200,
    maintenanceCost: 60,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/6P70_9x39_automatic_rifle_-_2013-01.jpg/1280px-6P70_9x39_automatic_rifle_-_2013-01.jpg",
  },
  AK15: {
    name: "AK-15",
    manufacturer: "IZHMASH",
    category: "Assault Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 600,
    fireRate: 700,
    weight: 3.5,
    unitCost: 1300,
    maintenanceCost: 65,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/AK-15_%282%29.jpg/1280px-AK-15_%282%29.jpg",
  },

  // European Rifles
  FN_SCAR_L: {
    name: "FN SCAR-L",
    manufacturer: "FN_USA",
    category: "Special Operations Rifle",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 600,
    fireRate: 625,
    weight: 3.3,
    unitCost: 3500,
    maintenanceCost: 140,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FN_SCAR-L.jpg/1280px-FN_SCAR-L.jpg",
  },
  FN_SCAR_H: {
    name: "FN SCAR-H",
    manufacturer: "FN_USA",
    category: "Battle Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 625,
    weight: 3.6,
    unitCost: 3800,
    maintenanceCost: 150,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/FN_SCAR-H_STD.jpg/1280px-FN_SCAR-H_STD.jpg",
  },
  HK_G36: {
    name: "Heckler & Koch G36",
    manufacturer: "HECKLER_KOCH",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 800,
    fireRate: 750,
    weight: 3.6,
    unitCost: 2200,
    maintenanceCost: 90,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/G36KV_sideview.jpg/1280px-G36KV_sideview.jpg",
  },
  STEYR_AUG: {
    name: "Steyr AUG",
    manufacturer: "STEYR",
    category: "Bullpup Rifle",
    era: "COLD_WAR",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 680,
    weight: 3.6,
    unitCost: 1800,
    maintenanceCost: 75,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Steyr_AUG_A1_508mm_04.jpg/1280px-Steyr_AUG_A1_508mm_04.jpg",
  },
  FAMAS: {
    name: "FAMAS F1",
    manufacturer: "BERETTA",
    category: "Bullpup Rifle",
    era: "COLD_WAR",
    caliber: "5.56x45mm NATO",
    capacity: 25,
    effectiveRange: 450,
    fireRate: 1100,
    weight: 3.6,
    unitCost: 1500,
    maintenanceCost: 70,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FAMAS_F1.jpg/1280px-FAMAS_F1.jpg",
  },
  SA80_A2: {
    name: "L85A2 (SA80)",
    manufacturer: "BAE_SYSTEMS",
    category: "Bullpup Rifle",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 650,
    weight: 4.0,
    unitCost: 2000,
    maintenanceCost: 80,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/SA80_AR-L85A1.png/1280px-SA80_AR-L85A1.png",
  },

  // Israeli
  TAVOR_X95: {
    name: "IWI Tavor X95",
    manufacturer: "IWI",
    category: "Bullpup Rifle",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 550,
    fireRate: 800,
    weight: 3.3,
    unitCost: 2400,
    maintenanceCost: 95,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/IWI-Tavor-X95-5.56.jpg/1280px-IWI-Tavor-X95-5.56.jpg",
  },
  GALIL_ACE: {
    name: "IWI Galil ACE",
    manufacturer: "IWI",
    category: "Assault Rifle",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm / 7.62x39mm",
    capacity: 35,
    effectiveRange: 550,
    fireRate: 650,
    weight: 3.4,
    unitCost: 1800,
    maintenanceCost: 75,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Galil_ACE_31.jpg/1280px-Galil_ACE_31.jpg",
  },

  // Asian
  QBZ95: {
    name: "QBZ-95",
    manufacturer: "NORINCO",
    category: "Bullpup Rifle",
    era: "MODERN",
    caliber: "5.8x42mm",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 650,
    weight: 3.3,
    unitCost: 900,
    maintenanceCost: 45,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/QBZ-95_automatic_rifle_20170902.jpg/1280px-QBZ-95_automatic_rifle_20170902.jpg",
  },
  K2_RIFLE: {
    name: "Daewoo K2",
    manufacturer: "DAEWOO",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 460,
    fireRate: 750,
    weight: 3.3,
    unitCost: 1100,
    maintenanceCost: 55,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Daewoo_Precision_Industries_K2_Assault_Rifle.png/1280px-Daewoo_Precision_Industries_K2_Assault_Rifle.png",
  },

  // Additional Assault Rifles - Expanded
  SIG_SG550: {
    name: "SIG SG 550",
    manufacturer: "SIG_SWISS",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 700,
    weight: 3.9,
    unitCost: 2200,
    maintenanceCost: 88,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/SIG_SG_550.jpg/1280px-SIG_SG_550.jpg",
  },
  SIG_MCX: {
    name: "SIG MCX",
    manufacturer: "SIG_SAUER",
    category: "Modular Carbine",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm / .300 BLK",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 800,
    weight: 3.1,
    unitCost: 2800,
    maintenanceCost: 110,
  },
  SIG_MPX: {
    name: "SIG MPX",
    manufacturer: "SIG_SAUER",
    category: "Submachine Gun / Carbine",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 30,
    effectiveRange: 200,
    fireRate: 850,
    weight: 2.7,
    unitCost: 2400,
    maintenanceCost: 95,
  },
  AK103: {
    name: "AK-103",
    manufacturer: "IZHMASH",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 600,
    weight: 3.4,
    unitCost: 800,
    maintenanceCost: 38,
  },
  AK104: {
    name: "AK-104",
    manufacturer: "IZHMASH",
    category: "Compact Assault Rifle",
    era: "MODERN",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 350,
    fireRate: 600,
    weight: 3.0,
    unitCost: 850,
    maintenanceCost: 40,
  },
  AK105: {
    name: "AK-105",
    manufacturer: "IZHMASH",
    category: "Compact Assault Rifle",
    era: "MODERN",
    caliber: "5.45x39mm",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 650,
    weight: 2.9,
    unitCost: 800,
    maintenanceCost: 38,
  },
  AKS74U: {
    name: "AKS-74U",
    manufacturer: "IZHMASH",
    category: "Compact Assault Rifle",
    era: "COLD_WAR",
    caliber: "5.45x39mm",
    capacity: 30,
    effectiveRange: 300,
    fireRate: 700,
    weight: 2.7,
    unitCost: 600,
    maintenanceCost: 32,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/AKS-74U.jpg/1280px-AKS-74U.jpg",
  },
  ZASTAVA_M70: {
    name: "Zastava M70",
    manufacturer: "ZASTAVA",
    category: "Assault Rifle",
    era: "COLD_WAR",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 620,
    weight: 3.7,
    unitCost: 450,
    maintenanceCost: 24,
  },
  VZ58: {
    name: "Vz. 58",
    manufacturer: "CZ",
    category: "Assault Rifle",
    era: "COLD_WAR",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 800,
    weight: 2.9,
    unitCost: 700,
    maintenanceCost: 34,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Vz_58.jpg/1280px-Vz_58.jpg",
  },
  CZ_BREN_2: {
    name: "CZ Bren 2",
    manufacturer: "CZ",
    category: "Modular Assault Rifle",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm / 7.62x39mm",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 750,
    weight: 3.2,
    unitCost: 1800,
    maintenanceCost: 72,
  },
  QBZ03: {
    name: "QBZ-03",
    manufacturer: "NORINCO",
    category: "Assault Rifle",
    era: "CONTEMPORARY",
    caliber: "5.8x42mm",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 650,
    weight: 3.4,
    unitCost: 950,
    maintenanceCost: 46,
  },
  TYPE_56: {
    name: "Type 56",
    manufacturer: "NORINCO",
    category: "Assault Rifle",
    era: "COLD_WAR",
    caliber: "7.62x39mm",
    capacity: 30,
    effectiveRange: 380,
    fireRate: 600,
    weight: 3.8,
    unitCost: 350,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Type_56_Rifle.jpg/1280px-Type_56_Rifle.jpg",
  },
  K1_CARBINE: {
    name: "Daewoo K1",
    manufacturer: "DAEWOO",
    category: "Carbine",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 350,
    fireRate: 750,
    weight: 2.9,
    unitCost: 1000,
    maintenanceCost: 48,
  },
  TYPE_89: {
    name: "Howa Type 89",
    manufacturer: "HOWA",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 750,
    weight: 3.5,
    unitCost: 1400,
    maintenanceCost: 58,
  },
  FNC: {
    name: "FN FNC",
    manufacturer: "FN_USA",
    category: "Assault Rifle",
    era: "COLD_WAR",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 650,
    weight: 3.8,
    unitCost: 1200,
    maintenanceCost: 52,
  },
  INSAS: {
    name: "INSAS Rifle",
    manufacturer: "NORINCO",
    category: "Assault Rifle",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 400,
    fireRate: 650,
    weight: 3.2,
    unitCost: 600,
    maintenanceCost: 28,
  },
  ARX160: {
    name: "Beretta ARX160",
    manufacturer: "BERETTA",
    category: "Modular Assault Rifle",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 500,
    fireRate: 700,
    weight: 3.0,
    unitCost: 2000,
    maintenanceCost: 80,
  },
  MK18: {
    name: "Mk 18 CQBR",
    manufacturer: "COLT",
    category: "Close Quarters Carbine",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 30,
    effectiveRange: 350,
    fireRate: 750,
    weight: 2.9,
    unitCost: 2200,
    maintenanceCost: 88,
  },
} as const;

// ===========================
// BATTLE RIFLES & DMRs (20+ Items)
// ===========================

export const BATTLE_RIFLES = {
  M14_EBR: {
    name: "M14 EBR",
    manufacturer: "COLT",
    category: "Designated Marksman Rifle",
    era: "MODERN",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 750,
    weight: 5.1,
    unitCost: 3500,
    maintenanceCost: 140,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/M14_rifle_-_USA_-_7.62x51mm_-_Legermuseet.jpg/1280px-M14_rifle_-_USA_-_7.62x51mm_-_Legermuseet.jpg",
  },
  SR25: {
    name: "SR-25",
    manufacturer: "HECKLER_KOCH",
    category: "Semi-Automatic Sniper Rifle",
    era: "MODERN",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 1000,
    fireRate: 0,
    weight: 4.9,
    unitCost: 6500,
    maintenanceCost: 200,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/PEO_KAC_SR-25.jpg/1280px-PEO_KAC_SR-25.jpg",
  },
  MK17_SCAR_H: {
    name: "Mk 17 SCAR-H",
    manufacturer: "FN_USA",
    category: "Battle Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 625,
    weight: 3.6,
    unitCost: 3800,
    maintenanceCost: 150,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/FN_SCAR-H_STD.jpg/1280px-FN_SCAR-H_STD.jpg",
  },
  HK417: {
    name: "Heckler & Koch HK417",
    manufacturer: "HECKLER_KOCH",
    category: "Battle Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 600,
    weight: 4.2,
    unitCost: 4200,
    maintenanceCost: 160,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Heckler_and_Koch_HK417.JPG/1280px-Heckler_and_Koch_HK417.JPG",
  },
  FAL: {
    name: "FN FAL",
    manufacturer: "FN_USA",
    category: "Battle Rifle",
    era: "COLD_WAR",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 600,
    fireRate: 650,
    weight: 4.3,
    unitCost: 1200,
    maintenanceCost: 60,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/FN_FAL_rifle.jpg/1280px-FN_FAL_rifle.jpg",
  },
  G3: {
    name: "Heckler & Koch G3",
    manufacturer: "HECKLER_KOCH",
    category: "Battle Rifle",
    era: "COLD_WAR",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 600,
    fireRate: 550,
    weight: 4.4,
    unitCost: 1000,
    maintenanceCost: 50,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/G3A3.jpeg/1280px-G3A3.jpeg",
  },
  SVD_DRAGUNOV: {
    name: "SVD Dragunov",
    manufacturer: "IZHMASH",
    category: "Designated Marksman Rifle",
    era: "COLD_WAR",
    caliber: "7.62x54mmR",
    capacity: 10,
    effectiveRange: 800,
    fireRate: 0,
    weight: 4.3,
    unitCost: 2000,
    maintenanceCost: 80,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Dragunov_Sniper_Rifle.jpg/1280px-Dragunov_Sniper_Rifle.jpg",
  },

  // Additional Battle Rifles
  M110_SASS: {
    name: "M110 SASS",
    manufacturer: "HECKLER_KOCH",
    category: "Semi-Automatic Sniper System",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 0,
    weight: 6.9,
    unitCost: 7500,
    maintenanceCost: 240,
  },
  SCAR_20S: {
    name: "FN SCAR 20S",
    manufacturer: "FN_USA",
    category: "Precision Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 0,
    weight: 4.5,
    unitCost: 4500,
    maintenanceCost: 180,
  },
  AR10: {
    name: "AR-10",
    manufacturer: "COLT",
    category: "Battle Rifle",
    era: "COLD_WAR",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 600,
    fireRate: 700,
    weight: 4.0,
    unitCost: 1800,
    maintenanceCost: 75,
  },
  MK20_SSR: {
    name: "Mk 20 SSR",
    manufacturer: "FN_USA",
    category: "Sniper Support Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 900,
    fireRate: 0,
    weight: 5.9,
    unitCost: 5200,
    maintenanceCost: 200,
  },
  SVDM: {
    name: "SVDM",
    manufacturer: "IZHMASH",
    category: "Designated Marksman Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x54mmR",
    capacity: 10,
    effectiveRange: 800,
    fireRate: 0,
    weight: 5.3,
    unitCost: 3000,
    maintenanceCost: 120,
  },
  VSS_VINTOREZ: {
    name: "VSS Vintorez",
    manufacturer: "TULA",
    category: "Suppressed Sniper Rifle",
    era: "COLD_WAR",
    caliber: "9x39mm",
    capacity: 10,
    effectiveRange: 400,
    fireRate: 0,
    weight: 2.6,
    unitCost: 2500,
    maintenanceCost: 95,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/VSS_Vintorez.jpg/1280px-VSS_Vintorez.jpg",
  },
  AS_VAL: {
    name: "AS Val",
    manufacturer: "TULA",
    category: "Suppressed Assault Rifle",
    era: "COLD_WAR",
    caliber: "9x39mm",
    capacity: 20,
    effectiveRange: 400,
    fireRate: 900,
    weight: 2.5,
    unitCost: 2200,
    maintenanceCost: 88,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/AS_Val.jpg/1280px-AS_Val.jpg",
  },
  QBU88: {
    name: "QBU-88",
    manufacturer: "NORINCO",
    category: "Designated Marksman Rifle",
    era: "MODERN",
    caliber: "5.8x42mm",
    capacity: 10,
    effectiveRange: 800,
    fireRate: 0,
    weight: 4.2,
    unitCost: 1800,
    maintenanceCost: 72,
  },
} as const;

// ===========================
// SNIPER RIFLES (25+ Items)
// ===========================

export const SNIPER_RIFLES = {
  // Bolt-Action - USA
  M24_SWS: {
    name: "M24 SWS",
    manufacturer: "REMINGTON",
    category: "Sniper Rifle",
    era: "MODERN",
    caliber: "7.62x51mm NATO",
    capacity: 5,
    effectiveRange: 800,
    fireRate: 0,
    weight: 5.5,
    unitCost: 5500,
    maintenanceCost: 180,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/PEO_M24_Sniper_Weapon_System.jpg/1280px-PEO_M24_Sniper_Weapon_System.jpg",
  },
  M40_A5: {
    name: "M40A5",
    manufacturer: "REMINGTON",
    category: "Sniper Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 5,
    effectiveRange: 1000,
    fireRate: 0,
    weight: 7.5,
    unitCost: 11000,
    maintenanceCost: 300,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/M40A1_USMC_sniper_rifle.png/1280px-M40A1_USMC_sniper_rifle.png",
  },
  M2010_ESR: {
    name: "M2010 Enhanced Sniper Rifle",
    manufacturer: "REMINGTON",
    category: "Sniper Rifle",
    era: "CONTEMPORARY",
    caliber: ".300 Winchester Magnum",
    capacity: 5,
    effectiveRange: 1200,
    fireRate: 0,
    weight: 7.5,
    unitCost: 15000,
    maintenanceCost: 400,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/M2010_Enhanced_Sniper_Rifle.jpg/1280px-M2010_Enhanced_Sniper_Rifle.jpg",
  },
  BARRETT_M82: {
    name: "Barrett M82A1",
    manufacturer: "BARRETT",
    category: "Anti-Materiel Rifle",
    era: "MODERN",
    caliber: ".50 BMG",
    capacity: 10,
    effectiveRange: 1800,
    fireRate: 0,
    weight: 13.5,
    unitCost: 8900,
    maintenanceCost: 280,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Barrett_M82A1.jpg/1280px-Barrett_M82A1.jpg",
  },
  BARRETT_M107: {
    name: "Barrett M107",
    manufacturer: "BARRETT",
    category: "Anti-Materiel Rifle",
    era: "CONTEMPORARY",
    caliber: ".50 BMG",
    capacity: 10,
    effectiveRange: 2000,
    fireRate: 0,
    weight: 12.9,
    unitCost: 11000,
    maintenanceCost: 350,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/M107_1.jpg/1280px-M107_1.jpg",
  },

  // European Precision Rifles
  ACCURACY_INTERNATIONAL_AWM: {
    name: "Accuracy International AWM",
    manufacturer: "ACCURACY_INT",
    category: "Sniper Rifle",
    era: "MODERN",
    caliber: ".338 Lapua Magnum",
    capacity: 5,
    effectiveRange: 1500,
    fireRate: 0,
    weight: 6.5,
    unitCost: 12000,
    maintenanceCost: 350,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Accuracy_International_AWM.jpg/1280px-Accuracy_International_AWM.jpg",
  },
  ACCURACY_INTERNATIONAL_AS50: {
    name: "Accuracy International AS50",
    manufacturer: "ACCURACY_INT",
    category: "Anti-Materiel Rifle",
    era: "CONTEMPORARY",
    caliber: ".50 BMG",
    capacity: 5,
    effectiveRange: 1800,
    fireRate: 0,
    weight: 14.1,
    unitCost: 15000,
    maintenanceCost: 450,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/AS50.jpeg/1280px-AS50.jpeg",
  },
  PSG1: {
    name: "Heckler & Koch PSG1",
    manufacturer: "HECKLER_KOCH",
    category: "Semi-Automatic Sniper Rifle",
    era: "MODERN",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 0,
    weight: 8.1,
    unitCost: 10000,
    maintenanceCost: 300,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/PSG1.JPG/1280px-PSG1.JPG",
  },

  // Russian/Eastern
  ORSIS_T5000: {
    name: "Orsis T-5000",
    manufacturer: "IZHMASH",
    category: "Sniper Rifle",
    era: "CONTEMPORARY",
    caliber: ".338 Lapua Magnum",
    capacity: 5,
    effectiveRange: 1500,
    fireRate: 0,
    weight: 6.5,
    unitCost: 9000,
    maintenanceCost: 270,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/ORSIS-T-5000.jpg/1280px-ORSIS-T-5000.jpg",
  },
  OSV96: {
    name: "OSV-96",
    manufacturer: "TULA",
    category: "Anti-Materiel Rifle",
    era: "MODERN",
    caliber: "12.7x108mm",
    capacity: 5,
    effectiveRange: 2000,
    fireRate: 0,
    weight: 12.9,
    unitCost: 7500,
    maintenanceCost: 240,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/OSV-96_sniper_rifle.jpg/1280px-OSV-96_sniper_rifle.jpg",
  },

  // Additional Sniper Rifles
  MK13_MOD7: {
    name: "Mk 13 Mod 7",
    manufacturer: "REMINGTON",
    category: "Sniper Rifle",
    era: "CONTEMPORARY",
    caliber: ".300 Winchester Magnum",
    capacity: 5,
    effectiveRange: 1300,
    fireRate: 0,
    weight: 6.8,
    unitCost: 14000,
    maintenanceCost: 420,
  },
  MK14_EBR: {
    name: "Mk 14 Enhanced Battle Rifle",
    manufacturer: "COLT",
    category: "Designated Marksman Rifle",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 750,
    weight: 5.1,
    unitCost: 4000,
    maintenanceCost: 160,
  },
  SAKO_TRG: {
    name: "Sako TRG-42",
    manufacturer: "SAKO",
    category: "Sniper Rifle",
    era: "CONTEMPORARY",
    caliber: ".338 Lapua Magnum",
    capacity: 5,
    effectiveRange: 1500,
    fireRate: 0,
    weight: 6.0,
    unitCost: 9000,
    maintenanceCost: 270,
  },
  TIKKA_T3: {
    name: "Tikka T3",
    manufacturer: "TIKKA",
    category: "Sniper Rifle",
    era: "CONTEMPORARY",
    caliber: ".308 Winchester",
    capacity: 5,
    effectiveRange: 800,
    fireRate: 0,
    weight: 3.2,
    unitCost: 3500,
    maintenanceCost: 105,
  },
  BLASER_R93: {
    name: "Blaser R93 Tactical",
    manufacturer: "HECKLER_KOCH",
    category: "Sniper Rifle",
    era: "MODERN",
    caliber: ".338 Lapua Magnum",
    capacity: 5,
    effectiveRange: 1500,
    fireRate: 0,
    weight: 5.9,
    unitCost: 11000,
    maintenanceCost: 330,
  },
  CHEYTAC_M200: {
    name: "CheyTac M200",
    manufacturer: "BARRETT",
    category: "Long Range Sniper Rifle",
    era: "CONTEMPORARY",
    caliber: ".408 CheyTac",
    capacity: 7,
    effectiveRange: 2500,
    fireRate: 0,
    weight: 14.0,
    unitCost: 18000,
    maintenanceCost: 540,
  },
  SVD_TIGR: {
    name: "SVDS (Tiger)",
    manufacturer: "IZHMASH",
    category: "Compact DMR",
    era: "MODERN",
    caliber: "7.62x54mmR",
    capacity: 10,
    effectiveRange: 800,
    fireRate: 0,
    weight: 4.4,
    unitCost: 2200,
    maintenanceCost: 88,
  },
  SVU: {
    name: "SVU Bullpup Sniper",
    manufacturer: "IZHMASH",
    category: "Bullpup Sniper Rifle",
    era: "MODERN",
    caliber: "7.62x54mmR",
    capacity: 10,
    effectiveRange: 800,
    fireRate: 0,
    weight: 4.5,
    unitCost: 2600,
    maintenanceCost: 104,
  },
  M21_SWS: {
    name: "M21 Sniper Weapon System",
    manufacturer: "COLT",
    category: "Sniper Rifle",
    era: "COLD_WAR",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 0,
    weight: 5.1,
    unitCost: 2800,
    maintenanceCost: 112,
  },
  MSG90: {
    name: "Heckler & Koch MSG90",
    manufacturer: "HECKLER_KOCH",
    category: "Sniper Rifle",
    era: "MODERN",
    caliber: "7.62x51mm NATO",
    capacity: 20,
    effectiveRange: 800,
    fireRate: 0,
    weight: 6.4,
    unitCost: 9500,
    maintenanceCost: 285,
  },
} as const;

// ===========================
// SUBMACHINE GUNS (20+ Items)
// ===========================

export const SUBMACHINE_GUNS = {
  MP5: {
    name: "Heckler & Koch MP5",
    manufacturer: "HECKLER_KOCH",
    category: "Submachine Gun",
    era: "COLD_WAR",
    caliber: "9x19mm Parabellum",
    capacity: 30,
    effectiveRange: 200,
    fireRate: 800,
    weight: 2.5,
    unitCost: 2500,
    maintenanceCost: 100,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Heckler_%26_Koch_MP5.jpg/1280px-Heckler_%26_Koch_MP5.jpg",
  },
  MP7: {
    name: "Heckler & Koch MP7",
    manufacturer: "HECKLER_KOCH",
    category: "Personal Defense Weapon",
    era: "CONTEMPORARY",
    caliber: "4.6x30mm",
    capacity: 40,
    effectiveRange: 200,
    fireRate: 950,
    weight: 1.9,
    unitCost: 3500,
    maintenanceCost: 140,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/MP7_A1.jpg/1280px-MP7_A1.jpg",
  },
  UMP45: {
    name: "Heckler & Koch UMP45",
    manufacturer: "HECKLER_KOCH",
    category: "Submachine Gun",
    era: "MODERN",
    caliber: ".45 ACP",
    capacity: 25,
    effectiveRange: 200,
    fireRate: 600,
    weight: 2.3,
    unitCost: 2200,
    maintenanceCost: 90,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Heckler_%26_Koch_UMP.jpg/1280px-Heckler_%26_Koch_UMP.jpg",
  },
  FN_P90: {
    name: "FN P90",
    manufacturer: "FN_USA",
    category: "Personal Defense Weapon",
    era: "MODERN",
    caliber: "5.7x28mm",
    capacity: 50,
    effectiveRange: 200,
    fireRate: 900,
    weight: 2.6,
    unitCost: 3200,
    maintenanceCost: 130,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/FN_P90.jpg/1280px-FN_P90.jpg",
  },
  KRISS_VECTOR: {
    name: "KRISS Vector",
    manufacturer: "FN_USA",
    category: "Submachine Gun",
    era: "CONTEMPORARY",
    caliber: ".45 ACP",
    capacity: 25,
    effectiveRange: 150,
    fireRate: 1200,
    weight: 2.7,
    unitCost: 2800,
    maintenanceCost: 110,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/KRISS_Vector.jpg/1280px-KRISS_Vector.jpg",
  },
  UZI: {
    name: "IMI Uzi",
    manufacturer: "IWI",
    category: "Submachine Gun",
    era: "COLD_WAR",
    caliber: "9x19mm Parabellum",
    capacity: 32,
    effectiveRange: 200,
    fireRate: 600,
    weight: 3.5,
    unitCost: 1200,
    maintenanceCost: 50,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Uzi_of_the_Failures_Museum.jpg/1280px-Uzi_of_the_Failures_Museum.jpg",
  },
  PP19_BIZON: {
    name: "PP-19 Bizon",
    manufacturer: "IZHMASH",
    category: "Submachine Gun",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 64,
    effectiveRange: 200,
    fireRate: 700,
    weight: 2.1,
    unitCost: 800,
    maintenanceCost: 35,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/PP-19-01_Vityaz-SN.jpg/1280px-PP-19-01_Vityaz-SN.jpg",
  },

  // Additional Submachine Guns
  MAC10: {
    name: "MAC-10",
    manufacturer: "COLT",
    category: "Compact SMG",
    era: "COLD_WAR",
    caliber: ".45 ACP",
    capacity: 30,
    effectiveRange: 100,
    fireRate: 1100,
    weight: 2.8,
    unitCost: 900,
    maintenanceCost: 36,
  },
  STERLING: {
    name: "Sterling SMG",
    manufacturer: "ACCURACY_INT",
    category: "Submachine Gun",
    era: "COLD_WAR",
    caliber: "9x19mm Parabellum",
    capacity: 34,
    effectiveRange: 200,
    fireRate: 550,
    weight: 2.7,
    unitCost: 700,
    maintenanceCost: 28,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sterling_SMG.jpg/1280px-Sterling_SMG.jpg",
  },
  MP40: {
    name: "MP 40",
    manufacturer: "WALTHER",
    category: "Submachine Gun",
    era: "WWII",
    caliber: "9x19mm Parabellum",
    capacity: 32,
    effectiveRange: 200,
    fireRate: 500,
    weight: 4.0,
    unitCost: 600,
    maintenanceCost: 24,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/MP_40.jpg/1280px-MP_40.jpg",
  },
  THOMPSON: {
    name: "Thompson M1A1",
    manufacturer: "COLT",
    category: "Submachine Gun",
    era: "WWII",
    caliber: ".45 ACP",
    capacity: 30,
    effectiveRange: 150,
    fireRate: 700,
    weight: 4.8,
    unitCost: 850,
    maintenanceCost: 34,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/M1sb.jpg/1280px-M1sb.jpg",
  },
  SKORPION: {
    name: "Škorpion vz. 61",
    manufacturer: "CZ",
    category: "Machine Pistol",
    era: "COLD_WAR",
    caliber: ".32 ACP",
    capacity: 20,
    effectiveRange: 100,
    fireRate: 850,
    weight: 1.3,
    unitCost: 500,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Vz_61.jpg/1280px-Vz_61.jpg",
  },
  SPECTRE_M4: {
    name: "Spectre M4",
    manufacturer: "BERETTA",
    category: "Submachine Gun",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 50,
    effectiveRange: 200,
    fireRate: 850,
    weight: 2.9,
    unitCost: 1500,
    maintenanceCost: 60,
  },
  PPSH41: {
    name: "PPSh-41",
    manufacturer: "TULA",
    category: "Submachine Gun",
    era: "WWII",
    caliber: "7.62x25mm Tokarev",
    capacity: 71,
    effectiveRange: 200,
    fireRate: 900,
    weight: 3.6,
    unitCost: 300,
    maintenanceCost: 15,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/PPSh-41_from_soviet.jpg/1280px-PPSh-41_from_soviet.jpg",
  },
  PPS43: {
    name: "PPS-43",
    manufacturer: "TULA",
    category: "Submachine Gun",
    era: "WWII",
    caliber: "7.62x25mm Tokarev",
    capacity: 35,
    effectiveRange: 200,
    fireRate: 700,
    weight: 3.0,
    unitCost: 250,
    maintenanceCost: 12,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/PPS_submachine_gun.jpg/1280px-PPS_submachine_gun.jpg",
  },
  MINI_UZI: {
    name: "Mini Uzi",
    manufacturer: "IWI",
    category: "Compact SMG",
    era: "MODERN",
    caliber: "9x19mm Parabellum",
    capacity: 32,
    effectiveRange: 100,
    fireRate: 950,
    weight: 2.7,
    unitCost: 1100,
    maintenanceCost: 44,
  },
  MP9: {
    name: "Brügger & Thomet MP9",
    manufacturer: "BRUGGER_THOMET",
    category: "Machine Pistol",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 30,
    effectiveRange: 100,
    fireRate: 900,
    weight: 1.4,
    unitCost: 1800,
    maintenanceCost: 72,
  },
  TYPE_05: {
    name: "Type 05",
    manufacturer: "NORINCO",
    category: "Submachine Gun",
    era: "CONTEMPORARY",
    caliber: "9x19mm Parabellum",
    capacity: 30,
    effectiveRange: 200,
    fireRate: 700,
    weight: 2.0,
    unitCost: 800,
    maintenanceCost: 32,
  },
} as const;

// ===========================
// MACHINE GUNS (25+ Items)
// ===========================

export const MACHINE_GUNS = {
  // Light Machine Guns
  M249_SAW: {
    name: "M249 SAW",
    manufacturer: "FN_USA",
    category: "Light Machine Gun",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 200, // belt-fed
    effectiveRange: 800,
    fireRate: 850,
    weight: 7.5,
    unitCost: 4500,
    maintenanceCost: 180,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/PEO_M249_Para_ACOG.jpg/1280px-PEO_M249_Para_ACOG.jpg",
  },
  M240B: {
    name: "M240B",
    manufacturer: "FN_USA",
    category: "General Purpose Machine Gun",
    era: "MODERN",
    caliber: "7.62x51mm NATO",
    capacity: 100,
    effectiveRange: 1100,
    fireRate: 750,
    weight: 12.5,
    unitCost: 6600,
    maintenanceCost: 220,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/M240_Medium_Machine_Gun.jpg/1280px-M240_Medium_Machine_Gun.jpg",
  },
  M60: {
    name: "M60 Machine Gun",
    manufacturer: "COLT",
    category: "General Purpose Machine Gun",
    era: "COLD_WAR",
    caliber: "7.62x51mm NATO",
    capacity: 100,
    effectiveRange: 1100,
    fireRate: 550,
    weight: 10.5,
    unitCost: 3000,
    maintenanceCost: 120,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/M60_GPMG.jpeg/1280px-M60_GPMG.jpeg",
  },
  M2_BROWNING: {
    name: "M2 Browning .50 Cal",
    manufacturer: "COLT",
    category: "Heavy Machine Gun",
    era: "WWII",
    caliber: ".50 BMG",
    capacity: 100,
    effectiveRange: 1800,
    fireRate: 550,
    weight: 38.1,
    unitCost: 8000,
    maintenanceCost: 280,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/M2_Browning.jpg/1280px-M2_Browning.jpg",
  },

  // European MGs
  FN_MINIMI: {
    name: "FN Minimi",
    manufacturer: "FN_USA",
    category: "Light Machine Gun",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 200,
    effectiveRange: 800,
    fireRate: 850,
    weight: 6.8,
    unitCost: 4200,
    maintenanceCost: 170,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Minimi_FN.jpg/1280px-Minimi_FN.jpg",
  },
  HK_MG4: {
    name: "Heckler & Koch MG4",
    manufacturer: "HECKLER_KOCH",
    category: "Light Machine Gun",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 200,
    effectiveRange: 800,
    fireRate: 885,
    weight: 8.5,
    unitCost: 5500,
    maintenanceCost: 200,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Heckler_%26_Koch_MG4.jpg/1280px-Heckler_%26_Koch_MG4.jpg",
  },
  MG3: {
    name: "MG3",
    manufacturer: "HECKLER_KOCH",
    category: "General Purpose Machine Gun",
    era: "COLD_WAR",
    caliber: "7.62x51mm NATO",
    capacity: 100,
    effectiveRange: 1200,
    fireRate: 1200,
    weight: 11.5,
    unitCost: 3500,
    maintenanceCost: 140,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/MG_3.jpg/1280px-MG_3.jpg",
  },

  // Russian MGs
  PKM: {
    name: "PKM",
    manufacturer: "IZHMASH",
    category: "General Purpose Machine Gun",
    era: "COLD_WAR",
    caliber: "7.62x54mmR",
    capacity: 100,
    effectiveRange: 1000,
    fireRate: 650,
    weight: 7.5,
    unitCost: 2000,
    maintenanceCost: 80,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/PKM_machine_gun_MOD_45158406.jpg/1280px-PKM_machine_gun_MOD_45158406.jpg",
  },
  RPK74: {
    name: "RPK-74",
    manufacturer: "IZHMASH",
    category: "Light Machine Gun",
    era: "COLD_WAR",
    caliber: "5.45x39mm",
    capacity: 45,
    effectiveRange: 800,
    fireRate: 600,
    weight: 5.0,
    unitCost: 1200,
    maintenanceCost: 50,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/RPK-74_NTW_12_92.jpg/1280px-RPK-74_NTW_12_92.jpg",
  },
  DSHK: {
    name: "DShK Heavy Machine Gun",
    manufacturer: "TULA",
    category: "Heavy Machine Gun",
    era: "WWII",
    caliber: "12.7x108mm",
    capacity: 50,
    effectiveRange: 2000,
    fireRate: 600,
    weight: 34.0,
    unitCost: 5000,
    maintenanceCost: 180,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/DShK_machine_gun_on_an_AA_mount.jpg/1280px-DShK_machine_gun_on_an_AA_mount.jpg",
  },

  // Additional Machine Guns
  FN_MAG: {
    name: "FN MAG",
    manufacturer: "FN_USA",
    category: "General Purpose Machine Gun",
    era: "COLD_WAR",
    caliber: "7.62x51mm NATO",
    capacity: 100,
    effectiveRange: 1100,
    fireRate: 750,
    weight: 11.8,
    unitCost: 4000,
    maintenanceCost: 160,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/FN-MAG.jpg/1280px-FN-MAG.jpg",
  },
  M249_PARA: {
    name: "M249 Para",
    manufacturer: "FN_USA",
    category: "Light Machine Gun",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm NATO",
    capacity: 200,
    effectiveRange: 800,
    fireRate: 850,
    weight: 6.9,
    unitCost: 4800,
    maintenanceCost: 192,
  },
  MG42: {
    name: "MG 42",
    manufacturer: "HECKLER_KOCH",
    category: "General Purpose Machine Gun",
    era: "WWII",
    caliber: "7.92x57mm Mauser",
    capacity: 50,
    effectiveRange: 1000,
    fireRate: 1200,
    weight: 11.6,
    unitCost: 2000,
    maintenanceCost: 80,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/MG42.jpg/1280px-MG42.jpg",
  },
  M1919_BROWNING: {
    name: "M1919 Browning",
    manufacturer: "COLT",
    category: "Medium Machine Gun",
    era: "WWII",
    caliber: ".30-06 Springfield",
    capacity: 250,
    effectiveRange: 1400,
    fireRate: 400,
    weight: 14.0,
    unitCost: 2500,
    maintenanceCost: 100,
  },
  NEGEV: {
    name: "IWI Negev",
    manufacturer: "IWI",
    category: "Light Machine Gun",
    era: "MODERN",
    caliber: "5.56x45mm NATO",
    capacity: 200,
    effectiveRange: 800,
    fireRate: 850,
    weight: 7.2,
    unitCost: 5000,
    maintenanceCost: 200,
  },
  TYPE_67: {
    name: "Type 67",
    manufacturer: "NORINCO",
    category: "General Purpose Machine Gun",
    era: "COLD_WAR",
    caliber: "7.62x54mmR",
    capacity: 100,
    effectiveRange: 1000,
    fireRate: 650,
    weight: 8.4,
    unitCost: 1800,
    maintenanceCost: 72,
  },
  QJY88: {
    name: "QJY-88",
    manufacturer: "NORINCO",
    category: "General Purpose Machine Gun",
    era: "MODERN",
    caliber: "5.8x42mm",
    capacity: 200,
    effectiveRange: 1000,
    fireRate: 650,
    weight: 7.8,
    unitCost: 3500,
    maintenanceCost: 140,
  },
  KORD: {
    name: "Kord Heavy Machine Gun",
    manufacturer: "TULA",
    category: "Heavy Machine Gun",
    era: "CONTEMPORARY",
    caliber: "12.7x108mm",
    capacity: 50,
    effectiveRange: 2000,
    fireRate: 650,
    weight: 25.5,
    unitCost: 7500,
    maintenanceCost: 240,
  },
  PECHENEG: {
    name: "Pecheneg Machine Gun",
    manufacturer: "IZHMASH",
    category: "General Purpose Machine Gun",
    era: "CONTEMPORARY",
    caliber: "7.62x54mmR",
    capacity: 100,
    effectiveRange: 1200,
    fireRate: 650,
    weight: 8.7,
    unitCost: 3000,
    maintenanceCost: 120,
  },
  MG5: {
    name: "Heckler & Koch MG5",
    manufacturer: "HECKLER_KOCH",
    category: "General Purpose Machine Gun",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm NATO",
    capacity: 100,
    effectiveRange: 1200,
    fireRate: 800,
    weight: 11.3,
    unitCost: 6500,
    maintenanceCost: 220,
  },
} as const;

// ===========================
// GRENADE LAUNCHERS (15+ Items)
// ===========================

export const GRENADE_LAUNCHERS = {
  M203: {
    name: "M203 Grenade Launcher",
    manufacturer: "COLT",
    category: "Under-Barrel Grenade Launcher",
    era: "COLD_WAR",
    caliber: "40x46mm",
    capacity: 1,
    effectiveRange: 350,
    fireRate: 0,
    weight: 1.6,
    unitCost: 1100,
    maintenanceCost: 40,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/M203_40mm-EN-2.jpg/1280px-M203_40mm-EN-2.jpg",
  },
  M320: {
    name: "M320 Grenade Launcher",
    manufacturer: "HECKLER_KOCH",
    category: "Grenade Launcher",
    era: "CONTEMPORARY",
    caliber: "40x46mm",
    capacity: 1,
    effectiveRange: 400,
    fireRate: 0,
    weight: 1.7,
    unitCost: 1500,
    maintenanceCost: 50,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/M320_Grenade_Launcher.jpg/1280px-M320_Grenade_Launcher.jpg",
  },
  MK19: {
    name: "Mk 19 Automatic Grenade Launcher",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Automatic Grenade Launcher",
    era: "MODERN",
    caliber: "40x53mm",
    capacity: 48, // belt-fed
    effectiveRange: 1600,
    fireRate: 350,
    weight: 34.5,
    unitCost: 13000,
    maintenanceCost: 400,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Mk_19_Grenade_Launcher.jpg/1280px-Mk_19_Grenade_Launcher.jpg",
  },
  AG36: {
    name: "Heckler & Koch AG36",
    manufacturer: "HECKLER_KOCH",
    category: "Under-Barrel Grenade Launcher",
    era: "MODERN",
    caliber: "40x46mm",
    capacity: 1,
    effectiveRange: 350,
    fireRate: 0,
    weight: 1.3,
    unitCost: 1200,
    maintenanceCost: 45,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/AG36-G36K.jpg/1280px-AG36-G36K.jpg",
  },
  GP25: {
    name: "GP-25 Kostyor",
    manufacturer: "IZHMASH",
    category: "Under-Barrel Grenade Launcher",
    era: "COLD_WAR",
    caliber: "40mm VOG-25",
    capacity: 1,
    effectiveRange: 400,
    fireRate: 0,
    weight: 1.5,
    unitCost: 500,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/GP-25_detached.jpg/1280px-GP-25_detached.jpg",
  },
  AGS30: {
    name: "AGS-30 Automatic Grenade Launcher",
    manufacturer: "TULA",
    category: "Automatic Grenade Launcher",
    era: "MODERN",
    caliber: "30mm VOG-17",
    capacity: 29,
    effectiveRange: 1700,
    fireRate: 400,
    weight: 16.0,
    unitCost: 8000,
    maintenanceCost: 250,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/AGS-30_on_6G15_tripod.jpg/1280px-AGS-30_on_6G15_tripod.jpg",
  },
} as const;

// ===========================
// SHOTGUNS (12+ Items)
// ===========================

export const SHOTGUNS = {
  M870: {
    name: "Remington 870",
    manufacturer: "REMINGTON",
    category: "Pump-Action Shotgun",
    era: "COLD_WAR",
    caliber: "12 gauge",
    capacity: 7,
    effectiveRange: 50,
    fireRate: 0,
    weight: 3.6,
    unitCost: 450,
    maintenanceCost: 18,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Remington_Model_870.JPG/1280px-Remington_Model_870.JPG",
  },
  M500: {
    name: "Mossberg 500",
    manufacturer: "REMINGTON",
    category: "Pump-Action Shotgun",
    era: "COLD_WAR",
    caliber: "12 gauge",
    capacity: 8,
    effectiveRange: 50,
    fireRate: 0,
    weight: 3.4,
    unitCost: 420,
    maintenanceCost: 16,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Mossberg_500.jpg/1280px-Mossberg_500.jpg",
  },
  M1014: {
    name: "Benelli M4 (M1014)",
    manufacturer: "BERETTA",
    category: "Semi-Automatic Shotgun",
    era: "CONTEMPORARY",
    caliber: "12 gauge",
    capacity: 7,
    effectiveRange: 50,
    fireRate: 0,
    weight: 3.8,
    unitCost: 1800,
    maintenanceCost: 70,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Benelli_M4_Super_90.jpg/1280px-Benelli_M4_Super_90.jpg",
  },
  AA12: {
    name: "AA-12 Auto Shotgun",
    manufacturer: "COLT",
    category: "Automatic Shotgun",
    era: "CONTEMPORARY",
    caliber: "12 gauge",
    capacity: 20,
    effectiveRange: 100,
    fireRate: 300,
    weight: 5.2,
    unitCost: 6000,
    maintenanceCost: 200,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Auto_Assault_12.jpg/1280px-Auto_Assault_12.jpg",
  },
  SAIGA12: {
    name: "Saiga-12",
    manufacturer: "IZHMASH",
    category: "Semi-Automatic Shotgun",
    era: "MODERN",
    caliber: "12 gauge",
    capacity: 10,
    effectiveRange: 75,
    fireRate: 0,
    weight: 3.6,
    unitCost: 900,
    maintenanceCost: 35,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Saiga12_with_mag.jpg/1280px-Saiga12_with_mag.jpg",
  },

  // Additional Shotguns
  SPAS12: {
    name: "Franchi SPAS-12",
    manufacturer: "BERETTA",
    category: "Combat Shotgun",
    era: "MODERN",
    caliber: "12 gauge",
    capacity: 8,
    effectiveRange: 50,
    fireRate: 0,
    weight: 4.4,
    unitCost: 1500,
    maintenanceCost: 60,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Franchi_SPAS-12.jpg/1280px-Franchi_SPAS-12.jpg",
  },
  WINCHESTER_1897: {
    name: "Winchester Model 1897",
    manufacturer: "WINCHESTER",
    category: "Trench Gun",
    era: "WWII",
    caliber: "12 gauge",
    capacity: 6,
    effectiveRange: 40,
    fireRate: 0,
    weight: 3.6,
    unitCost: 350,
    maintenanceCost: 14,
  },
  ITHACA_37: {
    name: "Ithaca 37",
    manufacturer: "REMINGTON",
    category: "Pump-Action Shotgun",
    era: "COLD_WAR",
    caliber: "12 gauge",
    capacity: 5,
    effectiveRange: 40,
    fireRate: 0,
    weight: 3.0,
    unitCost: 400,
    maintenanceCost: 16,
  },
  KSG: {
    name: "Kel-Tec KSG",
    manufacturer: "MOSSBERG",
    category: "Bullpup Shotgun",
    era: "CONTEMPORARY",
    caliber: "12 gauge",
    capacity: 14,
    effectiveRange: 50,
    fireRate: 0,
    weight: 3.8,
    unitCost: 850,
    maintenanceCost: 34,
  },
  USAS12: {
    name: "USAS-12",
    manufacturer: "DAEWOO",
    category: "Automatic Shotgun",
    era: "MODERN",
    caliber: "12 gauge",
    capacity: 20,
    effectiveRange: 100,
    fireRate: 300,
    weight: 5.5,
    unitCost: 4500,
    maintenanceCost: 180,
  },
  VEPR12: {
    name: "Molot Vepr-12",
    manufacturer: "IZHMASH",
    category: "Semi-Automatic Shotgun",
    era: "CONTEMPORARY",
    caliber: "12 gauge",
    capacity: 10,
    effectiveRange: 75,
    fireRate: 0,
    weight: 3.7,
    unitCost: 1100,
    maintenanceCost: 44,
  },
  KS23: {
    name: "KS-23",
    manufacturer: "TULA",
    category: "Special Purpose Shotgun",
    era: "COLD_WAR",
    caliber: "23mm (6 gauge)",
    capacity: 3,
    effectiveRange: 100,
    fireRate: 0,
    weight: 4.2,
    unitCost: 800,
    maintenanceCost: 32,
  },
} as const;

// ===========================
// TACTICAL EQUIPMENT (30+ Items)
// ===========================

export const TACTICAL_EQUIPMENT = {
  // Body Armor
  IOTV_ARMOR: {
    name: "IOTV Body Armor",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Body Armor",
    era: "CONTEMPORARY",
    protectionLevel: "Level IV",
    weight: 14.0,
    unitCost: 1600,
    maintenanceCost: 60,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/IOTV_body_armor.jpg/1280px-IOTV_body_armor.jpg",
  },
  OTV_ARMOR: {
    name: "Outer Tactical Vest",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Body Armor",
    era: "MODERN",
    protectionLevel: "Level IIIA",
    weight: 12.0,
    unitCost: 1200,
    maintenanceCost: 45,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Outer_Tactical_Vest.jpg/1280px-Outer_Tactical_Vest.jpg",
  },
  PASGT_HELMET: {
    name: "PASGT Helmet",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Helmet",
    era: "MODERN",
    protectionLevel: "Level IIIA",
    weight: 1.5,
    unitCost: 150,
    maintenanceCost: 5,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/PASGT_helmet.jpg/1280px-PASGT_helmet.jpg",
  },
  ACH_HELMET: {
    name: "Advanced Combat Helmet",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Helmet",
    era: "CONTEMPORARY",
    protectionLevel: "Level IIIA+",
    weight: 1.4,
    unitCost: 320,
    maintenanceCost: 10,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Advanced_Combat_Helmet.jpg/1280px-Advanced_Combat_Helmet.jpg",
  },

  // Optics & Sights
  ACOG: {
    name: "Trijicon ACOG",
    manufacturer: "RAYTHEON",
    category: "Optical Sight",
    era: "MODERN",
    magnification: "4x",
    weight: 0.3,
    unitCost: 1300,
    maintenanceCost: 40,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/ACOG.jpg/1280px-ACOG.jpg",
  },
  EOTECH_HOLOGRAPHIC: {
    name: "EOTech Holographic Sight",
    manufacturer: "RAYTHEON",
    category: "Holographic Sight",
    era: "CONTEMPORARY",
    magnification: "1x",
    weight: 0.3,
    unitCost: 600,
    maintenanceCost: 20,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/EOTech_holographic_sight.jpg/1280px-EOTech_holographic_sight.jpg",
  },
  AIMPOINT_M68: {
    name: "Aimpoint M68 CCO",
    manufacturer: "RAYTHEON",
    category: "Red Dot Sight",
    era: "MODERN",
    magnification: "1x",
    weight: 0.2,
    unitCost: 450,
    maintenanceCost: 15,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/M68_CCO.jpg/1280px-M68_CCO.jpg",
  },
  LEUPOLD_SCOPE: {
    name: "Leupold Mark 4 Scope",
    manufacturer: "RAYTHEON",
    category: "Sniper Scope",
    era: "CONTEMPORARY",
    magnification: "6.5-20x",
    weight: 0.8,
    unitCost: 2200,
    maintenanceCost: 70,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Leupold_Mark_4.jpg/1280px-Leupold_Mark_4.jpg",
  },

  // Night Vision & Thermal
  PVS14_NVG: {
    name: "AN/PVS-14 Night Vision",
    manufacturer: "ELBIT",
    category: "Night Vision Monocular",
    era: "CONTEMPORARY",
    generation: "Gen 3",
    weight: 0.35,
    unitCost: 4500,
    maintenanceCost: 150,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/AN-PVS-14.jpg/1280px-AN-PVS-14.jpg",
  },
  PVS7_NVG: {
    name: "AN/PVS-7 Night Vision",
    manufacturer: "ELBIT",
    category: "Night Vision Goggles",
    era: "MODERN",
    generation: "Gen 3",
    weight: 0.6,
    unitCost: 5500,
    maintenanceCost: 180,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/AN-PVS-7.jpg/1280px-AN-PVS-7.jpg",
  },
  FLIR_THERMAL: {
    name: "FLIR Thermal Sight",
    manufacturer: "RAYTHEON",
    category: "Thermal Imaging",
    era: "CONTEMPORARY",
    resolution: "640x480",
    weight: 0.7,
    unitCost: 8500,
    maintenanceCost: 280,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Thermal_weapon_sight.jpg/1280px-Thermal_weapon_sight.jpg",
  },

  // Communications
  PRC152_RADIO: {
    name: "AN/PRC-152 Radio",
    manufacturer: "RAYTHEON",
    category: "Tactical Radio",
    era: "CONTEMPORARY",
    range: "5 km",
    weight: 1.1,
    unitCost: 7500,
    maintenanceCost: 240,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/AN-PRC-152.jpg/1280px-AN-PRC-152.jpg",
  },
  PRC148_RADIO: {
    name: "AN/PRC-148 MBITR",
    manufacturer: "RAYTHEON",
    category: "Tactical Radio",
    era: "MODERN",
    range: "3 km",
    weight: 0.7,
    unitCost: 5000,
    maintenanceCost: 160,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/MBITR_radio.jpg/1280px-MBITR_radio.jpg",
  },

  // Medical Equipment
  IFAK: {
    name: "Individual First Aid Kit",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Medical Kit",
    era: "CONTEMPORARY",
    contents: "Tourniquet, bandages, gauze",
    weight: 0.5,
    unitCost: 85,
    maintenanceCost: 3,
  },
  CLS_BAG: {
    name: "Combat Lifesaver Bag",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Medical Kit",
    era: "MODERN",
    contents: "Advanced trauma supplies",
    weight: 4.5,
    unitCost: 450,
    maintenanceCost: 15,
  },

  // Breaching Tools
  SHOTGUN_BREACHER: {
    name: "Masterkey Breaching Shotgun",
    manufacturer: "REMINGTON",
    category: "Breaching Tool",
    era: "MODERN",
    caliber: "12 gauge",
    capacity: 3,
    weight: 2.3,
    unitCost: 900,
    maintenanceCost: 35,
  },
  EXPLOSIVE_BREACHER: {
    name: "C4 Breaching Charge",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Explosive Breaching",
    era: "MODERN",
    weight: 0.6,
    unitCost: 120,
    maintenanceCost: 5,
  },

  // Suppression
  SUPPRESSOR_556: {
    name: "5.56mm Suppressor",
    manufacturer: "HECKLER_KOCH",
    category: "Sound Suppressor",
    era: "CONTEMPORARY",
    caliber: "5.56x45mm",
    weight: 0.45,
    unitCost: 800,
    maintenanceCost: 25,
  },
  SUPPRESSOR_762: {
    name: "7.62mm Suppressor",
    manufacturer: "HECKLER_KOCH",
    category: "Sound Suppressor",
    era: "CONTEMPORARY",
    caliber: "7.62x51mm",
    weight: 0.65,
    unitCost: 950,
    maintenanceCost: 30,
  },

  // Additional Tactical Equipment - Massively Expanded
  PLATE_CARRIER_JPC: {
    name: "Jumpable Plate Carrier (JPC)",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Plate Carrier",
    era: "CONTEMPORARY",
    protectionLevel: "Level IV",
    weight: 1.2,
    unitCost: 280,
    maintenanceCost: 10,
  },
  MOLLE_VEST: {
    name: "MOLLE Tactical Vest",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Load Bearing Vest",
    era: "CONTEMPORARY",
    weight: 2.5,
    unitCost: 150,
    maintenanceCost: 5,
  },
  BALLISTIC_SHIELD: {
    name: "Ballistic Shield Level IIIA",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Shield",
    era: "CONTEMPORARY",
    protectionLevel: "Level IIIA",
    weight: 8.6,
    unitCost: 1200,
    maintenanceCost: 40,
  },
  HELMET_MICH: {
    name: "MICH Combat Helmet",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Helmet",
    era: "MODERN",
    protectionLevel: "Level IIIA",
    weight: 1.4,
    unitCost: 250,
    maintenanceCost: 8,
  },
  HELMET_FAST: {
    name: "FAST Tactical Helmet",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Helmet",
    era: "CONTEMPORARY",
    protectionLevel: "Level IIIA+",
    weight: 1.2,
    unitCost: 400,
    maintenanceCost: 12,
  },
  GAS_MASK_M50: {
    name: "M50 Joint Service General Purpose Mask",
    manufacturer: "GENERAL_DYNAMICS",
    category: "CBRN Protection",
    era: "CONTEMPORARY",
    weight: 0.79,
    unitCost: 850,
    maintenanceCost: 28,
  },
  CHEM_SUIT: {
    name: "MOPP Protective Suit",
    manufacturer: "GENERAL_DYNAMICS",
    category: "CBRN Protection",
    era: "MODERN",
    weight: 2.3,
    unitCost: 220,
    maintenanceCost: 8,
  },

  // Optics - Expanded
  ELCAN_SPECTER: {
    name: "Elcan SpecterDR",
    manufacturer: "ELBIT",
    category: "Variable Optical Sight",
    era: "CONTEMPORARY",
    magnification: "1-4x",
    weight: 0.68,
    unitCost: 1800,
    maintenanceCost: 60,
  },
  SCHMIDT_BENDER: {
    name: "Schmidt & Bender PM II",
    manufacturer: "HECKLER_KOCH",
    category: "Sniper Scope",
    era: "CONTEMPORARY",
    magnification: "5-25x",
    weight: 1.1,
    unitCost: 3200,
    maintenanceCost: 96,
  },
  VORTEX_RAZOR: {
    name: "Vortex Razor HD",
    manufacturer: "RAYTHEON",
    category: "Optical Sight",
    era: "CONTEMPORARY",
    magnification: "1-6x",
    weight: 0.65,
    unitCost: 1500,
    maintenanceCost: 48,
  },
  TRIJICON_MRO: {
    name: "Trijicon MRO",
    manufacturer: "RAYTHEON",
    category: "Red Dot Sight",
    era: "CONTEMPORARY",
    magnification: "1x",
    weight: 0.13,
    unitCost: 580,
    maintenanceCost: 18,
  },
  HOLOSUN_REFLEX: {
    name: "Holosun Red Dot",
    manufacturer: "NORINCO",
    category: "Reflex Sight",
    era: "CONTEMPORARY",
    magnification: "1x",
    weight: 0.09,
    unitCost: 280,
    maintenanceCost: 9,
  },

  // Night Vision - Expanded
  PVS31_BNVD: {
    name: "AN/PVS-31 BNVD",
    manufacturer: "ELBIT",
    category: "Binocular Night Vision",
    era: "CONTEMPORARY",
    generation: "Gen 3+",
    weight: 0.52,
    unitCost: 11000,
    maintenanceCost: 350,
  },
  PVS15_NVG: {
    name: "AN/PVS-15 Night Vision",
    manufacturer: "ELBIT",
    category: "Dual Tube NVG",
    era: "MODERN",
    generation: "Gen 3",
    weight: 0.68,
    unitCost: 8500,
    maintenanceCost: 270,
  },
  GPNVG18: {
    name: "GPNVG-18 Panoramic NVG",
    manufacturer: "ELBIT",
    category: "Panoramic Night Vision",
    era: "CONTEMPORARY",
    generation: "Gen 3",
    weight: 0.77,
    unitCost: 42000,
    maintenanceCost: 1260,
  },
  THERMAL_PAS29: {
    name: "AN/PAS-29 COTI",
    manufacturer: "RAYTHEON",
    category: "Clip-On Thermal Imager",
    era: "CONTEMPORARY",
    resolution: "640x480",
    weight: 0.34,
    unitCost: 7500,
    maintenanceCost: 240,
  },

  // Communications - Expanded
  PRC117G_RADIO: {
    name: "AN/PRC-117G Radio",
    manufacturer: "RAYTHEON",
    category: "Manpack Radio",
    era: "CONTEMPORARY",
    range: "40 km",
    weight: 4.5,
    unitCost: 26000,
    maintenanceCost: 780,
  },
  SINCGARS_RADIO: {
    name: "SINCGARS Radio",
    manufacturer: "RAYTHEON",
    category: "Tactical Radio",
    era: "MODERN",
    range: "10 km",
    weight: 3.2,
    unitCost: 15000,
    maintenanceCost: 450,
  },
  COMTAC_HEADSET: {
    name: "Peltor ComTac Headset",
    manufacturer: "RAYTHEON",
    category: "Communication Headset",
    era: "CONTEMPORARY",
    weight: 0.35,
    unitCost: 480,
    maintenanceCost: 15,
  },

  // Laser Devices
  PEQLA: {
    name: "AN/PEQ-15 ATPIAL",
    manufacturer: "ELBIT",
    category: "Laser Aiming Module",
    era: "CONTEMPORARY",
    features: "Visible/IR laser + IR illuminator",
    weight: 0.21,
    unitCost: 1600,
    maintenanceCost: 52,
  },
  DBAL_A3: {
    name: "DBAL-A3",
    manufacturer: "ELBIT",
    category: "Dual Beam Laser",
    era: "CONTEMPORARY",
    features: "Visible/IR laser",
    weight: 0.18,
    unitCost: 1400,
    maintenanceCost: 45,
  },

  // Medical Equipment - Expanded
  TCCC_KIT: {
    name: "TCCC Trauma Kit",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Medical Kit",
    era: "CONTEMPORARY",
    contents: "Combat trauma supplies",
    weight: 2.2,
    unitCost: 280,
    maintenanceCost: 10,
  },
  TOURNIQUET_CAT: {
    name: "CAT Tourniquet",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Medical Device",
    era: "CONTEMPORARY",
    weight: 0.08,
    unitCost: 28,
    maintenanceCost: 1,
  },
  HEMOSTATIC_GAUZE: {
    name: "Combat Gauze",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Medical Supply",
    era: "CONTEMPORARY",
    weight: 0.05,
    unitCost: 42,
    maintenanceCost: 2,
  },
  CHEST_SEAL: {
    name: "Chest Seal (Vented)",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Medical Device",
    era: "CONTEMPORARY",
    weight: 0.03,
    unitCost: 22,
    maintenanceCost: 1,
  },

  // Tactical Accessories
  FOREGRIP_VERTICAL: {
    name: "Vertical Foregrip",
    manufacturer: "HECKLER_KOCH",
    category: "Weapon Accessory",
    era: "MODERN",
    weight: 0.09,
    unitCost: 45,
    maintenanceCost: 2,
  },
  FOREGRIP_ANGLED: {
    name: "Angled Foregrip",
    manufacturer: "HECKLER_KOCH",
    category: "Weapon Accessory",
    era: "CONTEMPORARY",
    weight: 0.06,
    unitCost: 35,
    maintenanceCost: 1,
  },
  BIPOD_HARRIS: {
    name: "Harris Bipod",
    manufacturer: "REMINGTON",
    category: "Weapon Stabilizer",
    era: "MODERN",
    weight: 0.38,
    unitCost: 120,
    maintenanceCost: 4,
  },
  FLASHLIGHT_SUREFIRE: {
    name: "SureFire M600 Scout Light",
    manufacturer: "RAYTHEON",
    category: "Weapon Light",
    era: "CONTEMPORARY",
    lumens: 600,
    weight: 0.13,
    unitCost: 280,
    maintenanceCost: 9,
  },
  FLASHLIGHT_STREAMLIGHT: {
    name: "Streamlight TLR-1",
    manufacturer: "RAYTHEON",
    category: "Weapon Light",
    era: "CONTEMPORARY",
    lumens: 800,
    weight: 0.13,
    unitCost: 150,
    maintenanceCost: 5,
  },

  // Breaching - Expanded
  BATTERING_RAM: {
    name: "Tactical Battering Ram",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Breaching Tool",
    era: "MODERN",
    weight: 16.0,
    unitCost: 240,
    maintenanceCost: 8,
  },
  HALLIGAN_BAR: {
    name: "Halligan Breaching Tool",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Breaching Tool",
    era: "MODERN",
    weight: 4.5,
    unitCost: 120,
    maintenanceCost: 4,
  },
  SHOTGUN_BREACHING_ROUNDS: {
    name: "Hatton Breaching Rounds",
    manufacturer: "REMINGTON",
    category: "Breaching Ammunition",
    era: "MODERN",
    caliber: "12 gauge",
    weight: 0.05,
    unitCost: 8,
    maintenanceCost: 0,
  },

  // Utility Equipment
  CARABINER_TACTICAL: {
    name: "Tactical Carabiner",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Utility Gear",
    era: "MODERN",
    weight: 0.06,
    unitCost: 15,
    maintenanceCost: 1,
  },
  RAPPEL_HARNESS: {
    name: "Tactical Rappelling Harness",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Climbing Gear",
    era: "MODERN",
    weight: 1.2,
    unitCost: 180,
    maintenanceCost: 6,
  },
  ROPE_TACTICAL: {
    name: "Tactical Rope (50m)",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Climbing Gear",
    era: "MODERN",
    weight: 2.5,
    unitCost: 90,
    maintenanceCost: 3,
  },
  MULTITOOL: {
    name: "Leatherman MUT",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Multi-Tool",
    era: "CONTEMPORARY",
    weight: 0.31,
    unitCost: 150,
    maintenanceCost: 5,
  },
  COMBAT_KNIFE: {
    name: "KA-BAR Combat Knife",
    manufacturer: "COLT",
    category: "Knife",
    era: "WWII",
    blade: "7 inch",
    weight: 0.45,
    unitCost: 80,
    maintenanceCost: 3,
  },
  BAYONET_M9: {
    name: "M9 Bayonet",
    manufacturer: "COLT",
    category: "Bayonet",
    era: "MODERN",
    blade: "7 inch",
    weight: 0.43,
    unitCost: 120,
    maintenanceCost: 4,
  },

  // Grenades & Explosives
  FRAG_M67: {
    name: "M67 Fragmentation Grenade",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Hand Grenade",
    era: "MODERN",
    type: "Fragmentation",
    weight: 0.4,
    unitCost: 45,
    maintenanceCost: 2,
  },
  SMOKE_M18: {
    name: "M18 Smoke Grenade",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Smoke Grenade",
    era: "COLD_WAR",
    type: "Smoke",
    weight: 0.54,
    unitCost: 35,
    maintenanceCost: 1,
  },
  FLASHBANG_M84: {
    name: "M84 Stun Grenade",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Stun Grenade",
    era: "MODERN",
    type: "Flashbang",
    weight: 0.39,
    unitCost: 40,
    maintenanceCost: 2,
  },
  CLAYMORE_M18A1: {
    name: "M18A1 Claymore Mine",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Directional Mine",
    era: "COLD_WAR",
    weight: 1.6,
    unitCost: 180,
    maintenanceCost: 6,
  },
  C4_EXPLOSIVE: {
    name: "C-4 Plastic Explosive (1lb)",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Explosive",
    era: "MODERN",
    weight: 0.45,
    unitCost: 60,
    maintenanceCost: 2,
  },
  DETONATOR_M57: {
    name: "M57 Firing Device",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Detonator",
    era: "COLD_WAR",
    weight: 0.23,
    unitCost: 120,
    maintenanceCost: 4,
  },

  // Surveillance & Recon
  BINOCULARS_M22: {
    name: "M22 Binoculars",
    manufacturer: "RAYTHEON",
    category: "Optical Device",
    era: "MODERN",
    magnification: "7x",
    weight: 0.85,
    unitCost: 480,
    maintenanceCost: 15,
  },
  RANGEFINDER_VECTOR: {
    name: "Vector 21 Rangefinder",
    manufacturer: "RAYTHEON",
    category: "Laser Rangefinder",
    era: "CONTEMPORARY",
    range: "10000m",
    weight: 1.1,
    unitCost: 4200,
    maintenanceCost: 135,
  },
  DRONE_RQ11_RAVEN: {
    name: "RQ-11 Raven UAV",
    manufacturer: "RAYTHEON",
    category: "Small UAV",
    era: "CONTEMPORARY",
    endurance: "90 minutes",
    weight: 1.9,
    unitCost: 35000,
    maintenanceCost: 1050,
  },
} as const;

// ===========================
// ANTI-TANK WEAPONS (15+ Items)
// ===========================

export const ANTI_TANK_WEAPONS = {
  JAVELIN: {
    name: "FGM-148 Javelin",
    manufacturer: "RAYTHEON",
    category: "Anti-Tank Guided Missile",
    era: "CONTEMPORARY",
    range: 2500,
    fireRate: 0,
    weight: 22.3,
    unitCost: 175000,
    maintenanceCost: 5000,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Javelin_missile.jpg/1280px-Javelin_missile.jpg",
  },
  AT4: {
    name: "AT4 Anti-Tank Weapon",
    manufacturer: "SAAB",
    category: "Disposable Anti-Tank",
    era: "MODERN",
    range: 300,
    fireRate: 0,
    weight: 6.7,
    unitCost: 1500,
    maintenanceCost: 0,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/AT4_firing.jpg/1280px-AT4_firing.jpg",
  },
  M72_LAW: {
    name: "M72 LAW",
    manufacturer: "GENERAL_DYNAMICS",
    category: "Disposable Anti-Tank",
    era: "COLD_WAR",
    range: 200,
    fireRate: 0,
    weight: 2.5,
    unitCost: 750,
    maintenanceCost: 0,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/M72_LAW.jpg/1280px-M72_LAW.jpg",
  },
  TOW_MISSILE: {
    name: "BGM-71 TOW",
    manufacturer: "RAYTHEON",
    category: "Anti-Tank Guided Missile",
    era: "COLD_WAR",
    range: 3750,
    fireRate: 0,
    weight: 22.6,
    unitCost: 93000,
    maintenanceCost: 2800,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/BGM-71_TOW_missile.jpg/1280px-BGM-71_TOW_missile.jpg",
  },
  RPG7: {
    name: "RPG-7",
    manufacturer: "IZHMASH",
    category: "Rocket Propelled Grenade",
    era: "COLD_WAR",
    range: 300,
    fireRate: 0,
    weight: 7.0,
    unitCost: 500,
    maintenanceCost: 15,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/RPG-7_detached.jpg/1280px-RPG-7_detached.jpg",
  },
  RPG29: {
    name: "RPG-29",
    manufacturer: "IZHMASH",
    category: "Rocket Propelled Grenade",
    era: "MODERN",
    range: 500,
    fireRate: 0,
    weight: 11.5,
    unitCost: 2000,
    maintenanceCost: 60,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/RPG-29.jpg/1280px-RPG-29.jpg",
  },
  NLAW: {
    name: "MBT LAW (NLAW)",
    manufacturer: "SAAB",
    category: "Anti-Tank Guided Missile",
    era: "CONTEMPORARY",
    range: 800,
    fireRate: 0,
    weight: 12.5,
    unitCost: 40000,
    maintenanceCost: 1200,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/NLAW_missile.jpg/1280px-NLAW_missile.jpg",
  },
} as const;

// ===========================
// MANPADS (Portable Air Defense) (10+ Items)
// ===========================

export const MANPADS = {
  STINGER: {
    name: "FIM-92 Stinger",
    manufacturer: "RAYTHEON",
    category: "Man-Portable Air Defense",
    era: "MODERN",
    range: 4800,
    altitude: 3800,
    weight: 15.2,
    unitCost: 120000,
    maintenanceCost: 3600,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/FIM-92_Stinger.jpg/1280px-FIM-92_Stinger.jpg",
  },
  IGLA: {
    name: "Igla (SA-18)",
    manufacturer: "IZHMASH",
    category: "Man-Portable Air Defense",
    era: "MODERN",
    range: 5200,
    altitude: 3500,
    weight: 17.9,
    unitCost: 85000,
    maintenanceCost: 2550,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/9K38_Igla.jpg/1280px-9K38_Igla.jpg",
  },
  STARSTREAK: {
    name: "Starstreak HVM",
    manufacturer: "THALES",
    category: "Man-Portable Air Defense",
    era: "CONTEMPORARY",
    range: 7000,
    altitude: 5000,
    weight: 16.7,
    unitCost: 150000,
    maintenanceCost: 4500,
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Starstreak_missile.jpg/1280px-Starstreak_missile.jpg",
  },
} as const;

// ===========================
// COMBINED DATABASE
// ===========================

export const SMALL_ARMS_DATABASE = {
  pistols: PISTOLS,
  assault_rifles: ASSAULT_RIFLES,
  battle_rifles: BATTLE_RIFLES,
  sniper_rifles: SNIPER_RIFLES,
  submachine_guns: SUBMACHINE_GUNS,
  machine_guns: MACHINE_GUNS,
  grenade_launchers: GRENADE_LAUNCHERS,
  shotguns: SHOTGUNS,
  tactical_equipment: TACTICAL_EQUIPMENT,
  anti_tank_weapons: ANTI_TANK_WEAPONS,
  manpads: MANPADS,
} as const;

// Helper function to get all equipment count
export function getSmallArmsCount() {
  return {
    pistols: Object.keys(PISTOLS).length,
    assault_rifles: Object.keys(ASSAULT_RIFLES).length,
    battle_rifles: Object.keys(BATTLE_RIFLES).length,
    sniper_rifles: Object.keys(SNIPER_RIFLES).length,
    submachine_guns: Object.keys(SUBMACHINE_GUNS).length,
    machine_guns: Object.keys(MACHINE_GUNS).length,
    grenade_launchers: Object.keys(GRENADE_LAUNCHERS).length,
    shotguns: Object.keys(SHOTGUNS).length,
    tactical_equipment: Object.keys(TACTICAL_EQUIPMENT).length,
    anti_tank_weapons: Object.keys(ANTI_TANK_WEAPONS).length,
    manpads: Object.keys(MANPADS).length,
    total:
      Object.keys(PISTOLS).length +
      Object.keys(ASSAULT_RIFLES).length +
      Object.keys(BATTLE_RIFLES).length +
      Object.keys(SNIPER_RIFLES).length +
      Object.keys(SUBMACHINE_GUNS).length +
      Object.keys(MACHINE_GUNS).length +
      Object.keys(GRENADE_LAUNCHERS).length +
      Object.keys(SHOTGUNS).length +
      Object.keys(TACTICAL_EQUIPMENT).length +
      Object.keys(ANTI_TANK_WEAPONS).length +
      Object.keys(MANPADS).length,
  };
}

// Filter by era
export function getSmallArmsByEra(era: keyof typeof WEAPON_ERAS) {
  const result: Record<string, any[]> = {};

  Object.entries(SMALL_ARMS_DATABASE).forEach(([category, items]) => {
    const filtered = Object.entries(items)
      .filter(([_, item]: [string, any]) => item.era === era)
      .map(([key, item]) => ({ ...item, key }));

    if (filtered.length > 0) {
      result[category] = filtered;
    }
  });

  return result;
}

// Filter by manufacturer
export function getSmallArmsByManufacturer(manufacturer: keyof typeof SMALL_ARMS_MANUFACTURERS) {
  const result: Record<string, any[]> = {};

  Object.entries(SMALL_ARMS_DATABASE).forEach(([category, items]) => {
    const filtered = Object.entries(items)
      .filter(([_, item]: [string, any]) => item.manufacturer === manufacturer)
      .map(([key, item]) => ({ ...item, key }));

    if (filtered.length > 0) {
      result[category] = filtered;
    }
  });

  return result;
}

export default SMALL_ARMS_DATABASE;
