import { z } from "zod";
import { createTRPCRouter, publicProcedure } from "~/server/api/trpc";
import { env } from "~/env";

export const thinkpagesPostsReactionsQueriesRouter = createTRPCRouter({
  // ===== THINKSHARE (MESSAGING) ENDPOINTS =====

  // Get post reactions with account details
  getPostReactions: publicProcedure
    .input(
      z.object({
        postId: z.string(),
        reactionType: z.string().optional(), // Filter by specific reaction type
      })
    )
    .query(async ({ ctx, input }) => {
      const { db } = ctx;

      const whereClause: any = {
        postId: input.postId,
      };

      if (input.reactionType) {
        whereClause.reactionType = input.reactionType;
      }

      const localReactions = await db.postReaction.findMany({
        where: whereClause,
        include: {
          account: {
            select: {
              id: true,
              username: true,
              displayName: true,
              profileImageUrl: true,
              accountType: true,
              verified: true,
            },
          },
        },
        orderBy: {
          timestamp: "desc",
        },
      });

      const post = await db.thinkpagesPost.findUnique({
        where: { id: input.postId },
        select: {
          id: true,
          content: true,
          isAutoGenerated: true,
          reactionCounts: true,
          createdAt: true,
        },
      });

      const discordReactions: any[] = [];
      if (post) {
        const match = post.content.match(/\[DiscordMsg:(\d+)\]/);
        const discordMsgId = match ? match[1] : null;

        let counts: Record<string, number> = {};
        try {
          if (post.reactionCounts) {
            counts = JSON.parse(post.reactionCounts);
          }
        } catch (e) {
          console.warn("Failed to parse reactionCounts in getPostReactions:", e);
        }

        if (discordMsgId) {
          const discordBotToken = process.env.DISCORD_BOT_TOKEN;
          const channelId = process.env.DISCORD_IXTWITTER_CHANNEL_ID || "557223534418722818";

          if (discordBotToken) {
            try {
              const activeTypes = input.reactionType ? [input.reactionType] : Object.keys(counts);

              // Fetch reactors for all active emoji types in parallel
              const fetchPromises = activeTypes.map(async (type) => {
                const count = counts[type] || 0;
                if (count <= 0) return [];

                // Map reaction type to Discord emoji format
                let emojiStr = type;
                if (type.startsWith("discord:")) {
                  const parts = type.split(":");
                  const name = parts[1] || "";
                  const id = parts[2] || "";
                  emojiStr = id ? `${name}:${id}` : name;
                } else {
                  switch (type) {
                    case "like":
                      emojiStr = "❤️";
                      break;
                    case "laugh":
                      emojiStr = "😂";
                      break;
                    case "angry":
                      emojiStr = "😡";
                      break;
                    case "sad":
                      emojiStr = "😢";
                      break;
                    case "fire":
                      emojiStr = "🔥";
                      break;
                    case "thumbsup":
                      emojiStr = "👍";
                      break;
                    case "thumbsdown":
                      emojiStr = "👎";
                      break;
                  }
                }

                const encodedEmoji = encodeURIComponent(emojiStr);
                const res = await fetch(
                  `https://discord.com/api/v10/channels/${channelId}/messages/${discordMsgId}/reactions/${encodedEmoji}?limit=100`,
                  {
                    method: "GET",
                    headers: {
                      Authorization: `Bot ${discordBotToken}`,
                      "User-Agent": "IxStats/1.0",
                    },
                    signal: AbortSignal.timeout(5000),
                  }
                );

                if (res.ok) {
                  const users = (await res.json()) as any[];
                  return users.map((u) => ({ ...u, type }));
                }
                return [];
              });

              const fetchedResults = await Promise.all(fetchPromises);
              const allFetchedReactors = fetchedResults.flat();

              // Fetch guild member nicknames and map accounts in parallel
              const memberPromises = allFetchedReactors.map(async (u) => {
                if (u.bot) return null;

                const discordAvatarUrl = u.avatar
                  ? `https://cdn.discordapp.com/avatars/${u.id}/${u.avatar}.png?size=128`
                  : null;

                let serverNickname = u.global_name || u.username;

                // Guild nicknames need the guild ID; without it the Discord name is shown.
                const guildId = env.DISCORD_GUILD_ID;
                if (guildId) {
                  try {
                    const memberRes = await fetch(
                      `https://discord.com/api/v10/guilds/${guildId}/members/${u.id}`,
                      {
                        method: "GET",
                        headers: {
                          Authorization: `Bot ${discordBotToken}`,
                          "User-Agent": "IxStats/1.0",
                        },
                        signal: AbortSignal.timeout(3000),
                      }
                    );
                    if (memberRes.ok) {
                      const memberData = (await memberRes.json()) as { nick?: string | null };
                      if (memberData.nick) {
                        serverNickname = memberData.nick;
                      }
                    }
                  } catch (err) {
                    console.warn(`Failed to fetch guild member nickname for ${u.id}:`, err);
                  }
                }

                let localAcc = null;

                // 1. Look up User by Discord ID or Username (IxnayID auth sync)
                const linkedUser = await db.user.findFirst({
                  where: {
                    OR: [{ discordUserId: u.id }, { discordUsername: u.username }],
                  },
                  select: {
                    clerkUserId: true,
                  },
                });

                // 2. If User found, look up their ThinkpagesAccount
                if (linkedUser) {
                  localAcc = await db.thinkpagesAccount.findFirst({
                    where: {
                      clerkUserId: linkedUser.clerkUserId,
                    },
                    select: {
                      id: true,
                      username: true,
                      displayName: true,
                      profileImageUrl: true,
                      accountType: true,
                      verified: true,
                    },
                  });
                }

                // 3. Fallback to direct username or bio lookup
                if (!localAcc) {
                  localAcc = await db.thinkpagesAccount.findFirst({
                    where: {
                      OR: [
                        { username: u.username },
                        { bio: { contains: `discord:${u.username}` } },
                      ],
                    },
                    select: {
                      id: true,
                      username: true,
                      displayName: true,
                      profileImageUrl: true,
                      accountType: true,
                      verified: true,
                    },
                  });
                }

                if (localAcc) {
                  return {
                    id: `discord_react_${u.id}_${u.type}`,
                    postId: input.postId,
                    reactionType: u.type,
                    timestamp: new Date(post.createdAt),
                    account: {
                      ...localAcc,
                      displayName: serverNickname || localAcc.displayName,
                      profileImageUrl: discordAvatarUrl || localAcc.profileImageUrl,
                    },
                  };
                } else {
                  return {
                    id: `discord_react_${u.id}_${u.type}`,
                    postId: input.postId,
                    reactionType: u.type,
                    timestamp: new Date(post.createdAt),
                    account: {
                      id: `discord_user_${u.id}`,
                      username: serverNickname,
                      displayName: serverNickname,
                      profileImageUrl: discordAvatarUrl,
                      accountType: "citizen",
                      verified: false,
                      isDiscordUser: true,
                    },
                  };
                }
              });

              const processedReactions = await Promise.all(memberPromises);
              discordReactions.push(...processedReactions.filter(Boolean));
            } catch (e) {
              console.error("Failed to fetch reactions from Discord API:", e);
            }
          }

          // No fallback: when the Discord fetch fails or no bot token is set, only local
          // reactors are listed. The post's reaction counts still come from reactionCounts.
        }
      }

      return [...localReactions, ...discordReactions];
    }),
});
