/**
 * ThinkPages → Discord Feed Mirror
 *
 * Mirrors eligible public ThinkPages feed posts to a dedicated, admin-configurable
 * Discord channel (the "#thinkpages" RSS-style feed). Separate from the legacy
 * IxTwitter sync in `discord-ixtwitter-sync.ts` — this one is gated by an
 * admin-editable filter config (`ThinkpagesDiscordFeedConfig`) and de-duplicated
 * via `ThinkpagesDiscordMirror`.
 *
 * Posting reuses `formatThinkPagesEmbed` and the bot-token REST pattern.
 */

import { formatThinkPagesEmbed } from "./ixtwitter-sync";

const DISCORD_BOT_TOKEN = process.env.DISCORD_BOT_TOKEN;
const DISCORD_API_BASE = "https://discord.com/api/v10";

/** The #thinkpages channel created for this feed (seed default; admin can change). */
export const DEFAULT_THINKPAGES_CHANNEL_ID = "1514756187193741433";

export interface FeedFilterConfig {
  enabled: boolean;
  channelId: string;
  includeGovernment: boolean;
  includeMedia: boolean;
  includeCitizen: boolean;
  includeSports: boolean;
  verifiedOnly: boolean;
  accountAllowlist: string[];
  accountBlocklist: string[];
  hashtagAllowlist: string[];
  hashtagBlocklist: string[];
  excludeReplies: boolean;
  excludeAutoGenerated: boolean;
  minEngagement: number;
}

interface FeedPostLike {
  visibility: string;
  postType: string;
  isAutoGenerated: boolean;
  hashtags?: string | null;
  likeCount?: number;
  repostCount?: number;
  replyCount?: number;
}

interface FeedAccountLike {
  username: string;
  accountType: string;
  verified: boolean;
}

const normalizeHandle = (s: string) => s.trim().replace(/^@/, "").toLowerCase();
const normalizeTag = (s: string) => s.trim().replace(/^#/, "").toLowerCase();

/** Safely parse a JSON string[] column (allowlists/blocklists, post hashtags). */
export function parseJsonStringArray(raw: string | null | undefined): string[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.map((v) => String(v)).filter(Boolean) : [];
  } catch {
    return [];
  }
}

/** Strip the IxTwitter sync's `[DiscordMsg:123]` marker and any sports bulletin JSON comments so they never leak into the embed. */
export function cleanPostContent(content: string): string {
  return content
    .replace(/<!-- sports-bulletin:[\s\S]*?-->\n*/gi, "")
    .replace(/\n*\[DiscordMsg:\d+\]\s*$/i, "")
    .trim();
}

/** Map a raw DB config row into the parsed filter config. */
export function toFilterConfig(row: {
  enabled: boolean;
  channelId: string;
  includeGovernment: boolean;
  includeMedia: boolean;
  includeCitizen: boolean;
  includeSports: boolean;
  verifiedOnly: boolean;
  accountAllowlist: string | null;
  accountBlocklist: string | null;
  hashtagAllowlist: string | null;
  hashtagBlocklist: string | null;
  excludeReplies: boolean;
  excludeAutoGenerated: boolean;
  minEngagement: number;
}): FeedFilterConfig {
  return {
    enabled: row.enabled,
    channelId: row.channelId,
    includeGovernment: row.includeGovernment,
    includeMedia: row.includeMedia,
    includeCitizen: row.includeCitizen,
    includeSports: row.includeSports,
    verifiedOnly: row.verifiedOnly,
    accountAllowlist: parseJsonStringArray(row.accountAllowlist),
    accountBlocklist: parseJsonStringArray(row.accountBlocklist),
    hashtagAllowlist: parseJsonStringArray(row.hashtagAllowlist),
    hashtagBlocklist: parseJsonStringArray(row.hashtagBlocklist),
    excludeReplies: row.excludeReplies,
    excludeAutoGenerated: row.excludeAutoGenerated,
    minEngagement: row.minEngagement,
  };
}

export interface FilterVerdict {
  eligible: boolean;
  reason: string;
}

/**
 * Pure filter evaluation — decides whether a post should be mirrored.
 * Precedence: blocklists win → account allowlist force-includes → standard filters.
 */
export function evaluateFeedFilter(
  config: FeedFilterConfig,
  post: FeedPostLike,
  account: FeedAccountLike
): FilterVerdict {
  if (!config.enabled) return { eligible: false, reason: "Feed disabled" };
  if (!config.channelId) return { eligible: false, reason: "No channel configured" };
  if (post.visibility !== "public") return { eligible: false, reason: "Not public" };
  if (post.postType === "repost") return { eligible: false, reason: "Repost (not original)" };

  const uname = normalizeHandle(account.username);
  const blocked = config.accountBlocklist.map(normalizeHandle);
  const allowed = config.accountAllowlist.map(normalizeHandle);
  const postTags = parseJsonStringArray(post.hashtags).map(normalizeTag);
  const tagBlock = config.hashtagBlocklist.map(normalizeTag);
  const tagAllow = config.hashtagAllowlist.map(normalizeTag);

  // 1. Blocklists always win
  if (blocked.includes(uname)) {
    return { eligible: false, reason: `@${account.username} is blocklisted` };
  }
  if (tagBlock.length > 0 && postTags.some((t) => tagBlock.includes(t))) {
    return { eligible: false, reason: "Contains a blocked hashtag" };
  }

  // 2. Account allowlist force-includes (bypasses the standard filters below)
  if (allowed.includes(uname)) {
    return { eligible: true, reason: `@${account.username} is allowlisted` };
  }

  // 3. Standard filters
  if (config.excludeReplies && post.postType === "reply") {
    return { eligible: false, reason: "Replies excluded" };
  }

  if (uname === "sportsnews") {
    if (!config.includeSports) {
      return { eligible: false, reason: "Sports posts excluded" };
    }
  } else {
    if (config.excludeAutoGenerated && post.isAutoGenerated) {
      return { eligible: false, reason: "Auto-generated posts excluded" };
    }

    const typeAllowed =
      (account.accountType === "government" && config.includeGovernment) ||
      (account.accountType === "media" && config.includeMedia) ||
      (account.accountType === "citizen" && config.includeCitizen);
    if (!typeAllowed) {
      return { eligible: false, reason: `Account type "${account.accountType}" excluded` };
    }
  }

  if (config.verifiedOnly && !account.verified) {
    return { eligible: false, reason: "Verified accounts only" };
  }

  if (tagAllow.length > 0 && !postTags.some((t) => tagAllow.includes(t))) {
    return { eligible: false, reason: "Missing a required hashtag" };
  }

  const engagement = (post.likeCount ?? 0) + (post.repostCount ?? 0) + (post.replyCount ?? 0);
  if (config.minEngagement > 0 && engagement < config.minEngagement) {
    return {
      eligible: false,
      reason: `Below min engagement (${engagement}/${config.minEngagement})`,
    };
  }

  return { eligible: true, reason: "Passes all filters" };
}

export interface MirrorResult {
  mirrored: boolean;
  reason: string;
  discordMessageId?: string;
}

/**
 * Mirror a single post to the configured #thinkpages Discord channel if it passes
 * the admin filter and hasn't already been sent. Fire-and-forget safe — never throws.
 */
export async function mirrorThinkPagesPostToDiscordFeed(
  db: any,
  postId: string,
  mediaUrls?: string[]
): Promise<MirrorResult> {
  try {
    if (!DISCORD_BOT_TOKEN) return { mirrored: false, reason: "DISCORD_BOT_TOKEN not set" };

    const cfgRow = await db.thinkpagesDiscordFeedConfig.findUnique({ where: { id: "default" } });
    if (!cfgRow || !cfgRow.enabled) return { mirrored: false, reason: "Feed disabled" };
    if (!cfgRow.channelId) return { mirrored: false, reason: "No channel configured" };

    // Dedupe — never post the same post twice
    const existing = await db.thinkpagesDiscordMirror.findUnique({ where: { postId } });
    if (existing) return { mirrored: false, reason: "Already mirrored" };

    const post = await db.thinkpagesPost.findUnique({
      where: { id: postId },
      include: { account: true, mediaAttachments: true },
    });
    if (!post || !post.account) return { mirrored: false, reason: "Post not found" };

    const config = toFilterConfig(cfgRow);
    const verdict = evaluateFeedFilter(config, post, post.account);
    if (!verdict.eligible) return { mirrored: false, reason: verdict.reason };

    const urls =
      mediaUrls && mediaUrls.length > 0
        ? mediaUrls
        : (post.mediaAttachments ?? [])
            .filter((m: any) => typeof m.type === "string" && m.type.startsWith("image"))
            .map((m: any) => m.url as string);

    const embeds = formatThinkPagesEmbed(
      {
        id: post.id,
        content: post.content,
        ixTimeTimestamp: post.ixTimeTimestamp,
      },
      {
        displayName: post.account.displayName,
        username: post.account.username,
        verified: post.account.verified,
        profileImageUrl: post.account.profileImageUrl,
      },
      urls
    );

    const res = await fetch(`${DISCORD_API_BASE}/channels/${cfgRow.channelId}/messages`, {
      method: "POST",
      headers: {
        Authorization: `Bot ${DISCORD_BOT_TOKEN}`,
        "Content-Type": "application/json",
        "User-Agent": "IxStats/1.0 (https://ixwiki.com; contact: admin@ixwiki.com)",
      },
      body: JSON.stringify({ embeds }),
      signal: AbortSignal.timeout(15000),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => "");
      await db.thinkpagesDiscordMirror
        .create({
          data: {
            postId,
            channelId: cfgRow.channelId,
            status: "failed",
            error: `${res.status} ${res.statusText} ${text}`.slice(0, 500),
          },
        })
        .catch(() => undefined);
      return { mirrored: false, reason: `Discord error ${res.status}` };
    }

    const msg = (await res.json()) as { id: string };
    await db.thinkpagesDiscordMirror.create({
      data: { postId, channelId: cfgRow.channelId, discordMessageId: msg.id, status: "sent" },
    });
    return { mirrored: true, reason: "Sent", discordMessageId: msg.id };
  } catch (error) {
    console.error("[ThinkPagesFeed] Mirror error:", error);
    return { mirrored: false, reason: "Internal error" };
  }
}

/** Post a plain test message to a channel — used by the admin "Send test" button. */
export async function sendThinkPagesFeedTestMessage(
  channelId: string
): Promise<{ ok: boolean; error?: string }> {
  if (!DISCORD_BOT_TOKEN) return { ok: false, error: "DISCORD_BOT_TOKEN not set on the server" };
  if (!channelId) return { ok: false, error: "No channel ID configured" };
  try {
    const res = await fetch(`${DISCORD_API_BASE}/channels/${channelId}/messages`, {
      method: "POST",
      headers: {
        Authorization: `Bot ${DISCORD_BOT_TOKEN}`,
        "Content-Type": "application/json",
        "User-Agent": "IxStats/1.0 (https://ixwiki.com; contact: admin@ixwiki.com)",
      },
      body: JSON.stringify({
        content:
          "✅ **ThinkPages → Discord feed** test message from IxStats admin. If you can see this, the channel ID and bot token are configured correctly and posts will mirror here.",
      }),
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return { ok: false, error: `Discord ${res.status} ${res.statusText} ${text}`.slice(0, 300) };
    }
    return { ok: true };
  } catch (error) {
    return { ok: false, error: String(error) };
  }
}
