// Feed-item builders shared by the global and following feeds.

import type { PrismaClient } from "@prisma/client";
import { formatPollForClient } from "../../thinkpages/post-utils";

/** Feed author for an activity row: its country when it has one, the platform otherwise. */
export function countryFeedUser(country: any) {
  return country
    ? {
        id: `country-${country.id}`,
        name: country.name,
        countryName: country.name,
        countryId: country.id,
        countryFlag: country.flag ?? null,
      }
    : { id: "system", name: "IxStats System", countryFlag: null };
}

/** Feed item for an ActivityFeed row; the caller supplies the resolved user, metadata and related countries. */
export function activityFeedItem(
  activity: any,
  user: unknown,
  metadata: unknown,
  relatedCountries: string[]
) {
  return {
    id: activity.id,
    type: activity.type,
    category: activity.category,
    source: "activity",
    user,
    content: {
      title: activity.title,
      description: activity.description,
      metadata,
    },
    poll: activity.poll ? formatPollForClient(activity.poll) : null,
    engagement: {
      likes: activity.likes,
      comments: activity.comments,
      shares: activity.shares,
      views: activity.views,
    },
    timestamp: activity.createdAt,
    priority: activity.priority.toLowerCase(),
    visibility: activity.visibility,
    relatedCountries,
  };
}

/** Feed item for a ThinkPages post, without the poll and rawPost fields each feed adds itself. */
export function thinkpagesFeedItem(post: any) {
  const cleanContent = post.content.replace(/\s*\[DiscordMsg:\d+\]\s*$/, "");
  const squashed = cleanContent.replace(/\s+/g, " ").trim();
  return {
    id: `thinkpages-${post.id}`,
    type: "social",
    category: "social",
    source: "thinkpages",
    user: {
      id: post.accountId,
      name: `@${post.account.username}`,
      countryName: post.account.country?.name,
      countryId: post.account.country?.id,
      countryFlag: post.account.country?.flag ?? null,
    },
    content: {
      title: squashed.length ? squashed : `@${post.account.username} · ThinkPages`,
      description: cleanContent,
      mediaAttachments: post.mediaAttachments.map((m: any) => ({
        id: m.id,
        url: m.url,
        filename: m.filename,
      })),
      reactionCounts: parseStoredReactionCounts(post.reactionCounts),
      metadata: {
        accountType: post.account.accountType,
        verified: post.account.verified,
        trending: post.trending,
        postType: "thinkpages",
      },
    },
    engagement: {
      likes: post.likeCount,
      comments: post.replyCount,
      shares: post.repostCount,
      views: post.impressions,
    },
    timestamp: post.isAutoGenerated ? post.ixTimeTimestamp : post.createdAt,
    priority: post.trending ? "high" : "medium",
    visibility: post.visibility,
    relatedCountries: post.account.country?.id ? [post.account.country.id] : [],
  };
}

function parseStoredReactionCounts(stored: unknown) {
  try {
    return typeof stored === "string" ? JSON.parse(stored) : stored || null;
  } catch {
    return null;
  }
}

/** Merge the viewer's own poll votes (hasVoted / userVotedOptionIds) into the paginated slice. */
export async function withViewerPollVotes<T extends { poll?: { id: string } | null }>(
  db: PrismaClient,
  viewerClerkId: string | null | undefined,
  activities: T[]
): Promise<T[]> {
  const pollIds = activities.flatMap((a) => (a.poll?.id ? [a.poll.id] : []));
  const votedOptions = new Map<string, string[]>();
  if (viewerClerkId && pollIds.length > 0) {
    const userVotes = await db.pollVote.findMany({
      where: { pollId: { in: pollIds }, userId: viewerClerkId },
      select: { pollId: true, optionId: true },
    });
    for (const vote of userVotes) {
      votedOptions.set(vote.pollId, [...(votedOptions.get(vote.pollId) ?? []), vote.optionId]);
    }
  }
  return activities.map((act) =>
    act.poll
      ? {
          ...act,
          poll: {
            ...act.poll,
            hasVoted: votedOptions.has(act.poll.id),
            userVotedOptionIds: votedOptions.get(act.poll.id) ?? [],
          },
        }
      : act
  );
}
