/**
 * Admin sub-router: ThinkPages → Discord feed configuration.
 *
 * Controls which public ThinkPages posts are mirrored to the dedicated
 * #thinkpages Discord channel. Merged into the top-level admin router, so the
 * public API paths are `api.admin.getThinkpagesDiscordFeedConfig` etc.
 */
import { z } from "zod";
import { createTRPCRouter, adminProcedure } from "~/server/api/trpc";
import {
  DEFAULT_THINKPAGES_CHANNEL_ID,
  toFilterConfig,
  evaluateFeedFilter,
  cleanPostContent,
  parseJsonStringArray,
  sendThinkPagesFeedTestMessage,
} from "~/lib/thinkpages-discord-feed";

async function loadOrSeedConfig(db: any) {
  let row = await db.thinkpagesDiscordFeedConfig.findUnique({ where: { id: "default" } });
  if (!row) {
    row = await db.thinkpagesDiscordFeedConfig.create({
      data: { id: "default", channelId: DEFAULT_THINKPAGES_CHANNEL_ID },
    });
  }
  return row;
}

const ConfigInput = z.object({
  enabled: z.boolean(),
  channelId: z.string().trim().max(40),
  includeGovernment: z.boolean(),
  includeMedia: z.boolean(),
  includeCitizen: z.boolean(),
  verifiedOnly: z.boolean(),
  accountAllowlist: z.array(z.string().trim()).max(500),
  accountBlocklist: z.array(z.string().trim()).max(500),
  hashtagAllowlist: z.array(z.string().trim()).max(500),
  hashtagBlocklist: z.array(z.string().trim()).max(500),
  excludeReplies: z.boolean(),
  excludeAutoGenerated: z.boolean(),
  minEngagement: z.number().int().min(0).max(100000),
});

export const adminThinkpagesDiscordFeedRouter = createTRPCRouter({
  getThinkpagesDiscordFeedConfig: adminProcedure.query(async ({ ctx }) => {
    const row = await loadOrSeedConfig(ctx.db as any);
    const [sentCount, failedCount, lastSent] = await Promise.all([
      (ctx.db as any).thinkpagesDiscordMirror.count({ where: { status: "sent" } }),
      (ctx.db as any).thinkpagesDiscordMirror.count({ where: { status: "failed" } }),
      (ctx.db as any).thinkpagesDiscordMirror.findFirst({
        where: { status: "sent" },
        orderBy: { createdAt: "desc" },
        select: { createdAt: true },
      }),
    ]);

    return {
      enabled: row.enabled,
      channelId: row.channelId,
      includeGovernment: row.includeGovernment,
      includeMedia: row.includeMedia,
      includeCitizen: row.includeCitizen,
      verifiedOnly: row.verifiedOnly,
      accountAllowlist: parseJsonStringArray(row.accountAllowlist),
      accountBlocklist: parseJsonStringArray(row.accountBlocklist),
      hashtagAllowlist: parseJsonStringArray(row.hashtagAllowlist),
      hashtagBlocklist: parseJsonStringArray(row.hashtagBlocklist),
      excludeReplies: row.excludeReplies,
      excludeAutoGenerated: row.excludeAutoGenerated,
      minEngagement: row.minEngagement,
      stats: { sentCount, failedCount, lastSentAt: lastSent?.createdAt ?? null },
    };
  }),

  saveThinkpagesDiscordFeedConfig: adminProcedure
    .input(ConfigInput)
    .mutation(async ({ ctx, input }) => {
      const data = {
        enabled: input.enabled,
        channelId: input.channelId,
        includeGovernment: input.includeGovernment,
        includeMedia: input.includeMedia,
        includeCitizen: input.includeCitizen,
        verifiedOnly: input.verifiedOnly,
        accountAllowlist: JSON.stringify(input.accountAllowlist.filter(Boolean)),
        accountBlocklist: JSON.stringify(input.accountBlocklist.filter(Boolean)),
        hashtagAllowlist: JSON.stringify(input.hashtagAllowlist.filter(Boolean)),
        hashtagBlocklist: JSON.stringify(input.hashtagBlocklist.filter(Boolean)),
        excludeReplies: input.excludeReplies,
        excludeAutoGenerated: input.excludeAutoGenerated,
        minEngagement: input.minEngagement,
      };
      await (ctx.db as any).thinkpagesDiscordFeedConfig.upsert({
        where: { id: "default" },
        update: data,
        create: { id: "default", ...data },
      });
      return { success: true };
    }),

  sendThinkpagesDiscordFeedTest: adminProcedure
    .input(z.object({ channelId: z.string().trim().optional() }).optional())
    .mutation(async ({ ctx, input }) => {
      const row = await loadOrSeedConfig(ctx.db as any);
      const channelId = input?.channelId?.trim() || row.channelId;
      return sendThinkPagesFeedTestMessage(channelId);
    }),

  // Recent public posts with their live eligibility verdict + mirror status — powers
  // the admin preview so you can see exactly what the current filter would mirror.
  getThinkpagesDiscordFeedPreview: adminProcedure
    .input(z.object({ limit: z.number().int().min(1).max(50).default(20) }).optional())
    .query(async ({ ctx, input }) => {
      const row = await loadOrSeedConfig(ctx.db as any);
      const config = toFilterConfig(row);

      const posts = await (ctx.db as any).thinkpagesPost.findMany({
        where: { visibility: "public" },
        orderBy: { createdAt: "desc" },
        take: input?.limit ?? 20,
        include: { account: true, discordMirror: true },
      });

      return posts.map((p: any) => {
        const verdict = p.account
          ? evaluateFeedFilter(config, p, p.account)
          : { eligible: false, reason: "No account" };
        const content = cleanPostContent(p.content ?? "");
        return {
          id: p.id,
          content: content.length > 160 ? `${content.slice(0, 160)}…` : content,
          authorName: p.account?.displayName ?? "Unknown",
          authorHandle: p.account?.username ?? "",
          accountType: p.account?.accountType ?? "",
          verified: !!p.account?.verified,
          createdAt: p.createdAt,
          eligible: verdict.eligible,
          reason: verdict.reason,
          mirrorStatus: p.discordMirror?.status ?? null,
        };
      });
    }),
});
