/**
 * Admin sub-router: ThinkPages → Discord feed configuration.
 *
 * Controls which public ThinkPages posts are mirrored to the dedicated
 * #thinkpages Discord channel. Merged into the top-level admin router, so the
 * public API paths are `api.admin.getThinkpagesDiscordFeedConfig` etc.
 */
import { z } from "zod";
import { createTRPCRouter, adminProcedure } from "~/server/api/trpc";
import { DEFAULT_THINKPAGES_CHANNEL_ID, parseJsonStringArray } from "~/lib/discord/thinkpages-feed";

const handleList = z.array(z.string().trim().min(1).max(100)).max(200);

const FeedConfigInput = z
  .object({
    enabled: z.boolean(),
    channelId: z
      .string()
      .trim()
      .regex(/^\d{5,30}$/, "Channel ID must be a Discord snowflake"),
    includeGovernment: z.boolean(),
    includeMedia: z.boolean(),
    includeCitizen: z.boolean(),
    includeSports: z.boolean(),
    verifiedOnly: z.boolean(),
    accountAllowlist: handleList,
    accountBlocklist: handleList,
    hashtagAllowlist: handleList,
    hashtagBlocklist: handleList,
    excludeReplies: z.boolean(),
    excludeAutoGenerated: z.boolean(),
    minEngagement: z.number().int().min(0).max(100000),
  })
  .partial();

async function loadOrSeedConfig(db: any) {
  let row = await db.thinkpagesDiscordFeedConfig.findUnique({ where: { id: "default" } });
  if (!row) {
    row = await db.thinkpagesDiscordFeedConfig.create({
      data: { id: "default", channelId: DEFAULT_THINKPAGES_CHANNEL_ID },
    });
  }
  return row;
}

export const adminThinkpagesDiscordFeedRouter = createTRPCRouter({
  getThinkpagesDiscordFeedConfig: adminProcedure.query(async ({ ctx }) => {
    const row = await loadOrSeedConfig(ctx.db as any);
    const [sentCount, failedCount, lastSent] = await Promise.all([
      (ctx.db as any).thinkpagesDiscordMirror.count({ where: { status: "sent" } }),
      (ctx.db as any).thinkpagesDiscordMirror.count({ where: { status: "failed" } }),
      (ctx.db as any).thinkpagesDiscordMirror.findFirst({
        where: { status: "sent" },
        orderBy: { createdAt: "desc" },
        select: { createdAt: true },
      }),
    ]);

    return {
      enabled: row.enabled,
      channelId: row.channelId,
      includeGovernment: row.includeGovernment,
      includeMedia: row.includeMedia,
      includeCitizen: row.includeCitizen,
      includeSports: row.includeSports,
      verifiedOnly: row.verifiedOnly,
      accountAllowlist: parseJsonStringArray(row.accountAllowlist),
      accountBlocklist: parseJsonStringArray(row.accountBlocklist),
      hashtagAllowlist: parseJsonStringArray(row.hashtagAllowlist),
      hashtagBlocklist: parseJsonStringArray(row.hashtagBlocklist),
      excludeReplies: row.excludeReplies,
      excludeAutoGenerated: row.excludeAutoGenerated,
      minEngagement: row.minEngagement,
      stats: { sentCount, failedCount, lastSentAt: lastSent?.createdAt ?? null },
    };
  }),

  /** Update the feed configuration; omitted fields keep their stored value. */
  saveThinkpagesDiscordFeedConfig: adminProcedure
    .input(FeedConfigInput)
    .mutation(async ({ ctx, input }) => {
      await loadOrSeedConfig(ctx.db as any);
      const { accountAllowlist, accountBlocklist, hashtagAllowlist, hashtagBlocklist, ...flags } =
        input;
      const lists = { accountAllowlist, accountBlocklist, hashtagAllowlist, hashtagBlocklist };
      const data: Record<string, unknown> = { ...flags };
      for (const [key, list] of Object.entries(lists)) {
        if (list) data[key] = JSON.stringify(list);
      }
      await (ctx.db as any).thinkpagesDiscordFeedConfig.update({ where: { id: "default" }, data });
      return { success: true };
    }),
});
