/**
 * Admin sub-router: ThinkPages → Discord feed configuration.
 *
 * Controls which public ThinkPages posts are mirrored to the dedicated
 * #thinkpages Discord channel. Merged into the top-level admin router, so the
 * public API paths are `api.admin.getThinkpagesDiscordFeedConfig` etc.
 */
import { createTRPCRouter, adminProcedure } from "~/server/api/trpc";
import { DEFAULT_THINKPAGES_CHANNEL_ID, parseJsonStringArray } from "~/lib/discord/thinkpages-feed";

async function loadOrSeedConfig(db: any) {
  let row = await db.thinkpagesDiscordFeedConfig.findUnique({ where: { id: "default" } });
  if (!row) {
    row = await db.thinkpagesDiscordFeedConfig.create({
      data: { id: "default", channelId: DEFAULT_THINKPAGES_CHANNEL_ID },
    });
  }
  return row;
}

export const adminThinkpagesDiscordFeedRouter = createTRPCRouter({
  getThinkpagesDiscordFeedConfig: adminProcedure.query(async ({ ctx }) => {
    const row = await loadOrSeedConfig(ctx.db as any);
    const [sentCount, failedCount, lastSent] = await Promise.all([
      (ctx.db as any).thinkpagesDiscordMirror.count({ where: { status: "sent" } }),
      (ctx.db as any).thinkpagesDiscordMirror.count({ where: { status: "failed" } }),
      (ctx.db as any).thinkpagesDiscordMirror.findFirst({
        where: { status: "sent" },
        orderBy: { createdAt: "desc" },
        select: { createdAt: true },
      }),
    ]);

    return {
      enabled: row.enabled,
      channelId: row.channelId,
      includeGovernment: row.includeGovernment,
      includeMedia: row.includeMedia,
      includeCitizen: row.includeCitizen,
      includeSports: row.includeSports,
      verifiedOnly: row.verifiedOnly,
      accountAllowlist: parseJsonStringArray(row.accountAllowlist),
      accountBlocklist: parseJsonStringArray(row.accountBlocklist),
      hashtagAllowlist: parseJsonStringArray(row.hashtagAllowlist),
      hashtagBlocklist: parseJsonStringArray(row.hashtagBlocklist),
      excludeReplies: row.excludeReplies,
      excludeAutoGenerated: row.excludeAutoGenerated,
      minEngagement: row.minEngagement,
      stats: { sentCount, failedCount, lastSentAt: lastSent?.createdAt ?? null },
    };
  }),
});
