/** @jest-environment node */
/**
 * SL-10: bookmarks have a "Saved posts" list, flags belong to the caller, and admins work the
 * flag queue (dismiss keeps the post, remove deletes it; both resolve every open flag on it).
 */
jest.mock("~/server/db", () => ({ db: {} }));
jest.mock("~/lib/cache", () => ({
  ...jest.requireActual("~/lib/cache"),
  globalCache: {
    get: jest.fn().mockResolvedValue(null),
    set: jest.fn().mockResolvedValue(undefined),
    deleteByPattern: jest.fn().mockResolvedValue(undefined),
  },
}));

import { createCallerFactory } from "~/server/api/trpc";
import { thinkpagesPostsBookmarksRouter } from "~/server/api/routers/thinkpages/posts/bookmarks";
import { thinkpagesPostsFlagsRouter } from "~/server/api/routers/thinkpages/posts/flags";
import { adminThinkpagesFlagsRouter } from "~/server/api/routers/admin/thinkpagesFlags";
import { createMockRouterContext } from "~/tests/helpers/router-context";
import { createMockPrisma } from "~/tests/helpers/mock-db";

const bookmarks = createCallerFactory(thinkpagesPostsBookmarksRouter);
const flags = createCallerFactory(thinkpagesPostsFlagsRouter);
const adminFlags = createCallerFactory(adminThinkpagesFlagsRouter);

function userCtx(db: ReturnType<typeof createMockPrisma>, clerk = "viewer") {
  return createMockRouterContext({
    db,
    auth: { userId: clerk },
    user: { id: "db1", clerkUserId: clerk, role: { name: "user", level: 100 } },
  }) as never;
}

function adminCtx(db: ReturnType<typeof createMockPrisma>) {
  return createMockRouterContext({
    db,
    auth: { userId: "admin_1" },
    user: { id: "db_admin", clerkUserId: "admin_1", role: { name: "admin", level: 10 } },
  }) as never;
}

const post = (id: string, visibility = "public", owner = "author") => ({
  id,
  visibility,
  content: `post ${id}`,
  hashtags: null,
  reactions: [],
  reactionCounts: null,
  poll: null,
  isAutoGenerated: false,
  createdAt: new Date("2026-10-01T00:00:00Z"),
  ixTimeTimestamp: new Date("2026-10-01T00:00:00Z"),
  account: { clerkUserId: owner },
});

describe("thinkpages.getBookmarkedPosts", () => {
  it("lists the caller's saved posts newest first, skipping deleted and unreadable posts", async () => {
    const db = createMockPrisma();
    db.postBookmark.findMany.mockResolvedValue([
      { id: "b3", postId: "p3", createdAt: new Date("2026-10-04") },
      { id: "b2", postId: "gone", createdAt: new Date("2026-10-03") },
      { id: "b1", postId: "p1", createdAt: new Date("2026-10-02") },
      { id: "b0", postId: "secret", createdAt: new Date("2026-10-01") },
    ]);
    db.thinkpagesPost.findMany.mockResolvedValue([
      post("p1"),
      post("p3"),
      post("secret", "private", "someone_else"),
    ]);

    const result = await bookmarks(userCtx(db)).getBookmarkedPosts({ limit: 3 });

    expect(db.postBookmark.findMany.mock.calls[0]![0]).toMatchObject({
      where: { userId: "viewer" },
      take: 4,
    });
    expect(result.posts.map((p: { id: string }) => p.id)).toEqual(["p3", "p1"]);
    expect(result.nextCursor).toBe("b1");
  });
});

describe("thinkpages.flagPost", () => {
  it("records the flag for the caller, whatever userId the client sends", async () => {
    const db = createMockPrisma();
    db.thinkpagesPost.findUnique.mockResolvedValue({ id: "p1" });
    await flags(userCtx(db)).flagPost({ postId: "p1", userId: "someone_else", reason: "spam" });
    expect(db.postFlag.create).toHaveBeenCalledWith({
      data: { postId: "p1", userId: "viewer", reason: "spam" },
    });
  });

  it("refuses a missing post and a repeat flag", async () => {
    const db = createMockPrisma();
    await expect(flags(userCtx(db)).flagPost({ postId: "nope" })).rejects.toMatchObject({
      code: "NOT_FOUND",
    });
    db.thinkpagesPost.findUnique.mockResolvedValue({ id: "p1" });
    db.postFlag.findUnique.mockResolvedValue({ id: "f1" });
    await expect(flags(userCtx(db)).flagPost({ postId: "p1" })).rejects.toMatchObject({
      code: "BAD_REQUEST",
    });
  });
});

describe("admin flag queue", () => {
  it("is admin only", async () => {
    const db = createMockPrisma();
    await expect(adminFlags(userCtx(db)).listFlaggedPosts({ limit: 10 })).rejects.toThrow();
    await expect(
      adminFlags(userCtx(db)).resolveFlaggedPost({ postId: "p1", action: "remove" })
    ).rejects.toThrow();
    expect(db.thinkpagesPost.delete).not.toHaveBeenCalled();
  });

  it("groups open flags by post, most flagged first", async () => {
    const db = createMockPrisma();
    db.postFlag.findMany.mockResolvedValue([
      { postId: "p2", reason: "rude", createdAt: new Date("2026-10-04") },
      { postId: "p1", reason: "spam", createdAt: new Date("2026-10-03") },
      { postId: "p1", reason: " ", createdAt: new Date("2026-10-02") },
    ]);
    db.thinkpagesPost.findMany.mockResolvedValue([
      {
        id: "p1",
        content: "buy now",
        visibility: "public",
        createdAt: new Date(),
        account: { username: "spammer", displayName: null },
      },
    ]);

    const result = await adminFlags(adminCtx(db)).listFlaggedPosts({ limit: 10 });

    expect(db.postFlag.findMany.mock.calls[0]![0].where).toEqual({ status: "open" });
    expect(result.totalOpen).toBe(3);
    expect(result.items.map((i) => [i.postId, i.flagCount])).toEqual([
      ["p1", 2],
      ["p2", 1],
    ]);
    expect(result.items[0]!.reasons).toEqual(["spam"]);
    expect(result.items[0]!.post?.authorUsername).toBe("spammer");
    expect(result.items[1]!.post).toBeNull();
  });

  it("dismiss resolves the flags and keeps the post", async () => {
    const db = createMockPrisma();
    db.postFlag.count.mockResolvedValue(2);
    db.postFlag.updateMany.mockResolvedValue({ count: 2 });

    const result = await adminFlags(adminCtx(db)).resolveFlaggedPost({
      postId: "p1",
      action: "dismiss",
    });

    expect(result).toEqual({ resolved: 2, removed: false });
    expect(db.thinkpagesPost.delete).not.toHaveBeenCalled();
    expect(db.postFlag.updateMany.mock.calls[0]![0]).toMatchObject({
      where: { postId: "p1", status: "open" },
      data: { status: "dismissed", resolvedBy: "admin_1" },
    });
  });

  it("remove deletes the post and keeps counters in step", async () => {
    const db = createMockPrisma();
    db.postFlag.count.mockResolvedValue(1);
    db.postFlag.updateMany.mockResolvedValue({ count: 1 });
    db.thinkpagesPost.findUnique.mockResolvedValue({
      id: "p1",
      accountId: "acc1",
      content: "bad",
      parentPostId: "parent",
      repostOfId: null,
      pollId: null,
    });
    db.thinkpagesPost.count.mockResolvedValue(0);
    db.thinkpagesPost.delete.mockResolvedValue({ id: "p1" });

    const result = await adminFlags(adminCtx(db)).resolveFlaggedPost({
      postId: "p1",
      action: "remove",
    });

    expect(result).toEqual({ resolved: 1, removed: true });
    expect(db.thinkpagesPost.delete).toHaveBeenCalledWith({ where: { id: "p1" } });
    expect(db.thinkpagesPost.updateMany).toHaveBeenCalledWith({
      where: { id: "parent", replyCount: { gt: 0 } },
      data: { replyCount: { decrement: 1 } },
    });
    expect(db.thinkpagesAccount.update).toHaveBeenCalledWith({
      where: { id: "acc1" },
      data: { postCount: { decrement: 1 } },
    });
    expect(db.postFlag.updateMany.mock.calls[0]![0].data.status).toBe("removed");
  });

  it("refuses a post with no open flags", async () => {
    const db = createMockPrisma();
    db.postFlag.count.mockResolvedValue(0);
    await expect(
      adminFlags(adminCtx(db)).resolveFlaggedPost({ postId: "p1", action: "dismiss" })
    ).rejects.toMatchObject({ code: "NOT_FOUND" });
  });
});
