/**
 * SL-3: reactions on a Discord-mirrored post are never credited to made-up community members
 * when the Discord fetch is unavailable.
 */
import { describe, it, expect, beforeEach, afterEach } from "@jest/globals";
import { createCallerFactory } from "~/server/api/trpc";
import { thinkpagesPostsReactionsQueriesRouter } from "~/server/api/routers/thinkpages/posts/reactions/queries";
import { createMockRouterContext } from "~/tests/helpers/router-context";
import { createMockPrisma } from "~/tests/helpers/mock-db";

const createCaller = createCallerFactory(thinkpagesPostsReactionsQueriesRouter);

describe("SL-3: getPostReactions on a Discord-mirrored post", () => {
  const savedToken = process.env.DISCORD_BOT_TOKEN;

  beforeEach(() => {
    delete process.env.DISCORD_BOT_TOKEN;
  });

  afterEach(() => {
    if (savedToken === undefined) delete process.env.DISCORD_BOT_TOKEN;
    else process.env.DISCORD_BOT_TOKEN = savedToken;
  });

  it("lists only real local reactors when Discord can't be reached", async () => {
    const db = createMockPrisma();
    const local = {
      id: "r1",
      postId: "post_1",
      reactionType: "like",
      account: { id: "acc_1", username: "real", displayName: "Real Person" },
    };
    db.postReaction.findMany.mockResolvedValue([local]);
    db.thinkpagesPost.findUnique.mockResolvedValue({
      id: "post_1",
      content: "Hello [DiscordMsg:123456789]",
      isAutoGenerated: true,
      reactionCounts: JSON.stringify({ like: 5, fire: 3 }),
      createdAt: new Date("2026-09-01T00:00:00Z"),
    });

    const caller = createCaller(createMockRouterContext({ auth: null, user: null, db }) as never);
    const reactions = await caller.getPostReactions({ postId: "post_1" });

    expect(reactions).toEqual([local]);
    expect(db.thinkpagesAccount.findFirst).not.toHaveBeenCalled();
  });
});
