#!/usr/bin/env bash
# setup.sh - start the WikiOS test MediaWiki and, on first start, install it (plan 417). DEV ONLY.
#
# Usage:  ./scripts/ops/wikios-test-mediawiki/setup.sh
#
# Idempotent: it generates random credentials once (into the gitignored .env.test-mediawiki next to
# this script), starts the container, runs MediaWiki's installer (SQLite) if the database does not
# exist yet, creates the WikiOSMirror account in the `wikios-mirror` group with a bot password, and
# prints where the credentials are. It never prints a secret and never contacts anything but
# 127.0.0.1 (the image pull aside).

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

ENV_FILE=".env.test-mediawiki"
SERVICE="mediawiki"
DB_FILE="/var/www/data/wikios_test.sqlite"
# Lives in the data volume next to the database, so `docker compose down -v` resets both.
BOT_MARKER="/var/www/data/.wikios-mirror-bot-created"
WIKI_URL="http://127.0.0.1:8089"
ADMIN_USER="WikiOSAdmin"
BOT_USER="WikiOSMirror"
BOT_APP="wikios"
# Bot password grants: the rights the `wikios-mirror` group has that a bot password can express.
# No editinterface / editsiteconfig: WikiOS keeps those namespaces admin-only.
BOT_GRANTS="basic,highvolume,editpage,editprotected,createeditmovepage,uploadfile,uploadeditmovefile,import"

log() { echo "[wikios-test-mediawiki] $*"; }

if ! command -v docker >/dev/null 2>&1; then
    log "ERROR: docker is required." >&2
    exit 1
fi

random_secret() {
    # 48 hex characters; /dev/urandom so it works without openssl.
    head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
}

compose() {
    docker compose --env-file "$ENV_FILE" "$@"
}

mw_exec() {
    # -T: no TTY (scripted); runs as www-data so SQLite files end up owned by the web server user.
    compose exec -T -u www-data "$@"
}

# --- 1. Credentials (created once) ---
fresh_credentials=false
if [ ! -f "$ENV_FILE" ]; then
    fresh_credentials=true
    log "Generating credentials in $ENV_FILE (gitignored)"
    umask 077
    {
        echo "# Generated by setup.sh for the local WikiOS test MediaWiki. Throwaway secrets, never commit."
        echo "WIKIOS_TEST_MW_SECRET_KEY=$(random_secret)"
        echo "WIKIOS_TEST_MW_ADMIN_USER=$ADMIN_USER"
        echo "WIKIOS_TEST_MW_ADMIN_PASSWORD=$(random_secret)"
        echo "WIKIOS_TEST_MW_BOT_USER=$BOT_USER"
        echo "WIKIOS_TEST_MW_BOT_APP=$BOT_APP"
        echo "WIKIOS_TEST_MW_BOT_PASSWORD=$(random_secret)"
        echo "# Point a local WikiOS at the test wiki with these (source this file, or copy them):"
        echo "WIKIOS_MEDIAWIKI_API=$WIKI_URL/api.php"
        echo "WIKIOS_MEDIAWIKI_INTERNAL_URL=$WIKI_URL/api.php"
        echo "WIKIOS_MEDIAWIKI_BOT_USER=$BOT_USER@$BOT_APP"
    } > "$ENV_FILE"
    # The bot token equals the generated bot password; keep it in one place.
    bot_password="$(sed -n 's/^WIKIOS_TEST_MW_BOT_PASSWORD=//p' "$ENV_FILE")"
    echo "WIKIOS_MEDIAWIKI_BOT_TOKEN=$bot_password" >> "$ENV_FILE"
    unset bot_password
fi

set -a
# shellcheck source=/dev/null
source "$ENV_FILE"
set +a

# --- 2. Container ---
log "Starting the container (127.0.0.1:8089)"
compose up -d

log "Waiting for the container to accept commands"
for _ in $(seq 1 30); do
    if compose exec -T "$SERVICE" php -v >/dev/null 2>&1; then
        break
    fi
    sleep 2
done
compose exec -T "$SERVICE" php -v >/dev/null

# --- 3. Install on first start ---
if compose exec -T "$SERVICE" test -f "$DB_FILE"; then
    if [ "$fresh_credentials" = true ]; then
        log "ERROR: $ENV_FILE was just regenerated but the wiki database already exists, so the stored" >&2
        log "       passwords would not match. Reset the wiki first: docker compose down -v" >&2
        exit 1
    fi
    log "Database exists, skipping install"
else
    log "Running install.php (SQLite)"
    compose exec -T "$SERVICE" chown www-data:www-data /var/www/data
    # The admin password goes in through stdin into a 0600 file, not onto a command line.
    printf '%s' "$WIKIOS_TEST_MW_ADMIN_PASSWORD" |
        mw_exec "$SERVICE" sh -c 'umask 077; cat > /tmp/wikios-admin.pass'
    # MW_CONFIG_FILE points at a file that does not exist, so the installer does not see the mounted
    # LocalSettings.php and the generated one goes to /tmp/LocalSettings.php and is discarded (ours is the real config).
    mw_exec -e MW_CONFIG_FILE=/tmp/wikios-no-localsettings.php "$SERVICE" \
        php maintenance/run.php install \
        --dbtype sqlite --dbpath /var/www/data --dbname wikios_test \
        --server "$WIKI_URL" --scriptpath "" \
        --passfile /tmp/wikios-admin.pass \
        --confpath /tmp \
        "WikiOS Test Wiki" "$WIKIOS_TEST_MW_ADMIN_USER"
    mw_exec "$SERVICE" rm -f /tmp/wikios-admin.pass
fi

# --- 4. Extension tables (idempotent) ---
log "Running update.php (quiet)"
mw_exec "$SERVICE" php maintenance/run.php update --quick >/dev/null

# --- 5. The WikiOS mirror account + bot password (once per database) ---
if compose exec -T "$SERVICE" test -f "$BOT_MARKER"; then
    log "$WIKIOS_TEST_MW_BOT_USER and its bot password exist, skipping"
else
    log "Creating the $WIKIOS_TEST_MW_BOT_USER account (group wikios-mirror)"
    mw_exec "$SERVICE" php maintenance/run.php createAndPromote --force \
        --custom-groups wikios-mirror \
        "$WIKIOS_TEST_MW_BOT_USER" "$WIKIOS_TEST_MW_BOT_PASSWORD" >/dev/null
    log "Creating the bot password $WIKIOS_TEST_MW_BOT_USER@$WIKIOS_TEST_MW_BOT_APP"
    mw_exec "$SERVICE" php maintenance/run.php createBotPassword \
        --appid "$WIKIOS_TEST_MW_BOT_APP" --grants "$BOT_GRANTS" \
        "$WIKIOS_TEST_MW_BOT_USER" "$WIKIOS_TEST_MW_BOT_PASSWORD" >/dev/null
    mw_exec "$SERVICE" touch "$BOT_MARKER"
fi

# --- 6. Smoke test ---
if command -v curl >/dev/null 2>&1; then
    if curl -fsS "$WIKI_URL/api.php?action=query&meta=siteinfo&format=json" | grep -q '"sitename"'; then
        log "api.php answers at $WIKI_URL/api.php"
    else
        log "WARNING: api.php did not answer as expected at $WIKI_URL" >&2
    fi
fi

log "Ready. Credentials: $(pwd)/$ENV_FILE. Stop with: docker compose down  (add -v to reset the wiki)"
