/**
 * Demo seed for diplomacy, social feed, thinktanks, geography, activity, and achievements.
 */

import { type PrismaClient } from "@prisma/client";
import { IxTime } from "../../ixtime";
import fallbackSoc from "../../../../data/seed/fallback-social.json";

type Prisma = PrismaClient;

export async function seedDiplomacy(
  prisma: Prisma,
  countryId: string,
  countryName?: string
): Promise<number> {
  let count = 0;
  const name = countryName || "Republic";

  const otherCountries = await prisma.country.findMany({
    where: { id: { not: countryId } },
    take: 6,
    select: { id: true, name: true, flag: true },
  });

  if (otherCountries.length === 0) return 0;

  for (let i = 0; i < Math.min(otherCountries.length, 5); i++) {
    const other = otherCountries[i]!;
    const relationships = ["allied", "friendly", "neutral", "tense", "friendly"];
    const strengths = [85, 72, 50, 30, 68];

    await prisma.diplomaticRelation.create({
      data: {
        country1: countryId,
        country2: other.id,
        relationship: relationships[i]!,
        strength: strengths[i]!,
        status: "active",
        lastContact: new Date(),
        tradeVolume: Math.random() * 50000000000,
      },
    });
    count++;
  }

  for (let i = 0; i < Math.min(otherCountries.length, 3); i++) {
    const other = otherCountries[i]!;
    const embassy = await prisma.embassy.create({
      data: {
        hostCountryId: other.id,
        guestCountryId: countryId,
        name: `Embassy of ${name} in ${other.name}`,
        ambassadorName: [
          "Ambassador Helena Varus",
          "Ambassador Marcus Scipio",
          "Ambassador Julia Cornelia",
        ][i],
        staffCount: 8 + i * 3,
        status: "active",
        level: 2 + i,
        experience: 500 + i * 300,
        influence: 30 + i * 15,
        effectiveness: 55 + i * 10,
        reputation: 60 + i * 8,
        budget: 100000 + i * 50000,
      },
    });
    count++;

    if (i === 0) {
      await prisma.embassyMission.create({
        data: {
          embassyId: embassy.id,
          name: "Trade Negotiation",
          type: "economic",
          description: "Negotiate preferential trade terms for agricultural exports.",
          difficulty: "moderate",
          status: "active",
          cost: 15000,
          duration: 14,
          startedAt: new Date(),
          completesAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
          experienceReward: 100,
          influenceReward: 5,
          successChance: 65,
          progress: 35,
          ixTimeStarted: IxTime.getCurrentIxTime(),
          ixTimeCompletes: IxTime.getCurrentIxTime() + 20160,
        },
      });
      count++;
    }
  }

  return count;
}

export async function seedSocial(
  prisma: Prisma,
  countryId: string,
  userId: string,
  countryName?: string
): Promise<number> {
  let count = 0;
  const name = countryName || "Nation";

  const account = await prisma.thinkpagesAccount.create({
    data: {
      clerkUserId: userId,
      countryId,
      accountType: "official",
      username: `demo_${name.toLowerCase().replace(/\s+/g, "_")}_${Date.now()}`,
      displayName: `Republic of ${name}`,
      firstName: "Government",
      lastName: "Communications",
      bio: `Official government communications account for the Republic of ${name}.`,
      verified: true,
      followerCount: 12500,
      followingCount: 45,
      postCount: 5,
      personality: "formal",
      politicalLean: "center_right",
    },
  });
  count++;

  const posts = [
    {
      accountId: account.id,
      content: `The Infrastructure Investment Summit concluded today with unanimous cabinet approval for the National Digital Infrastructure Act. 95% broadband coverage target set for 2028. #Digital${name.replace(/\s+/g, "")} #Infrastructure`,
      postType: "original",
      likeCount: 342,
      repostCount: 87,
      replyCount: 23,
      impressions: 15600,
      hashtags: JSON.stringify([`Digital${name.replace(/\s+/g, "")}`, "Infrastructure"]),
      ixTimeTimestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      isAutoGenerated: true,
    },
    {
      accountId: account.id,
      content:
        "Breaking: Navy successfully completes maritime exercises. Our territorial waters remain secure. #NationalDefense",
      postType: "original",
      likeCount: 891,
      repostCount: 234,
      replyCount: 56,
      impressions: 45000,
      hashtags: JSON.stringify(["NationalDefense"]),
      ixTimeTimestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      isAutoGenerated: true,
    },
    {
      accountId: account.id,
      content:
        "Healthcare reform update: Universal coverage expansion has reached 3 of 5 target regions ahead of schedule. Rural healthcare initiative continues to make strong progress. #HealthcareForAll",
      postType: "original",
      likeCount: 567,
      repostCount: 145,
      replyCount: 89,
      impressions: 28000,
      hashtags: JSON.stringify(["HealthcareForAll"]),
      ixTimeTimestamp: new Date(),
      isAutoGenerated: true,
    },
  ];

  await prisma.thinkpagesPost.createMany({ data: posts });
  count += posts.length;

  return count;
}

export async function seedThinkTanks(
  prisma: Prisma,
  userId: string,
  countryName?: string
): Promise<number> {
  const name = countryName || "National";
  const existing = await (prisma as any).thinktankGroup.count({ where: { createdBy: userId } });
  if (existing > 0) return 0;

  let count = 0;
  const now = new Date();

  const econGroup = await (prisma as any).thinktankGroup.create({
    data: {
      name: `${name} Economic Policy Forum`,
      description:
        "A collaborative space for discussing economic policy, fiscal strategy, and trade agreements. Open to government advisors and policy analysts.",
      type: "public",
      category: "economics",
      tags: JSON.stringify(["economics", "fiscal-policy", "trade"]),
      memberCount: 3,
      createdBy: userId,
      isActive: true,
      settings: JSON.stringify({ allowInvites: true, moderationLevel: "standard" }),
    },
  });
  count++;

  await (prisma as any).thinktankMember.createMany({
    data: [
      { groupId: econGroup.id, userId, role: "admin" },
      { groupId: econGroup.id, userId: "system_advisor_1", role: "moderator" },
      { groupId: econGroup.id, userId: "system_analyst_1", role: "member" },
    ],
  });
  count += 3;

  for (const m of fallbackSoc.econMessages) {
    await (prisma as any).thinktankMessage.create({
      data: {
        groupId: econGroup.id,
        userId: "system_advisor_1",
        content: `[${m.sender}] ${m.content}`,
        messageType: "text",
        ixTimeTimestamp: new Date(now.getTime() - m.minutesAgo * 60 * 1000),
      },
    });
    count++;
  }

  return count;
}

export async function seedNationalIdentity(
  prisma: Prisma,
  countryId: string,
  countryName: string
): Promise<number> {
  await prisma.nationalIdentity.upsert({
    where: { countryId },
    update: {},
    create: {
      countryId,
      countryName,
      officialName: `Republic of ${countryName}`,
      governmentType: "Constitutional Republic",
      capitalCity: "Metropolis Prime",
      currency: "Credits",
      currencySymbol: "CR",
      demonym: `${countryName}n`,
      nationalLanguage: "Standard",
      nationalReligion: "Secular",
    },
  });
  return 1;
}

export async function seedGeography(prisma: Prisma, countryId: string): Promise<number> {
  let count = 0;
  const emptyGeom = { type: "Polygon", coordinates: [] };

  await prisma.territory.createMany({
    data: [
      { countryId, name: "Mainland", geometry: emptyGeom, isMainland: true, areaSqKm: 320000 },
      {
        countryId,
        name: "Southern Islands",
        geometry: emptyGeom,
        isMainland: false,
        areaSqKm: 15000,
      },
    ],
  });
  count += 2;

  const subdivisionData = [
    { name: "Capital Region", population: 14000000, capital: "Nova Capita", areaSqKm: 28000 },
    { name: "Northern Province", population: 9000000, capital: "Northgate", areaSqKm: 72000 },
    { name: "Eastern Territories", population: 7500000, capital: "Eastport", areaSqKm: 65000 },
    { name: "Western District", population: 7000000, capital: "Westholm", areaSqKm: 58000 },
    { name: "Southern Coast", population: 6500000, capital: "Southhaven", areaSqKm: 55000 },
    { name: "Central Highlands", population: 6000000, capital: "Highlands City", areaSqKm: 57000 },
  ];

  const subIds: string[] = [];
  const { updateSubdivisionSpatialProfile } = await import("~/lib/country-geo");
  for (const sub of subdivisionData) {
    const created = await prisma.subdivision.create({
      data: {
        countryId,
        name: sub.name,
        type: "province",
        geometry: emptyGeom,
        level: 1,
        population: sub.population,
        capital: sub.capital,
        areaSqKm: sub.areaSqKm,
        status: "approved",
        submittedBy: "system",
      },
    });
    subIds.push(created.id);
    await updateSubdivisionSpatialProfile(prisma, created.id).catch(() => {});
    count++;
  }

  const cities = [
    {
      name: "Nova Capita",
      type: "capital",
      subdivisionId: subIds[0]!,
      population: 4200000,
      isNationalCapital: true,
      isSubdivisionCapital: true,
    },
    {
      name: "Northgate",
      type: "city",
      subdivisionId: subIds[1]!,
      population: 1800000,
      isNationalCapital: false,
      isSubdivisionCapital: true,
    },
  ];

  const { updateCitySpatialProfile } = await import("~/lib/country-geo");
  for (const city of cities) {
    const created = await prisma.city.create({
      data: {
        countryId,
        name: city.name,
        type: city.type,
        coordinates: { lat: 45.0, lng: 20.0 },
        population: city.population,
        isNationalCapital: city.isNationalCapital,
        isSubdivisionCapital: city.isSubdivisionCapital,
        subdivisionId: city.subdivisionId,
        status: "approved",
        submittedBy: "system",
      },
    });
    await updateCitySpatialProfile(prisma, created.id).catch(() => {});
    count++;
  }

  const pois = [
    {
      name: "National Parliament",
      category: "government",
      coordinates: { lat: 45.01, lng: 20.01 },
      description: "Seat of the national legislature and primary government complex.",
    },
  ];
  for (const poi of pois) {
    await prisma.pointOfInterest.create({
      data: {
        countryId,
        subdivisionId: subIds[0],
        name: poi.name,
        category: poi.category,
        coordinates: poi.coordinates,
        description: poi.description,
        status: "approved",
        submittedBy: "system",
      },
    });
    count++;
  }

  return count;
}

export async function seedActivityFeed(
  prisma: Prisma,
  countryId: string,
  userId: string
): Promise<number> {
  const now = new Date();

  const activities = [
    {
      type: "economic_report",
      category: "economic",
      title: "GDP Report Published",
      description: "Quarterly GDP figures released showing continued growth across key sectors.",
      priority: "low" as const,
    },
    {
      type: "diplomatic_event",
      category: "diplomatic",
      title: "New Embassy Established",
      description: "Diplomatic mission opened in allied nation, expanding the diplomatic network.",
      priority: "medium" as const,
    },
    {
      type: "military_update",
      category: "military",
      title: "Naval Exercise Completed",
      description: "Joint maritime exercise concluded successfully with allied forces.",
      priority: "medium" as const,
    },
  ];

  const records = activities.map((activity, i) => {
    const daysAgo = Math.floor((i / activities.length) * 30);
    const hoursOffset = (i * 7) % 12;
    return {
      ...activity,
      userId,
      countryId,
      likes: (i * 13 + 7) % 50,
      views: ((i * 37 + 50) % 500) + 50,
      createdAt: new Date(
        now.getTime() - daysAgo * 24 * 60 * 60 * 1000 - hoursOffset * 60 * 60 * 1000
      ),
    };
  });

  await prisma.activityFeed.createMany({ data: records });
  return records.length;
}

export async function seedAchievements(prisma: Prisma, userId: string): Promise<number> {
  const now = new Date();

  const achievements = [
    {
      achievementId: "econ-first-million",
      title: "First Million",
      description: "Country GDP reached $1M",
      category: "Economic",
      rarity: "Common",
      daysAgo: 25,
    },
    {
      achievementId: "econ-millionaire-nation",
      title: "Millionaire Nation",
      description: "GDP per capita exceeded $10,000",
      category: "Economic",
      rarity: "Uncommon",
      daysAgo: 20,
    },
  ];

  const existing = await prisma.userAchievement
    .findMany({
      where: { userId },
      select: { achievementId: true },
    })
    .catch(() => []);
  const existingIds = new Set(existing.map((e: { achievementId: string }) => e.achievementId));

  const toCreate = achievements
    .filter((a) => !existingIds.has(a.achievementId))
    .map(({ daysAgo, ...a }) => ({
      ...a,
      userId,
      unlockedAt: new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000),
    }));

  if (toCreate.length > 0) {
    await prisma.userAchievement.createMany({ data: toCreate });
  }
  return toCreate.length;
}
