import { z } from "zod";
import { createTRPCRouter, rateLimitedPublicProcedure } from "~/server/api/trpc";
import { TRPCError } from "@trpc/server";
import { canViewPost, resolveReactionCounts } from "../../post-utils";

function formatPollForClient(poll: any) {
  if (!poll) return null;
  const votes: Record<string, number> = {};
  let totalVotes = 0;
  poll.options.forEach((opt: any) => {
    const count = opt._count?.votes ?? 0;
    votes[opt.id] = count;
    totalVotes += count;
  });

  return {
    id: poll.id,
    question: poll.question,
    description: poll.description,
    pollType: poll.pollType,
    multiple: poll.multiple,
    isActive: poll.isActive,
    endDate: poll.endDate,
    countryId: poll.countryId,
    options: poll.options.map((opt: any) => ({
      id: opt.id,
      label: opt.label,
      description: opt.description,
    })),
    votes,
    totalVotes,
    hasVoted: false,
    userVotedOptionIds: [],
  };
}

const pollInclude = {
  poll: {
    include: {
      options: {
        include: {
          _count: {
            select: { votes: true },
          },
        },
      },
    },
  },
};

const accountSelect = {
  id: true,
  username: true,
  displayName: true,
  profileImageUrl: true,
  accountType: true,
  verified: true,
  clerkUserId: true,
  countryId: true,
  country: {
    select: {
      id: true,
      name: true,
      flag: true,
    },
  },
} as const;

const accountInclude = {
  account: {
    select: accountSelect,
  },
};

const postInclude = {
  ...accountInclude,
  parentPost: {
    include: accountInclude,
  },
  repostOf: {
    include: accountInclude,
  },
  reactions: true,
  mediaAttachments: true,
  ...pollInclude,
  reposts: {
    select: { accountId: true },
  },
  _count: {
    select: {
      replies: true,
      reposts: true,
    },
  },
};

function transformPost(p: any) {
  if (!p) return p;
  const reactionCounts = resolveReactionCounts(p.reactionCounts, p.reactions);

  return {
    ...p,
    poll: formatPollForClient(p.poll),
    hashtags: p.hashtags
      ? typeof p.hashtags === "string"
        ? JSON.parse(p.hashtags)
        : p.hashtags
      : [],
    reactionCounts,
    timestamp: p.isAutoGenerated ? p.ixTimeTimestamp.toISOString() : p.createdAt.toISOString(),
  };
}

export const thinkpagesPostsPostsQueriesRouter = createTRPCRouter({
  // Get post details with replies
  getPost: rateLimitedPublicProcedure
    .input(z.object({ postId: z.string() }))
    .query(async ({ ctx, input }) => {
      const { db } = ctx;
      const viewerClerkUserId = ctx.auth?.userId ?? null;

      const post = await db.thinkpagesPost.findUnique({
        where: { id: input.postId },
        include: {
          ...postInclude,
          replies: {
            include: {
              ...accountInclude,
              reactions: true,
              mediaAttachments: true,
              ...pollInclude,
            },
            orderBy: { ixTimeTimestamp: "asc" },
            take: 50,
          },
        },
      });

      // Private/draft posts are owner-only; respond as if the post does not exist.
      if (!post || !canViewPost(post as any, viewerClerkUserId)) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Post not found",
        });
      }

      // Don't leak embedded parent/repost/replies the viewer couldn't read on their own.
      const visible = (p: any) => (p && canViewPost(p, viewerClerkUserId) ? p : null);
      const transformed = transformPost({
        ...post,
        parentPost: visible((post as any).parentPost),
        repostOf: visible((post as any).repostOf),
      });

      return {
        ...transformed,
        replies: post.replies
          ? post.replies
              .filter((reply: any) => canViewPost(reply, viewerClerkUserId))
              .map((reply: any) => transformPost(reply))
          : [],
      };
    }),

  // Get posts by Clerk User ID - shows all posts from all accounts owned by this user
  getPostsByClerkUserId: rateLimitedPublicProcedure
    .input(
      z.object({
        clerkUserId: z.string(),
        limit: z.number().min(1).max(50).default(20),
        cursor: z.string().optional(),
      })
    )
    .query(async ({ ctx, input }) => {
      const { db } = ctx;

      const accounts = await db.thinkpagesAccount.findMany({
        where: { clerkUserId: input.clerkUserId },
        select: { id: true },
      });

      const accountIds = accounts.map((acc) => acc.id);

      if (accountIds.length === 0) {
        return { posts: [], nextCursor: null };
      }

      const posts = await db.thinkpagesPost.findMany({
        where: {
          accountId: { in: accountIds },
          visibility: "public",
        },
        include: postInclude,
        orderBy: [{ pinned: "desc" }, { ixTimeTimestamp: "desc" }],
        take: input.limit,
        cursor: input.cursor ? { id: input.cursor } : undefined,
        skip: input.cursor ? 1 : 0,
      });

      const transformedPosts = posts.map((post) => ({
        ...post,
        poll: formatPollForClient((post as any).poll),
        hashtags: post.hashtags ? JSON.parse(post.hashtags) : [],
        reactionCounts: resolveReactionCounts(post.reactionCounts, (post as any).reactions),
        timestamp: post.isAutoGenerated
          ? post.ixTimeTimestamp.toISOString()
          : post.createdAt.toISOString(),
      }));

      return {
        posts: transformedPosts,
        nextCursor: posts.length === input.limit ? posts[posts.length - 1]?.id : null,
      };
    }),
});
