import { z } from "zod";
import { createTRPCRouter, rateLimitedPublicProcedure } from "~/server/api/trpc";
import { TRPCError } from "@trpc/server";

function formatPollForClient(poll: any) {
  if (!poll) return null;
  const votes: Record<string, number> = {};
  let totalVotes = 0;
  poll.options.forEach((opt: any) => {
    const count = opt._count?.votes ?? 0;
    votes[opt.id] = count;
    totalVotes += count;
  });

  return {
    id: poll.id,
    question: poll.question,
    description: poll.description,
    pollType: poll.pollType,
    multiple: poll.multiple,
    isActive: poll.isActive,
    endDate: poll.endDate,
    countryId: poll.countryId,
    options: poll.options.map((opt: any) => ({
      id: opt.id,
      label: opt.label,
      description: opt.description,
    })),
    votes,
    totalVotes,
    hasVoted: false,
    userVotedOptionIds: [],
  };
}

const pollInclude = {
  poll: {
    include: {
      options: {
        include: {
          _count: {
            select: { votes: true },
          },
        },
      },
    },
  },
};

const accountSelect = {
  id: true,
  username: true,
  displayName: true,
  profileImageUrl: true,
  accountType: true,
  verified: true,
  clerkUserId: true,
  countryId: true,
  country: {
    select: {
      id: true,
      name: true,
      flag: true,
    },
  },
} as const;

const accountInclude = {
  account: {
    select: accountSelect,
  },
};

const postInclude = {
  ...accountInclude,
  parentPost: {
    include: accountInclude,
  },
  repostOf: {
    include: accountInclude,
  },
  reactions: true,
  mediaAttachments: true,
  ...pollInclude,
  reposts: {
    select: { accountId: true },
  },
  _count: {
    select: {
      replies: true,
      reposts: true,
    },
  },
};

function transformPost(p: any) {
  if (!p) return p;
  const reactionCounts = (() => {
    let baseline: Record<string, number> = {};
    try {
      if (p.reactionCounts) {
        baseline =
          typeof p.reactionCounts === "string" ? JSON.parse(p.reactionCounts) : p.reactionCounts;
      }
    } catch {
      // ignore
    }
    if (p.reactions) {
      return p.reactions.reduce((acc: any, reaction: any) => {
        acc[reaction.reactionType] = (acc[reaction.reactionType] || 0) + 1;
        return acc;
      }, baseline);
    }
    return baseline;
  })();

  return {
    ...p,
    poll: formatPollForClient(p.poll),
    hashtags: p.hashtags
      ? typeof p.hashtags === "string"
        ? JSON.parse(p.hashtags)
        : p.hashtags
      : [],
    reactionCounts,
    timestamp: p.isAutoGenerated ? p.ixTimeTimestamp.toISOString() : p.createdAt.toISOString(),
  };
}

export const thinkpagesPostsPostsQueriesRouter = createTRPCRouter({
  // Get post details with replies
  getPost: rateLimitedPublicProcedure
    .input(z.object({ postId: z.string() }))
    .query(async ({ ctx, input }) => {
      const { db } = ctx;

      const post = await db.thinkpagesPost.findUnique({
        where: { id: input.postId },
        include: {
          ...postInclude,
          replies: {
            include: {
              ...accountInclude,
              reactions: true,
              mediaAttachments: true,
              ...pollInclude,
            },
            orderBy: { ixTimeTimestamp: "asc" },
            take: 50,
          },
        },
      });

      if (!post) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Post not found",
        });
      }

      return {
        ...transformPost(post),
        replies: post.replies ? post.replies.map((reply: any) => transformPost(reply)) : [],
      };
    }),

  // Get posts by Clerk User ID - shows all posts from all accounts owned by this user
  getPostsByClerkUserId: rateLimitedPublicProcedure
    .input(
      z.object({
        clerkUserId: z.string(),
        limit: z.number().min(1).max(50).default(20),
        cursor: z.string().optional(),
      })
    )
    .query(async ({ ctx, input }) => {
      const { db } = ctx;

      const accounts = await db.thinkpagesAccount.findMany({
        where: { clerkUserId: input.clerkUserId },
        select: { id: true },
      });

      const accountIds = accounts.map((acc) => acc.id);

      if (accountIds.length === 0) {
        return { posts: [], nextCursor: null };
      }

      const posts = await db.thinkpagesPost.findMany({
        where: {
          accountId: { in: accountIds },
          visibility: "public",
        },
        include: postInclude,
        orderBy: [{ pinned: "desc" }, { ixTimeTimestamp: "desc" }],
        take: input.limit,
        cursor: input.cursor ? { id: input.cursor } : undefined,
        skip: input.cursor ? 1 : 0,
      });

      const transformedPosts = posts.map((post) => ({
        ...post,
        poll: formatPollForClient((post as any).poll),
        hashtags: post.hashtags ? JSON.parse(post.hashtags) : [],
        reactionCounts: (() => {
          let baseline: Record<string, number> = {};
          try {
            if (post.reactionCounts) {
              baseline =
                typeof post.reactionCounts === "string"
                  ? JSON.parse(post.reactionCounts)
                  : post.reactionCounts;
            }
          } catch {
            // ignore
          }
          return (post as any).reactions.reduce((acc: any, reaction: any) => {
            acc[reaction.reactionType] = (acc[reaction.reactionType] || 0) + 1;
            return acc;
          }, baseline);
        })(),
        timestamp: post.isAutoGenerated
          ? post.ixTimeTimestamp.toISOString()
          : post.createdAt.toISOString(),
      }));

      return {
        posts: transformedPosts,
        nextCursor: posts.length === input.limit ? posts[posts.length - 1]?.id : null,
      };
    }),

  /** Get draft posts for a country or user accounts (for ThinkPages draft sync) */
  getDraftPosts: rateLimitedPublicProcedure
    .input(z.object({ countryId: z.string().optional(), clerkUserId: z.string().optional() }))
    .query(async ({ ctx, input }) => {
      const { db } = ctx;
      if (!input.countryId && !input.clerkUserId) return [];

      const accountIds: string[] = [];
      if (input.countryId) {
        const accs = await db.thinkpagesAccount.findMany({
          where: { countryId: input.countryId },
          select: { id: true },
        });
        accountIds.push(...accs.map((a: any) => a.id));
      }
      if (input.clerkUserId) {
        const accs = await db.thinkpagesAccount.findMany({
          where: { clerkUserId: input.clerkUserId },
          select: { id: true },
        });
        accountIds.push(...accs.map((a: any) => a.id));
      }

      if (accountIds.length === 0) return [];

      const drafts = await db.thinkpagesPost.findMany({
        where: {
          accountId: { in: Array.from(new Set(accountIds)) },
          visibility: "draft",
        },
        include: postInclude,
        orderBy: { createdAt: "desc" },
        take: 20,
      });

      return drafts.map((p: any) => transformPost(p));
    }),
});
