"use client";
// src/app/admin/_components/ThinkPagesDiscordFeedCard.tsx
// ThinkPages → Discord feed: which public posts the bot mirrors to the #thinkpages channel (WK-10).

import { useEffect, useState } from "react";
import { FloppyDisk as Save } from "iconoir-react";
import { Button } from "~/components/ui/button";
import { Card } from "~/components/ui/card";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import { Skeleton } from "~/components/ui/skeleton";
import { Switch } from "~/components/ui/switch";
import { useNotify } from "~/hooks/useNotify";
import { api } from "~/trpc/react";

type FlagKey =
  | "enabled"
  | "includeGovernment"
  | "includeMedia"
  | "includeCitizen"
  | "includeSports"
  | "verifiedOnly"
  | "excludeReplies"
  | "excludeAutoGenerated";
type ListKey = "accountAllowlist" | "accountBlocklist" | "hashtagAllowlist" | "hashtagBlocklist";

const FLAGS: Array<[FlagKey, string, string]> = [
  ["enabled", "Mirror posts to Discord", "Send matching public posts to the channel below"],
  ["includeGovernment", "Government accounts", "Posts by government personas"],
  ["includeMedia", "Media accounts", "Posts by media personas"],
  ["includeCitizen", "Citizen accounts", "Posts by citizen personas"],
  ["includeSports", "Sports bulletins", "Posts by @SportsNews"],
  ["verifiedOnly", "Verified accounts only", "Skip posts from unverified accounts"],
  ["excludeReplies", "Skip replies", "Only mirror top-level posts"],
  ["excludeAutoGenerated", "Skip automated posts", "Leave out auto-generated news posts"],
];

const LISTS: Array<[ListKey, string]> = [
  ["accountAllowlist", "Always include accounts"],
  ["accountBlocklist", "Never include accounts"],
  ["hashtagAllowlist", "Only posts with hashtags"],
  ["hashtagBlocklist", "Never include hashtags"],
];

const splitList = (raw: string) =>
  raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

export function ThinkPagesDiscordFeedCard() {
  const notify = useNotify();
  const { data, isLoading, refetch } = api.admin.getThinkpagesDiscordFeedConfig.useQuery();
  const [flags, setFlags] = useState<Record<FlagKey, boolean> | null>(null);
  const [channelId, setChannelId] = useState("");
  const [minEngagement, setMinEngagement] = useState(0);
  const [lists, setLists] = useState<Record<ListKey, string>>({
    accountAllowlist: "",
    accountBlocklist: "",
    hashtagAllowlist: "",
    hashtagBlocklist: "",
  });

  useEffect(() => {
    if (!data) return;
    setFlags(Object.fromEntries(FLAGS.map(([k]) => [k, data[k]])) as Record<FlagKey, boolean>);
    setChannelId(data.channelId);
    setMinEngagement(data.minEngagement);
    setLists(
      Object.fromEntries(LISTS.map(([k]) => [k, data[k].join(", ")])) as Record<ListKey, string>
    );
  }, [data]);

  const save = api.admin.saveThinkpagesDiscordFeedConfig.useMutation({
    onSuccess: () => {
      notify.success("Saved", "Discord feed settings updated.");
      void refetch();
    },
    onError: (err) => notify.error("Save failed", err.message),
  });

  if (isLoading || !flags) {
    return <Skeleton className="rounded-row h-64 w-full" />;
  }

  const handleSave = () =>
    save.mutate({
      ...flags,
      channelId,
      minEngagement,
      accountAllowlist: splitList(lists.accountAllowlist),
      accountBlocklist: splitList(lists.accountBlocklist),
      hashtagAllowlist: splitList(lists.hashtagAllowlist),
      hashtagBlocklist: splitList(lists.hashtagBlocklist),
    });

  const stats = data?.stats;

  return (
    <Card className="space-y-5 p-5">
      <div className="border-separator flex items-center justify-between border-b pb-4">
        <div>
          <h3 className="text-label text-caption">Discord ThinkPages feed</h3>
          <p className="text-label-secondary text-footnote mt-0.5">
            {stats
              ? `${stats.sentCount} sent, ${stats.failedCount} failed${
                  stats.lastSentAt ? `, last ${new Date(stats.lastSentAt).toLocaleString()}` : ""
                }`
              : "Mirrors public posts to a Discord channel through the bot"}
          </p>
        </div>
        <Button size="sm" onClick={handleSave} disabled={save.isPending}>
          <Save className="mr-2 h-3.5 w-3.5" />
          {save.isPending ? "Saving..." : "Save"}
        </Button>
      </div>

      <div className="space-y-3">
        {FLAGS.map(([key, label, description]) => (
          <div
            key={key}
            className="border-separator bg-fill-3 rounded-row flex items-center justify-between border p-4"
          >
            <div>
              <Label className="text-label text-caption">{label}</Label>
              <p className="text-label-secondary text-footnote">{description}</p>
            </div>
            <Switch
              checked={flags[key]}
              onCheckedChange={(checked) => setFlags((f) => f && { ...f, [key]: checked })}
              className="scale-90"
            />
          </div>
        ))}

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label className="text-label text-caption">Channel ID</Label>
            <Input
              value={channelId}
              onChange={(e) => setChannelId(e.target.value)}
              className="rounded-control-sm md:text-footnote h-(--control-height-sm) font-mono"
            />
          </div>
          <div className="space-y-1.5">
            <Label className="text-label text-caption">Minimum engagement</Label>
            <Input
              type="number"
              min={0}
              value={minEngagement}
              onChange={(e) => setMinEngagement(Math.max(0, parseInt(e.target.value) || 0))}
              className="rounded-control-sm md:text-footnote h-(--control-height-sm) font-mono"
            />
          </div>
          {LISTS.map(([key, label]) => (
            <div key={key} className="space-y-1.5">
              <Label className="text-label text-caption">{label}</Label>
              <Input
                value={lists[key]}
                onChange={(e) => setLists((l) => ({ ...l, [key]: e.target.value }))}
                placeholder="Comma-separated"
                className="rounded-control-sm md:text-footnote h-(--control-height-sm)"
              />
            </div>
          ))}
        </div>
      </div>
    </Card>
  );
}
