// Government archetypes: political and legal systems.
import {
  Building,
  CheckSquare as Vote,
  Crown,
  Hammer as Gavel,
  OpenBook as BookOpen,
} from "iconoir-react";
import type { RealCountryData } from "../../lib/economy-data-service";
import type { ArchetypeSeed } from "../country-archetypes";

export const governmentArchetypes: ArchetypeSeed[] = [
  {
    id: "gov-democratic",
    name: "Democratic",
    description: "Full or flawed democracies",
    icon: Vote,
    color: "text-blue",
    filter: (country: RealCountryData) => {
      // This is a simplified heuristic - in reality would use democracy index
      const democraticCountries = [
        "Australia",
        "Austria",
        "Belgium",
        "Canada",
        "Denmark",
        "Finland",
        "France",
        "Germany",
        "Iceland",
        "Ireland",
        "Italy",
        "Japan",
        "Luxembourg",
        "Netherlands",
        "New Zealand",
        "Norway",
        "Portugal",
        "South Korea",
        "Spain",
        "Sweden",
        "Switzerland",
        "United Kingdom",
        "United States",
        "Costa Rica",
        "Uruguay",
        "Taiwan",
      ];
      return democraticCountries.includes(country.name);
    },
    gradient: "bg-blue/10",
    categoryId: "political-systems",
    priority: 12,
  },
  {
    id: "gov-federal",
    name: "Federal",
    description: "Federal system of government",
    icon: Building,
    color: "text-purple",
    filter: (country: RealCountryData) => {
      const federalCountries = [
        "Argentina",
        "Australia",
        "Austria",
        "Belgium",
        "Bosnia and Herzegovina",
        "Brazil",
        "Canada",
        "Ethiopia",
        "Germany",
        "India",
        "Iraq",
        "Malaysia",
        "Mexico",
        "Nepal",
        "Nigeria",
        "Pakistan",
        "Russia",
        "South Sudan",
        "Sudan",
        "Switzerland",
        "United States",
        "Venezuela",
      ];
      return federalCountries.includes(country.name);
    },
    gradient: "bg-purple/10",
    categoryId: "political-systems",
    priority: 13,
  },
  {
    id: "gov-monarchy",
    name: "Monarchy",
    description: "Constitutional or absolute monarchy",
    icon: Crown,
    color: "text-yellow",
    filter: (country: RealCountryData) => {
      const monarchies = [
        "Andorra",
        "Bahrain",
        "Belgium",
        "Bhutan",
        "Brunei",
        "Cambodia",
        "Denmark",
        "Japan",
        "Jordan",
        "Kuwait",
        "Lesotho",
        "Liechtenstein",
        "Luxembourg",
        "Malaysia",
        "Monaco",
        "Morocco",
        "Netherlands",
        "Norway",
        "Oman",
        "Qatar",
        "Saudi Arabia",
        "Spain",
        "Eswatini",
        "Sweden",
        "Thailand",
        "Tonga",
        "United Arab Emirates",
        "United Kingdom",
      ];
      return monarchies.includes(country.name);
    },
    gradient: "bg-yellow/10",
    categoryId: "political-systems",
    priority: 14,
  },
  {
    id: "gov-common-law",
    name: "Common Law",
    description: "English common law legal tradition",
    icon: Gavel,
    color: "text-teal",
    filter: (country: RealCountryData) => {
      const commonLawCountries = [
        "Antigua and Barbuda",
        "Australia",
        "Bahamas",
        "Bangladesh",
        "Barbados",
        "Belize",
        "Botswana",
        "Canada",
        "Cyprus",
        "Dominica",
        "Fiji",
        "Gambia",
        "Ghana",
        "Grenada",
        "Guyana",
        "Hong Kong",
        "India",
        "Ireland",
        "Israel",
        "Jamaica",
        "Kenya",
        "Kiribati",
        "Liberia",
        "Malawi",
        "Malaysia",
        "Malta",
        "Mauritius",
        "Myanmar",
        "Namibia",
        "Nauru",
        "New Zealand",
        "Nigeria",
        "Pakistan",
        "Papua New Guinea",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Solomon Islands",
        "South Africa",
        "Sri Lanka",
        "Tanzania",
        "Tonga",
        "Trinidad and Tobago",
        "Tuvalu",
        "Uganda",
        "United Kingdom",
        "United States",
        "Vanuatu",
        "Zambia",
        "Zimbabwe",
      ];
      return commonLawCountries.includes(country.name);
    },
    gradient: "bg-teal/10",
    categoryId: "legal-systems",
    priority: 15,
  },
  {
    id: "gov-civil-law",
    name: "Civil Law",
    description: "Continental European civil law tradition",
    icon: BookOpen,
    color: "text-indigo",
    filter: (country: RealCountryData) => {
      const civilLawCountries = [
        "Albania",
        "Argentina",
        "Austria",
        "Belgium",
        "Bolivia",
        "Brazil",
        "Bulgaria",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Czech Republic",
        "Denmark",
        "Dominican Republic",
        "Ecuador",
        "El Salvador",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "Indonesia",
        "Italy",
        "Japan",
        "Latvia",
        "Lithuania",
        "Luxembourg",
        "Mexico",
        "Netherlands",
        "Nicaragua",
        "Norway",
        "Panama",
        "Paraguay",
        "Peru",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "South Korea",
        "Spain",
        "Sweden",
        "Switzerland",
        "Taiwan",
        "Turkey",
        "Ukraine",
        "Uruguay",
        "Venezuela",
        "Vietnam",
      ];
      return civilLawCountries.includes(country.name);
    },
    gradient: "bg-indigo/10",
    categoryId: "legal-systems",
    priority: 16,
  },
];
