// Region archetypes: continental groupings.
import { Globe } from "iconoir-react";
import type { RealCountryData } from "../../lib/economy-data-service";
import type { ArchetypeSeed } from "../country-archetypes";

export const regionArchetypes: ArchetypeSeed[] = [
  {
    id: "region-europe",
    name: "European",
    description: "Countries from Europe",
    icon: Globe,
    color: "text-blue-500",
    filter: (country: RealCountryData) => {
      const europeanCountries = [
        "Albania",
        "Andorra",
        "Armenia",
        "Austria",
        "Azerbaijan",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Czechia",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Georgia",
        "Germany",
        "Greece",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Kazakhstan",
        "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Turkey",
        "Ukraine",
        "United Kingdom",
        "Vatican City",
      ];
      return europeanCountries.includes(country.name);
    },
    gradient: "from-blue-500/20 to-indigo-500/10",
    categoryId: "geographical-regions",
    priority: 8,
  },
  {
    id: "region-asia",
    name: "Asian",
    description: "Countries from Asia",
    icon: Globe,
    color: "text-red-500",
    filter: (country: RealCountryData) => {
      const asianCountries = [
        "Afghanistan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Cambodia",
        "China",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Lebanon",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "North Korea",
        "Oman",
        "Pakistan",
        "Palestine",
        "Philippines",
        "Qatar",
        "Saudi Arabia",
        "Singapore",
        "South Korea",
        "Sri Lanka",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Timor-Leste",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Vietnam",
        "Yemen",
      ];
      return asianCountries.includes(country.name);
    },
    gradient: "from-red-500/20 to-orange-500/10",
    categoryId: "geographical-regions",
    priority: 9,
  },
  {
    id: "region-americas",
    name: "Americas",
    description: "Countries from North, Central & South America",
    icon: Globe,
    color: "text-green-500",
    filter: (country: RealCountryData) => {
      const americanCountries = [
        "Antigua and Barbuda",
        "Argentina",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bolivia",
        "Brazil",
        "Canada",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "El Salvador",
        "Grenada",
        "Guatemala",
        "Guyana",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Mexico",
        "Nicaragua",
        "Panama",
        "Paraguay",
        "Peru",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Suriname",
        "Trinidad and Tobago",
        "United States",
        "Uruguay",
        "Venezuela",
      ];
      return americanCountries.includes(country.name);
    },
    gradient: "from-green-500/20 to-teal-500/10",
    categoryId: "geographical-regions",
    priority: 10,
  },
  {
    id: "region-africa",
    name: "African",
    description: "Countries from Africa",
    icon: Globe,
    color: "text-orange-500",
    filter: (country: RealCountryData) => {
      const africanCountries = [
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo",
        "Côte d'Ivoire",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "São Tomé and Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe",
      ];
      return africanCountries.includes(country.name);
    },
    gradient: "from-orange-500/20 to-amber-500/10",
    categoryId: "geographical-regions",
    priority: 11,
  },
  {
    id: "region-oceania",
    name: "Oceanian",
    description: "Countries from Oceania and the Pacific",
    icon: Globe,
    color: "text-teal-500",
    filter: (country: RealCountryData) => {
      const oceanianCountries = [
        "Australia",
        "New Zealand",
        "Papua New Guinea",
        "Fiji",
        "Solomon Islands",
        "Vanuatu",
        "Samoa",
        "Kiribati",
        "Tonga",
        "Micronesia",
        "Palau",
        "Marshall Islands",
        "Nauru",
        "Tuvalu",
      ];
      return (
        oceanianCountries.includes(country.name) ||
        (country.continent || "").toLowerCase().includes("oceania")
      );
    },
    gradient: "from-teal-600/20 to-cyan-600/10",
    categoryId: "geographical-regions",
    priority: 12,
  },
];
