"use client";

import { Globe, MapPin, Settings } from "lucide-react";
import { ArticleLayout, Section, InfoBox } from "../../_components/ArticleLayout";

export default function FirstCountryArticle() {
  return (
    <ArticleLayout
      title="Creating Your First Country"
      description="Walk through the builder workflow to configure identity, government, economy, and demographics."
      icon={Globe}
    >
      <Section title="Builder Checklist">
        <ol className="list-decimal pl-6 space-y-2">
          <li>Choose a foundation country or start from scratch in `/builder`.</li>
          <li>Complete Identity, Government, Economy, Labor, Demographics, and Fiscal steps.</li>
          <li>Review the summary page, adjust policy recommendations, and save to publish the nation.</li>
        </ol>
      </Section>

      <Section title="Data Sources & Tips">
        <InfoBox title="Helpful Tools">
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Wiki Import:</strong> Pull baseline data via `wikiImporter.previewImport` and customise before saving.</li>
            <li><strong>Atomic Components:</strong> Combine government/economic/tax components for synergy bonuses.</li>
            <li><strong>Policy Advisor:</strong> Review recommendations generated by builder utilities (`src/app/builder/utils`).</li>
          </ul>
        </InfoBox>
      </Section>

      <Section title="After You Save">
        <ul className="list-disc pl-6 space-y-2">
          <li>New metrics become available immediately inside `/mycountry` (vitality rings, compliance tasks, quick actions).</li>
          <li>Leaderboards update on next refresh; run `npm run test:crud` if seeding in bulk.</li>
          <li>Update documentation in `docs/systems/builder.md` when introducing new builder fields.</li>
        </ul>
      </Section>

      <InfoBox title="Related Reading">
        <ul className="list-disc pl-6 space-y-1">
          <li><MapPin className="inline h-4 w-4" /> `docs/systems/builder.md` – deep dive into builder structure.</li>
          <li><Settings className="inline h-4 w-4" /> `/help/government/atomic` & `/help/economy/tiers` for advanced configuration guidance.</li>
        </ul>
      </InfoBox>
    </ArticleLayout>
  );
}
