// src/lib/onoma/cultural-profiles.ts
// Onoma Lab — Cultural & Linguistic Seed Data

import type { CulturalProfile, NameCategory } from "./types";

/**
 * Seed names representing different linguistic and cultural families.
 * Curated to train the Markov Chain to generate phone-consistent names.
 */
export const CULTURAL_PROFILES: Record<CulturalProfile, Record<NameCategory, string[]>> = {
  latin: {
    country: [
      "Hispania",
      "Gallia",
      "Italia",
      "Lusitania",
      "Britannia",
      "Mauritania",
      "Dacia",
      "Dalmatia",
      "Raetia",
      "Noricum",
      "Pannonia",
      "Thracia",
      "Galatia",
      "Cappadocia",
      "Cilicia",
      "Judea",
      "Aegyptus",
      "Cyrenaica",
      "Numidia",
      "Corsica",
      "Sardinia",
      "Sicilia",
      "Achaia",
      "Epirus",
      "Macedonia",
      "Mesopotamia",
      "Armenia",
      "Bithynia",
    ],
    city: [
      "Roma",
      "Mediolanum",
      "Lugdunum",
      "Carthago",
      "Byzantium",
      "Lutetia",
      "Florentia",
      "Pompeii",
      "Corduba",
      "Toletum",
      "Tarraco",
      "Caesaraugusta",
      "Emerita",
      "Olisipo",
      "Hispalis",
      "Massilia",
      "Genua",
      "Ravenna",
      "Verona",
      "Neapolis",
      "Syracusae",
      "Brundisium",
      "Tarentum",
      "Capua",
      "Ostia",
      "Beneventum",
      "Ariminum",
      "Bononia",
      "Aquileia",
    ],
    province: [
      "Tarraconensis",
      "Baetica",
      "Lusitania",
      "Narbonensis",
      "Aquitania",
      "Belgica",
      "Lugdunensis",
      "Campania",
      "Apulia",
      "Calabria",
      "Etruria",
      "Umbria",
      "Liguria",
      "Venetia",
      "Istria",
      "Emilia",
      "Flaminia",
      "Picenum",
      "Samnium",
      "Latium",
    ],
    geography: [
      "Vesuvius",
      "Aetna",
      "Olympus",
      "Apenninus",
      "Pyrenaeus",
      "Danubius",
      "Padus",
      "Tiberis",
      "Rhenus",
      "Rhodanus",
      "Tagus",
      "Durius",
      "Iberus",
      "Sequana",
      "Liger",
      "Garumna",
      "Anas",
      "Baetis",
      "Rubico",
      "Arnus",
      "Albis",
      "Viadus",
      "Vistula",
    ],
    person: [
      "Marcus",
      "Lucius",
      "Gaius",
      "Julius",
      "Tiberius",
      "Claudius",
      "Nero",
      "Augustus",
      "Trajanus",
      "Hadrianus",
      "Antoninus",
      "Aurelius",
      "Commodus",
      "Septimius",
      "Severus",
      "Caracalla",
      "Diocletianus",
      "Constantinus",
      "Valerius",
      "Cornelius",
      "Fabius",
      "Decimus",
      "Aulus",
      "Quintus",
      "Servius",
      "Spurius",
      "Publius",
      "Titus",
      "Gnaeus",
      "Lucretia",
      "Cornelia",
    ],
    dynasty: [
      "Julio-Claudian",
      "Flavian",
      "Antonine",
      "Severan",
      "Constantinian",
      "Valentinian",
      "Theodosian",
      "Justinian",
      "Heraclian",
      "Isaurian",
      "Macedonian",
      "Komnenian",
      "Angelan",
      "Palaiologan",
      "Tarquin",
      "Valerian",
      "Decian",
      "Aurelian",
    ],
    military: [
      "Legio Augusta",
      "Legio Rapax",
      "Legio Victrix",
      "Legio Ferrata",
      "Legio Fulminata",
      "Legio Gemina",
      "Legio Alaudae",
      "Legio Adiutrix",
      "Legio Fretensis",
      "Cohors Italica",
      "Ala Augusta",
      "Classis Misenensis",
      "Classis Ravennas",
      "Classis Britannica",
    ],
    organization: [
      "Senatus",
      "Comitia",
      "Pontifices",
      "Vestales",
      "Augures",
      "Decemviri",
      "Quindecimviri",
      "Collegium Aurificum",
      "Collegium Fabrorum",
      "Collegium Mercatorum",
      "Sodalitas",
    ],
    culture: [
      "Romanus",
      "Latinus",
      "Sabinus",
      "Etruscus",
      "Samnis",
      "Campanus",
      "Apulus",
      "Calaber",
      "Ligurius",
      "Venetus",
      "Galli",
      "Iberi",
      "Lusitani",
      "Daci",
      "Thracians",
      "Greeks",
    ],
    ship: [
      "Neptunus",
      "Minerva",
      "Diana",
      "Apollo",
      "Mars",
      "Bacchus",
      "Mercury",
      "Ceres",
      "Juno",
      "Jupiter",
      "Vulcanus",
      "Vesta",
      "Pluto",
      "Proserpina",
      "Hercules",
      "Victoria",
    ],
  },
  germanic: {
    country: [
      "Gotland",
      "Jutland",
      "Friesland",
      "Westphalia",
      "Bavaria",
      "Saxony",
      "Swabia",
      "Franconia",
      "Thuringia",
      "Holstein",
      "Pomerania",
      "Silesia",
      "Bohemia",
      "Austria",
      "Denmark",
      "Norway",
      "Sweden",
      "Iceland",
      "England",
      "Mercia",
      "Wessex",
      "Northumbria",
    ],
    city: [
      "Hamburg",
      "Bremen",
      "Cologne",
      "Munich",
      "Frankfurt",
      "Nuremberg",
      "Stuttgart",
      "Hanover",
      "Leipzig",
      "Dresden",
      "Berlin",
      "Vienna",
      "Salzburg",
      "Zurich",
      "Basel",
      "Bern",
      "Geneva",
      "Copenhagen",
      "Oslo",
      "Bergen",
      "Trondheim",
      "Stockholm",
      "Gothenburg",
      "Uppsala",
      "Visby",
      "Reykjavik",
      "Akureyri",
      "London",
      "York",
      "Winchester",
    ],
    province: [
      "Baden",
      "Bavaria",
      "Brandenburg",
      "Hesse",
      "Hanover",
      "Rhineland",
      "Westphalia",
      "Saxony",
      "Silesia",
      "Pomerania",
      "Thuringia",
      "Tyrol",
      "Styria",
      "Carinthia",
      "Flanders",
      "Zeeland",
      "Holland",
      "Utrecht",
      "Gelderland",
      "Frisia",
    ],
    geography: [
      "Rhine",
      "Elbe",
      "Danube",
      "Oder",
      "Vistula",
      "Weser",
      "Ems",
      "Main",
      "Neckar",
      "Moselle",
      "Inn",
      "Salzach",
      "Glomma",
      "Klaralven",
      "Dalalven",
      "Torne",
      "Vatnajokull",
      "Kebnekaise",
      "Galdhopiggen",
      "Brocken",
      "Feldberg",
      "Watzmann",
      "Zugspitze",
    ],
    person: [
      "Ragnar",
      "Bjorn",
      "Sigurd",
      "Harald",
      "Olaf",
      "Eric",
      "Leif",
      "Knut",
      "Ivar",
      "Rollo",
      "Thorstein",
      "Hakon",
      "Magnus",
      "Sven",
      "Gustav",
      "Adolf",
      "Wilhelm",
      "Friedrich",
      "Heinrich",
      "Ludwig",
      "Karl",
      "Otto",
      "Konrad",
      "Dietrich",
      "Siegfried",
      "Gunther",
      "Hagen",
      "Alboin",
      "Theodoric",
      "Clovis",
      "Freydis",
      "Gudrun",
      "Astrid",
    ],
    dynasty: [
      "Merovingian",
      "Carolingian",
      "Ottonian",
      "Salian",
      "Hohenstaufen",
      "Habsburg",
      "Wasa",
      "Bernadotte",
      "Hohenzollern",
      "Wittelsbach",
      "Wettin",
      "Oldenburg",
      "Hanover",
      "Windsor",
      "Plantagenet",
      "Tudor",
      "Stuart",
    ],
    military: [
      "Fyrd",
      "Huskarls",
      "Einherjar",
      "Landsknecht",
      "Reiter",
      "Gefolge",
      "Heer",
      "Wiking",
      "Varangian",
      "Hird",
      "Leidang",
      "Spathar",
      "Schiltron",
    ],
    organization: [
      "Althing",
      "Thing",
      "Guild",
      "Hansa",
      "Vehm",
      "Ritterorden",
      "Bund",
      "Zunft",
      "Gilde",
      "Gemeinschaft",
      "Orden",
      "Bruderschaft",
    ],
    culture: [
      "Goth",
      "Vandal",
      "Burgundian",
      "Frank",
      "Saxon",
      "Angle",
      "Jute",
      "Frisian",
      "Lombard",
      "Suebi",
      "Norse",
      "Dane",
      "Swede",
      "Norwegian",
      "German",
      "Dutch",
    ],
    ship: [
      "Drakkar",
      "Knarr",
      "Skeid",
      "Karve",
      "Snekkja",
      "Galeon",
      "Kogge",
      "Hulk",
      "Wasa",
      "Gjoa",
      "Fram",
      "Siri",
      "Freja",
      "Thor",
      "Odin",
      "Loki",
    ],
  },
  celtic: {
    country: [
      "Eire",
      "Alba",
      "Cymru",
      "Breizh",
      "Kernow",
      "Mannin",
      "Galatia",
      "Helvetia",
      "Noricum",
      "Belgica",
      "Caledonia",
      "Hibernia",
      "Cambria",
      "Armorica",
    ],
    city: [
      "Dublin",
      "Belfast",
      "Cork",
      "Galway",
      "Limerick",
      "Waterford",
      "Glasgow",
      "Edinburgh",
      "Aberdeen",
      "Dundee",
      "Inverness",
      "Cardiff",
      "Swansea",
      "Newport",
      "Bangor",
      "St Davids",
      "Rennes",
      "Brest",
      "Quimper",
      "Lorient",
      "Vannes",
      "Saint-Malo",
      "Douglas",
      "Peel",
      "Ramsey",
      "Castletown",
    ],
    province: [
      "Leinster",
      "Munster",
      "Connacht",
      "Ulster",
      "Gwynedd",
      "Powys",
      "Dyfed",
      "Gwent",
      "Glamorgan",
      "Cornwall",
      "Brittany",
      "Lothian",
      "Fife",
      "Argyll",
    ],
    geography: [
      "Shannon",
      "Liffey",
      "Boyne",
      "Blackwater",
      "Suir",
      "Nore",
      "Barrow",
      "Foyle",
      "Clyde",
      "Tay",
      "Forth",
      "Spey",
      "Dee",
      "Don",
      "Ness",
      "Severn",
      "Thames",
      "Wye",
      "Trent",
      "Ouse",
      "Snowdon",
      "Ben Nevis",
      "Carrauntoohil",
    ],
    person: [
      "Connor",
      "Cuchulainn",
      "Fingal",
      "Ossian",
      "Brian",
      "Cormac",
      "Diarmuid",
      "Lugh",
      "Nuada",
      "Angus",
      "Donald",
      "Duncan",
      "Malcolm",
      "Kenneth",
      "Alpin",
      "Arthur",
      "Merlin",
      "Gawain",
      "Galahad",
      "Tristan",
      "Lancelot",
      "Geraint",
      "Percival",
      "Kay",
      "Bedivere",
      "Uther",
      "Pendragon",
      "Vortigern",
      "Boudica",
      "Caratacus",
    ],
    dynasty: [
      "O'Connor",
      "O'Neill",
      "O'Brien",
      "McCarthy",
      "McDonald",
      "Campbell",
      "Stewart",
      "Tudor",
      "Gwynedd",
      "Aberffraw",
      "Dinefwr",
      "Mathrafal",
    ],
    military: [
      "Gallowglass",
      "Kern",
      "Fianna",
      "Teulu",
      "Clanna",
      "Celts",
      "Picts",
      "Gauls",
      "Helvetians",
      "Galatians",
    ],
    organization: [
      "Druids",
      "Bards",
      "Ovate",
      "Clan",
      "Tuath",
      "Fine",
      "Senechus",
      "Brehon",
      "Gorsedd",
      "Eisteddfod",
    ],
    culture: [
      "Gael",
      "Briton",
      "Pict",
      "Gaul",
      "Breton",
      "Cornish",
      "Manx",
      "Welsh",
      "Irish",
      "Scottish",
      "Belgae",
      "Helvetii",
    ],
    ship: [
      "Currach",
      "Coracle",
      "Birlinn",
      "Galley",
      "Fingal",
      "Lugh",
      "Bran",
      "Cuchulainn",
      "Danu",
      "Dagda",
      "Morrigan",
      "Aengus",
    ],
  },
  slavic: {
    country: [
      "Rossiya",
      "Ukraina",
      "Belarus",
      "Polsha",
      "Chekhiya",
      "Slovakiya",
      "Sloveniya",
      "Khorvatiya",
      "Bosniya",
      "Serbiya",
      "Chernogoriya",
      "Makedoniya",
      "Bulgariya",
      "Moravia",
      "Silesia",
      "Ruthenia",
      "Galicia",
      "Volhynia",
      "Pomerania",
    ],
    city: [
      "Moskva",
      "Kiev",
      "Minsk",
      "Varshava",
      "Praga",
      "Bratislava",
      "Ljubljana",
      "Zagreb",
      "Sarajevo",
      "Beograd",
      "Podgorica",
      "Skopje",
      "Sofiya",
      "Novgorod",
      "Vladimir",
      "Suzdal",
      "Yaroslavl",
      "Kostroma",
      "Nizhny",
      "Kazan",
      "Samara",
      "Saratov",
      "Volgograd",
      "Rostov",
      "Krasnodar",
      "Sochi",
      "Sevastopol",
      "Odessa",
      "Kharkov",
      "Lvov",
      "Gdansk",
      "Krakow",
      "Wroclaw",
      "Poznan",
    ],
    province: [
      "Mazovia",
      "Silesia",
      "Pomerania",
      "Galicia",
      "Podolia",
      "Volhynia",
      "Transcarpathia",
      "Dalmatia",
      "Istria",
      "Slavonia",
      "Vojvodina",
      "Kosovo",
      "Sandzak",
      "Thrace",
      "Macedonia",
      "Dobruja",
      "Krajina",
      "Lesser Poland",
      "Greater Poland",
    ],
    geography: [
      "Volga",
      "Dnepr",
      "Don",
      "Dnestr",
      "Vistula",
      "Oder",
      "Elbe",
      "Danube",
      "Ural",
      "Ob",
      "Yenisey",
      "Lena",
      "Amur",
      "Baikal",
      "Ladoga",
      "Onega",
      "Ilmen",
      "Peipus",
      "Carpathian",
      "Balkan",
      "Tatra",
      "Sudeten",
      "Caucasus",
    ],
    person: [
      "Vladimir",
      "Yaroslav",
      "Svyatoslav",
      "Mstislav",
      "Vsevolod",
      "Rostislav",
      "Vyacheslav",
      "Boleslav",
      "Vladislav",
      "Stanislav",
      "Bronislav",
      "Miroslav",
      "Dobromir",
      "Radomir",
      "Casimir",
      "Rurik",
      "Oleg",
      "Igor",
      "Gleb",
      "Boris",
      "Dmitry",
      "Ivan",
      "Peter",
      "Alexei",
      "Mikhail",
      "Nikolai",
      "Alexander",
      "Sergei",
      "Yuri",
      "Andrey",
      "Olga",
      "Ludmila",
    ],
    dynasty: [
      "Rurikid",
      "Romanov",
      "Piast",
      "Jagiellonian",
      "Premyslid",
      "Arpad",
      "Nemanjić",
      "Obrenović",
      "Karadjordjević",
      "Kotromanić",
      "Trpimirović",
    ],
    military: [
      "Druzhina",
      "Streltsy",
      "Cossacks",
      "Hussars",
      "Bogatyrs",
      "Voivode",
      "Opolcheniye",
      "Pulk",
      "Sotnia",
      "Zaporozhians",
      "Heyduks",
    ],
    organization: [
      "Veche",
      "Boyar Duma",
      "Sabor",
      "Sejm",
      "Rada",
      "Zemstvo",
      "Mir",
      "Obschina",
      "Sobor",
      "Chetniks",
      "Partizani",
    ],
    culture: [
      "Russian",
      "Ukrainian",
      "Belarusian",
      "Pole",
      "Czech",
      "Slovak",
      "Slovene",
      "Croat",
      "Serb",
      "Bosniak",
      "Bulgarian",
      "Macedonian",
      "Moravian",
      "Sorbs",
    ],
    ship: [
      "Ladya",
      "Chaika",
      "Koch",
      "Struga",
      "Aurora",
      "Potemkin",
      "Varyag",
      "Novgorod",
      "Rurik",
      "Svyatoslav",
      "Vladimir",
      "Alexander",
    ],
  },
  arabic: {
    country: [
      "Misr",
      "Iraq",
      "Suriyah",
      "Lubnan",
      "Filastin",
      "Urdun",
      "Hijaz",
      "Nejd",
      "Yaman",
      "Oman",
      "Imarat",
      "Qatar",
      "Bahrain",
      "Kuwait",
      "Sudan",
      "Libya",
      "Tunis",
      "Jazair",
      "Maghrib",
      "Mauritanya",
      "Somalia",
      "Djibouti",
    ],
    city: [
      "Baghdad",
      "Dimashq",
      "Halab",
      "Beirut",
      "Quds",
      "Amman",
      "Makkah",
      "Madinah",
      "Riyadh",
      "Jeddah",
      "Sanaa",
      "Aden",
      "Muscat",
      "Abu Dhabi",
      "Dubai",
      "Doha",
      "Manama",
      "Kuwait City",
      "Khartum",
      "Tripoli",
      "Tunis",
      "Algiers",
      "Rabat",
      "Casablanca",
      "Marrakech",
      "Fez",
      "Cairo",
      "Alexandria",
      "Giza",
      "Port Said",
    ],
    province: [
      "Hijaz",
      "Nejd",
      "Hadramaut",
      "Asir",
      "Al-Ahsa",
      "Barqa",
      "Tripolitania",
      "Fezzan",
      "Rif",
      "Souss",
      "Tafilalet",
      "Sinai",
      "Gaza",
      "West Bank",
      "Galilee",
      "Golans",
      "Khuzestan",
      "Dhofar",
    ],
    geography: [
      "Nile",
      "Euphrates",
      "Tigris",
      "Jordan",
      "Orontes",
      "Litani",
      "Yarmouk",
      "Red Sea",
      "Persian Gulf",
      "Gulf of Aden",
      "Sinai",
      "Atlas Mountains",
      "Hijaz Mountains",
      "Hadramaut",
      "Rub' al Khali",
      "Sahara",
      "Nefud",
      "Qattara",
      "Dead Sea",
      "Lake Nasser",
    ],
    person: [
      "Muhammad",
      "Ahmed",
      "Mahmoud",
      "Mustafa",
      "Ali",
      "Hassan",
      "Hussein",
      "Ibrahim",
      "Ismail",
      "Yusuf",
      "Musa",
      "Isa",
      "Suleiman",
      "Dawud",
      "Harun",
      "Yahya",
      "Zakariya",
      "Ayyub",
      "Yunus",
      "Idris",
      "Nuh",
      "Hud",
      "Salih",
      "Shuaib",
      "Luqman",
      "Al-Amin",
      "Al-Mansur",
      "Harun al-Rashid",
      "Saladin",
      "Baibars",
      "Fatima",
      "Aisha",
      "Khadija",
    ],
    dynasty: [
      "Umayyad",
      "Abbasid",
      "Fatimid",
      "Ayyubid",
      "Mamluk",
      "Ottoman",
      "Almoravid",
      "Almohad",
      "Saadi",
      "Alaouite",
      "Hashemite",
      "Saud",
      "Al-Sabah",
      "Al-Nahyan",
      "Al-Thani",
      "Idrisid",
      "Tulunid",
      "Ikhshidid",
    ],
    military: [
      "Jund",
      "Mamluks",
      "Janissaries",
      "Sipahi",
      "Mujahideen",
      "Fedayeen",
      "Ansar",
      "Ghazis",
      "Askars",
    ],
    organization: [
      "Caliphate",
      "Sultanate",
      "Emirate",
      "Divan",
      "Shura",
      "Waqf",
      "Madrasa",
      "Caravanserai",
      "Harem",
      "Bazaar",
      "Souk",
    ],
    culture: [
      "Arab",
      "Bedouin",
      "Egyptian",
      "Syrian",
      "Iraqi",
      "Yemeni",
      "Moor",
      "Berber",
      "Tuareg",
      "Nubian",
      "Levantine",
      "Maghrebi",
    ],
    ship: [
      "Dhow",
      "Sambuq",
      "Baghla",
      "Ghanjah",
      "Jalibut",
      "Bum",
      "Shu'ai",
      "Zarook",
      "Fattah",
      "Salamat",
      "Mansur",
      "Mubarak",
    ],
  },
  "east-asian": {
    country: [
      "Zhongguo",
      "Riben",
      "Chaoxian",
      "Hanguo",
      "Menggu",
      "Yuenan",
      "Taiwan",
      "Ryukyu",
      "Tibet",
      "Manchuria",
      "Sinkiang",
    ],
    city: [
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Shenzhen",
      "Tianjin",
      "Wuhan",
      "Chengdu",
      "Chongqing",
      "Xian",
      "Nanjing",
      "Tokyo",
      "Osaka",
      "Kyoto",
      "Nagoya",
      "Yokohama",
      "Kobe",
      "Fukuoka",
      "Sapporo",
      "Seoul",
      "Busan",
      "Incheon",
      "Daegu",
      "Daejeon",
      "Gwangju",
      "Ulsan",
      "Pyongyang",
      "Nampo",
      "Kaesong",
      "Hanoi",
      "Saigon",
      "Da Nang",
      "Hue",
      "Haiphong",
      "Ulaanbaatar",
    ],
    province: [
      "Guangdong",
      "Sichuan",
      "Shandong",
      "Jiangsu",
      "Henan",
      "Hebei",
      "Zhejiang",
      "Hunan",
      "Hubei",
      "Fujian",
      "Kanto",
      "Kansai",
      "Chubu",
      "Tohoku",
      "Chugoku",
      "Kyushu",
      "Shikoku",
      "Hokkaido",
      "Gyeonggi",
      "Gangwon",
      "Chungcheong",
      "Jeolla",
      "Gyeongsang",
      "Jeju",
    ],
    geography: [
      "Yangtze",
      "Yellow River",
      "Pearl River",
      "Amur",
      "Mekong",
      "Red River",
      "Mount Fuji",
      "Mount Tai",
      "Mount Huang",
      "Mount Hua",
      "Mount Song",
      "Mount Heng",
      "Lake Biwa",
      "Lake Poyang",
      "Lake Dongting",
      "Lake Tai",
      "Lake Khanka",
      "Sea of Japan",
      "East China Sea",
      "South China Sea",
      "Yellow Sea",
    ],
    person: [
      "Kangxi",
      "Qianlong",
      "Yongzheng",
      "Taizong",
      "Xuanzong",
      "Kublai",
      "Genghis",
      "Oda Nobunaga",
      "Toyotomi Hideyoshi",
      "Tokugawa Ieyasu",
      "Minamoto Yoritomo",
      "Taira Kiyomori",
      "Sejong",
      "Taejo",
      "Gwanggaeto",
      "Le Loi",
      "Ly Thai To",
      "Tran Hung Dao",
      "Nguyen Hue",
      "Zhuge Liang",
      "Cao Cao",
      "Liu Bei",
      "Sun Quan",
      "Li Bai",
      "Du Fu",
    ],
    dynasty: [
      "Han",
      "Tang",
      "Song",
      "Yuan",
      "Ming",
      "Qing",
      "Yamato",
      "Kamakura",
      "Muromachi",
      "Edo",
      "Joseon",
      "Goryeo",
      "Silla",
      "Baekje",
      "Goguryeo",
      "Le",
      "Ly",
      "Tran",
      "Nguyen",
    ],
    military: [
      "Samurai",
      "Ashigaru",
      "Ninja",
      "Monks",
      "Sohei",
      "Bannermen",
      "Hwarang",
      "Red Turbans",
      "Yellow Turbans",
      "Taiping",
      "Boxers",
    ],
    organization: [
      "Shogunate",
      "Bakufu",
      "Yamen",
      "Zongli Yamen",
      "Censorate",
      "Tongs",
      "Triads",
      "Zaibatsu",
      "Chaebol",
    ],
    culture: [
      "Han",
      "Manchu",
      "Mongol",
      "Tibetan",
      "Hui",
      "Uighur",
      "Japanese",
      "Korean",
      "Vietnamese",
      "Ryukyuan",
      "Ainu",
      "Zhuang",
    ],
    ship: [
      "Junk",
      "Atakebune",
      "Sengokubune",
      "Kobaya",
      "Turtle Ship",
      "Panokseon",
      "Treasure Ship",
      "Louchuan",
      "Mengchong",
      "Donghai",
      "Nanhai",
    ],
  },
  austronesian: {
    country: [
      "Indonesia",
      "Malaysia",
      "Pilipinas",
      "Brunei",
      "Timor",
      "Madagaskar",
      "Taiwan",
      "Hawaii",
      "Samoa",
      "Tonga",
      "Fiji",
      "Tahiti",
      "Aotearoa",
      "Tuvalu",
      "Kiribati",
      "Nauru",
      "Vanuatu",
      "Solomons",
      "Micronesia",
      "Palau",
      "Guam",
    ],
    city: [
      "Jakarta",
      "Surabaya",
      "Bandung",
      "Medan",
      "Palembang",
      "Makassar",
      "Denpasar",
      "Kuala Lumpur",
      "Penang",
      "Ipoh",
      "Melaka",
      "Kota Kinabalu",
      "Kuching",
      "Manila",
      "Cebu",
      "Davao",
      "Quezon City",
      "Zamboanga",
      "Bandar Seri Begawan",
      "Dili",
      "Antananarivo",
      "Taipei",
      "Honolulu",
      "Hilo",
      "Apia",
      "Nuku'alofa",
      "Suva",
      "Papeete",
      "Wellington",
      "Auckland",
      "Christchurch",
      "Hamilton",
    ],
    province: [
      "Jawa",
      "Sumatera",
      "Kalimantan",
      "Sulawesi",
      "Papua",
      "Selangor",
      "Johor",
      "Perak",
      "Kedah",
      "Kelantan",
      "Terengganu",
      "Pahang",
      "Negri Sembilan",
      "Luzon",
      "Visayas",
      "Mindanao",
      "Oahu",
      "Maui",
      "Kauai",
      "Tahiti",
      "Bora Bora",
    ],
    geography: [
      "Toba",
      "Batur",
      "Rinjani",
      "Semeru",
      "Merapi",
      "Bromo",
      "Krakatoa",
      "Tambora",
      "Kinabalu",
      "Apo",
      "Mayon",
      "Taal",
      "Pulag",
      "Mauna Loa",
      "Mauna Kea",
      "Kilauea",
      "Haleakala",
      "Orohena",
      "Aoraki",
      "Ruapehu",
      "Tongariro",
      "Tarawera",
    ],
    person: [
      "Gajah Mada",
      "Hayam Wuruk",
      "Raden Wijaya",
      "Parameswara",
      "Hang Tuah",
      "Lapu-Lapu",
      "Jose Rizal",
      "Andres Bonifacio",
      "Emilio Aguinaldo",
      "Kamehameha",
      "Kalakaua",
      "Liliuokalani",
      "Pomare",
      "Tamatoa",
      "Tu'i Tonga",
      "Malietoa",
      "Te Rauparaha",
      "Hone Heke",
      "Potatau",
      "Rata",
      "Kupe",
      "Maui",
      "Lono",
      "Pele",
    ],
    dynasty: [
      "Majapahit",
      "Sriwijaya",
      "Sailendra",
      "Sanjaya",
      "Singhasari",
      "Kediri",
      "Mataram",
      "Melaka",
      "Brunei",
      "Sulu",
      "Kamehameha",
      "Kalakaua",
      "Pomare",
      "Tu'i Tonga",
    ],
    military: [
      "Bolo",
      "Panglima",
      "Kris",
      "Silat",
      "Haka",
      "Toa",
      "Warrior",
      "Navigators",
      "Outriggers",
    ],
    organization: [
      "Adat",
      "Kampung",
      "Barangay",
      "Datu",
      "Raja",
      "Ali'i",
      "Kahuna",
      "Marae",
      "Hula",
      "Kava",
      "Luau",
    ],
    culture: [
      "Malay",
      "Javanese",
      "Sundanese",
      "Balinese",
      "Filipino",
      "Tagalog",
      "Ilocano",
      "Visayan",
      "Moro",
      "Malagasy",
      "Hawaiian",
      "Samoan",
      "Tongan",
      "Fijian",
      "Tahitian",
      "Maori",
    ],
    ship: [
      "Outrigger",
      "Waka",
      "Canoe",
      "Pinisi",
      "Lantaka",
      "Proa",
      "Karakoa",
      "Prahu",
      "Kanoa",
      "Wa'a",
      "Hokule'a",
    ],
  },
  constructed: {
    country: [
      "Gondor",
      "Rohan",
      "Arnor",
      "Lothlorien",
      "Rivendell",
      "Mordor",
      "Isengard",
      "Harad",
      "Umbar",
      "Rhun",
      "Valinor",
      "Numenor",
      "Beleriand",
      "Doriath",
      "Nargothrond",
      "Gondolin",
      "Khazad-dum",
      "Erebor",
      "Angmar",
      "Cardolan",
    ],
    city: [
      "Minas Tirith",
      "Minas Morgul",
      "Osgiliath",
      "Edoras",
      "Helms Deep",
      "Bree",
      "Hobbiton",
      "Rivendell",
      "Caras Galadhon",
      "Barad-dur",
      "Orthanc",
      "Umbar",
      "Esgaroth",
      "Dale",
      "Fornost",
      "Tharbad",
      "Annuminas",
      "Avallone",
      "Tirion",
      "Valmar",
    ],
    province: [
      "Anfalas",
      "Belfalas",
      "Ithilien",
      "Lebennin",
      "Lossarnach",
      "Anorien",
      "Westfold",
      "Eastfold",
      "Folde",
      "Dorwinion",
      "Enedwaith",
      "Minhiriath",
      "Rhudaur",
      "Arthedain",
      "Dor-lomin",
      "Hithlum",
      "Ladros",
    ],
    geography: [
      "Anduin",
      "Brandywine",
      "Bruinen",
      "Sirion",
      "Gelion",
      "Narog",
      "Teiglin",
      "Mindolluin",
      "Caradhras",
      "Celebdil",
      "Fanuidhol",
      "Orodruin",
      "Ephel Duath",
      "Ered Lithui",
      "Ered Luin",
      "Blue Mountains",
      "Misty Mountains",
      "White Mountains",
      "Sea of Nurn",
      "Sea of Helcar",
    ],
    person: [
      "Aragorn",
      "Legolas",
      "Gimli",
      "Gandalf",
      "Frodo",
      "Samwise",
      "Pippin",
      "Merry",
      "Boromir",
      "Faramir",
      "Denethor",
      "Theoden",
      "Eomer",
      "Eowyn",
      "Elrond",
      "Arwen",
      "Galadriel",
      "Celeborn",
      "Thranduil",
      "Sauron",
      "Saruman",
      "Morgoth",
      "Feanor",
      "Fingolfin",
      "Finarfin",
      "Thingol",
      "Luthien",
      "Beren",
      "Turin",
      "Tuor",
    ],
    dynasty: [
      "Elendil",
      "Anarion",
      "Isildur",
      "House of Hurin",
      "House of Hador",
      "House of Haleth",
      "House of Beor",
      "Eorlingas",
      "Durin",
      "Feanorians",
      "Finwe",
    ],
    military: [
      "Rangers",
      "Rohirrim",
      "Guard of the Fountain",
      "Uruk-hai",
      "Nazgul",
      "Olog-hai",
      "Easterlings",
      "Haradrim",
      "Corsairs",
      "Ork-host",
    ],
    organization: [
      "White Council",
      "Istari",
      "Council of Elrond",
      "Mithril-smiths",
      "Dunedain",
      "Fellowship",
      "Beornings",
      "Ents",
    ],
    culture: [
      "Dunadan",
      "Sindar",
      "Noldor",
      "Vanyar",
      "Teleri",
      "Eldar",
      "Silvan",
      "Avari",
      "Khazad",
      "Hobbit",
      "Orc",
      "Troll",
      "Easterling",
      "Haradrim",
    ],
    ship: [
      "Earendil",
      "Vingilot",
      "Alqualonde",
      "Swan-ship",
      "Numenorean",
      "Corsair",
      "Grey Havens",
      "Cirdan",
    ],
  },
  persian: {
    country: [
      "Persia",
      "Parthia",
      "Media",
      "Bactria",
      "Sogdiana",
      "Elam",
      "Khwarezm",
      "Khorasan",
      "Gilan",
      "Mazandaran",
      "Sistan",
      "Hyrcania",
      "Carmania",
      "Aria",
      "Margiana",
      "Luristan",
    ],
    city: [
      "Persepolis",
      "Pasargadae",
      "Ecbatana",
      "Susa",
      "Ctesiphon",
      "Isfahan",
      "Shiraz",
      "Nishapur",
      "Merv",
      "Balkh",
      "Rey",
      "Hamadan",
      "Tabriz",
      "Yazd",
      "Kerman",
      "Gundeshapur",
    ],
    province: [
      "Pars",
      "Khuzestan",
      "Kerman",
      "Khorasan",
      "Gilan",
      "Mazandaran",
      "Sistan",
      "Lorestan",
      "Hamadan",
      "Yazd",
      "Semnan",
      "Fars",
    ],
    geography: [
      "Zagros",
      "Alborz",
      "Damavand",
      "Karun",
      "Zayandeh",
      "Helmand",
      "Urmia",
      "Sefid",
      "Aras",
      "Sabalan",
      "Taftan",
      "Kavir",
    ],
    person: [
      "Cyrus",
      "Darius",
      "Xerxes",
      "Cambyses",
      "Artaxerxes",
      "Shapur",
      "Khosrow",
      "Bahram",
      "Ardashir",
      "Kavadh",
      "Hormizd",
      "Rostam",
      "Sohrab",
      "Esfandiar",
      "Kaveh",
      "Anushiravan",
      "Yazdegerd",
      "Dariush",
      "Kourosh",
      "Roxana",
    ],
    dynasty: [
      "Achaemenid",
      "Sasanian",
      "Parthian",
      "Safavid",
      "Qajar",
      "Buyid",
      "Samanid",
      "Ghaznavid",
      "Seleucid",
      "Arsacid",
      "Zand",
      "Afsharid",
      "Kayanian",
    ],
    military: [
      "Immortals",
      "Sparabara",
      "Pushtigban",
      "Savaran",
      "Asabaran",
      "Daylami",
      "Cataphract",
      "Anusiya",
      "Takhuara",
    ],
    organization: [
      "Magi",
      "Mobads",
      "Divan",
      "Satrapy",
      "Spahbod",
      "Zurkhaneh",
      "Hazarbed",
      "Bazaar",
    ],
    culture: [
      "Persians",
      "Medes",
      "Parthians",
      "Sogdians",
      "Bactrians",
      "Kurds",
      "Tajiks",
      "Baloch",
      "Lurs",
      "Gilaki",
      "Pashtuns",
      "Scythians",
    ],
    ship: ["Anahita", "Mithra", "Ahura", "Simorgh", "Rostam", "Farr", "Zal", "Tahmineh"],
  },
  turkic: {
    country: [
      "Turan",
      "Khazaria",
      "Cumania",
      "Kipchakia",
      "Oghuzia",
      "Sogdia",
      "Khwarezmia",
      "Kashgaria",
      "Dzungaria",
      "Tartary",
      "Turkestan",
      "Anatolia",
      "Karaman",
      "Bulgaria",
    ],
    city: [
      "Samarkand",
      "Bukhara",
      "Tashkent",
      "Khiva",
      "Kashgar",
      "Otrar",
      "Sarai",
      "Bolghar",
      "Konya",
      "Bursa",
      "Edirne",
      "Almaty",
      "Ashgabat",
      "Balasagun",
      "Suyab",
      "Karakorum",
    ],
    province: [
      "Anatolia",
      "Rumelia",
      "Transoxiana",
      "Ferghana",
      "Khorezm",
      "Zhetysu",
      "Mangystau",
      "Karakalpak",
      "Kashgaria",
      "Karaman",
      "Aydin",
      "Mentese",
    ],
    geography: [
      "Tian Shan",
      "Altai",
      "Pamir",
      "Amu Darya",
      "Syr Darya",
      "Issyk Kul",
      "Balkhash",
      "Karakum",
      "Kyzylkum",
      "Talas",
      "Irtysh",
      "Ili",
    ],
    person: [
      "Oghuz",
      "Bumin",
      "Istemi",
      "Tonyukuk",
      "Bilge",
      "Kultegin",
      "Alp Arslan",
      "Tughril",
      "Osman",
      "Orhan",
      "Mehmed",
      "Bayezid",
      "Timur",
      "Babur",
      "Mete",
      "Subutai",
      "Kashgari",
      "Ertugrul",
      "Suleiman",
      "Tomyris",
    ],
    dynasty: [
      "Seljuk",
      "Ottoman",
      "Timurid",
      "Karakhanid",
      "Ghaznavid",
      "Khazar",
      "Gokturk",
      "Uyghur",
      "Karaman",
      "Aq Qoyunlu",
      "Qara Qoyunlu",
      "Shaybanid",
    ],
    military: [
      "Janissary",
      "Sipahi",
      "Akinci",
      "Bashi-bazouk",
      "Kapikulu",
      "Nokod",
      "Tumen",
      "Keshig",
      "Yaya",
      "Azap",
    ],
    organization: ["Divan", "Beylik", "Khaganate", "Horde", "Ordu", "Kurultai", "Waqf", "Ahi"],
    culture: [
      "Turks",
      "Oghuz",
      "Kipchak",
      "Uyghurs",
      "Kazakhs",
      "Uzbeks",
      "Turkmens",
      "Kyrgyz",
      "Tatars",
      "Azeris",
      "Cumans",
      "Pechenegs",
      "Khazars",
      "Yakuts",
    ],
    ship: ["Bumin", "Tengri", "Bozkurt", "Ergenekon", "Asena", "Kursat", "Alp", "Kagan"],
  },
  african: {
    country: [
      "Mali",
      "Songhai",
      "Ghana",
      "Kanem",
      "Bornu",
      "Axum",
      "Kush",
      "Nubia",
      "Zimbabwe",
      "Kongo",
      "Benin",
      "Oyo",
      "Ashanti",
      "Buganda",
      "Lunda",
      "Luba",
      "Wagadu",
      "Dahomey",
    ],
    city: [
      "Timbuktu",
      "Gao",
      "Djenne",
      "Kano",
      "Kumbi Saleh",
      "Mbanza",
      "Meroe",
      "Adulis",
      "Lalibela",
      "Gondar",
      "Kilwa",
      "Mombasa",
      "Zanzibar",
      "Ife",
      "Loango",
      "Kumasi",
    ],
    province: [
      "Sahel",
      "Kordofan",
      "Darfur",
      "Wollega",
      "Shewa",
      "Tigray",
      "Katanga",
      "Kasai",
      "Buganda",
      "Ashanti",
      "Yorubaland",
      "Hausaland",
      "Senegambia",
      "Zululand",
    ],
    geography: [
      "Kilimanjaro",
      "Nyiragongo",
      "Niger",
      "Congo",
      "Zambezi",
      "Limpopo",
      "Volta",
      "Senegal",
      "Tana",
      "Victoria",
      "Tanganyika",
      "Kalahari",
      "Serengeti",
      "Rwenzori",
    ],
    person: [
      "Sundiata",
      "Mansa",
      "Sonni",
      "Askia",
      "Shaka",
      "Cetshwayo",
      "Moshoeshoe",
      "Menelik",
      "Ezana",
      "Nzinga",
      "Samori",
      "Behanzin",
      "Osei",
      "Lobengula",
      "Idris",
      "Kankan",
      "Mutota",
      "Sekou",
      "Kwame",
      "Yaa",
    ],
    dynasty: [
      "Keita",
      "Solomonic",
      "Zagwe",
      "Sefuwa",
      "Rozvi",
      "Aksumite",
      "Sonni",
      "Oyo",
      "Kongo",
      "Lunda",
      "Bito",
      "Hinda",
      "Dahomey",
    ],
    military: [
      "Impi",
      "Ahosi",
      "Sofa",
      "Askari",
      "Ngoni",
      "Tirailleur",
      "Zulu Regiment",
      "Mandinka Horse",
    ],
    organization: ["Griot", "Marabout", "Lukiiko", "Kgotla", "Ekpe", "Poro", "Sande", "Mbari"],
    culture: [
      "Zulu",
      "Yoruba",
      "Igbo",
      "Akan",
      "Hausa",
      "Swahili",
      "Maasai",
      "Amhara",
      "Shona",
      "Mandinka",
      "Wolof",
      "Kongo",
      "Fulani",
      "Xhosa",
      "Oromo",
    ],
    ship: ["Anansi", "Shango", "Oya", "Mami Wata", "Olokun", "Yemoja", "Nyami", "Sundiata"],
  },
  indic: {
    country: [
      "Bharata",
      "Maurya",
      "Gupta",
      "Chola",
      "Pala",
      "Vijayanagara",
      "Magadha",
      "Kalinga",
      "Kosala",
      "Avanti",
      "Gandhara",
      "Sindh",
      "Kamarupa",
      "Pandya",
      "Pallava",
      "Kuru",
    ],
    city: [
      "Pataliputra",
      "Varanasi",
      "Ujjain",
      "Taxila",
      "Hampi",
      "Madurai",
      "Kanchipuram",
      "Thanjavur",
      "Mathura",
      "Dwarka",
      "Nalanda",
      "Amaravati",
      "Srirangam",
      "Indraprastha",
      "Vaishali",
      "Ayodhya",
    ],
    province: [
      "Magadha",
      "Kalinga",
      "Gujarat",
      "Bengal",
      "Punjab",
      "Rajputana",
      "Malwa",
      "Deccan",
      "Vidarbha",
      "Konkan",
      "Marwar",
      "Mewar",
      "Kashmir",
      "Sindh",
    ],
    geography: [
      "Himalaya",
      "Vindhya",
      "Ganga",
      "Yamuna",
      "Indus",
      "Godavari",
      "Krishna",
      "Kaveri",
      "Narmada",
      "Brahmaputra",
      "Sutlej",
      "Aravalli",
      "Nilgiri",
      "Thar",
    ],
    person: [
      "Ashoka",
      "Chandragupta",
      "Harsha",
      "Samudragupta",
      "Rajaraja",
      "Krishnadevaraya",
      "Vikramaditya",
      "Bimbisara",
      "Pushyamitra",
      "Kanishka",
      "Arjuna",
      "Bhima",
      "Rama",
      "Bharata",
      "Lakshmi",
      "Indira",
      "Shivaji",
      "Ravi",
      "Kamala",
      "Sita",
    ],
    dynasty: [
      "Maurya",
      "Gupta",
      "Chola",
      "Pala",
      "Maratha",
      "Pallava",
      "Chalukya",
      "Rashtrakuta",
      "Pandya",
      "Vijayanagara",
      "Tughlaq",
      "Sena",
    ],
    military: ["Rajput", "Mahout", "Sepoy", "Senapati", "Gajasena", "Akshauhini", "Maula", "Chamu"],
    organization: [
      "Sabha",
      "Samiti",
      "Panchayat",
      "Sangha",
      "Mahajanapada",
      "Shreni",
      "Mutt",
      "Ashram",
    ],
    culture: [
      "Tamils",
      "Bengalis",
      "Marathas",
      "Rajputs",
      "Gujaratis",
      "Punjabis",
      "Sinhalese",
      "Telugus",
      "Kannadigas",
      "Gondi",
      "Assamese",
      "Mughals",
    ],
    ship: ["Garuda", "Vishnu", "Lakshmi", "Saraswati", "Indra", "Varuna", "Ganga", "Naga"],
  },
  uralic: {
    country: [
      "Suomi",
      "Karjala",
      "Eesti",
      "Permia",
      "Biarmia",
      "Mordovia",
      "Maria",
      "Komia",
      "Ugria",
      "Savo",
      "Hame",
      "Pohjola",
      "Kainuu",
      "Vepsia",
    ],
    city: [
      "Turku",
      "Tampere",
      "Viipuri",
      "Tallinn",
      "Tartu",
      "Parnu",
      "Buda",
      "Pest",
      "Debrecen",
      "Szeged",
      "Eger",
      "Oulu",
      "Savonlinna",
      "Sortavala",
      "Petroskoi",
    ],
    province: [
      "Savo",
      "Hame",
      "Karjala",
      "Pohjanmaa",
      "Lappi",
      "Uusimaa",
      "Harju",
      "Saare",
      "Voru",
      "Somogy",
      "Zala",
      "Heves",
      "Borsod",
    ],
    geography: [
      "Saimaa",
      "Inari",
      "Paijanne",
      "Vuoksi",
      "Kemijoki",
      "Tornio",
      "Balaton",
      "Tisza",
      "Peipus",
      "Imatra",
      "Halti",
      "Oulujarvi",
    ],
    person: [
      "Vainamoinen",
      "Ilmarinen",
      "Lemminkainen",
      "Kullervo",
      "Aino",
      "Louhi",
      "Arpad",
      "Geza",
      "Istvan",
      "Kaleva",
      "Tapio",
      "Mielikki",
      "Ahti",
      "Ukko",
      "Bela",
      "Lehel",
      "Bulcsu",
      "Tuoni",
      "Untamo",
      "Marjatta",
    ],
    dynasty: ["Arpad", "Kaleva", "Pohjola", "Kalev", "Lembitu", "Suku", "Heimo", "Vaki"],
    military: ["Hakkapeliitta", "Husar", "Sissi", "Jaeger", "Talonpoika", "Karhu", "Susi", "Kotka"],
    organization: ["Karajat", "Maakunta", "Pitaja", "Kyla", "Sampo", "Kalevala", "Tuva", "Heimo"],
    culture: [
      "Finns",
      "Hungarians",
      "Estonians",
      "Sami",
      "Karelians",
      "Mordvins",
      "Mari",
      "Udmurts",
      "Komi",
      "Mansi",
      "Khanty",
      "Nenets",
      "Veps",
      "Ingrians",
    ],
    ship: ["Sampo", "Vainamoinen", "Ilmarinen", "Ahti", "Tapio", "Ukko", "Louhi", "Kaleva"],
  },
};
