import type { RealCountryData, EconomicInputs } from "./economy-types";

// Helper function to create default economic inputs
export function createDefaultEconomicInputs(referenceCountry?: RealCountryData): EconomicInputs {
  const basePopulation = referenceCountry?.population || 10000000;
  const baseGDPPerCapita = referenceCountry?.gdpPerCapita || 25000;
  const baseNominalGDP = basePopulation * baseGDPPerCapita;
  const baseTaxRevenuePercent = referenceCountry?.taxRevenuePercent || 20;
  const baseUnemploymentRate = referenceCountry?.unemploymentRate || 5;

  // Calculate default government spending
  const totalSpending = (baseNominalGDP * Math.min(baseTaxRevenuePercent + 2, 25)) / 100;

  return {
    countryName: referenceCountry ? `New ${referenceCountry.name}` : "New Nation",
    flagUrl: referenceCountry?.flag || referenceCountry?.flagUrl || "",
    coatOfArmsUrl: referenceCountry?.coatOfArms || referenceCountry?.coatOfArmsUrl || "",
    coreIndicators: {
      totalPopulation: basePopulation,
      nominalGDP: baseNominalGDP,
      gdpPerCapita: baseGDPPerCapita,
      realGDPGrowthRate: 3.0,
      inflationRate: 2.0,
      currencyExchangeRate: 1.0,
    },
    laborEmployment: {
      laborForceParticipationRate: 65,
      employmentRate: 100 - baseUnemploymentRate,
      unemploymentRate: baseUnemploymentRate,
      totalWorkforce: Math.round(basePopulation * 0.65),
      averageWorkweekHours: 40,
      minimumWage: Math.round(baseGDPPerCapita * 0.02),
      averageAnnualIncome: Math.round(baseGDPPerCapita * 0.8),
      laborProtections: true,
    },
    fiscalSystem: {
      taxRevenueGDPPercent: baseTaxRevenuePercent,
      governmentRevenueTotal: (baseNominalGDP * baseTaxRevenuePercent) / 100,
      taxRevenuePerCapita: (baseNominalGDP * baseTaxRevenuePercent) / (100 * basePopulation),
      taxRates: {
        personalIncomeTaxRates: [
          { bracket: 0, rate: 0 },
          { bracket: 20000, rate: 10 },
          { bracket: 50000, rate: 22 },
          { bracket: 100000, rate: 32 },
          { bracket: 200000, rate: 37 },
        ],
        corporateTaxRates: [
          { size: "Small (< $1M revenue)", rate: 15 },
          { size: "Medium ($1M - $10M)", rate: 21 },
          { size: "Large (> $10M)", rate: 25 },
        ],
        salesTaxRate: 8.5,
        propertyTaxRate: 1.2,
        payrollTaxRate: 15.3,
        exciseTaxRates: [
          { type: "Fuel", rate: 25 },
          { type: "Alcohol", rate: 35 },
          { type: "Tobacco", rate: 50 },
          { type: "Luxury Goods", rate: 15 },
        ],
        wealthTaxRate: 0.5,
        income: [
          { bracket: 0, rate: 0 },
          { bracket: 20000, rate: 10 },
          { bracket: 50000, rate: 22 },
          { bracket: 100000, rate: 32 },
          { bracket: 200000, rate: 37 },
        ],
        corporate: [
          { size: "Small (< $1M revenue)", rate: 15 },
          { size: "Medium ($1M - $10M)", rate: 21 },
          { size: "Large (> $10M)", rate: 25 },
        ],
        sales: 8.5,
      },
      governmentBudgetGDPPercent: Math.min(baseTaxRevenuePercent + 2, 25),
      budgetDeficitSurplus:
        (baseNominalGDP * baseTaxRevenuePercent) / 100 -
        (baseNominalGDP * Math.min(baseTaxRevenuePercent + 2, 25)) / 100,
      governmentSpendingByCategory: [
        { category: "Defense", amount: 0, percent: 15 },
        { category: "Education", amount: 0, percent: 18 },
        { category: "Healthcare", amount: 0, percent: 22 },
        { category: "Infrastructure", amount: 0, percent: 12 },
        { category: "Social Security", amount: 0, percent: 20 },
        { category: "Other", amount: 0, percent: 13 },
      ],
      internalDebtGDPPercent: 45,
      externalDebtGDPPercent: 25,
      totalDebtGDPRatio: 70,
      debtPerCapita: (baseNominalGDP * 0.7) / basePopulation,
      interestRates: 3.5,
      debtServiceCosts: baseNominalGDP * 0.7 * 0.035,
      incomeTaxRate: 22,
      corporateTaxRate: 25,
      salesTaxRate: 10,
      progressiveTaxation: true,
      balancedBudgetRule: false,
      debtCeiling: 80,
      antiAvoidance: true,
    },
    incomeWealth: {
      economicClasses: [
        {
          name: "Upper Class",
          populationPercent: 5,
          wealthPercent: 40,
          averageIncome: baseGDPPerCapita * 5,
          color: "var(--color-chart-1)",
        },
        {
          name: "Upper Middle Class",
          populationPercent: 15,
          wealthPercent: 30,
          averageIncome: baseGDPPerCapita * 2,
          color: "var(--color-chart-2)",
        },
        {
          name: "Middle Class",
          populationPercent: 30,
          wealthPercent: 20,
          averageIncome: baseGDPPerCapita,
          color: "var(--color-chart-3)",
        },
        {
          name: "Lower Middle Class",
          populationPercent: 30,
          wealthPercent: 8,
          averageIncome: baseGDPPerCapita * 0.5,
          color: "var(--color-chart-4)",
        },
        {
          name: "Lower Class",
          populationPercent: 20,
          wealthPercent: 2,
          averageIncome: baseGDPPerCapita * 0.2,
          color: "var(--color-chart-5)",
        },
      ],
      povertyRate: 15,
      incomeInequalityGini: 0.38,
      socialMobilityIndex: 60,
    },
    governmentSpending: {
      totalSpending,
      spendingGDPPercent: Math.min(baseTaxRevenuePercent + 2, 25),
      spendingPerCapita: totalSpending / basePopulation,
      spendingCategories: [
        {
          category: "Defense",
          amount: totalSpending * 0.15,
          percent: 15,
          icon: "Shield",
          color: "var(--color-chart-1)",
          description: "Military, security, and defense infrastructure",
        },
        {
          category: "Education",
          amount: totalSpending * 0.18,
          percent: 18,
          icon: "GraduationCap",
          color: "var(--color-chart-2)",
          description: "Schools, universities, and education programs",
        },
        {
          category: "Healthcare",
          amount: totalSpending * 0.22,
          percent: 22,
          icon: "Heart",
          color: "var(--color-chart-5)",
          description: "Public health services and medical care",
        },
        {
          category: "Infrastructure",
          amount: totalSpending * 0.12,
          percent: 12,
          icon: "Truck",
          color: "var(--color-chart-3)",
          description: "Roads, utilities, and public works",
        },
        {
          category: "Social Security",
          amount: totalSpending * 0.2,
          percent: 20,
          icon: "Users2",
          color: "var(--color-chart-4)",
          description: "Welfare, pensions, and social benefits",
        },
        {
          category: "Other",
          amount: totalSpending * 0.13,
          percent: 13,
          icon: "MoreHorizontal",
          color: "var(--color-chart-6)",
          description: "Administration, debt service, and miscellaneous",
        },
      ],
      deficitSurplus: (baseNominalGDP * baseTaxRevenuePercent) / 100 - totalSpending,
      education: totalSpending * 0.18,
      healthcare: totalSpending * 0.22,
      socialSafety: totalSpending * 0.2,
      performanceBasedBudgeting: true,
      universalBasicServices: false,
      greenInvestmentPriority: true,
      digitalGovernmentInitiative: true,
      zeroBasedBudgeting: false,
      publicPrivatePartnerships: false,
      participatoryBudgeting: false,
      emergencyReserveFund: false,
      socialImpactBonds: false,
      childWelfareFirstPolicy: false,
      preventiveCareEmphasis: false,
      infrastructureBankFund: false,
      universalBasicIncome: false,
      progressiveTaxation: false,
      carbonTax: false,
      wealthTax: false,
      financialTransactionTax: false,
      universalHealthcare: false,
      freeEducation: false,
      affordableHousing: false,
      elderlyCare: false,
      disabilitySupport: false,
      mentalHealthServices: false,
      stemEducationFocus: false,
      vocationalTraining: false,
      adultEducation: false,
      earlyChildhoodEducation: false,
      smartCityInitiative: false,
      publicTransportExpansion: false,
      renewableEnergyTransition: false,
      highSpeedInternet: false,
      waterInfrastructure: false,
      researchDevelopmentFund: false,
      startupIncubators: false,
      patentReform: false,
      openDataInitiative: false,
      cybersecurityInitiative: false,
      borderSecurity: false,
      disasterPreparedness: false,
      crimePrevention: false,
      carbonNeutrality: false,
      biodiversityProtection: false,
      wasteReduction: false,
      greenBuildingStandards: false,
      sustainableAgriculture: false,
      criminalJusticeReform: false,
      legalAidExpansion: false,
      restorativeJustice: false,
      courtSystemModernization: false,
      artsCultureFunding: false,
      heritagePreservation: false,
      multiculturalPrograms: false,
      languagePreservation: false,
      ruralDevelopment: false,
      ruralHealthcare: false,
      ruralBroadband: false,
      agriculturalSupport: false,
      foreignAidProgram: false,
      refugeeSupport: false,
      diplomaticEngagement: false,
      tradePromotion: false,
      transparencyInitiative: false,
      citizenEngagement: false,
      antiCorruption: false,
      publicServiceReform: false,
    },
    demographics: {
      ageDistribution: [
        { group: "0-15", percent: 20, color: "var(--color-chart-2)" },
        { group: "16-64", percent: 65, color: "var(--color-chart-3)" },
        { group: "65+", percent: 15, color: "var(--color-chart-4)" },
      ],
      lifeExpectancy: 78.5,
      urbanRuralSplit: { urban: 65, rural: 35 },
      regions: [
        { name: "North", population: basePopulation * 0.25, urbanPercent: 70, color: "var(--color-chart-1)" },
        { name: "South", population: basePopulation * 0.3, urbanPercent: 60, color: "var(--color-chart-2)" },
        { name: "East", population: basePopulation * 0.2, urbanPercent: 75, color: "var(--color-chart-3)" },
        { name: "West", population: basePopulation * 0.15, urbanPercent: 55, color: "var(--color-chart-4)" },
        { name: "Central", population: basePopulation * 0.1, urbanPercent: 50, color: "var(--color-chart-5)" },
      ],
      educationLevels: [
        { level: "No Formal Education", percent: 5, color: "var(--color-chart-5)" },
        { level: "Primary Education", percent: 15, color: "var(--color-chart-4)" },
        { level: "Secondary Education", percent: 55, color: "var(--color-chart-3)" },
        { level: "Higher Education", percent: 25, color: "var(--color-chart-2)" },
        { level: "Postgraduate Education", percent: 5, color: "var(--color-chart-1)" },
      ],
      literacyRate: 95,
      citizenshipStatuses: [
        { status: "Citizens", percent: 92, color: "var(--color-chart-1)" },
        { status: "Permanent Residents", percent: 5, color: "var(--color-chart-3)" },
        { status: "Temporary Residents", percent: 2, color: "var(--color-chart-4)" },
        { status: "Other", percent: 1, color: "var(--color-chart-5)" },
      ],
      education: 85,
      populationGrowthRate: 0.5,
    },
  };
}
