// Article slugs that are really WikiOS tool routes; the reader redirects them to the tool.
export const RESERVED_TOOL_PAGES: Record<string, string> = {
  categories: "/util/categories",
  "category-index": "/util/categories",
  "categories-index": "/util/categories",
  contributions: "/util/contributions",
  utilities: "/util",
  templates: "/util/templates",
  "template-palette": "/util/templates",
  diff: "/util/diff",
  "diff-viewer": "/util/diff",
  watchlist: "/util/watchlist",
  random: "/util/random",
  randompage: "/util/random",
  search: "/util/search",
  "recent-changes": "/util/recent-changes",
  recentchanges: "/util/recent-changes",
  repository: "/util/repository",
  whatlinkshere: "/util/whatlinkshere",
  "what-links-here": "/util/whatlinkshere",
  lorewards: "/util/lorewards",
  specialpages: "/util",
  "special-pages": "/util",
};
