/**
 * Comprehensive World Fiat, CCY Cryptocurrency, and Sovereign Currency Catalog.
 * Provides 420+ currencies encompassing the entire ISO 4217 world fiat roster,
 * the complete DominicTobias/ccy-icons cryptocurrency collection, top modern digital assets,
 * and sovereign worldbuilding presets.
 */

export interface CurrencyOption {
  code: string;
  name: string;
  symbol: string;
  category?: "fiat" | "crypto" | "sovereign";
}

/**
 * World reserve and national fiat currencies (ISO 4217).
 */
export const ALL_FIAT_CURRENCIES: CurrencyOption[] = [
  // Major Reserve & Global Fiat
  { code: "USD", name: "US Dollar", symbol: "$", category: "fiat" },
  { code: "EUR", name: "Euro", symbol: "€", category: "fiat" },
  { code: "GBP", name: "British Pound", symbol: "£", category: "fiat" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", category: "fiat" },
  { code: "CAD", name: "Canadian Dollar", symbol: "CA$", category: "fiat" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", category: "fiat" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr", category: "fiat" },
  { code: "CNY", name: "Chinese Yuan", symbol: "元", category: "fiat" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", category: "fiat" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", category: "fiat" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", category: "fiat" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", category: "fiat" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", category: "fiat" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", category: "fiat" },
  { code: "MXN", name: "Mexican Peso", symbol: "Mex$", category: "fiat" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", category: "fiat" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", category: "fiat" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", category: "fiat" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", category: "fiat" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", category: "fiat" },
  { code: "ZAR", name: "South African Rand", symbol: "R", category: "fiat" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", category: "fiat" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", category: "fiat" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", category: "fiat" },
  { code: "THB", name: "Thai Baht", symbol: "฿", category: "fiat" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", category: "fiat" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", category: "fiat" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", category: "fiat" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", category: "fiat" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", category: "fiat" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", category: "fiat" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", category: "fiat" },
  { code: "COP", name: "Colombian Peso", symbol: "$", category: "fiat" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", category: "fiat" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", category: "fiat" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD", category: "fiat" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "BD", category: "fiat" },
  { code: "OMR", name: "Omani Rial", symbol: "RO", category: "fiat" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JD", category: "fiat" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", category: "fiat" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", category: "fiat" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", category: "fiat" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", category: "fiat" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", category: "fiat" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr", category: "fiat" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", category: "fiat" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", category: "fiat" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", category: "fiat" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", category: "fiat" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", category: "fiat" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵", category: "fiat" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", category: "fiat" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", category: "fiat" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", category: "fiat" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "DH", category: "fiat" },
  { code: "DZD", name: "Algerian Dinar", symbol: "DA", category: "fiat" },
  { code: "TND", name: "Tunisian Dinar", symbol: "DT", category: "fiat" },
  { code: "LYD", name: "Libyan Dinar", symbol: "LD", category: "fiat" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", category: "fiat" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", category: "fiat" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", category: "fiat" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", category: "fiat" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", category: "fiat" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", category: "fiat" },
  { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲", category: "fiat" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", category: "fiat" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "soʻm", category: "fiat" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", category: "fiat" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", category: "fiat" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", category: "fiat" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", category: "fiat" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", category: "fiat" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", category: "fiat" },
  { code: "XAF", name: "Central African CFA", symbol: "FCFA", category: "fiat" },
  { code: "XOF", name: "West African CFA", symbol: "CFA", category: "fiat" },
  { code: "XPF", name: "CFP Franc", symbol: "₣", category: "fiat" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "$", category: "fiat" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", category: "fiat" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин.", category: "fiat" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", category: "fiat" },
  { code: "BAM", name: "Bosnia Mark", symbol: "KM", category: "fiat" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", category: "fiat" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", category: "fiat" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", category: "fiat" },
  { code: "LAK", name: "Lao Kip", symbol: "₭", category: "fiat" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", category: "fiat" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", category: "fiat" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", category: "fiat" },
  { code: "TTD", name: "Trinidad Dollar", symbol: "TT$", category: "fiat" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", category: "fiat" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", category: "fiat" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", category: "fiat" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", category: "fiat" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", category: "fiat" },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", category: "fiat" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", category: "fiat" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", category: "fiat" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", category: "fiat" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", category: "fiat" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", category: "fiat" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", category: "fiat" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", category: "fiat" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "SR", category: "fiat" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "Rs", category: "fiat" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "E", category: "fiat" },
  { code: "LSL", name: "Lesotho Loti", symbol: "M", category: "fiat" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", category: "fiat" },
  { code: "WST", name: "Samoan Tala", symbol: "WS$", category: "fiat" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", category: "fiat" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", category: "fiat" },
  { code: "SBD", name: "Solomon Dollar", symbol: "SI$", category: "fiat" },
  { code: "PGK", name: "Papua Kina", symbol: "K", category: "fiat" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", category: "fiat" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", category: "fiat" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", category: "fiat" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ID", category: "fiat" },
  { code: "SYP", name: "Syrian Pound", symbol: "LS", category: "fiat" },
  { code: "YER", name: "Yemeni Rial", symbol: "YR", category: "fiat" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", category: "fiat" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", category: "fiat" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T", category: "fiat" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", category: "fiat" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", category: "fiat" },
  { code: "CUC", name: "Cuban Convertible", symbol: "CUC$", category: "fiat" },
  { code: "CUP", name: "Cuban Peso", symbol: "$MN", category: "fiat" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", category: "fiat" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", category: "fiat" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", category: "fiat" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", category: "fiat" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", category: "fiat" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", category: "fiat" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", category: "fiat" },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", category: "fiat" },
  { code: "SOS", name: "Somali Shilling", symbol: "Ssh", category: "fiat" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SS£", category: "fiat" },
  { code: "SDG", name: "Sudanese Pound", symbol: "SD", category: "fiat" },
  { code: "STN", name: "São Tomé Dobra", symbol: "Db", category: "fiat" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc", category: "fiat" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", category: "fiat" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", category: "fiat" },
  { code: "LBP", name: "Lebanese Pound", symbol: "L£", category: "fiat" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", category: "fiat" },
  { code: "KPW", name: "North Korean Won", symbol: "₩", category: "fiat" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", category: "fiat" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", category: "fiat" },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", category: "fiat" },
  { code: "ANG", name: "Antillean Guilder", symbol: "ƒ", category: "fiat" },
  { code: "KYD", name: "Cayman Dollar", symbol: "CI$", category: "fiat" },
  { code: "BMD", name: "Bermudian Dollar", symbol: "BD$", category: "fiat" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", category: "fiat" },
  { code: "FKP", name: "Falkland Pound", symbol: "£", category: "fiat" },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", category: "fiat" },
  { code: "JEP", name: "Jersey Pound", symbol: "£", category: "fiat" },
  { code: "GGP", name: "Guernsey Pound", symbol: "£", category: "fiat" },
  { code: "IMP", name: "Isle of Man Pound", symbol: "£", category: "fiat" },
];

/**
 * Entire ccy-icons cryptocurrency and digital asset collection.
 */
export const ALL_CRYPTO_CURRENCIES: CurrencyOption[] = [
  // Top Market Cap & Primary CCY Glyphs
  { code: "BTC", name: "Bitcoin", symbol: "₿", category: "crypto" },
  { code: "ETH", name: "Ethereum", symbol: "Ξ", category: "crypto" },
  { code: "USDT", name: "Tether USD", symbol: "₮", category: "crypto" },
  { code: "USDC", name: "USD Coin", symbol: "$", category: "crypto" },
  { code: "BNB", name: "BNB / Binance", symbol: "BNB", category: "crypto" },
  { code: "XRP", name: "XRP / Ripple", symbol: "XRP", category: "crypto" },
  { code: "SOL", name: "Solana", symbol: "SOL", category: "crypto" },
  { code: "ADA", name: "Cardano", symbol: "ADA", category: "crypto" },
  { code: "DOGE", name: "Dogecoin", symbol: "Ð", category: "crypto" },
  { code: "TRX", name: "TRON", symbol: "TRX", category: "crypto" },
  { code: "AVAX", name: "Avalanche", symbol: "AVAX", category: "crypto" },
  { code: "LINK", name: "Chainlink", symbol: "LINK", category: "crypto" },
  { code: "DOT", name: "Polkadot", symbol: "DOT", category: "crypto" },
  { code: "MATIC", name: "Polygon", symbol: "MATIC", category: "crypto" },
  { code: "LTC", name: "Litecoin", symbol: "Ł", category: "crypto" },
  { code: "DAI", name: "Dai Stablecoin", symbol: "◈", category: "crypto" },
  { code: "SHIB", name: "Shiba Inu", symbol: "SHIB", category: "crypto" },
  { code: "UNI", name: "Uniswap", symbol: "UNI", category: "crypto" },
  { code: "ATOM", name: "Cosmos", symbol: "ATOM", category: "crypto" },
  { code: "XMR", name: "Monero", symbol: "XMR", category: "crypto" },
  { code: "ETC", name: "Ethereum Classic", symbol: "ETC", category: "crypto" },
  { code: "XLM", name: "Stellar Lumens", symbol: "XLM", category: "crypto" },
  { code: "NEAR", name: "NEAR Protocol", symbol: "NEAR", category: "crypto" },
  { code: "ALGO", name: "Algorand", symbol: "ALGO", category: "crypto" },
  { code: "FIL", name: "Filecoin", symbol: "FIL", category: "crypto" },
  { code: "VET", name: "VeChain", symbol: "VET", category: "crypto" },
  { code: "ICP", name: "Internet Computer", symbol: "ICP", category: "crypto" },
  { code: "APT", name: "Aptos", symbol: "APT", category: "crypto" },
  { code: "HBAR", name: "Hedera", symbol: "HBAR", category: "crypto" },
  { code: "LDO", name: "Lido DAO", symbol: "LDO", category: "crypto" },
  { code: "ARB", name: "Arbitrum", symbol: "ARB", category: "crypto" },
  { code: "OP", name: "Optimism", symbol: "OP", category: "crypto" },
  { code: "SUI", name: "Sui", symbol: "SUI", category: "crypto" },
  { code: "FTM", name: "Fantom", symbol: "FTM", category: "crypto" },
  { code: "PEPE", name: "Pepe", symbol: "PEPE", category: "crypto" },
  { code: "CRO", name: "Cronos", symbol: "CRO", category: "crypto" },
  { code: "AAVE", name: "Aave", symbol: "AAVE", category: "crypto" },
  { code: "MKR", name: "Maker", symbol: "MKR", category: "crypto" },
  { code: "GRT", name: "The Graph", symbol: "GRT", category: "crypto" },
  { code: "EOS", name: "EOS", symbol: "EOS", category: "crypto" },
  { code: "QNT", name: "Quant", symbol: "QNT", category: "crypto" },
  { code: "SAND", name: "The Sandbox", symbol: "SAND", category: "crypto" },
  { code: "MANA", name: "Decentraland", symbol: "MANA", category: "crypto" },
  { code: "THETA", name: "Theta Network", symbol: "THETA", category: "crypto" },
  { code: "AXS", name: "Axie Infinity", symbol: "AXS", category: "crypto" },
  { code: "FLOW", name: "Flow", symbol: "FLOW", category: "crypto" },
  { code: "KCS", name: "KuCoin Token", symbol: "KCS", category: "crypto" },
  { code: "EGLD", name: "MultiversX", symbol: "EGLD", category: "crypto" },
  { code: "CHZ", name: "Chiliz", symbol: "CHZ", category: "crypto" },
  { code: "NEO", name: "NEO", symbol: "NEO", category: "crypto" },
  { code: "BTT", name: "BitTorrent", symbol: "BTT", category: "crypto" },
  { code: "KLAY", name: "Klaytn", symbol: "KLAY", category: "crypto" },
  { code: "ZEC", name: "Zcash", symbol: "ZEC", category: "crypto" },
  { code: "MIOTA", name: "IOTA", symbol: "MIOTA", category: "crypto" },
  { code: "DASH", name: "Dash", symbol: "DASH", category: "crypto" },
  { code: "COMP", name: "Compound", symbol: "COMP", category: "crypto" },
  { code: "BAT", name: "Basic Attention Token", symbol: "BAT", category: "crypto" },
  { code: "ENJ", name: "Enjin Coin", symbol: "ENJ", category: "crypto" },
  { code: "WAVES", name: "Waves", symbol: "WAVES", category: "crypto" },
  { code: "ZIL", name: "Zilliqa", symbol: "ZIL", category: "crypto" },
  { code: "QTUM", name: "Qtum", symbol: "QTUM", category: "crypto" },
  { code: "BTG", name: "Bitcoin Gold", symbol: "BTG", category: "crypto" },
  { code: "DCR", name: "Decred", symbol: "DCR", category: "crypto" },
  { code: "RVN", name: "Ravencoin", symbol: "RVN", category: "crypto" },
  { code: "XTZ", name: "Tezos", symbol: "XTZ", category: "crypto" },
  { code: "KAVA", name: "Kava", symbol: "KAVA", category: "crypto" },
  { code: "1INCH", name: "1inch", symbol: "1INCH", category: "crypto" },
  { code: "RUNE", name: "THORChain", symbol: "RUNE", category: "crypto" },
  { code: "SNX", name: "Synthetix", symbol: "SNX", category: "crypto" },
  { code: "CRV", name: "Curve DAO", symbol: "CRV", category: "crypto" },
  { code: "GNO", name: "Gnosis", symbol: "GNO", category: "crypto" },
  { code: "BNT", name: "Bancor", symbol: "BNT", category: "crypto" },
  { code: "LRC", name: "Loopring", symbol: "LRC", category: "crypto" },
  { code: "KNC", name: "Kyber Network", symbol: "KNC", category: "crypto" },
  { code: "BUSD", name: "Binance USD", symbol: "BUSD", category: "crypto" },
  { code: "TUSD", name: "TrueUSD", symbol: "TUSD", category: "crypto" },
  { code: "USDP", name: "Pax Dollar", symbol: "USDP", category: "crypto" },
  { code: "GUSD", name: "Gemini Dollar", symbol: "GUSD", category: "crypto" },
  { code: "PAXG", name: "PAX Gold", symbol: "PAXG", category: "crypto" },
  { code: "LSK", name: "Lisk", symbol: "LSK", category: "crypto" },
  { code: "NANO", name: "Nano", symbol: "NANO", category: "crypto" },
  { code: "SC", name: "Siacoin", symbol: "SC", category: "crypto" },
  { code: "DGB", name: "DigiByte", symbol: "DGB", category: "crypto" },
  { code: "BCN", name: "Bytecoin", symbol: "BCN", category: "crypto" },
  { code: "XVG", name: "Verge", symbol: "XVG", category: "crypto" },
  { code: "SYS", name: "Syscoin", symbol: "SYS", category: "crypto" },
  { code: "ARDR", name: "Ardor", symbol: "ARDR", category: "crypto" },
  { code: "STEEM", name: "Steem", symbol: "STEEM", category: "crypto" },
  { code: "ARK", name: "Ark", symbol: "ARK", category: "crypto" },
  // CCY-Icons Comprehensive Asset Roster
  { code: "1ST", name: "FirstBlood", symbol: "1ST", category: "crypto" },
  { code: "300", name: "300 Token", symbol: "300", category: "crypto" },
  { code: "ADC", name: "AudioCoin", symbol: "ADC", category: "crypto" },
  { code: "ADST", name: "AdShares", symbol: "ADST", category: "crypto" },
  { code: "ADT", name: "adToken", symbol: "ADT", category: "crypto" },
  { code: "ADX", name: "AdEx", symbol: "ADX", category: "crypto" },
  { code: "AE", name: "Aeternity", symbol: "AE", category: "crypto" },
  { code: "AEON", name: "Aeon", symbol: "AEON", category: "crypto" },
  { code: "AIDOC", name: "AI Doctor", symbol: "AIDOC", category: "crypto" },
  { code: "AION", name: "Aion", symbol: "AION", category: "crypto" },
  { code: "AMIS", name: "AMIS", symbol: "AMIS", category: "crypto" },
  { code: "AMP", name: "Amp Token", symbol: "AMP", category: "crypto" },
  { code: "ANC", name: "Anoncoin", symbol: "ANC", category: "crypto" },
  { code: "ANKR", name: "Ankr", symbol: "ANKR", category: "crypto" },
  { code: "ANT", name: "Aragon", symbol: "ANT", category: "crypto" },
  { code: "APIS", name: "APIS", symbol: "APIS", category: "crypto" },
  { code: "ARC", name: "Arcade City", symbol: "ARC", category: "crypto" },
  { code: "ARCH", name: "Arch", symbol: "ARCH", category: "crypto" },
  { code: "ARN", name: "Aeron", symbol: "ARN", category: "crypto" },
  { code: "ATH", name: "Atheios", symbol: "ATH", category: "crypto" },
  { code: "ATL", name: "Atlant", symbol: "ATL", category: "crypto" },
  { code: "AUR", name: "Auroracoin", symbol: "AUR", category: "crypto" },
  { code: "AWC", name: "Atomic Wallet Coin", symbol: "AWC", category: "crypto" },
  { code: "AYA", name: "Aryacoin", symbol: "AYA", category: "crypto" },
  { code: "BAL", name: "Balancer", symbol: "BAL", category: "crypto" },
  { code: "BAND", name: "Band Protocol", symbol: "BAND", category: "crypto" },
  { code: "BANX", name: "Banx", symbol: "BANX", category: "crypto" },
  { code: "BAY", name: "BitBay", symbol: "BAY", category: "crypto" },
  { code: "BC", name: "Bitcoin Confidential", symbol: "BC", category: "crypto" },
  { code: "BCH", name: "Bitcoin Cash", symbol: "BCH", category: "crypto" },
  { code: "BFT", name: "BnkToTheFuture", symbol: "BFT", category: "crypto" },
  { code: "BRD", name: "Bread", symbol: "BRD", category: "crypto" },
  { code: "BRK", name: "Breakout", symbol: "BRK", category: "crypto" },
  { code: "BRX", name: "Breakout Stake", symbol: "BRX", category: "crypto" },
  { code: "BSV", name: "Bitcoin SV", symbol: "BSV", category: "crypto" },
  { code: "BTA", name: "Bata", symbol: "BTA", category: "crypto" },
  { code: "BTCD", name: "BitcoinDark", symbol: "BTCD", category: "crypto" },
  { code: "BTCP", name: "Bitcoin Private", symbol: "BTCP", category: "crypto" },
  { code: "BTH", name: "Bithereum", symbol: "BTH", category: "crypto" },
  { code: "BTM", name: "Bytom", symbol: "BTM", category: "crypto" },
  { code: "BTS", name: "BitShares", symbol: "BTS", category: "crypto" },
  { code: "BTU", name: "BTU Protocol", symbol: "BTU", category: "crypto" },
  { code: "BYTS", name: "Bytecent", symbol: "BYTS", category: "crypto" },
  { code: "CFI", name: "Cofound.it", symbol: "CFI", category: "crypto" },
  { code: "CGLD", name: "Celo Gold", symbol: "CGLD", category: "crypto" },
  { code: "CLAM", name: "Clams", symbol: "CLAM", category: "crypto" },
  { code: "CLO", name: "Callisto Network", symbol: "CLO", category: "crypto" },
  { code: "CLOAK", name: "CloakCoin", symbol: "CLOAK", category: "crypto" },
  { code: "CND", name: "Cindicator", symbol: "CND", category: "crypto" },
  { code: "CRM", name: "Cream", symbol: "CRM", category: "crypto" },
  { code: "CRPT", name: "Crypterium", symbol: "CRPT", category: "crypto" },
  { code: "CVC", name: "Civic", symbol: "CVC", category: "crypto" },
  { code: "DAO", name: "DAO", symbol: "DAO", category: "crypto" },
  { code: "DCN", name: "Dentacoin", symbol: "DCN", category: "crypto" },
  { code: "DCT", name: "DECENT", symbol: "DCT", category: "crypto" },
  { code: "DENT", name: "Dent", symbol: "DENT", category: "crypto" },
  { code: "DGD", name: "DigixDAO", symbol: "DGD", category: "crypto" },
  { code: "DGX", name: "Digix Gold", symbol: "DGX", category: "crypto" },
  { code: "DMD", name: "Diamond", symbol: "DMD", category: "crypto" },
  { code: "DNT", name: "district0x", symbol: "DNT", category: "crypto" },
  { code: "EBST", name: "eBoost", symbol: "EBST", category: "crypto" },
  { code: "EDG", name: "Edgeless", symbol: "EDG", category: "crypto" },
  { code: "ELA", name: "Elastos", symbol: "ELA", category: "crypto" },
  { code: "ELF", name: "aelf", symbol: "ELF", category: "crypto" },
  { code: "ELY", name: "Elysn", symbol: "ELY", category: "crypto" },
  { code: "EMC", name: "Emercoin", symbol: "EMC", category: "crypto" },
  { code: "ENG", name: "Enigma", symbol: "ENG", category: "crypto" },
  { code: "EOSDT", name: "Equilibrium EOSDT", symbol: "EOSDT", category: "crypto" },
  { code: "ERC", name: "EuropeCoin", symbol: "ERC", category: "crypto" },
  { code: "ERD", name: "Elrond", symbol: "ERD", category: "crypto" },
  { code: "EURS", name: "STASIS EURO", symbol: "EURS", category: "crypto" },
  { code: "EXP", name: "Expanse", symbol: "EXP", category: "crypto" },
  { code: "FC2", name: "FuelCoin", symbol: "FC2", category: "crypto" },
  { code: "FCN", name: "F円 Token", symbol: "FCN", category: "crypto" },
  { code: "FCT", name: "Factom", symbol: "FCT", category: "crypto" },
  { code: "FIO", name: "FIO Protocol", symbol: "FIO", category: "crypto" },
  { code: "FLO", name: "FlorinCoin", symbol: "FLO", category: "crypto" },
  { code: "FRK", name: "Franko", symbol: "FRK", category: "crypto" },
  { code: "FSBT", name: "Forty Seven Bank", symbol: "FSBT", category: "crypto" },
  { code: "FTC", name: "Feathercoin", symbol: "FTC", category: "crypto" },
  { code: "FUN", name: "FUNToken", symbol: "FUN", category: "crypto" },
  { code: "GAME", name: "GameCredits", symbol: "GAME", category: "crypto" },
  { code: "GBG", name: "Golos Gold", symbol: "GBG", category: "crypto" },
  { code: "GBYTE", name: "Obyte / Gbyte", symbol: "GBYTE", category: "crypto" },
  { code: "GDC", name: "GrandCoin", symbol: "GDC", category: "crypto" },
  { code: "GEMZ", name: "Gemz", symbol: "GEMZ", category: "crypto" },
  { code: "GLD", name: "GoldCoin", symbol: "GLD", category: "crypto" },
  { code: "GNT", name: "Golem", symbol: "GNT", category: "crypto" },
  { code: "GOLOS", name: "Golos", symbol: "GOLOS", category: "crypto" },
  { code: "GRC", name: "Gridcoin", symbol: "GRC", category: "crypto" },
  { code: "GRS", name: "Groestlcoin", symbol: "GRS", category: "crypto" },
  { code: "GUP", name: "Matchpool", symbol: "GUP", category: "crypto" },
  { code: "HEAT", name: "HEAT", symbol: "HEAT", category: "crypto" },
  { code: "HEX", name: "HEX", symbol: "HEX", category: "crypto" },
  { code: "HMQ", name: "Humaniq", symbol: "HMQ", category: "crypto" },
  { code: "HOT", name: "Holo", symbol: "HOT", category: "crypto" },
  { code: "HSR", name: "Hshare", symbol: "HSR", category: "crypto" },
  { code: "ICN", name: "Iconomi", symbol: "ICN", category: "crypto" },
  { code: "ICX", name: "ICON", symbol: "ICX", category: "crypto" },
  { code: "IFC", name: "Infinitecoin", symbol: "IFC", category: "crypto" },
  { code: "INCNT", name: "Incent", symbol: "INCNT", category: "crypto" },
  { code: "IOC", name: "I/O Coin", symbol: "IOC", category: "crypto" },
  { code: "IOST", name: "IOST", symbol: "IOST", category: "crypto" },
  { code: "IOTX", name: "IoTeX", symbol: "IOTX", category: "crypto" },
  { code: "IQ", name: "Everipedia", symbol: "IQ", category: "crypto" },
  { code: "IXT", name: "iXledger", symbol: "IXT", category: "crypto" },
  { code: "JBS", name: "Jumbucks", symbol: "JBS", category: "crypto" },
  { code: "JOB", name: "Jobscoin", symbol: "JOB", category: "crypto" },
  { code: "JOYS", name: "Joys Digital", symbol: "JOYS", category: "crypto" },
  { code: "KIN", name: "Kin", symbol: "KIN", category: "crypto" },
  { code: "KMD", name: "Komodo", symbol: "KMD", category: "crypto" },
  { code: "KORE", name: "Kore", symbol: "KORE", category: "crypto" },
  { code: "LBC", name: "LBRY Credits", symbol: "LBC", category: "crypto" },
  { code: "LDOGE", name: "LiteDoge", symbol: "LDOGE", category: "crypto" },
  { code: "LEDGER", name: "Ledger", symbol: "LEDGER", category: "crypto" },
  { code: "LOKI", name: "Oxen / Loki", symbol: "LOKI", category: "crypto" },
  { code: "LOOM", name: "Loom Network", symbol: "LOOM", category: "crypto" },
  { code: "LST", name: "Lendroid", symbol: "LST", category: "crypto" },
  { code: "LTO", name: "LTO Network", symbol: "LTO", category: "crypto" },
  { code: "LUN", name: "Lunyr", symbol: "LUN", category: "crypto" },
  { code: "MAID", name: "MaidSafeCoin", symbol: "MAID", category: "crypto" },
  { code: "MCO", name: "Crypto.com MCO", symbol: "MCO", category: "crypto" },
  { code: "MER", name: "Mercury", symbol: "MER", category: "crypto" },
  { code: "MINT", name: "Mintcoin", symbol: "MINT", category: "crypto" },
  { code: "MLN", name: "Enzyme / Melon", symbol: "MLN", category: "crypto" },
  { code: "MONA", name: "MonaCoin", symbol: "MONA", category: "crypto" },
  { code: "MRC", name: "microCoin", symbol: "MRC", category: "crypto" },
  { code: "MSC", name: "Omni / MSC", symbol: "MSC", category: "crypto" },
  { code: "MSP", name: "Mothership", symbol: "MSP", category: "crypto" },
  { code: "MTL", name: "Metal", symbol: "MTL", category: "crypto" },
  { code: "MTR", name: "Meter", symbol: "MTR", category: "crypto" },
  { code: "MUE", name: "MonetaryUnit", symbol: "MUE", category: "crypto" },
  { code: "MYST", name: "Mysterium", symbol: "MYST", category: "crypto" },
  { code: "NAS", name: "Nebulas", symbol: "NAS", category: "crypto" },
  { code: "NAV", name: "NAV Coin", symbol: "NAV", category: "crypto" },
  { code: "NBT", name: "NuBits", symbol: "NBT", category: "crypto" },
  { code: "NCASH", name: "Nucleus Vision", symbol: "NCASH", category: "crypto" },
  { code: "NEOS", name: "NeosCoin", symbol: "NEOS", category: "crypto" },
  { code: "NEU", name: "Neumark", symbol: "NEU", category: "crypto" },
  { code: "NGC", name: "NAGA", symbol: "NGC", category: "crypto" },
  { code: "NLG", name: "Gulden", symbol: "NLG", category: "crypto" },
  { code: "NMC", name: "Namecoin", symbol: "NMC", category: "crypto" },
  { code: "NMR", name: "Numeraire", symbol: "NMR", category: "crypto" },
  { code: "NOTE", name: "DNotes", symbol: "NOTE", category: "crypto" },
  { code: "NOW", name: "ChangeNOW", symbol: "NOW", category: "crypto" },
  { code: "NPXS", name: "Pundi X", symbol: "NPXS", category: "crypto" },
  { code: "NU", name: "NuCypher", symbol: "NU", category: "crypto" },
  { code: "NUT", name: "Native Utility Token", symbol: "NUT", category: "crypto" },
  { code: "NVC", name: "Novacoin", symbol: "NVC", category: "crypto" },
  { code: "NXT", name: "Nxt", symbol: "NXT", category: "crypto" },
  { code: "OAX", name: "OAX", symbol: "OAX", category: "crypto" },
  { code: "OK", name: "OKCash", symbol: "OK", category: "crypto" },
  { code: "OMG", name: "OMG Network", symbol: "OMG", category: "crypto" },
  { code: "OMNI", name: "Omni", symbol: "OMNI", category: "crypto" },
  { code: "ONG", name: "Ontology Gas", symbol: "ONG", category: "crypto" },
  { code: "ONT", name: "Ontology", symbol: "ONT", category: "crypto" },
  { code: "OPAL", name: "Opal", symbol: "OPAL", category: "crypto" },
  { code: "OXT", name: "Orchid", symbol: "OXT", category: "crypto" },
  { code: "PART", name: "Particl", symbol: "PART", category: "crypto" },
  { code: "PAX", name: "Paxos Standard", symbol: "PAX", category: "crypto" },
  { code: "PAY", name: "TenX", symbol: "PAY", category: "crypto" },
  { code: "PIGGY", name: "Piggycoin", symbol: "PIGGY", category: "crypto" },
  { code: "PINK", name: "PinkCoin", symbol: "PINK", category: "crypto" },
  { code: "PIVX", name: "PIVX", symbol: "PIVX", category: "crypto" },
  { code: "PLBT", name: "Polybius", symbol: "PLBT", category: "crypto" },
  { code: "PLR", name: "Pillar", symbol: "PLR", category: "crypto" },
  { code: "PLU", name: "Pluton", symbol: "PLU", category: "crypto" },
  { code: "POT", name: "PotCoin", symbol: "POT", category: "crypto" },
  { code: "POWR", name: "Power Ledger", symbol: "POWR", category: "crypto" },
  { code: "PPC", name: "Peercoin", symbol: "PPC", category: "crypto" },
  { code: "PTOY", name: "Patientory", symbol: "PTOY", category: "crypto" },
  { code: "PYN", name: "Paycent", symbol: "PYN", category: "crypto" },
  { code: "QCN", name: "QuazarCoin", symbol: "QCN", category: "crypto" },
  { code: "QRK", name: "Quark", symbol: "QRK", category: "crypto" },
  { code: "RADS", name: "Radium", symbol: "RADS", category: "crypto" },
  { code: "RBIES", name: "Rubies", symbol: "RBIES", category: "crypto" },
  { code: "RBT", name: "Rimbit", symbol: "RBT", category: "crypto" },
  { code: "RBY", name: "Rubycoin", symbol: "RBY", category: "crypto" },
  { code: "RCN", name: "Ripio Credit", symbol: "RCN", category: "crypto" },
  { code: "RDD", name: "ReddCoin", symbol: "RDD", category: "crypto" },
  { code: "REN", name: "Ren", symbol: "REN", category: "crypto" },
  { code: "REP", name: "Augur", symbol: "REP", category: "crypto" },
  { code: "RHOC", name: "RChain", symbol: "RHOC", category: "crypto" },
  { code: "RISE", name: "Rise", symbol: "RISE", category: "crypto" },
  { code: "RLC", name: "iExec RLC", symbol: "RLC", category: "crypto" },
  { code: "ROSE", name: "Oasis Network", symbol: "ROSE", category: "crypto" },
  { code: "SALT", name: "SALT", symbol: "SALT", category: "crypto" },
  { code: "SBTC", name: "Super Bitcoin", symbol: "SBTC", category: "crypto" },
  { code: "SCOT", name: "Scotcoin", symbol: "SCOT", category: "crypto" },
  { code: "SDC", name: "Shadow", symbol: "SDC", category: "crypto" },
  { code: "SIA", name: "Sia", symbol: "SIA", category: "crypto" },
  { code: "SJCX", name: "Storjcoin X", symbol: "SJCX", category: "crypto" },
  { code: "SLG", name: "Sterlingcoin", symbol: "SLG", category: "crypto" },
  { code: "SLS", name: "SaluS", symbol: "SLS", category: "crypto" },
  { code: "SMART", name: "SmartCash", symbol: "SMART", category: "crypto" },
  { code: "SNGLS", name: "SingularDTV", symbol: "SNGLS", category: "crypto" },
  { code: "SNM", name: "SONM", symbol: "SNM", category: "crypto" },
  { code: "SNRG", name: "Synergy", symbol: "SNRG", category: "crypto" },
  { code: "SNT", name: "Status", symbol: "SNT", category: "crypto" },
  { code: "SRN", name: "Sirin Labs", symbol: "SRN", category: "crypto" },
  { code: "START", name: "Startcoin", symbol: "START", category: "crypto" },
  { code: "STASH", name: "Stash", symbol: "STASH", category: "crypto" },
  { code: "STORJ", name: "Storj", symbol: "STORJ", category: "crypto" },
  { code: "STR", name: "StarCredits", symbol: "STR", category: "crypto" },
  { code: "STRAT", name: "Stratis", symbol: "STRAT", category: "crypto" },
  { code: "SWIFT", name: "Bitswift", symbol: "SWIFT", category: "crypto" },
  { code: "SWT", name: "Swarm City", symbol: "SWT", category: "crypto" },
  { code: "SYNC", name: "Sync", symbol: "SYNC", category: "crypto" },
  { code: "SYNX", name: "Syndicate", symbol: "SYNX", category: "crypto" },
  { code: "TIME", name: "Chronobank", symbol: "TIME", category: "crypto" },
  { code: "TIP", name: "Tip", symbol: "TIP", category: "crypto" },
  { code: "TIX", name: "Blocktix", symbol: "TIX", category: "crypto" },
  { code: "TKN", name: "TokenCard", symbol: "TKN", category: "crypto" },
  { code: "TREZOR", name: "Trezor", symbol: "TREZOR", category: "crypto" },
  { code: "TRIG", name: "Triggers", symbol: "TRIG", category: "crypto" },
  { code: "TRST", name: "WeTrust", symbol: "TRST", category: "crypto" },
  { code: "TX", name: "TransferCoin", symbol: "TX", category: "crypto" },
  { code: "UBQ", name: "Ubiq", symbol: "UBQ", category: "crypto" },
  { code: "UKG", name: "Unikoin Gold", symbol: "UKG", category: "crypto" },
  { code: "UMA", name: "UMA", symbol: "UMA", category: "crypto" },
  { code: "UND", name: "Unification", symbol: "UND", category: "crypto" },
  { code: "UNITY", name: "SuperNET Unity", symbol: "UNITY", category: "crypto" },
  { code: "VEN", name: "VeChain", symbol: "VEN", category: "crypto" },
  { code: "VERA", name: "Vera", symbol: "VERA", category: "crypto" },
  { code: "VERI", name: "Veritaseum", symbol: "VERI", category: "crypto" },
  { code: "VIA", name: "Viacoin", symbol: "VIA", category: "crypto" },
  { code: "VIB", name: "Viberate", symbol: "VIB", category: "crypto" },
  { code: "VIOR", name: "Vior", symbol: "VIOR", category: "crypto" },
  { code: "VIU", name: "Viuly", symbol: "VIU", category: "crypto" },
  { code: "VNL", name: "Vanilla", symbol: "VNL", category: "crypto" },
  { code: "VPN", name: "VPNCoin", symbol: "VPN", category: "crypto" },
  { code: "VRC", name: "VeriCoin", symbol: "VRC", category: "crypto" },
  { code: "VTC", name: "Vertcoin", symbol: "VTC", category: "crypto" },
  { code: "VTHO", name: "VeThor", symbol: "VTHO", category: "crypto" },
  { code: "WAN", name: "Wanchain", symbol: "WAN", category: "crypto" },
  { code: "WAX", name: "WAX", symbol: "WAX", category: "crypto" },
  { code: "WBTC", name: "Wrapped Bitcoin", symbol: "WBTC", category: "crypto" },
  { code: "WINGS", name: "Wings", symbol: "WINGS", category: "crypto" },
  { code: "XAI", name: "Sapience / XAI", symbol: "XAI", category: "crypto" },
  { code: "XAUR", name: "Xaurum", symbol: "XAUR", category: "crypto" },
  { code: "XBS", name: "Bitstake", symbol: "XBS", category: "crypto" },
  { code: "XCP", name: "Counterparty", symbol: "XCP", category: "crypto" },
  { code: "XDN", name: "DigitalNote", symbol: "XDN", category: "crypto" },
  { code: "XEL", name: "Elastic", symbol: "XEL", category: "crypto" },
  { code: "XEM", name: "NEM", symbol: "XEM", category: "crypto" },
  { code: "XNN", name: "Xenon", symbol: "XNN", category: "crypto" },
  { code: "XNS", name: "Xeonbit", symbol: "XNS", category: "crypto" },
  { code: "XPM", name: "Primecoin", symbol: "XPM", category: "crypto" },
  { code: "XZC", name: "Firo / Zcoin", symbol: "XZC", category: "crypto" },
  { code: "YBC", name: "YbCoin", symbol: "YBC", category: "crypto" },
  { code: "YEC", name: "Ycash", symbol: "YEC", category: "crypto" },
  { code: "YFI", name: "yearn.finance", symbol: "YFI", category: "crypto" },
  { code: "ZEIT", name: "Zeitcoin", symbol: "ZEIT", category: "crypto" },
  { code: "ZEN", name: "Horizen", symbol: "ZEN", category: "crypto" },
  { code: "ZRX", name: "0x", symbol: "ZRX", category: "crypto" },
];

/**
 * Sovereign, historical, and worldbuilding currency presets.
 */
export const ALL_SOVEREIGN_CURRENCIES: CurrencyOption[] = [
  { code: "Crown", name: "Imperial Crown", symbol: "👑", category: "sovereign" },
  { code: "Taler", name: "Sovereign Taler", symbol: "₮", category: "sovereign" },
  { code: "Mark", name: "Sovereign Mark", symbol: "ℳ", category: "sovereign" },
  { code: "Credit", name: "Galactic Credit", symbol: "₡", category: "sovereign" },
  { code: "Ducat", name: "Royal Ducat", symbol: "₫", category: "sovereign" },
  { code: "Guilder", name: "Imperial Guilder", symbol: "ƒ", category: "sovereign" },
  { code: "Sovereign", name: "Gold Sovereign", symbol: "⩘", category: "sovereign" },
  { code: "Florin", name: "Golden Florin", symbol: "fl", category: "sovereign" },
  { code: "Denar", name: "Sovereign Denar", symbol: "Đ", category: "sovereign" },
  { code: "Aureus", name: "Roman Aureus", symbol: "₷", category: "sovereign" },
  { code: "Doubloon", name: "Spanish Doubloon", symbol: "⚜", category: "sovereign" },
  { code: "Shekel", name: "Sovereign Shekel", symbol: "₪", category: "sovereign" },
  { code: "Drachma", name: "Classical Drachma", symbol: "₯", category: "sovereign" },
  { code: "Sol", name: "Solar Credit", symbol: "☉", category: "sovereign" },
];

/**
 * Complete, unified, unseparated currency list (fiat + ccy crypto + sovereign).
 */
export const UNIFIED_CURRENCIES: CurrencyOption[] = [
  ...ALL_FIAT_CURRENCIES,
  ...ALL_CRYPTO_CURRENCIES,
  ...ALL_SOVEREIGN_CURRENCIES,
];
