#!/usr/bin/env bun
/**
 * Remove [DiscordMsg:ID] prefix from all auto-generated ThinkPages posts
 */

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

try {
  const posts = await db.thinkpagesPost.findMany({
    where: { isAutoGenerated: true, content: { startsWith: "[DiscordMsg:" } },
    select: { id: true, content: true },
  });

  console.log(`Found ${posts.length} posts to clean up...`);

  let updated = 0;
  for (const post of posts) {
    const cleaned = post.content.replace(/\[DiscordMsg:\d+\] /, "");
    if (cleaned !== post.content) {
      await db.thinkpagesPost.update({
        where: { id: post.id },
        data: { content: cleaned },
      });
      updated++;
    }
  }

  console.log(`Updated ${updated} posts`);
} catch (error) {
  console.error("Failed:", error);
} finally {
  await db.$disconnect();
}
