import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

try {
  const posts = await db.thinkpagesPost.findMany({
    where: { isAutoGenerated: true },
    select: { id: true, content: true, account: { select: { username: true } } },
    orderBy: { ixTimeTimestamp: "desc" },
  });

  // Map: @handle → { discordUsers: Map<discordUser, count>, total: number }
  const handleMap = new Map<string, { users: Map<string, number>; total: number }>();

  for (const post of posts) {
    const firstLine = post.content.split("\n")[0] || "";
    // Extract ALL @handles from first line
    const handles = firstLine.match(/@([A-Za-z0-9_]+)/g);
    if (!handles || handles.length === 0) continue;

    // Use the FIRST @handle as the primary account
    const primaryHandle = handles[0]!.slice(1);

    if (!handleMap.has(primaryHandle)) {
      handleMap.set(primaryHandle, { users: new Map(), total: 0 });
    }
    const entry = handleMap.get(primaryHandle)!;
    entry.total++;

    const discordUser = post.account.username;
    entry.users.set(discordUser, (entry.users.get(discordUser) || 0) + 1);
  }

  const sorted = [...handleMap.entries()].sort((a, b) => b[1].total - a[1].total);
  console.log(`Total unique @handles: ${sorted.length}\n`);

  for (const [handle, info] of sorted) {
    const topUser = [...info.users.entries()].sort((a, b) => b[1] - a[1])[0];
    const multiUser = info.users.size > 1 ? ` (${info.users.size} users)` : "";
    console.log(`@${handle.padEnd(35)} ${info.total.toString().padStart(4)} posts${multiUser} → ${topUser![0]}`);
  }
} catch (error: any) {
  console.error("Failed:", error.message);
} finally {
  await db.$disconnect();
}
