/**
 * Resync Discord Images Migration
 *
 * Iterates all MediaAttachment records containing Discord CDN URLs,
 * re-fetches from Discord API to get fresh attachment URLs,
 * downloads images locally, and updates the record.
 *
 * Usage: bun run scripts/resync-discord-images.ts
 */

import { PrismaClient } from "@prisma/client";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import * as path from "path";

const DISCORD_BOT_TOKEN = process.env.DISCORD_BOT_TOKEN;
const DISCORD_API_BASE = "https://discord.com/api/v10";
const BASE_PATH = process.env.BASE_PATH || process.env.NEXT_PUBLIC_BASE_PATH || "";
const IMAGE_DIR = path.join(process.cwd(), "public", "images", "discord");

const db = new PrismaClient();

async function downloadImage(url: string, filepath: string): Promise<boolean> {
  try {
    if (existsSync(filepath)) return true;
    const response = await fetch(url, {
      headers: {
        "User-Agent": "IxStats/1.0 (https://ixwiki.com; contact: admin@ixwiki.com)",
      },
      signal: AbortSignal.timeout(30000),
    });
    if (!response.ok) return false;
    const buffer = Buffer.from(await response.arrayBuffer());
    writeFileSync(filepath, buffer);
    return true;
  } catch {
    return false;
  }
}

function parseDiscordUrl(url: string): { channelId: string; messageId: string; filename: string } | null {
  try {
    const parsed = new URL(url);
    if (!["cdn.discordapp.com", "media.discordapp.net"].includes(parsed.hostname)) return null;
    const parts = parsed.pathname.split("/");
    const idx = parts.indexOf("attachments");
    if (idx === -1 || idx + 3 >= parts.length) return null;
    const rawFilename = parts.slice(idx + 3).join("/");
    const cleanName = rawFilename.split("?")[0]!;
    return {
      channelId: parts[idx + 1]!,
      messageId: parts[idx + 2]!,
      filename: decodeURIComponent(cleanName),
    };
  } catch {
    return null;
  }
}

async function main() {
  if (!DISCORD_BOT_TOKEN) {
    console.error("DISCORD_BOT_TOKEN is not set");
    process.exit(1);
  }

  if (!existsSync(IMAGE_DIR)) {
    mkdirSync(IMAGE_DIR, { recursive: true });
  }

  console.log("Finding Discord CDN media attachments...");

  const allAttachments = await db.mediaAttachment.findMany({
    where: { post: { isAutoGenerated: true } },
    orderBy: { createdAt: "desc" },
  });

  const discordAttachments = allAttachments.filter((a) =>
    a.url.includes("cdn.discordapp.com") || a.url.includes("media.discordapp.net")
  );

  console.log(`Found ${allAttachments.length} total attachments, ${discordAttachments.length} from Discord CDN`);

  let processed = 0;
  let failed = 0;
  let skipped = 0;

  for (let i = 0; i < discordAttachments.length; i++) {
    const att = discordAttachments[i]!;
    const info = parseDiscordUrl(att.url);

    if (!info) {
      skipped++;
      continue;
    }

    try {
      const apiUrl = `${DISCORD_API_BASE}/channels/${info.channelId}/messages/${info.messageId}`;
      const apiResponse = await fetch(apiUrl, {
        headers: {
          Authorization: `Bot ${DISCORD_BOT_TOKEN}`,
          "User-Agent": "IxStats/1.0 (https://ixwiki.com; contact: admin@ixwiki.com)",
        },
        signal: AbortSignal.timeout(10000),
      });

      if (apiResponse.status === 429) {
        const retryAfter = parseInt(apiResponse.headers.get("retry-after") ?? "5", 10);
        console.warn(`[${i + 1}/${discordAttachments.length}] 429 rate limited, waiting ${retryAfter}s...`);
        await new Promise((r) => setTimeout(r, (retryAfter + 1) * 1000));
        i--;
        continue;
      }

      if (!apiResponse.ok) {
        console.warn(`[${i + 1}/${discordAttachments.length}] Skipped ${att.id} (msg ${info.messageId}): API ${apiResponse.status}`);
        failed++;
        continue;
      }

      const message = await apiResponse.json();
      const attachment = message.attachments?.find(
        (a: any) => a.filename === info!.filename
      );

      if (!attachment?.url) {
        console.warn(`[${i + 1}/${discordAttachments.length}] Skipped ${att.id} (msg ${info.messageId}): attachment not in API`);
        failed++;
        continue;
      }

      const extMatch = attachment.url.match(/\.(png|jpg|jpeg|gif|webp)(\?|$)/i);
      const ext = extMatch ? extMatch[1]!.toLowerCase() : "jpg";
      const localFilename = `discord_${info.messageId}_${i}.${ext}`;
      const filepath = path.join(IMAGE_DIR, localFilename);

      const downloaded = await downloadImage(attachment.url, filepath);
      if (downloaded) {
        await db.mediaAttachment.update({
          where: { id: att.id },
          data: { url: `${BASE_PATH}/images/discord/${localFilename}` },
        });
        processed++;
        console.log(`[${i + 1}/${discordAttachments.length}] OK ${att.id} → /images/discord/${localFilename}`);
      } else {
        console.warn(`[${i + 1}/${discordAttachments.length}] Failed ${att.id}: download error`);
        failed++;
      }
    } catch (err) {
      console.warn(`[${i + 1}/${discordAttachments.length}] Error ${att.id}: ${err}`);
      failed++;
    }

    if (i > 0 && i % 3 === 0) {
      await new Promise((r) => setTimeout(r, 1000));
    }
  }

  console.log(`\nDone! ${processed} resynced, ${failed} failed, ${skipped} skipped`);
  await db.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
