"use client";
import React, { useEffect } from "react";
import Link from "next/link";
import { ArrowLeft, Cpu, ChevronRight, Info } from "lucide-react";
export default function ArchitecturePage() {
  useEffect(() => { document.title = "System Architecture - Help Center"; }, []);
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100 dark:from-slate-950 dark:via-blue-950 dark:to-slate-900">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Link href="/help" className="inline-flex items-center gap-2 text-blue-600 dark:text-blue-400 mb-6 transition-colors"><ArrowLeft className="w-4 h-4" />Back to Help Center</Link>
        <div className="mb-8"><div className="flex items-center gap-3 mb-4"><Cpu className="w-8 h-8 text-slate-600 dark:text-slate-400" /><h1 className="text-4xl font-bold text-slate-900 dark:text-white">System Architecture</h1></div><p className="text-xl text-slate-600 dark:text-slate-300">Technical overview of IxStats platform architecture</p></div>
        <div className="prose prose-slate dark:prose-invert prose-blue max-w-none"><div className="bg-white border border-slate-200 dark:bg-white/5 dark:border-white/10 rounded-xl p-8 backdrop-blur-xl space-y-6">
          <section><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Technology Stack</h2><p className="text-slate-700 dark:text-slate-300 leading-relaxed">IxStats is built on a modern, production-ready technology stack designed for performance, scalability, and developer experience.</p></section>
          <div className="bg-blue-50 border border-blue-200 dark:bg-blue-500/10 dark:border-blue-500/30 rounded-lg p-4"><div className="flex gap-3"><Info className="w-5 h-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" /><div><h3 className="text-blue-900 dark:text-blue-300 font-semibold mb-1">Production Status</h3><p className="text-blue-800 dark:text-blue-100/80 text-sm">IxStats v1.0.0 is 100% complete with all critical systems operational and audited.</p></div></div></div>
          <section><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Core Technologies</h2><ul className="space-y-2 text-slate-700 dark:text-slate-300"><li className="flex gap-2"><span className="text-blue-600 dark:text-blue-400">•</span><span><strong className="text-slate-900 dark:text-white">Next.js 15:</strong> React framework with App Router and Turbopack for optimal performance</span></li><li className="flex gap-2"><span className="text-blue-600 dark:text-blue-400">•</span><span><strong className="text-slate-900 dark:text-white">TypeScript:</strong> 100% TypeScript coverage with strict type checking</span></li><li className="flex gap-2"><span className="text-blue-600 dark:text-blue-400">•</span><span><strong className="text-slate-900 dark:text-white">tRPC:</strong> Type-safe API layer with 31 routers (304 endpoints)</span></li><li className="flex gap-2"><span className="text-blue-600 dark:text-blue-400">•</span><span><strong className="text-slate-900 dark:text-white">Prisma ORM:</strong> Database abstraction with 124 models and 8 migrations</span></li><li className="flex gap-2"><span className="text-blue-600 dark:text-blue-400">•</span><span><strong className="text-slate-900 dark:text-white">Clerk:</strong> Authentication and authorization with RBAC</span></li><li className="flex gap-2"><span className="text-blue-600 dark:text-blue-400">•</span><span><strong className="text-slate-900 dark:text-white">Tailwind CSS v4:</strong> Utility-first styling with custom glass physics design system</span></li></ul></section>
          <section><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Architecture Patterns</h2><div className="space-y-3"><div className="p-4 bg-slate-50 border border-slate-200 dark:bg-white/5 dark:border-white/10 rounded-lg"><h3 className="text-slate-900 dark:text-white font-semibold mb-2">Server Components</h3><p className="text-slate-700 dark:text-slate-300 text-sm">Leverages React Server Components for optimal data fetching and rendering performance</p></div><div className="p-4 bg-slate-50 border border-slate-200 dark:bg-white/5 dark:border-white/10 rounded-lg"><h3 className="text-slate-900 dark:text-white font-semibold mb-2">API Layer</h3><p className="text-slate-700 dark:text-slate-300 text-sm">tRPC procedures provide end-to-end type safety from database to UI</p></div><div className="p-4 bg-slate-50 border border-slate-200 dark:bg-white/5 dark:border-white/10 rounded-lg"><h3 className="text-slate-900 dark:text-white font-semibold mb-2">Database Strategy</h3><p className="text-slate-700 dark:text-slate-300 text-sm">SQLite for development, PostgreSQL for production, managed via Prisma migrations</p></div></div></section>
          <section><h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Next Steps</h2><div className="grid gap-3"><Link href="/help/technical/api" className="group flex items-center justify-between p-4 bg-blue-50 border border-blue-200 dark:bg-blue-500/10 dark:border-blue-500/30 rounded-lg hover:bg-blue-100 dark:hover:bg-blue-500/20 transition-all"><span className="text-slate-900 dark:text-white font-medium">tRPC API Documentation</span><ChevronRight className="w-5 h-5 text-blue-600 dark:text-blue-400 group-hover:translate-x-1 transition-transform" /></Link></div></section>
        </div></div>
        <div className="mt-8 flex justify-between items-center"><Link href="/help" className="text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors">← Back to Help Center</Link><Link href="/help/technical/api" className="text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 transition-colors">Next: API Documentation →</Link></div>
      </div>
    </div>
  );
}
