/**
 * src/lib/wiki-os/adapters/ixstates/wiki-mappings.ts
 *
 * Curated Master MediaWiki <-> Nation & Persona Mapping Dictionary
 * Single source of truth for identity reconciliation and admin overview.
 */

export interface MediaWikiAccountMapping {
  primaryCountry: string; // Country name or slug in IxStates DB
  isAltFor?: string; // If this account is an alt of another user / nation
  notes?: string;
}

export const MEDIAWIKI_MAPPING: Record<string, MediaWikiAccountMapping> = {
  // --- Core Power Authors & Alt Mappings ---
  Kir: { primaryCountry: "Kiravia", notes: "Primary Kiravia lorebuilder" },
  Carthinova: { primaryCountry: "Kiravia", isAltFor: "Kir", notes: "Kiravia alt account" },
  "ixnet>Drunk Uncle Kir": { primaryCountry: "Kiravia", isAltFor: "Kir", notes: "Kiravia legacy alt" },

  Urcea: { primaryCountry: "Urcea", notes: "Primary Urcea lorebuilder & admin" },
  Burgundie: { primaryCountry: "Burgundie", notes: "Primary Burgundie lorebuilder & admin" },
  Heku: { primaryCountry: "Caphiria", notes: "Primary Caphiria lorebuilder & founder" },
  Bobbo: { primaryCountry: "Daxia", notes: "Primary Daxia/Corumm lorebuilder & bureaucrat" },
  Rumahoki: { primaryCountry: "Castadilla", notes: "Primary Castadilla lorebuilder" },
  Insui: { primaryCountry: "Cartadania", notes: "Primary Cartadania lorebuilder" },
  Kistan: { primaryCountry: "Faneria", notes: "Primary Faneria/Eileada lorebuilder" },
  Tierrador: { primaryCountry: "Tierrador", notes: "Primary Tierrador lorebuilder" },
  Arco: { primaryCountry: "Arcerion", notes: "Primary Arcerion/Kuronia lorebuilder" },
  Yonderre: { primaryCountry: "Yonderre", notes: "Primary Yonderre lorebuilder" },
  Nasastan: { primaryCountry: "Nasastan", notes: "Primary Nasastan/Lunaria lorebuilder" },
  Pelaxia: { primaryCountry: "Pelaxia", notes: "Primary Pelaxia lorebuilder" },
  Valcenia: { primaryCountry: "Valcenia", notes: "Primary Valcenia/Kujalleq lorebuilder" },
  Galata: { primaryCountry: "Galata", notes: "Primary Galata lorebuilder" },
  Metzetta: { primaryCountry: "Metzetta", notes: "Primary Metzetta lorebuilder" },
  Caldera: { primaryCountry: "Caldera", notes: "Primary Caldera lorebuilder" },
  Alstin: { primaryCountry: "Alstin", notes: "Primary Alstin lorebuilder" },
  Hendalarsk: { primaryCountry: "Hendalarsk", notes: "Primary Hendalarsk lorebuilder" },
  Eldmora: { primaryCountry: "Eldmora", notes: "Primary Eldmora lorebuilder" },
  PotatoLover: { primaryCountry: "Canespa", notes: "Primary Canespa lorebuilder" },
  Puertego: { primaryCountry: "Puertego", notes: "Primary Puertego lorebuilder" },
  Diamavya: { primaryCountry: "Brumalea", notes: "Primary Brumalea/Duōmachāha lorebuilder" },
  Nolis: { primaryCountry: "The Cape", notes: "Primary The Cape lorebuilder" },
  Aciria: { primaryCountry: "Aciria", notes: "Primary Aciria lorebuilder" },
  Ralkern: { primaryCountry: "Vithinja", notes: "Primary Vithinja lorebuilder" },
  Drasenia: { primaryCountry: "Drasenia", notes: "Primary Drasenia lorebuilder" },
  David: { primaryCountry: "Vallejar", notes: "Primary Vallejar lorebuilder" },
  Olmeria: { primaryCountry: "Olmeria", notes: "Primary Olmeria lorebuilder" },
  Fiannria: { primaryCountry: "Fiannria", notes: "Primary Fiannria lorebuilder" },
  Akcelis: { primaryCountry: "Intaria", notes: "Primary Intaria lorebuilder" },
  Mazz38: { primaryCountry: "Calinthia", notes: "Primary Calinthia lorebuilder" },
  Chrobby: { primaryCountry: "Thervala", notes: "Primary Thervala lorebuilder" },
  Argyrea: { primaryCountry: "Argyrea", notes: "Primary Argyrea lorebuilder" },
  "Takatta Loa": { primaryCountry: "Loa", notes: "Primary Loa Empire lorebuilder" },
  Lambchops: { primaryCountry: "Timbia", notes: "Primary Timbia lorebuilder" },
  Farmandie: { primaryCountry: "Farmandie", notes: "Primary Farmandie lorebuilder" },
  Pauldustllah: { primaryCountry: "Paulastra", notes: "Primary Paulastra lorebuilder" },
  Asteria: { primaryCountry: "Asteria", notes: "Primary Asteria lorebuilder" },
  Grajnidar: { primaryCountry: "Grajnidar", notes: "Primary Grajnidar lorebuilder" },
  Helvianir: { primaryCountry: "Maresteyn", notes: "Primary Maresteyn lorebuilder" },
  Syliria: { primaryCountry: "Syliria", notes: "Primary Syliria lorebuilder" },
  Terazta: { primaryCountry: "Terazta", notes: "Primary Terazta lorebuilder" },
  Ogonkai: { primaryCountry: "Ogonkai", notes: "Primary Ogonkai lorebuilder" },
  Asteklion: { primaryCountry: "Asteklion", notes: "Primary Asteklion lorebuilder" },
  Qubuj: { primaryCountry: "Coburia", notes: "Primary Coburia lorebuilder" },
  Patraja: { primaryCountry: "Patraja", notes: "Primary Patraja lorebuilder" },
  Almadaria: { primaryCountry: "Almadaria", notes: "Primary Almadaria lorebuilder" },
  Sakartvelos: { primaryCountry: "Sakartvelos", notes: "Primary Sakartvelos lorebuilder" },
  Sketch: { primaryCountry: "Nunsiak", notes: "Primary Nunsiak lorebuilder" },

  // --- Moderate & Minor Contributors ---
  Enserlano: { primaryCountry: "Enserlano" },
  Yueguo: { primaryCountry: "Yueguo" },
  Kloistan: { primaryCountry: "Kloistan" },
  FrustratedProgressive: { primaryCountry: "Caergwynn" },
  Dectroia: { primaryCountry: "Dectroia" },
  Aleajayib: { primaryCountry: "Aleajayib" },
  Unintra: { primaryCountry: "Unintra" },
  Arthur30: { primaryCountry: "Convale" },
  Azikoria: { primaryCountry: "Azikoria" },
  Ghebeek: { primaryCountry: "Boyamoor" },
  Orecula: { primaryCountry: "Doulan" },
  Tifosi30: { primaryCountry: "Fiorano" },
  Insulam: { primaryCountry: "Udon Khai" },
  Sassain: { primaryCountry: "Sassain" },
  Vesta: { primaryCountry: "Vesta" },
  Arctic: { primaryCountry: "Kōtaiyo" },
  Grussland: { primaryCountry: "Grussland" },
  Dhayavastan: { primaryCountry: "Dhayavastan" },
  Thalaia: { primaryCountry: "Thalaia" },
  "Yytuskia-Helvana": { primaryCountry: "Yytuskia-Helvana" },
  "Music is a Drug": { primaryCountry: "Music is a Drug" },
  Etzil: { primaryCountry: "Etzil" },
  Neutropic: { primaryCountry: "Neutropic" },
  Lmald: { primaryCountry: "Lmald" },
  Solgavden: { primaryCountry: "Solgavden" },
  Tashidaypa: { primaryCountry: "Tashidaypa" },
  Vellara: { primaryCountry: "Vellara" },
  Ekelos: { primaryCountry: "Ekelos" },
  Locrya: { primaryCountry: "Locrya" },
  OceanMan: { primaryCountry: "OceanMan" },
  Cohe: { primaryCountry: "Cohe" },
  Ishonga: { primaryCountry: "Ishonga" },
  Leorez: { primaryCountry: "Leorez" },
  Rylivian: { primaryCountry: "Rylivian" },
  "The Alesian Empire": { primaryCountry: "The Alesian Empire" },
  Daito: { primaryCountry: "Daito" },
  Pukhtunkhwa: { primaryCountry: "Pukhtunkhwa" },
  Qustantistan: { primaryCountry: "Qustantistan" },
  Vallorania: { primaryCountry: "Vallorania" },
};
