/**
 * Lore Category Enums
 *
 * Client-safe runtime constants for the lore-first card system.
 * These will match the Prisma schema enums once the migration lands.
 *
 * IMPORTANT: When the Prisma `LoreCategory` and `ArtworkSource` enums
 * are added, these values MUST match exactly.
 */

/**
 * Lore categories — the 13-value replacement for the legacy 5-value CardType.
 *
 * Organized into visual families:
 *   Heraldic:   MILITARY, GOVERNMENT, NATION
 *   Celestial:  RELIGION, SCIENCE, GEOGRAPHY
 *   Civic:      DIPLOMACY, ECONOMY
 *   Humanistic: PEOPLE, CULTURE, HISTORY
 *   Meta:       SPECIAL, NS_IMPORT
 */
export const LoreCategory = {
  MILITARY: "MILITARY",
  DIPLOMACY: "DIPLOMACY",
  GEOGRAPHY: "GEOGRAPHY",
  RELIGION: "RELIGION",
  CULTURE: "CULTURE",
  GOVERNMENT: "GOVERNMENT",
  PEOPLE: "PEOPLE",
  ECONOMY: "ECONOMY",
  SCIENCE: "SCIENCE",
  HISTORY: "HISTORY",
  NATION: "NATION",
  SPECIAL: "SPECIAL",
  NS_IMPORT: "NS_IMPORT",
} as const;

export type LoreCategory = (typeof LoreCategory)[keyof typeof LoreCategory];

/**
 * How a card's artwork was sourced.
 */
export const ArtworkSource = {
  /** No image — fully procedural rendering (Tier 1) */
  PROCEDURAL: "PROCEDURAL",
  /** Image pulled from wiki article via MediaWiki API (Tier 3) */
  WIKI_FETCHED: "WIKI_FETCHED",
  /** Admin-uploaded custom art (Tier 3) */
  UPLOADED: "UPLOADED",
  /** Country flag, auto-fetched (Tier 3) */
  FLAG: "FLAG",
} as const;

export type ArtworkSource = (typeof ArtworkSource)[keyof typeof ArtworkSource];

/**
 * All lore categories as an ordered array (useful for filters, navigation).
 * Excludes NS_IMPORT — that's a compatibility bucket, not a browsable category.
 */
export const BROWSABLE_CATEGORIES: LoreCategory[] = [
  LoreCategory.MILITARY,
  LoreCategory.DIPLOMACY,
  LoreCategory.GEOGRAPHY,
  LoreCategory.RELIGION,
  LoreCategory.CULTURE,
  LoreCategory.GOVERNMENT,
  LoreCategory.PEOPLE,
  LoreCategory.ECONOMY,
  LoreCategory.SCIENCE,
  LoreCategory.HISTORY,
  LoreCategory.NATION,
  LoreCategory.SPECIAL,
];

export function isValidLoreCategory(value: string): value is LoreCategory {
  return Object.values(LoreCategory).includes(value as LoreCategory);
}

export function isValidArtworkSource(value: string): value is ArtworkSource {
  return Object.values(ArtworkSource).includes(value as ArtworkSource);
}

/**
 * Comprehensive synonym, alias, and keyword mappings for each LoreCategory.
 * Includes alternate terms, plurals, subdivisions, and contextual variants
 * for search querying, crawler indexing, and automated lore classification.
 */
export const CATEGORY_SYNONYMS: Record<LoreCategory, readonly string[]> = {
  NATION: [
    "nation",
    "nations",
    "country",
    "countries",
    "state",
    "states",
    "sovereignty",
    "sovereign state",
    "sovereign states",
    "republic",
    "republics",
    "kingdom",
    "kingdoms",
    "empire",
    "empires",
    "principality",
    "principalities",
    "duchy",
    "duchies",
    "grand duchy",
    "federation",
    "federations",
    "confederacy",
    "confederation",
    "commonwealth",
    "realm",
    "realms",
    "dominion",
    "dominions",
    "homeland",
    "fatherland",
    "motherland",
    "polity",
    "polities",
  ],
  MILITARY: [
    "military",
    "war",
    "wars",
    "warfare",
    "battle",
    "battles",
    "conflict",
    "conflicts",
    "campaign",
    "campaigns",
    "siege",
    "sieges",
    "army",
    "armies",
    "navy",
    "navies",
    "naval",
    "fleet",
    "fleets",
    "air force",
    "air forces",
    "regiment",
    "regiments",
    "brigade",
    "brigades",
    "division",
    "divisions",
    "corps",
    "squadron",
    "squadrons",
    "battalion",
    "battalions",
    "armed forces",
    "defense force",
    "invasion",
    "invasions",
    "operation",
    "operations",
    "skirmish",
    "skirmishes",
    "clash",
    "combat",
    "offensive",
    "insurgency",
    "garrison",
    "fortress",
    "armory",
    "weaponry",
  ],
  GEOGRAPHY: [
    "geography",
    "geographic",
    "geographical",
    "ocean",
    "oceans",
    "sea",
    "seas",
    "mountain",
    "mountains",
    "mountain range",
    "peak",
    "peaks",
    "river",
    "rivers",
    "lake",
    "lakes",
    "gulf",
    "gulfs",
    "bay",
    "bays",
    "strait",
    "straits",
    "channel",
    "channels",
    "island",
    "islands",
    "archipelago",
    "archipelagos",
    "continent",
    "continents",
    "region",
    "regions",
    "province",
    "provinces",
    "valley",
    "valleys",
    "plateau",
    "plateaus",
    "desert",
    "deserts",
    "peninsula",
    "peninsulas",
    "cape",
    "capes",
    "coast",
    "coasts",
    "coastline",
    "territory",
    "territories",
    "forest",
    "forests",
    "jungle",
    "plain",
    "plains",
    "fjord",
    "fjords",
    "tundra",
    "volcano",
    "volcanoes",
    "canyon",
    "canyons",
    "landform",
    "landforms",
  ],
  RELIGION: [
    "religion",
    "religions",
    "religious",
    "faith",
    "faiths",
    "church",
    "churches",
    "cult",
    "cults",
    "creed",
    "creeds",
    "order",
    "orders",
    "sacred order",
    "temple",
    "temples",
    "cathedral",
    "cathedrals",
    "shrine",
    "shrines",
    "deity",
    "deities",
    "god",
    "gods",
    "goddess",
    "goddesses",
    "pantheon",
    "pantheons",
    "theology",
    "theological",
    "monastery",
    "monasteries",
    "monk",
    "monks",
    "priesthood",
    "clergy",
    "bishop",
    "patriarch",
    "pope",
    "pontiff",
    "sacred",
    "holy",
    "doctrine",
    "doctrines",
    "sect",
    "sects",
    "dogma",
    "pilgrimage",
    "ritual",
    "rituals",
    "pantheism",
    "monotheism",
    "polytheism",
  ],
  PEOPLE: [
    "people",
    "person",
    "persons",
    "figure",
    "figures",
    "historical figure",
    "historical figures",
    "biography",
    "biographies",
    "monarch",
    "monarchs",
    "king",
    "kings",
    "queen",
    "queens",
    "emperor",
    "emperors",
    "empress",
    "empresses",
    "ruler",
    "rulers",
    "sovereign",
    "sovereigns",
    "leader",
    "leaders",
    "head of state",
    "heads of state",
    "president",
    "presidents",
    "prime minister",
    "prime ministers",
    "chancellor",
    "chancellors",
    "statesman",
    "statesmen",
    "general",
    "generals",
    "admiral",
    "admirals",
    "hero",
    "heroes",
    "founder",
    "founders",
    "dynasty",
    "dynasties",
    "house",
    "houses",
    "lineage",
    "noble",
    "nobles",
    "nobility",
    "archduke",
    "duke",
    "dukes",
    "prince",
    "princes",
    "princess",
    "princesses",
    "aristocracy",
    "personality",
    "personalities",
  ],
  DIPLOMACY: [
    "diplomacy",
    "diplomatic",
    "treaty",
    "treaties",
    "accord",
    "accords",
    "concordat",
    "concordats",
    "alliance",
    "alliances",
    "pact",
    "pacts",
    "coalition",
    "coalitions",
    "convention",
    "conventions",
    "summit",
    "summits",
    "embassy",
    "embassies",
    "ambassador",
    "ambassadors",
    "protocol",
    "protocols",
    "entente",
    "ententes",
    "league",
    "leagues",
    "bloc",
    "blocs",
    "union",
    "unions",
    "charter",
    "charters",
    "armistice",
    "armistices",
    "truce",
    "truces",
    "negotiation",
    "negotiations",
    "foreign relations",
    "international relations",
    "envoy",
    "envoys",
  ],
  CULTURE: [
    "culture",
    "cultural",
    "monument",
    "monuments",
    "heritage",
    "tradition",
    "traditions",
    "art",
    "arts",
    "artistic",
    "architecture",
    "architectural",
    "palace",
    "palaces",
    "castle",
    "castles",
    "citadel",
    "citadels",
    "museum",
    "museums",
    "folklore",
    "mythology",
    "myths",
    "myth",
    "legend",
    "legends",
    "music",
    "musical",
    "literature",
    "literary",
    "festival",
    "festivals",
    "landmark",
    "landmarks",
    "symbol",
    "symbols",
    "regalia",
    "relic",
    "relics",
    "crown jewels",
    "costume",
    "custom",
    "customs",
    "holiday",
    "holidays",
    "theater",
    "theatre",
    "epic",
    "epics",
    "folktale",
    "folktales",
  ],
  SCIENCE: [
    "science",
    "scientific",
    "technology",
    "technologies",
    "tech",
    "technological",
    "industry",
    "industrial",
    "infrastructure",
    "railway",
    "railroad",
    "railroads",
    "trains",
    "telegraph",
    "aviation",
    "aeronautics",
    "aerospace",
    "space",
    "spaceflight",
    "orbital",
    "satellite",
    "satellites",
    "astronomy",
    "physics",
    "engineering",
    "invention",
    "inventions",
    "inventor",
    "laboratory",
    "laboratories",
    "observatory",
    "observatories",
    "energy",
    "power",
    "power grid",
    "academy",
    "academies",
    "research",
    "institute",
    "institutes",
    "chemistry",
    "biology",
    "medicine",
    "medical",
    "innovation",
    "innovations",
  ],
  GOVERNMENT: [
    "government",
    "governments",
    "governance",
    "parliament",
    "parliaments",
    "parliamentary",
    "congress",
    "congresses",
    "senate",
    "senates",
    "assembly",
    "assemblies",
    "ministry",
    "ministries",
    "cabinet",
    "cabinets",
    "constitution",
    "constitutions",
    "constitutional",
    "law",
    "laws",
    "legal",
    "judiciary",
    "judicial",
    "court",
    "courts",
    "supreme court",
    "legislation",
    "legislative",
    "decree",
    "decrees",
    "regime",
    "regimes",
    "administration",
    "administrations",
    "bureaucracy",
    "bureaucratic",
    "crown council",
    "statute",
    "statutes",
    "council",
    "councils",
    "elections",
    "election",
    "electoral",
    "suffrage",
    "democracy",
    "monarchy",
    "authoritarianism",
    "oligarchy",
  ],
  ECONOMY: [
    "economy",
    "economic",
    "economics",
    "trade",
    "commerce",
    "commercial",
    "finance",
    "financial",
    "bank",
    "banks",
    "banking",
    "central bank",
    "currency",
    "currencies",
    "money",
    "monetary",
    "mint",
    "minting",
    "corporation",
    "corporations",
    "corporate",
    "company",
    "companies",
    "conglomerate",
    "conglomerates",
    "enterprise",
    "enterprises",
    "market",
    "markets",
    "stock exchange",
    "export",
    "exports",
    "import",
    "imports",
    "tariff",
    "tariffs",
    "guild",
    "guilds",
    "treasury",
    "fiscal",
    "taxation",
    "taxes",
    "revenue",
    "commodity",
    "commodities",
    "merchant",
    "merchants",
    "gdp",
  ],
  HISTORY: [
    "history",
    "historical",
    "historic",
    "era",
    "eras",
    "epoch",
    "epochs",
    "age",
    "ages",
    "period",
    "periods",
    "chronicle",
    "chronicles",
    "century",
    "centuries",
    "antiquity",
    "ancient",
    "medieval",
    "middle ages",
    "renaissance",
    "revolution",
    "revolutions",
    "revolutionary",
    "rebellion",
    "rebellions",
    "revolt",
    "revolts",
    "civil war",
    "civil wars",
    "crisis",
    "crises",
    "collapse",
    "fall",
    "rise",
    "golden age",
    "annals",
    "event",
    "events",
    "timeline",
    "timelines",
    "dark ages",
  ],
  SPECIAL: [
    "special",
    "unique",
    "lore",
    "mythic",
    "artifact",
    "artifacts",
    "legendary",
    "wonder",
    "wonders",
    "world wonder",
    "relic",
    "relics",
    "tome",
    "tomes",
    "anomaly",
    "anomalies",
    "secret",
    "secrets",
    "archive",
    "archives",
    "enigma",
    "enigmas",
    "curiosity",
    "oddity",
    "masterpiece",
  ],
  NS_IMPORT: [
    "nationstates",
    "ns",
    "ns card",
    "ns import",
    "external deck",
    "flag import",
    "trading card",
    "nationstates import",
  ],
};

/**
 * Returns all synonyms/aliases for a given category.
 */
export function getCategorySynonyms(category: LoreCategory): readonly string[] {
  return CATEGORY_SYNONYMS[category] || [];
}

/**
 * Find matching LoreCategory for any keyword, synonym, or alias.
 */
export function findMatchingCategory(term: string): LoreCategory | null {
  const normalized = term.trim().toLowerCase();
  for (const [cat, synonyms] of Object.entries(CATEGORY_SYNONYMS)) {
    if (cat.toLowerCase() === normalized || synonyms.includes(normalized)) {
      return cat as LoreCategory;
    }
  }
  return null;
}
