import { IxTime } from "~/lib/ixtime";

export interface SummationDraftResult {
  postId: string;
  accountId: string;
  content: string;
  visibility: string;
  isAutoGenerated: boolean;
}

/**
 * Generates an executive prose summation draft in ThinkPages when an Intent completes.
 * (v2 Design Bible & Migration Plan §1: Auto-summation → ThinkPages draft post)
 */
export async function generateIntentSummationDraft(params: {
  db: any;
  intentId: string;
  countryId: string;
  visibility?: "draft" | "public";
  customContent?: string;
}): Promise<SummationDraftResult | null> {
  const { db, intentId, countryId, visibility = "draft", customContent } = params;

  // 1. Load intent & country data
  const [intent, country] = await Promise.all([
    db.intent.findUnique({ where: { id: intentId } }),
    db.country.findUnique({
      where: { id: countryId },
      select: { id: true, name: true, slug: true, flag: true },
    }),
  ]);

  if (!intent || !country) return null;

  // 2. Parse changes and construct prose narrative
  const countryName = country.name || "The Government";
  let parsedChanges: Array<{ label: string; detail?: string }> = [];
  try {
    if (intent.changesJson) {
      parsedChanges = JSON.parse(intent.changesJson);
    }
  } catch {
    /* fallback to empty */
  }

  const tierTitle = intent.tier ? intent.tier.toUpperCase() : "EXECUTIVE";
  const changesSummary = parsedChanges.length > 0
    ? parsedChanges.map((c) => c.label).join(", ")
    : intent.summary || intent.goal;

  const proseNarrative =
    `🏛️ **EXECUTIVE SUMMATION: ${intent.goal}**\n\n` +
    `Under ${tierTitle} Directive authority, ${countryName} has successfully completed state actions regarding "${intent.goal}".\n\n` +
    `**Key Policy & Budget Measures Implemented:**\n` +
    `• ${changesSummary}\n\n` +
    `#${country.slug || "Statecraft"} #ExecutiveDirective #${intent.category || "policy"}`;

  // 3. Find or ensure official ThinkPages account for this country
  let account = await db.thinkpagesAccount.findFirst({
    where: {
      OR: [
        { handle: `@${country.slug}` },
        { handle: `@gov_${country.slug}` },
        { name: `${countryName} Executive` },
      ],
    },
  });

  if (!account) {
    // Look up any account linked to this country's user/owner
    account = await db.thinkpagesAccount.findFirst({
      where: { verifiedBadge: true },
    }) || await db.thinkpagesAccount.findFirst();
  }

  if (!account) {
    // Create an official account fallback
    account = await db.thinkpagesAccount.create({
      data: {
        name: `${countryName} Executive`,
        handle: `@gov_${country.slug || "official"}`,
        accountType: "GOVERNMENT",
        verifiedBadge: true,
        bio: `Official executive channel for ${countryName}`,
        avatarUrl: country.flag || undefined,
      },
    });
  }

  const finalContent = customContent?.trim() ? customContent.trim() : proseNarrative;

  // 4. Create post in ThinkpagesPost table (draft or public)
  const post = await db.thinkpagesPost.create({
    data: {
      accountId: account.id,
      content: finalContent,
      postType: "original",
      hashtags: `#${country.slug || "Statecraft"} #${intent.category || "policy"}`,
      visibility,
      isAutoGenerated: true,
      ixTimeTimestamp: new Date(),
    },
  });

  return {
    postId: post.id,
    accountId: account.id,
    content: post.content,
    visibility: post.visibility,
    isAutoGenerated: post.isAutoGenerated,
  };
}
