import type { PrismaClient } from "@prisma/client";

export interface SummationDraftResult {
  postId: string;
  accountId: string;
  content: string;
  visibility: string;
  isAutoGenerated: boolean;
}

/**
 * Generates an executive prose summation draft in ThinkPages when an Intent completes.
 * (v2 Design Bible & Migration Plan §1: Auto-summation → ThinkPages draft post)
 */
export async function generateIntentSummationDraft(params: {
  db: PrismaClient | any;
  intentId: string;
  countryId: string;
  visibility?: "draft" | "public";
  customContent?: string;
}): Promise<SummationDraftResult | null> {
  const { db, intentId, countryId, visibility = "draft", customContent } = params;

  // 1. Load intent & country data
  const [intent, country] = await Promise.all([
    db.intent.findUnique({ where: { id: intentId } }),
    db.country.findUnique({
      where: { id: countryId },
      select: { id: true, name: true, slug: true, flag: true },
    }),
  ]);

  if (!intent || !country) return null;

  // 2. Parse changes and construct prose narrative
  const countryName = country.name || "The Government";
  let parsedChanges: Array<{ label: string; detail?: string }> = [];
  try {
    if (intent.changesJson) {
      parsedChanges = JSON.parse(intent.changesJson);
    }
  } catch {
    /* fallback to empty */
  }

  const tierTitle = intent.tier ? intent.tier.toUpperCase() : "EXECUTIVE";
  const changesSummary =
    parsedChanges.length > 0
      ? parsedChanges.map((c) => c.label).join(", ")
      : intent.summary || intent.goal;

  const proseNarrative =
    `🏛️ **EXECUTIVE SUMMATION: ${intent.goal}**\n\n` +
    `Under ${tierTitle} Directive authority, ${countryName} has successfully completed state actions regarding "${intent.goal}".\n\n` +
    `**Key Policy & Budget Measures Implemented:**\n` +
    `• ${changesSummary}\n\n` +
    `#${country.slug || "Statecraft"} #ExecutiveDirective #${intent.category || "policy"}`;

  // 3. Find or ensure official ThinkPages account for this country
  let account = await db.thinkpagesAccount.findFirst({
    where: {
      countryId,
      isActive: true,
      accountType: { in: ["GOVERNMENT", "government", "OFFICIAL", "official"] },
    },
  });

  if (!account) {
    account = await db.thinkpagesAccount.findFirst({
      where: { countryId, isActive: true },
      orderBy: { createdAt: "asc" },
    });
  }

  if (!account) {
    // Look up country owner user to link clerkUserId
    const user = await db.user.findFirst({
      where: { countryId },
      select: { clerkUserId: true },
    });
    const clerkUserId = user?.clerkUserId || `official_${countryId}`;
    const rawSlug = country.slug || countryName.toLowerCase().replace(/[^a-z0-9]/g, "_");
    const baseUsername = `gov_${rawSlug}`.slice(0, 24);

    const existingUsername = await db.thinkpagesAccount.findUnique({
      where: { username: baseUsername },
      select: { id: true },
    });

    const finalUsername = existingUsername
      ? `gov_${rawSlug.slice(0, 16)}_${Date.now().toString(36).slice(-5)}`
      : baseUsername;

    // Create an official account fallback matching Prisma schema
    account = await db.thinkpagesAccount.create({
      data: {
        clerkUserId,
        countryId,
        accountType: "GOVERNMENT",
        username: finalUsername,
        displayName: `${countryName} Executive`,
        firstName: countryName,
        lastName: "Executive",
        bio: `Official executive channel for ${countryName}.`,
        profileImageUrl: country.flag || undefined,
        verified: true,
        isActive: true,
      },
    });
  }

  const finalContent = customContent?.trim() ? customContent.trim() : proseNarrative;

  // 4. Create post in ThinkpagesPost table (draft or public)
  const post = await db.thinkpagesPost.create({
    data: {
      accountId: account.id,
      content: finalContent,
      postType: "original",
      hashtags: `#${country.slug || "Statecraft"} #${intent.category || "policy"}`,
      visibility,
      isAutoGenerated: true,
      ixTimeTimestamp: new Date(),
    },
  });

  return {
    postId: post.id,
    accountId: account.id,
    content: post.content,
    visibility: post.visibility,
    isAutoGenerated: post.isAutoGenerated,
  };
}
