import type { GovernmentTemplate } from "~/types/government";

export const Australian_CommonwealthTemplate: GovernmentTemplate = {
    name: "Australian Commonwealth",
    governmentType: "Constitutional Monarchy",
    description: "Federal system with strong state governments and resource-based economy",
    fiscalYear: "July to June",
    departments: [
      {
        name: "Department of Treasury",
        shortName: "Treasury",
        category: "Finance",
        description: "Economic policy, fiscal management, and financial regulation",
        ministerTitle: "Treasurer",
        organizationalLevel: "Department",
        icon: "DollarSign",
        color: "#7c3aed",
        priority: 100,
        functions: ["Economic Policy", "Fiscal Management", "Tax Policy", "Financial Regulation"],
        typicalBudgetPercent: 10,
        subBudgets: [
          {
            name: "Economic Analysis",
            budgetType: "Personnel",
            percent: 40,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Tax Administration",
            budgetType: "Personnel",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Financial Regulation",
            budgetType: "Operations",
            percent: 25,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Budget Balance",
            description: "Government budget balance as percentage of GDP",
            targetValue: 0,
            unit: "% GDP",
            frequency: "Quarterly",
            trend: "Stable",
            category: "Financial",
          },
        ],
      },
      {
        name: "Department of Foreign Affairs and Trade",
        shortName: "DFAT",
        category: "Foreign Affairs",
        description: "International relations, trade policy, and diplomatic affairs",
        ministerTitle: "Minister for Foreign Affairs",
        organizationalLevel: "Department",
        icon: "Globe",
        color: "#3b82f6",
        priority: 98,
        functions: ["Diplomacy", "Trade Policy", "International Relations", "Consular Services"],
        typicalBudgetPercent: 8,
        subBudgets: [
          {
            name: "Diplomatic Missions",
            budgetType: "Operations",
            percent: 50,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Trade Promotion",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "International Aid",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Trade Balance",
            description: "Balance of trade as percentage of GDP",
            targetValue: 2,
            unit: "% GDP",
            frequency: "Quarterly",
            trend: "Stable",
            category: "Performance",
          },
        ],
      },
      {
        name: "Department of Industry, Science and Resources",
        shortName: "DISR",
        category: "Science and Technology",
        description: "Industrial policy, scientific research, and resource management",
        ministerTitle: "Minister for Industry and Science",
        organizationalLevel: "Department",
        icon: "TrendingUp",
        color: "#10b981",
        priority: 95,
        functions: [
          "Industrial Policy",
          "Scientific Research",
          "Resource Management",
          "Innovation",
        ],
        typicalBudgetPercent: 12,
        subBudgets: [
          {
            name: "Research and Development",
            budgetType: "Operations",
            percent: 40,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Industrial Support",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Resource Management",
            budgetType: "Operations",
            percent: 25,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Research Intensity",
            description: "R&D expenditure as percentage of GDP",
            targetValue: 2.2,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Income Tax",
        category: "Direct Tax",
        rate: 45,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Goods and Services Tax",
        category: "Indirect Tax",
        rate: 10,
        collectionMethod: "Point of Sale",
      },
      { name: "Company Tax", category: "Direct Tax", rate: 30, collectionMethod: "Annual Filing" },
      {
        name: "Resource Rent Tax",
        category: "Direct Tax",
        rate: 40,
        collectionMethod: "Annual Filing",
      },
    ],
  },
];

/**
};
