import type { GovernmentTemplate } from "~/types/government";

export const Brazilian_Federal_RepublicTemplate: GovernmentTemplate = {
    name: "Brazilian Federal Republic",
    governmentType: "Presidential Republic",
    description: "Large federal system with strong regional diversity and social programs",
    fiscalYear: "Calendar Year",
    departments: [
      {
        name: "Ministry of Social Development",
        shortName: "MDS",
        category: "Social Services",
        description: "Social assistance programs and poverty reduction initiatives",
        ministerTitle: "Minister of Social Development",
        organizationalLevel: "Ministry",
        icon: "Users",
        color: "#059669",
        priority: 100,
        functions: ["Social Assistance", "Poverty Reduction", "Family Support", "Food Security"],
        typicalBudgetPercent: 20,
        subBudgets: [
          {
            name: "Bolsa Família Program",
            budgetType: "Operations",
            percent: 50,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Social Assistance",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Food Security",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Poverty Rate",
            description: "Percentage of population below poverty line",
            targetValue: 15,
            unit: "%",
            frequency: "Annually",
            trend: "Down",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Education",
        shortName: "MEC",
        category: "Education",
        description: "National education system and educational policy",
        ministerTitle: "Minister of Education",
        organizationalLevel: "Ministry",
        icon: "GraduationCap",
        color: "#2563eb",
        priority: 98,
        functions: [
          "Education Policy",
          "Higher Education",
          "Teacher Training",
          "Educational Infrastructure",
        ],
        typicalBudgetPercent: 18,
        subBudgets: [
          {
            name: "Basic Education",
            budgetType: "Operations",
            percent: 45,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Higher Education",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Infrastructure",
            budgetType: "Capital",
            percent: 20,
            isRecurring: false,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Literacy Rate",
            description: "Adult literacy rate",
            targetValue: 93,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Health",
        shortName: "MS",
        category: "Health",
        description: "Public health system and healthcare policy",
        ministerTitle: "Minister of Health",
        organizationalLevel: "Ministry",
        icon: "Heart",
        color: "#dc2626",
        priority: 95,
        functions: ["Public Health", "Healthcare Policy", "Disease Prevention", "Medical Services"],
        typicalBudgetPercent: 15,
        subBudgets: [
          {
            name: "Public Health Services",
            budgetType: "Personnel",
            percent: 50,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Disease Prevention",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Medical Infrastructure",
            budgetType: "Capital",
            percent: 20,
            isRecurring: false,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Life Expectancy",
            description: "Average life expectancy at birth",
            targetValue: 76,
            unit: "years",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Income Tax",
        category: "Direct Tax",
        rate: 27.5,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Corporate Tax",
        category: "Direct Tax",
        rate: 34,
        collectionMethod: "Annual Filing",
      },
      {
        name: "Value Added Tax",
        category: "Indirect Tax",
        rate: 17,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Social Security Contributions",
        category: "Direct Tax",
        rate: 11,
        collectionMethod: "Payroll Deduction",
      },
    ],
};
