import type { GovernmentTemplate } from "~/types/government";

export const Canadian_ConfederationTemplate: GovernmentTemplate = {
    name: "Canadian Confederation",
    governmentType: "Parliamentary Democracy",
    description:
      "Decentralized federation with strong provincial autonomy and multicultural society",
    fiscalYear: "April to March",
    departments: [
      {
        name: "Department of Finance",
        shortName: "FIN",
        category: "Finance",
        description: "Economic policy, fiscal management, and financial regulation",
        ministerTitle: "Minister of Finance",
        organizationalLevel: "Department",
        icon: "DollarSign",
        color: "#7c3aed",
        priority: 100,
        functions: ["Economic Policy", "Fiscal Management", "Financial Regulation", "Tax Policy"],
        typicalBudgetPercent: 8,
        subBudgets: [
          {
            name: "Economic Analysis",
            budgetType: "Personnel",
            percent: 40,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Financial Regulation",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Tax Administration",
            budgetType: "Personnel",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Fiscal Balance",
            description: "Government budget balance as percentage of GDP",
            targetValue: 0,
            unit: "% GDP",
            frequency: "Quarterly",
            trend: "Stable",
            category: "Financial",
          },
        ],
      },
      {
        name: "Department of Indigenous Services",
        shortName: "ISC",
        category: "Social Services",
        description: "Services for Indigenous peoples and reconciliation efforts",
        ministerTitle: "Minister of Indigenous Services",
        organizationalLevel: "Department",
        icon: "Users",
        color: "#059669",
        priority: 98,
        functions: [
          "Indigenous Services",
          "Reconciliation",
          "Community Development",
          "Cultural Support",
        ],
        typicalBudgetPercent: 12,
        subBudgets: [
          {
            name: "Community Services",
            budgetType: "Operations",
            percent: 45,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Infrastructure Development",
            budgetType: "Capital",
            percent: 35,
            isRecurring: false,
            priority: "High",
          },
          {
            name: "Cultural Programs",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Indigenous Well-being Index",
            description: "Overall quality of life for Indigenous communities",
            targetValue: 75,
            unit: "points",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Department of Environment and Climate Change",
        shortName: "ECCC",
        category: "Environment",
        description: "Environmental protection, climate action, and natural resource management",
        ministerTitle: "Minister of Environment and Climate Change",
        organizationalLevel: "Department",
        icon: "Leaf",
        color: "#10b981",
        priority: 95,
        functions: [
          "Environmental Protection",
          "Climate Action",
          "Natural Resources",
          "Biodiversity",
        ],
        typicalBudgetPercent: 10,
        subBudgets: [
          {
            name: "Climate Programs",
            budgetType: "Operations",
            percent: 40,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Environmental Monitoring",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Conservation Programs",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Greenhouse Gas Reduction",
            description: "Annual reduction in greenhouse gas emissions",
            targetValue: 8,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Personal Income Tax",
        category: "Direct Tax",
        rate: 33,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Goods and Services Tax",
        category: "Indirect Tax",
        rate: 5,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Corporate Tax",
        category: "Direct Tax",
        rate: 15,
        collectionMethod: "Annual Filing",
      },
      {
        name: "Employment Insurance",
        category: "Direct Tax",
        rate: 2.4,
        collectionMethod: "Payroll Deduction",
      },
    ],
};
