import type { GovernmentTemplate } from "~/types/government";

export const Emirati_FederationTemplate: GovernmentTemplate = {
    name: "Emirati Federation",
    governmentType: "Federal Constitutional Republic",
    description:
      "Federation of seven emirates with strong central coordination and oil-based economy",
    fiscalYear: "January to December",
    departments: [
      {
        name: "Ministry of Energy and Infrastructure",
        shortName: "MEI",
        category: "Energy",
        description: "Energy policy, oil and gas management, and infrastructure development",
        ministerTitle: "Minister of Energy and Infrastructure",
        organizationalLevel: "Ministry",
        icon: "Zap",
        color: "#f59e0b",
        priority: 100,
        functions: ["Energy Policy", "Oil & Gas", "Renewable Energy", "Infrastructure"],
        typicalBudgetPercent: 25,
        subBudgets: [
          {
            name: "Energy Infrastructure",
            budgetType: "Capital",
            percent: 45,
            isRecurring: false,
            priority: "Critical",
          },
          {
            name: "Oil & Gas Operations",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Renewable Energy",
            budgetType: "Capital",
            percent: 20,
            isRecurring: false,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Energy Production",
            description: "Total energy production capacity",
            targetValue: 95,
            unit: "% capacity",
            frequency: "Monthly",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Economy",
        shortName: "MoE",
        category: "Commerce",
        description: "Economic diversification, trade, and business development",
        ministerTitle: "Minister of Economy",
        organizationalLevel: "Ministry",
        icon: "TrendingUp",
        color: "#10b981",
        priority: 98,
        functions: [
          "Economic Diversification",
          "Trade Policy",
          "Business Development",
          "Investment",
        ],
        typicalBudgetPercent: 12,
        subBudgets: [
          {
            name: "Economic Development",
            budgetType: "Operations",
            percent: 40,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Trade Promotion",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Investment Attraction",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Economic Diversification Index",
            description: "Non-oil GDP as percentage of total GDP",
            targetValue: 70,
            unit: "%",
            frequency: "Quarterly",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Foreign Affairs",
        shortName: "MFA",
        category: "Foreign Affairs",
        description: "International relations and diplomatic affairs",
        ministerTitle: "Minister of Foreign Affairs",
        organizationalLevel: "Ministry",
        icon: "Globe",
        color: "#3b82f6",
        priority: 95,
        functions: ["Diplomacy", "International Relations", "Foreign Policy", "Consular Services"],
        typicalBudgetPercent: 8,
        subBudgets: [
          {
            name: "Diplomatic Missions",
            budgetType: "Operations",
            percent: 50,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "International Organizations",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Consular Services",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "International Relations Score",
            description: "Quality of diplomatic relationships",
            targetValue: 80,
            unit: "points",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Oil and Gas Revenue",
        category: "Non-Tax Revenue",
        rate: 60,
        collectionMethod: "State Owned Enterprises",
      },
      { name: "Corporate Tax", category: "Direct Tax", rate: 9, collectionMethod: "Annual Filing" },
      {
        name: "Value Added Tax",
        category: "Indirect Tax",
        rate: 5,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Customs Duties",
        category: "Indirect Tax",
        rate: 5,
        collectionMethod: "Import Based",
      },
    ],
  }
};
