import type { GovernmentTemplate } from "~/types/government";

export const German_Federal_RepublicTemplate: GovernmentTemplate = {
    name: "German Federal Republic",
    governmentType: "Federal Republic",
    description: "Strong federal system with social market economy and comprehensive welfare state",
    fiscalYear: "Calendar Year",
    departments: [
      {
        name: "Federal Ministry of Labour and Social Affairs",
        shortName: "BMAS",
        category: "Social Services",
        description: "Labor policy, social security, and worker protection",
        ministerTitle: "Federal Minister",
        organizationalLevel: "Ministry",
        icon: "Users",
        color: "#f59e0b",
        priority: 100,
        functions: ["Labor Policy", "Social Security", "Worker Protection", "Employment Services"],
        typicalBudgetPercent: 35,
        subBudgets: [
          {
            name: "Social Security",
            budgetType: "Operations",
            percent: 50,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Employment Services",
            budgetType: "Personnel",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Worker Protection",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Unemployment Rate",
            description: "National unemployment rate",
            targetValue: 3.5,
            unit: "%",
            frequency: "Monthly",
            trend: "Down",
            category: "Performance",
          },
        ],
      },
      {
        name: "Federal Ministry for Economic Affairs and Climate Action",
        shortName: "BMWK",
        category: "Commerce",
        description: "Economic policy, energy transition, and industrial development",
        ministerTitle: "Federal Minister",
        organizationalLevel: "Ministry",
        icon: "TrendingUp",
        color: "#10b981",
        priority: 98,
        functions: ["Economic Policy", "Energy Transition", "Industrial Policy", "Innovation"],
        typicalBudgetPercent: 18,
        subBudgets: [
          {
            name: "Economic Development",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Energy Transition",
            budgetType: "Capital",
            percent: 35,
            isRecurring: false,
            priority: "High",
          },
          {
            name: "Innovation Support",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Renewable Energy Share",
            description: "Percentage of energy from renewable sources",
            targetValue: 65,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Federal Ministry of Education and Research",
        shortName: "BMBF",
        category: "Education",
        description: "Education policy, research funding, and scientific development",
        ministerTitle: "Federal Minister",
        organizationalLevel: "Ministry",
        icon: "GraduationCap",
        color: "#2563eb",
        priority: 95,
        functions: [
          "Education Policy",
          "Research Funding",
          "Scientific Development",
          "Vocational Training",
        ],
        typicalBudgetPercent: 15,
        subBudgets: [
          {
            name: "Research Funding",
            budgetType: "Operations",
            percent: 45,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Education Programs",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Vocational Training",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Research and Development Intensity",
            description: "R&D spending as percentage of GDP",
            targetValue: 3.5,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Income Tax",
        category: "Direct Tax",
        rate: 42,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Value Added Tax",
        category: "Indirect Tax",
        rate: 19,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Corporate Tax",
        category: "Direct Tax",
        rate: 30,
        collectionMethod: "Annual Filing",
      },
      {
        name: "Social Insurance Contributions",
        category: "Direct Tax",
        rate: 20,
        collectionMethod: "Payroll Deduction",
      },
    ],
};
