import type { GovernmentTemplate } from "~/types/government";

export const Imperial_AdministrationTemplate: GovernmentTemplate = {
  name: "Imperial Administration",
  // ponytail: generic archetype, not a canon-nation claim. Was mislabeled "Caphirian
  // … Constitutional Monarchy" — Caphiria is a unitary constitutional republic with an
  // Imperator, NOT a monarchy. See plans/mycountry-lore-alignment*.md.
  governmentType: "Imperial Republic",
  description: "Complex administrative structure with imperial oversight and provincial autonomy",
  fiscalYear: "Calendar Year",
  departments: [
    {
      name: "Imperial Ministry of State",
      shortName: "IMS",
      category: "Interior",
      description: "Central coordination of imperial policy and provincial oversight",
      ministerTitle: "Imperial Chancellor",
      organizationalLevel: "Ministry",
      icon: "Crown",
      color: "#7c2d12",
      priority: 100,
      functions: [
        "Imperial Policy Coordination",
        "Provincial Relations",
        "Constitutional Affairs",
        "Imperial Ceremonies",
      ],
      typicalBudgetPercent: 8,
      subBudgets: [
        {
          name: "Imperial Court",
          budgetType: "Operations",
          percent: 25,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Provincial Liaison",
          budgetType: "Personnel",
          percent: 35,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "Policy Development",
          budgetType: "Operations",
          percent: 40,
          isRecurring: true,
          priority: "High",
        },
      ],
      kpis: [
        {
          name: "Imperial Unity Index",
          description: "Measure of provincial cooperation and imperial cohesion",
          targetValue: 85,
          unit: "%",
          frequency: "Quarterly",
          trend: "Up",
          category: "Performance",
        },
      ],
    },
    {
      name: "Ministry of Defense",
      shortName: "MoD",
      category: "Defense",
      description: "Imperial military forces and territorial defense",
      ministerTitle: "Minister of Defense",
      organizationalLevel: "Ministry",
      icon: "Shield",
      color: "#dc2626",
      priority: 95,
      functions: ["Military Operations", "Defense Policy", "National Security", "Veterans Affairs"],
      typicalBudgetPercent: 18,
      subBudgets: [
        {
          name: "Active Forces",
          budgetType: "Personnel",
          percent: 45,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Equipment & Procurement",
          budgetType: "Capital",
          percent: 30,
          isRecurring: false,
          priority: "High",
        },
        {
          name: "Operations & Training",
          budgetType: "Operations",
          percent: 20,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "Veterans Support",
          budgetType: "Personnel",
          percent: 5,
          isRecurring: true,
          priority: "Medium",
        },
      ],
      kpis: [
        {
          name: "Defense Readiness",
          description: "Overall military readiness and capability",
          targetValue: 90,
          unit: "%",
          frequency: "Monthly",
          trend: "Up",
          category: "Performance",
        },
        {
          name: "Recruitment Rate",
          description: "Success rate in meeting recruitment targets",
          targetValue: 95,
          unit: "%",
          frequency: "Monthly",
          trend: "Stable",
          category: "Performance",
        },
      ],
    },
    {
      name: "Ministry of Imperial Finance",
      shortName: "MIF",
      category: "Finance",
      description: "Economic policy, taxation, and imperial treasury management",
      ministerTitle: "Chancellor of the Imperial Treasury",
      organizationalLevel: "Ministry",
      icon: "Coins",
      color: "#7c3aed",
      priority: 98,
      functions: [
        "Tax Policy",
        "Budget Management",
        "Economic Planning",
        "Currency Management",
        "Trade Policy",
      ],
      typicalBudgetPercent: 6,
      subBudgets: [
        {
          name: "Tax Administration",
          budgetType: "Personnel",
          percent: 40,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Economic Analysis",
          budgetType: "Operations",
          percent: 25,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "Financial Systems",
          budgetType: "Capital",
          percent: 20,
          isRecurring: false,
          priority: "High",
        },
        {
          name: "International Relations",
          budgetType: "Operations",
          percent: 15,
          isRecurring: true,
          priority: "Medium",
        },
      ],
      kpis: [
        {
          name: "Tax Collection Efficiency",
          description: "Percentage of assessed taxes collected",
          targetValue: 92,
          unit: "%",
          frequency: "Monthly",
          trend: "Up",
          category: "Financial",
        },
        {
          name: "Budget Variance",
          description: "Deviation from planned budget allocations",
          targetValue: 5,
          unit: "%",
          frequency: "Quarterly",
          trend: "Down",
          category: "Financial",
        },
      ],
    },
    {
      name: "Ministry of Education",
      shortName: "MoE",
      category: "Education",
      description: "Educational policy and administration",
      ministerTitle: "Minister of Education",
      organizationalLevel: "Ministry",
      icon: "GraduationCap",
      color: "#2563eb",
      priority: 95,
      functions: ["Educational Policy", "School Administration", "Higher Education"],
      typicalBudgetPercent: 18,
      subBudgets: [
        {
          name: "Teacher Salaries",
          budgetType: "Personnel",
          percent: 55,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Infrastructure",
          budgetType: "Capital",
          percent: 25,
          isRecurring: false,
          priority: "High",
        },
        {
          name: "Programs",
          budgetType: "Operations",
          percent: 20,
          isRecurring: true,
          priority: "High",
        },
      ],
      kpis: [
        {
          name: "Literacy Rate",
          description: "National literacy rate",
          targetValue: 98,
          unit: "%",
          frequency: "Annually",
          trend: "Up",
          category: "Performance",
        },
      ],
    },
    {
      name: "Ministry of Health",
      shortName: "MoH",
      category: "Health",
      description: "Public health services and policy",
      ministerTitle: "Minister of Health",
      organizationalLevel: "Ministry",
      icon: "Heart",
      color: "#059669",
      priority: 92,
      functions: ["Healthcare Policy", "Public Health", "Medical Services"],
      typicalBudgetPercent: 16,
      subBudgets: [
        {
          name: "Medical Staff",
          budgetType: "Personnel",
          percent: 50,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Medical Equipment",
          budgetType: "Capital",
          percent: 30,
          isRecurring: false,
          priority: "High",
        },
        {
          name: "Public Health Programs",
          budgetType: "Operations",
          percent: 20,
          isRecurring: true,
          priority: "High",
        },
      ],
      kpis: [
        {
          name: "Life Expectancy",
          description: "Average life expectancy",
          targetValue: 82,
          unit: "years",
          frequency: "Annually",
          trend: "Up",
          category: "Performance",
        },
      ],
    },
    {
      name: "Ministry of Finance",
      shortName: "MoF",
      category: "Finance",
      description: "Economic policy and fiscal management",
      ministerTitle: "Chancellor of the Exchequer",
      organizationalLevel: "Ministry",
      icon: "Briefcase",
      color: "#7c3aed",
      priority: 98,
      functions: ["Budget Management", "Tax Policy", "Economic Policy"],
      typicalBudgetPercent: 8,
      subBudgets: [
        {
          name: "Administration",
          budgetType: "Personnel",
          percent: 40,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "Economic Programs",
          budgetType: "Operations",
          percent: 35,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "Infrastructure",
          budgetType: "Capital",
          percent: 25,
          isRecurring: false,
          priority: "Medium",
        },
      ],
      kpis: [
        {
          name: "Fiscal Balance",
          description: "Budget surplus/deficit ratio",
          targetValue: 2,
          unit: "% GDP",
          frequency: "Quarterly",
          trend: "Up",
          category: "Financial",
        },
      ],
    },
  ],
  typicalRevenueSources: [
    {
      name: "Personal Income Tax",
      category: "Direct Tax",
      rate: 25,
      collectionMethod: "Payroll Deduction",
    },
    {
      name: "Corporate Income Tax",
      category: "Direct Tax",
      rate: 20,
      collectionMethod: "Annual Filing",
    },
    {
      name: "Value Added Tax",
      category: "Indirect Tax",
      rate: 15,
      collectionMethod: "Point of Sale",
    },
    {
      name: "Property Tax",
      category: "Direct Tax",
      rate: 1.5,
      collectionMethod: "Annual Assessment",
    },
  ],
};
