import type { GovernmentTemplate } from "~/types/government";

export const Indian_Union_GovernmentTemplate: GovernmentTemplate = {
    name: "Indian Union Government",
    governmentType: "Federal Republic",
    description: "Large federal democracy with strong central government and state autonomy",
    fiscalYear: "April to March",
    departments: [
      {
        name: "Ministry of Finance",
        shortName: "MoF",
        category: "Finance",
        description: "Economic policy, fiscal management, and financial regulation",
        ministerTitle: "Finance Minister",
        organizationalLevel: "Ministry",
        icon: "DollarSign",
        color: "#7c3aed",
        priority: 100,
        functions: [
          "Economic Policy",
          "Fiscal Management",
          "Tax Administration",
          "Financial Regulation",
        ],
        typicalBudgetPercent: 12,
        subBudgets: [
          {
            name: "Tax Administration",
            budgetType: "Personnel",
            percent: 40,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Economic Programs",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Financial Regulation",
            budgetType: "Operations",
            percent: 25,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Tax to GDP Ratio",
            description: "Total tax revenue as percentage of GDP",
            targetValue: 17,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Financial",
          },
        ],
      },
      {
        name: "Ministry of Rural Development",
        shortName: "MoRD",
        category: "Agriculture",
        description: "Rural development programs and agricultural support",
        ministerTitle: "Minister of Rural Development",
        organizationalLevel: "Ministry",
        icon: "Home",
        color: "#10b981",
        priority: 98,
        functions: [
          "Rural Development",
          "Agricultural Support",
          "Rural Employment",
          "Infrastructure",
        ],
        typicalBudgetPercent: 15,
        subBudgets: [
          {
            name: "Rural Employment Programs",
            budgetType: "Operations",
            percent: 45,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Rural Infrastructure",
            budgetType: "Capital",
            percent: 35,
            isRecurring: false,
            priority: "High",
          },
          {
            name: "Agricultural Support",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Rural Employment Generation",
            description: "Number of rural employment opportunities created",
            targetValue: 250,
            unit: "million days",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Education",
        shortName: "MoE",
        category: "Education",
        description: "Education policy and school system administration",
        ministerTitle: "Minister of Education",
        organizationalLevel: "Ministry",
        icon: "GraduationCap",
        color: "#2563eb",
        priority: 95,
        functions: [
          "Education Policy",
          "School Administration",
          "Teacher Training",
          "Educational Access",
        ],
        typicalBudgetPercent: 16,
        subBudgets: [
          {
            name: "School Education",
            budgetType: "Operations",
            percent: 50,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Higher Education",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Teacher Training",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Gross Enrollment Ratio",
            description: "Percentage of children enrolled in schools",
            targetValue: 95,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Income Tax",
        category: "Direct Tax",
        rate: 30,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Goods and Services Tax",
        category: "Indirect Tax",
        rate: 18,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Corporate Tax",
        category: "Direct Tax",
        rate: 30,
        collectionMethod: "Annual Filing",
      },
      {
        name: "Customs Duties",
        category: "Indirect Tax",
        rate: 10,
        collectionMethod: "Import Based",
      },
    ],
  }
};
