import type { GovernmentTemplate } from "~/types/government";

export const Japanese_Parliamentary_SystemTemplate: GovernmentTemplate = {
    name: "Japanese Parliamentary System",
    governmentType: "Constitutional Monarchy",
    description:
      "Stable parliamentary democracy with strong bureaucracy and consensus-based decision making",
    fiscalYear: "April to March",
    departments: [
      {
        name: "Ministry of Internal Affairs and Communications",
        shortName: "MIC",
        category: "Interior",
        description: "Local government coordination, communications, and administrative oversight",
        ministerTitle: "Minister of Internal Affairs and Communications",
        organizationalLevel: "Ministry",
        icon: "Building2",
        color: "#6b7280",
        priority: 100,
        functions: [
          "Local Government",
          "Communications Policy",
          "Administrative Oversight",
          "Elections",
        ],
        typicalBudgetPercent: 12,
        subBudgets: [
          {
            name: "Local Government Support",
            budgetType: "Operations",
            percent: 40,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Communications Infrastructure",
            budgetType: "Capital",
            percent: 30,
            isRecurring: false,
            priority: "High",
          },
          {
            name: "Administrative Services",
            budgetType: "Personnel",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Administrative Efficiency",
            description: "Government service delivery effectiveness",
            targetValue: 88,
            unit: "%",
            frequency: "Quarterly",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Economy, Trade and Industry",
        shortName: "METI",
        category: "Commerce",
        description: "Economic policy, trade, and industrial development",
        ministerTitle: "Minister of Economy, Trade and Industry",
        organizationalLevel: "Ministry",
        icon: "TrendingUp",
        color: "#10b981",
        priority: 98,
        functions: ["Economic Policy", "Trade Relations", "Industrial Development", "Innovation"],
        typicalBudgetPercent: 15,
        subBudgets: [
          {
            name: "Economic Development",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Trade Promotion",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Industrial Support",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Export Growth Rate",
            description: "Annual export growth percentage",
            targetValue: 3,
            unit: "%",
            frequency: "Quarterly",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Health, Labour and Welfare",
        shortName: "MHLW",
        category: "Health",
        description: "Public health, labor standards, and social welfare programs",
        ministerTitle: "Minister of Health, Labour and Welfare",
        organizationalLevel: "Ministry",
        icon: "Heart",
        color: "#059669",
        priority: 95,
        functions: ["Public Health", "Labor Standards", "Social Welfare", "Pension System"],
        typicalBudgetPercent: 20,
        subBudgets: [
          {
            name: "Healthcare Services",
            budgetType: "Personnel",
            percent: 45,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Social Welfare",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Labor Services",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Life Expectancy",
            description: "Average life expectancy at birth",
            targetValue: 84,
            unit: "years",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Income Tax",
        category: "Direct Tax",
        rate: 45,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Consumption Tax",
        category: "Indirect Tax",
        rate: 10,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Corporate Tax",
        category: "Direct Tax",
        rate: 30,
        collectionMethod: "Annual Filing",
      },
      {
        name: "Social Insurance",
        category: "Direct Tax",
        rate: 15,
        collectionMethod: "Payroll Deduction",
      },
    ],
};
