import type { GovernmentTemplate } from "~/types/government";

export const Nordic_Social_DemocracyTemplate: GovernmentTemplate = {
    name: "Nordic Social Democracy",
    governmentType: "Parliamentary Democracy",
    description:
      "Comprehensive welfare state with strong social safety nets and progressive taxation",
    fiscalYear: "Calendar Year",
    departments: [
      {
        name: "Ministry of Social Affairs",
        shortName: "MSA",
        category: "Social Services",
        description: "Comprehensive social welfare and safety net programs",
        ministerTitle: "Minister of Social Affairs",
        organizationalLevel: "Ministry",
        icon: "Users",
        color: "#059669",
        priority: 100,
        functions: [
          "Social Security",
          "Unemployment Benefits",
          "Disability Support",
          "Family Services",
        ],
        typicalBudgetPercent: 25,
        subBudgets: [
          {
            name: "Social Security",
            budgetType: "Personnel",
            percent: 40,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Welfare Programs",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Social Services",
            budgetType: "Personnel",
            percent: 25,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "Social Welfare Coverage",
            description: "Percentage of population covered by social programs",
            targetValue: 95,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Labor",
        shortName: "MoL",
        category: "Social Services",
        description: "Labor relations, employment policy, and workplace safety",
        ministerTitle: "Minister of Labor",
        organizationalLevel: "Ministry",
        icon: "Briefcase",
        color: "#f59e0b",
        priority: 95,
        functions: ["Employment Policy", "Labor Relations", "Workplace Safety", "Job Training"],
        typicalBudgetPercent: 8,
        subBudgets: [
          {
            name: "Employment Services",
            budgetType: "Personnel",
            percent: 45,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Training Programs",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Labor Inspection",
            budgetType: "Operations",
            percent: 25,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Unemployment Rate",
            description: "National unemployment rate",
            targetValue: 4,
            unit: "%",
            frequency: "Monthly",
            trend: "Down",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Environment",
        shortName: "MoE",
        category: "Environment",
        description: "Environmental protection and climate policy",
        ministerTitle: "Minister of Environment",
        organizationalLevel: "Ministry",
        icon: "Leaf",
        color: "#10b981",
        priority: 90,
        functions: [
          "Environmental Protection",
          "Climate Policy",
          "Renewable Energy",
          "Conservation",
        ],
        typicalBudgetPercent: 6,
        subBudgets: [
          {
            name: "Environmental Monitoring",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Climate Programs",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Green Infrastructure",
            budgetType: "Capital",
            percent: 35,
            isRecurring: false,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Carbon Emissions Reduction",
            description: "Annual reduction in carbon emissions",
            targetValue: 5,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Progressive Income Tax",
        category: "Direct Tax",
        rate: 45,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Corporate Tax",
        category: "Direct Tax",
        rate: 22,
        collectionMethod: "Annual Filing",
      },
      {
        name: "Value Added Tax",
        category: "Indirect Tax",
        rate: 25,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Social Security Contributions",
        category: "Direct Tax",
        rate: 18,
        collectionMethod: "Payroll Deduction",
      },
    ],
};
