import type { GovernmentTemplate } from "~/types/government";

export const Singaporean_MeritocracyTemplate: GovernmentTemplate = {
    name: "Singaporean Meritocracy",
    governmentType: "Parliamentary Democracy",
    description:
      "Efficient technocratic governance with focus on economic development and merit-based advancement",
    fiscalYear: "April to March",
    departments: [
      {
        name: "Ministry of Trade and Industry",
        shortName: "MTI",
        category: "Commerce",
        description: "Economic development, trade policy, and industrial strategy",
        ministerTitle: "Minister of Trade and Industry",
        organizationalLevel: "Ministry",
        icon: "TrendingUp",
        color: "#7c3aed",
        priority: 100,
        functions: [
          "Trade Policy",
          "Economic Development",
          "Industrial Strategy",
          "Investment Promotion",
        ],
        typicalBudgetPercent: 15,
        subBudgets: [
          {
            name: "Trade Development",
            budgetType: "Operations",
            percent: 40,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Investment Promotion",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Economic Research",
            budgetType: "Operations",
            percent: 30,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "GDP Growth Rate",
            description: "Annual GDP growth percentage",
            targetValue: 4,
            unit: "%",
            frequency: "Quarterly",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Education",
        shortName: "MoE",
        category: "Education",
        description: "Education policy with focus on merit-based advancement and technical skills",
        ministerTitle: "Minister of Education",
        organizationalLevel: "Ministry",
        icon: "GraduationCap",
        color: "#2563eb",
        priority: 98,
        functions: [
          "Education Policy",
          "Curriculum Development",
          "Teacher Training",
          "Technical Education",
        ],
        typicalBudgetPercent: 20,
        subBudgets: [
          {
            name: "Teacher Salaries",
            budgetType: "Personnel",
            percent: 50,
            isRecurring: true,
            priority: "Critical",
          },
          {
            name: "Infrastructure",
            budgetType: "Capital",
            percent: 30,
            isRecurring: false,
            priority: "High",
          },
          {
            name: "Programs",
            budgetType: "Operations",
            percent: 20,
            isRecurring: true,
            priority: "High",
          },
        ],
        kpis: [
          {
            name: "PISA Score",
            description: "International student assessment score",
            targetValue: 550,
            unit: "points",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
      {
        name: "Ministry of Manpower",
        shortName: "MOM",
        category: "Labor",
        description: "Labor policy, foreign workforce management, and skills development",
        ministerTitle: "Minister of Manpower",
        organizationalLevel: "Ministry",
        icon: "Users",
        color: "#f59e0b",
        priority: 95,
        functions: ["Labor Policy", "Foreign Workers", "Skills Development", "Workplace Safety"],
        typicalBudgetPercent: 8,
        subBudgets: [
          {
            name: "Labor Services",
            budgetType: "Personnel",
            percent: 40,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Skills Programs",
            budgetType: "Operations",
            percent: 35,
            isRecurring: true,
            priority: "High",
          },
          {
            name: "Foreign Worker Management",
            budgetType: "Operations",
            percent: 25,
            isRecurring: true,
            priority: "Medium",
          },
        ],
        kpis: [
          {
            name: "Skills Development Rate",
            description: "Percentage of workforce in skills programs",
            targetValue: 60,
            unit: "%",
            frequency: "Annually",
            trend: "Up",
            category: "Performance",
          },
        ],
      },
    ],
    typicalRevenueSources: [
      {
        name: "Corporate Income Tax",
        category: "Direct Tax",
        rate: 17,
        collectionMethod: "Annual Filing",
      },
      {
        name: "Personal Income Tax",
        category: "Direct Tax",
        rate: 22,
        collectionMethod: "Payroll Deduction",
      },
      {
        name: "Goods and Services Tax",
        category: "Indirect Tax",
        rate: 7,
        collectionMethod: "Point of Sale",
      },
      {
        name: "Stamp Duty",
        category: "Direct Tax",
        rate: 3,
        collectionMethod: "Transaction Based",
      },
    ],
  }
};
