import type { GovernmentTemplate } from "~/types/government";

export const Swiss_Federal_ConfederationTemplate: GovernmentTemplate = {
  name: "Swiss Federal Confederation",
  governmentType: "Federal Republic",
  description: "Decentralized federal system with strong cantonal autonomy and direct democracy",
  fiscalYear: "Calendar Year",
  departments: [
    {
      name: "Federal Department of Foreign Affairs",
      shortName: "FDFA",
      category: "Foreign Affairs",
      description: "International relations, diplomacy, and foreign policy",
      ministerTitle: "Federal Councillor",
      organizationalLevel: "Department",
      icon: "Globe",
      color: "#3b82f6",
      priority: 100,
      functions: ["Diplomacy", "International Relations", "Foreign Aid", "Consular Services"],
      typicalBudgetPercent: 8,
      subBudgets: [
        {
          name: "Diplomatic Missions",
          budgetType: "Operations",
          percent: 50,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Foreign Aid",
          budgetType: "Operations",
          percent: 30,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "International Organizations",
          budgetType: "Operations",
          percent: 20,
          isRecurring: true,
          priority: "High",
        },
      ],
      kpis: [
        {
          name: "Diplomatic Relations Index",
          description: "Quality of international relationships",
          targetValue: 85,
          unit: "%",
          frequency: "Annually",
          trend: "Stable",
          category: "Performance",
        },
      ],
    },
    {
      name: "Federal Department of Justice and Police",
      shortName: "FDJP",
      category: "Justice",
      description: "Federal justice system, police coordination, and legal affairs",
      ministerTitle: "Federal Councillor",
      organizationalLevel: "Department",
      icon: "Scale",
      color: "#8b5cf6",
      priority: 98,
      functions: ["Federal Justice", "Police Coordination", "Legal Affairs", "Immigration"],
      typicalBudgetPercent: 12,
      subBudgets: [
        {
          name: "Federal Police",
          budgetType: "Personnel",
          percent: 45,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Justice System",
          budgetType: "Operations",
          percent: 35,
          isRecurring: true,
          priority: "Critical",
        },
        {
          name: "Immigration Services",
          budgetType: "Operations",
          percent: 20,
          isRecurring: true,
          priority: "High",
        },
      ],
      kpis: [
        {
          name: "Crime Rate",
          description: "Federal crimes per 100,000 population",
          targetValue: 250,
          unit: "crimes",
          frequency: "Annually",
          trend: "Down",
          category: "Performance",
        },
      ],
    },
    {
      name: "Federal Department of Economic Affairs",
      shortName: "EAER",
      category: "Commerce",
      description: "Economic policy, agriculture, and innovation",
      ministerTitle: "Federal Councillor",
      organizationalLevel: "Department",
      icon: "TrendingUp",
      color: "#10b981",
      priority: 95,
      functions: ["Economic Policy", "Agriculture", "Innovation", "Trade"],
      typicalBudgetPercent: 15,
      subBudgets: [
        {
          name: "Economic Development",
          budgetType: "Operations",
          percent: 40,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "Agricultural Support",
          budgetType: "Operations",
          percent: 35,
          isRecurring: true,
          priority: "High",
        },
        {
          name: "Innovation Programs",
          budgetType: "Operations",
          percent: 25,
          isRecurring: true,
          priority: "Medium",
        },
      ],
      kpis: [
        {
          name: "Innovation Index",
          description: "National innovation capacity score",
          targetValue: 75,
          unit: "points",
          frequency: "Annually",
          trend: "Up",
          category: "Performance",
        },
      ],
    },
  ],
  typicalRevenueSources: [
    {
      name: "Federal Income Tax",
      category: "Direct Tax",
      rate: 11.5,
      collectionMethod: "Annual Filing",
    },
    {
      name: "Value Added Tax",
      category: "Indirect Tax",
      rate: 7.7,
      collectionMethod: "Point of Sale",
    },
    {
      name: "Withholding Tax",
      category: "Direct Tax",
      rate: 35,
      collectionMethod: "Source Deduction",
    },
    {
      name: "Customs Duties",
      category: "Indirect Tax",
      rate: 3.2,
      collectionMethod: "Import Based",
    },
  ],
};
