import type { PrismaClient } from "@prisma/client";
import type { MatchDayResultLine, StandingMover } from "./feed-bulletins";

/**
 * Post a matchday result bulletin to the SportsNews feed (a ThinkpagesPost),
 * then asynchronously enrich it with LLM narration and mirror it to Discord.
 *
 * Best-effort: never throws into the simulation. Shared by the manual
 * `simulateMatchDay` mutation and the IxTime auto-advance cron so both paths
 * post identical bulletins.
 */
export async function postMatchDayBulletin(
  prisma: PrismaClient,
  args: {
    leagueName: string;
    sportPreset: string;
    matchDay: number;
    results: MatchDayResultLine[];
    movers?: StandingMover[];
  }
): Promise<void> {
  try {
    const acct = await prisma.thinkpagesAccount.findUnique({
      where: { username: "SportsNews" },
    });
    if (!acct) return;

    const { getSportEmoji } = await import("./presets");
    const { formatMatchDayBulletin } = await import("./feed-bulletins");

    const render = (llmSummary?: string) =>
      formatMatchDayBulletin({
        leagueName: args.leagueName,
        sportEmoji: getSportEmoji(args.sportPreset),
        matchDay: args.matchDay,
        results: args.results,
        movers: args.movers,
        llmSummary,
      });

    const post = await prisma.thinkpagesPost.create({
      data: {
        accountId: acct.id,
        content: render(),
        isAutoGenerated: true,
        ixTimeTimestamp: new Date(), // real-world time so bulletins stay chronological in the feed
      },
    });

    // Fire-and-forget: append LLM narration, then mirror to Discord either way.
    void (async () => {
      try {
        const { narrateBulletin } = await import("./commentary/narrator");
        const { getGlobalLLMConfig } = await import("./commentary/db-config");
        const dbConfig = await getGlobalLLMConfig(prisma);
        const summary = await narrateBulletin(args.results, {
          sport: args.sportPreset,
          leagueName: args.leagueName,
          matchDay: args.matchDay,
          config: dbConfig,
        });
        if (summary) {
          await prisma.thinkpagesPost.update({
            where: { id: post.id },
            data: { content: render(summary) },
          });
        }
      } catch (narrateErr) {
        console.error("[postMatchDayBulletin] narration failed:", narrateErr);
      } finally {
        try {
          const { mirrorThinkPagesPostToDiscordFeed } = await import(
            "~/lib/thinkpages-discord-feed"
          );
          await mirrorThinkPagesPostToDiscordFeed(prisma as never, post.id);
        } catch (mirrorErr) {
          console.error("[postMatchDayBulletin] Discord mirror failed:", mirrorErr);
        }
      }
    })();
  } catch (err) {
    console.error("[postMatchDayBulletin] feed bulletin failed:", err);
  }
}
