import { type PrismaClient } from "@prisma/client";
import { IxTime } from "../ixtime";
import { getPreset, getSportEmoji, type SportPresetKey } from "./presets";
import { processAging } from "./aging";
import { generateCoach, generateRookieClass } from "./talent";
import { persistSeasonSchedule } from "./scheduler";
import { resolveMatch, type TeamRatingVector } from "./resolver";
import { teamWageBill } from "./team-rating";
import { clamp } from "~/lib/utils";
import { mediaWikiImageUrl } from "~/lib/wiki-os/config";

type Prisma =
  | PrismaClient
  | Omit<PrismaClient, "$connect" | "$disconnect" | "$on" | "$transaction" | "$use" | "$extends">;

const loadSeason = (prisma: Prisma, seasonId: string) =>
  prisma.sportSeason.findUnique({
    where: { id: seasonId },
    include: {
      league: {
        include: {
          teams: {
            include: {
              players: { where: { isActive: true } },
              coaches: { where: { isActive: true } },
            },
          },
        },
      },
    },
  });
type LoadedSeason = NonNullable<Awaited<ReturnType<typeof loadSeason>>>;

const RETIRED = { isActive: false, careerStage: "retired" } as const;

/** Posts to the SportsNews account (when season bulletins are on) and mirrors it to Discord if enabled. */
async function postSportsBulletin(
  db: any,
  label: string,
  buildContent: () => string | Promise<string>
) {
  const { getSportsNotifyConfig } = await import("./notify-config");
  const notify = await getSportsNotifyConfig(db);
  const account = notify.seasonBulletins
    ? await db.thinkpagesAccount.findUnique({ where: { username: "SportsNews" } })
    : null;
  if (!account) return;

  const post = await db.thinkpagesPost.create({
    data: {
      accountId: account.id,
      content: await buildContent(),
      isAutoGenerated: true,
      ixTimeTimestamp: new Date(), // real-world time so bulletins stay chronological in the feed
    },
  });
  if (!notify.discordMirror) return;
  try {
    const { mirrorThinkPagesPostToDiscordFeed } = await import("~/lib/discord/thinkpages-feed");
    await mirrorThinkPagesPostToDiscordFeed(db, post.id);
  } catch (mirrorErr) {
    console.error(`[${label}] Failed to mirror sports post to Discord:`, mirrorErr);
  }
}

/** Finds-or-creates a one-off trophy card and grants a locked copy to its owner. */
async function mintTrophyCard(
  tx: any,
  opts: {
    ownerUserId: string;
    ownershipId: string;
    nextSerial: boolean;
    card: {
      title: string;
      description: string;
      artwork: string;
      rarity: string;
      season: number;
      stats: Record<string, unknown>;
      marketValue: number;
    };
  }
) {
  const template =
    (await tx.card.findFirst({ where: { title: opts.card.title } })) ??
    (await tx.card.create({ data: { ...opts.card, cardType: "SPECIAL", totalSupply: 1 } }));

  let serialNumber = 1;
  if (opts.nextSerial) {
    const last = await tx.cardOwnership.findFirst({
      where: { cardId: template.id },
      orderBy: { serialNumber: "desc" },
      select: { serialNumber: true },
    });
    serialNumber = (last?.serialNumber || 0) + 1;
  }

  const now = new Date();
  await tx.cardOwnership.create({
    data: {
      id: opts.ownershipId,
      userId: opts.ownerUserId,
      ownerId: opts.ownerUserId,
      cardId: template.id,
      serialNumber,
      quantity: 1,
      level: 1,
      experience: 0,
      isLocked: true,
      acquiredAt: now,
      createdAt: now,
      updatedAt: now,
    },
  });
}

async function postSeasonSummaryBulletin(prisma: Prisma, season: LoadedSeason) {
  try {
    const full = await prisma.sportSeason.findUnique({
      where: { id: season.id },
      include: {
        champion: { select: { id: true, name: true } },
        standings: {
          include: { team: { select: { name: true } } },
          orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
        },
      },
    });
    if (!full?.champion) return;
    const champion = full.champion;

    const standingsSummary = full.standings.map((s) => ({
      teamName: s.team.name,
      points: s.points,
      wins: s.wins,
      losses: s.losses,
    }));

    const { generateSeasonSummary } = await import("./commentary/narrator");
    const { formatSeasonChampionBulletin } = await import("./feed-bulletins");
    const { getGlobalLLMConfig } = await import("./commentary/db-config");
    const dbConfig = await getGlobalLLMConfig(prisma);
    const llmSummary = await generateSeasonSummary(
      season.league.name,
      champion.name,
      standingsSummary,
      season.league.sportPreset,
      dbConfig
    );

    await postSportsBulletin(prisma, "Post-Season Summary", () =>
      formatSeasonChampionBulletin({
        leagueName: season.league.name,
        leagueId: season.league.id,
        sportEmoji: getSportEmoji(season.league.sportPreset),
        championName: champion.name,
        championId: champion.id,
        llmSummary: llmSummary || undefined,
      })
    );
  } catch (summaryErr) {
    console.error("[Post-Season Summary Bulletin Error]", summaryErr);
  }
}

function applyRatingChanges(base: Record<string, number>, changes: Record<string, number>) {
  const next = { ...base };
  for (const [key, delta] of Object.entries(changes)) {
    next[key] = clamp((next[key] ?? 50) + delta, 1, 99);
  }
  return next;
}

/** Writes each aging result back: retirees are deactivated, everyone else ages a year with new ratings. */
function updateAged(
  model: any,
  results: Array<{
    playerId: string;
    retired: boolean;
    newStage: string;
    ratingChanges: Record<string, number>;
  }>,
  subjects: Array<{ id: string; age: number; ratings: Record<string, number> }>,
  onRetired?: (subject: { id: string } | undefined) => void
) {
  return Promise.all(
    results.map((res) => {
      const subject = subjects.find((s) => s.id === res.playerId);
      if (res.retired) {
        onRetired?.(subject);
        return model.update({ where: { id: res.playerId }, data: RETIRED });
      }
      if (!subject) return Promise.resolve(null);
      return model.update({
        where: { id: res.playerId },
        data: {
          age: subject.age + 1,
          careerStage: res.newStage,
          ratings: applyRatingChanges(subject.ratings, res.ratingChanges) as any,
        },
      });
    })
  );
}

const moveTeams = async (tx: any, teamIds: string[], leagueId: string) => {
  if (typeof tx.sportTeam?.updateMany === "function") {
    await tx.sportTeam.updateMany({ where: { id: { in: teamIds } }, data: { leagueId } });
    return;
  }
  for (const id of teamIds) await tx.sportTeam.update({ where: { id }, data: { leagueId } });
};

/** Swaps the bottom of this league with the top of each completed sub-league. */
async function swapPromotedAndRelegated(tx: any, season: LoadedSeason) {
  const league = season.league;
  const subLeagues: any[] =
    typeof tx.sportLeague?.findMany === "function"
      ? await tx.sportLeague.findMany({
          where: { parentLeagueId: league.id },
          include: { seasons: { orderBy: { seasonNumber: "desc" }, take: 1 } },
        })
      : [];

  for (const subLeague of subLeagues) {
    const subSeason = subLeague.seasons[0];
    if (!subSeason || subSeason.status !== "completed") {
      throw new Error(
        `Cannot transition parent league ${league.name} because sub-league ${subLeague.name} is not completed.`
      );
    }

    const parentStandings = await tx.sportStanding.findMany({
      where: { seasonId: season.id },
      orderBy: [{ points: "asc" }, { pointsFor: "asc" }],
      take: (league as any).relegationCount ?? 3,
    });
    const childStandings = await tx.sportStanding.findMany({
      where: { seasonId: subSeason.id },
      orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
      take: subLeague.promotionCount ?? 3,
    });
    const relegatedIds: string[] = parentStandings.map((s: { teamId: string }) => s.teamId);
    const promotedIds: string[] = childStandings.map((s: { teamId: string }) => s.teamId);
    if (relegatedIds.length === 0 || promotedIds.length === 0) continue;

    await moveTeams(tx, relegatedIds, subLeague.id);
    await moveTeams(tx, promotedIds, league.id);

    try {
      await postSportsBulletin(tx, "Promotion Relegation bulletin", async () => {
        const namesOf = async (ids: string[]) =>
          (await tx.sportTeam.findMany({ where: { id: { in: ids } }, select: { name: true } }))
            .map((t: { name: string }) => t.name)
            .join(", ");
        const relegated = await namesOf(relegatedIds);
        const promoted = await namesOf(promotedIds);
        return `📢 [League System Bulletin] Promotion & Relegation Swaps Completed!\n\nRelegated from ${league.name} to ${subLeague.name}: ${relegated}\nPromoted to ${league.name} from ${subLeague.name}: ${promoted}`;
      });
    } catch (bulletinErr) {
      console.error("[Promotion Relegation Bulletin Error]", bulletinErr);
    }
  }
}

/** Top scorer, most assists and MVP (the leading scorer) from the season's match stats. */
async function grantSeasonAwards(tx: any, season: LoadedSeason) {
  if (typeof tx.sportMatchStat?.findMany !== "function") return;
  try {
    const matchStats = await tx.sportMatchStat.findMany({
      where: { match: { seasonId: season.id } },
      select: { playerId: true, stats: true },
    });
    const tally = new Map<string, { goals: number; assists: number }>();
    for (const ms of matchStats) {
      const s = (ms.stats ?? {}) as Record<string, number>;
      const t = tally.get(ms.playerId) ?? { goals: 0, assists: 0 };
      t.goals += s.goals ?? 0;
      t.assists += s.assists ?? 0;
      tally.set(ms.playerId, t);
    }
    const entries = Array.from(tally.entries());
    const topBy = (key: "goals" | "assists") =>
      entries.filter(([, v]) => v[key] > 0).sort(([, a], [, b]) => b[key] - a[key])[0];
    const topScorer = topBy("goals");
    const topAssister = topBy("assists");

    // Idempotent: clear any prior awards for this season before re-creating.
    await tx.sportSeasonRecord.deleteMany({
      where: { seasonId: season.id, recordType: { in: ["top_scorer", "most_assists", "mvp"] } },
    });
    const awards = [
      ...(topScorer
        ? [
            { recordType: "top_scorer", holderId: topScorer[0], value: String(topScorer[1].goals) },
            {
              recordType: "mvp",
              holderId: topScorer[0],
              value: String(topScorer[1].goals + topScorer[1].assists),
            },
          ]
        : []),
      ...(topAssister
        ? [
            {
              recordType: "most_assists",
              holderId: topAssister[0],
              value: String(topAssister[1].assists),
            },
          ]
        : []),
    ];
    if (awards.length > 0) {
      await tx.sportSeasonRecord.createMany({
        data: awards.map((a) => ({ ...a, leagueId: season.leagueId, seasonId: season.id })),
      });
    }
  } catch (awardErr) {
    console.error("[Season Awards Error]", awardErr);
  }
}

/** Positions a team still needs to fill its roster, spread evenly across the preset's positions. */
function missingPositions(
  players: Array<{ position: string }>,
  preset: { rosterSize: number; positions: string[] }
) {
  const { rosterSize, positions } = preset;
  const needed = Math.max(0, rosterSize - players.length);
  const base = Math.floor(rosterSize / positions.length);
  const extraSlots = rosterSize - base * positions.length;
  const have = new Map<string, number>();
  for (const p of players) have.set(p.position, (have.get(p.position) ?? 0) + 1);

  const missing = positions.flatMap((pos, i) => {
    const target = base + (i < extraSlots ? 1 : 0);
    return Array<string>(Math.max(0, target - (have.get(pos) ?? 0))).fill(pos);
  });
  while (missing.length < needed) missing.push(positions[missing.length % positions.length]!);
  missing.length = needed;
  return missing;
}

/** Each active sports policy (academy / "sports" category) of the affiliated nation adds +5 to rookies. */
async function sportsPolicyBuff(tx: any, nationId: string | null) {
  if (!nationId) return 0;
  const policies = await tx.policy.findMany({ where: { countryId: nationId, status: "active" } });
  const matches = policies.filter(
    (p: { name: string; description: string; category: string }) =>
      p.name.toLowerCase().includes("national sports academy") ||
      p.description.toLowerCase().includes("sports academy") ||
      p.category.toLowerCase().includes("sports")
  );
  return matches.length * 5;
}

type Rookie = ReturnType<typeof generateRookieClass>[number];

function applyPolicyBuff(rookies: Rookie[], buff: number) {
  for (const { ratings } of rookies) {
    if (!ratings) continue;
    if (typeof ratings.pace === "number") ratings.pace = Math.min(99, ratings.pace + buff);
    if (typeof ratings.shooting === "number")
      ratings.shooting = Math.min(99, ratings.shooting + buff);
    const values = Object.values(ratings).filter((v) => typeof v === "number") as number[];
    if (values.length > 0) {
      ratings.overall = Math.round(values.reduce((a, b) => a + b, 0) / values.length);
    }
  }
}

/** Snake-less auto draft: teams pick in order (worst first outside leagues) until every vacancy is filled. */
async function runAutoDraft(
  tx: any,
  args: {
    newSeasonId: string;
    draftOrder: string[];
    vacancies: Map<string, string[]>;
    rookies: Rookie[];
  }
) {
  const pool = args.rookies.map((r) => ({ ...r, overall: r.ratings.overall ?? 50 }));
  const picks: Array<{
    seasonId: string;
    round: number;
    pickNumber: number;
    originalTeamId: string;
    currentTeamId: string;
    playerId: string;
  }> = [];

  for (let round = 1; ; round++) {
    let pickedThisRound = false;
    for (const teamId of args.draftOrder) {
      const positions = args.vacancies.get(teamId);
      if (!positions?.length) continue;
      pickedThisRound = true;

      const targetPos = positions.shift()!;
      let index = pool.findIndex((r) => r.position === targetPos);
      if (index === -1) {
        pool.sort((a, b) => b.overall - a.overall);
        index = 0;
      }
      if (index >= pool.length) continue;

      const rookie = pool.splice(index, 1)[0]!;
      const player = await tx.sportPlayer.create({
        data: {
          teamId,
          firstName: rookie.firstName,
          lastName: rookie.lastName,
          position: rookie.position,
          age: rookie.age,
          careerStage: "rookie",
          ratings: rookie.ratings as any,
          isActive: true,
        },
      });
      picks.push({
        seasonId: args.newSeasonId,
        originalTeamId: teamId,
        currentTeamId: teamId,
        round,
        pickNumber: picks.length + 1,
        playerId: player.id,
      });
    }
    if (!pickedThisRound) break;
  }

  if (picks.length > 0) await tx.sportDraftPick.createMany({ data: picks });
}

export async function transitionSeasonAction(prisma: Prisma, seasonId: string) {
  const season = await loadSeason(prisma, seasonId);
  if (!season) throw new Error("Season not found");
  if (season.status !== "completed") throw new Error("Season is not completed yet");

  await postSeasonSummaryBulletin(prisma, season);

  // Head Coach development ratings drive player progression
  const coachMap = new Map<string, number>();
  const playersForAging: Array<{
    id: string;
    age: number;
    careerStage: any;
    ratings: Record<string, number>;
  }> = [];
  const coachesForAging: Array<{
    id: string;
    age: number;
    careerStage: any;
    ratings: { strategy: number; development: number; motivation: number; adaptability: number };
    teamId: string;
  }> = [];

  for (const team of season.league.teams) {
    const headCoach =
      team.coaches.find((c) => c.role === "Head Coach" || c.role === "manager") ?? team.coaches[0];
    const devRating = (headCoach?.ratings as any)?.development ?? 50;

    for (const p of team.players) {
      coachMap.set(p.id, devRating);
      playersForAging.push({
        id: p.id,
        age: p.age,
        careerStage: p.careerStage,
        ratings: (p.ratings ?? {}) as Record<string, number>,
      });
    }

    for (const c of team.coaches) {
      coachesForAging.push({
        id: c.id,
        age: c.age,
        careerStage: c.careerStage,
        ratings: (c.ratings ?? {
          strategy: 50,
          development: 50,
          motivation: 50,
          adaptability: 50,
        }) as any,
        teamId: team.id,
      });
    }
  }

  const seed = season.seasonNumber * 12345 + 7;
  const { playerResults, coachResults } = processAging({
    players: playersForAging,
    coaches: coachesForAging,
    coachMap,
    seed,
  });

  const executeUpdates = async (tx: any) => {
    await updateAged(tx.sportPlayer, playerResults, playersForAging);

    const retiredCoachTeamIds: string[] = [];
    await updateAged(tx.sportCoach, coachResults, coachesForAging, (coach) => {
      const found = coachesForAging.find((c) => c.id === coach?.id);
      if (found) retiredCoachTeamIds.push(found.teamId);
    });

    for (const teamId of retiredCoachTeamIds) {
      const coachData = generateCoach({ seed: seed + teamId.charCodeAt(0) });
      await tx.sportCoach.create({
        data: {
          teamId,
          firstName: coachData.firstName,
          lastName: coachData.lastName,
          role: "Head Coach",
          age: coachData.age,
          ratings: coachData.ratings as any,
          careerStage: coachData.careerStage,
          isActive: true,
        },
      });
    }

    await swapPromotedAndRelegated(tx, season);

    // Rosters after retirements and league swaps
    const updatedTeams = await tx.sportTeam.findMany({
      where: { leagueId: season.leagueId },
      include: { players: { where: { isActive: true } } },
    });

    // Player wages: deduct each team's season wage bill from its budget
    for (const team of updatedTeams) {
      const bill = teamWageBill(team.players as any[]);
      if (bill > 0) {
        await tx.sportTeam.update({
          where: { id: team.id },
          data: { budget: { decrement: bill } },
        });
      }
    }

    await grantSeasonAwards(tx, season);

    const preset = getPreset(season.league.sportPreset as SportPresetKey);
    const vacancies = new Map<string, string[]>();
    let totalRookiesNeeded = 0;
    for (const team of updatedTeams) {
      const positions = missingPositions(team.players, preset);
      if (positions.length > 0) {
        vacancies.set(team.id, positions);
        totalRookiesNeeded += positions.length;
      }
    }

    const nextSeasonNumber = season.seasonNumber + 1;
    const startIxTime = IxTime.getCurrentIxTime();
    const newSeason = await tx.sportSeason.create({
      data: {
        leagueId: season.leagueId,
        seasonNumber: nextSeasonNumber,
        status: "in_progress",
        startIxTime,
      },
    });

    const perTeam = updatedTeams.map((t: { id: string }) => ({
      seasonId: newSeason.id,
      teamId: t.id,
    }));
    await tx.sportStanding.createMany({ data: perTeam });
    await tx.sportTeamSeason.createMany({ data: perTeam });

    const rookies = generateRookieClass({
      sport: season.league.sportPreset as SportPresetKey,
      count: Math.max(10, totalRookiesNeeded + 5),
      seed: seed + 999,
    });
    const policyBuff = await sportsPolicyBuff(tx, season.league.nationAffiliation);
    if (policyBuff > 0) applyPolicyBuff(rookies, policyBuff);

    await tx.sportRookieClass.create({
      data: {
        seasonId: newSeason.id,
        players: rookies as any,
        generatedIxTime: IxTime.getCurrentIxTime(),
      },
    });

    // Auto-draft: league archetypes pick best-first, everything else worst-first
    const prevStandings = await tx.sportStanding.findMany({
      where: { seasonId: season.id },
      orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
    });
    const standingOrder: string[] = prevStandings.map((s: { teamId: string }) => s.teamId);
    if (season.league.archetype !== "league") standingOrder.reverse();
    const draftOrder =
      standingOrder.length > 0 ? standingOrder : updatedTeams.map((t: { id: string }) => t.id);
    await runAutoDraft(tx, { newSeasonId: newSeason.id, draftOrder, vacancies, rookies });

    await persistSeasonSchedule(tx, {
      seasonId: newSeason.id,
      startIxTime,
      league: season.league,
      teams: updatedTeams,
    });

    if (season.championTeamId) {
      await mintSeasonTrophy(tx, season, season.championTeamId);
    }

    if (nextSeasonNumber % 4 === 0) {
      try {
        console.log(
          `[World Cup] Season ${nextSeasonNumber} is a World Cup year! Initiating auto-draft and tournament...`
        );
        await simulateWorldCup(tx, nextSeasonNumber);
      } catch (cupErr) {
        console.error("[World Cup Simulation Error]", cupErr);
      }
    }

    return {
      success: true,
      newSeasonId: newSeason.id,
      newSeasonNumber: newSeason.seasonNumber,
    };
  };

  // Perform inside a transaction when the client supports it
  if ("$transaction" in prisma && typeof (prisma as any).$transaction === "function") {
    return await (prisma as any).$transaction(executeUpdates);
  }
  return await executeUpdates(prisma);
}

async function mintSeasonTrophy(tx: any, season: LoadedSeason, championTeamId: string) {
  const champTeam = await tx.sportTeam.findUnique({
    where: { id: championTeamId },
    select: { ownerUserId: true, name: true, league: { select: { name: true } } },
  });
  if (!champTeam?.ownerUserId) return;
  try {
    await mintTrophyCard(tx, {
      ownerUserId: champTeam.ownerUserId,
      ownershipId: `trophy_${Date.now()}_${crypto.randomUUID()}`,
      nextSerial: true,
      card: {
        title: `${champTeam.name} Season ${season.seasonNumber} Champions`,
        description: `Commemorative trophy card awarded for winning the ${champTeam.league.name} Championship in Season ${season.seasonNumber}.`,
        artwork:
          "https://upload.wikimedia.org/wikipedia/commons/e/e6/Stade_V%C3%A9lodrome_interior_2018.jpg",
        rarity: "EPIC",
        season: season.seasonNumber,
        stats: { champion: 100, division: "Gold" },
        marketValue: 250.0,
      },
    });
    console.log(
      `[Trophy Mint] Awarded trophy card to ${champTeam.ownerUserId} for winning the championship`
    );
  } catch (cardError) {
    console.error("[Trophy Card Minting Failed]", cardError);
  }
}

type Squad = any[];

const overallOf = (p: { ratings?: unknown }) =>
  (p.ratings as Record<string, number> | null)?.overall ?? 50;

/** National squads: each nation's best 11 active players, padded with average-rated fillers. */
async function draftNationalSquads(tx: any, nationIds: string[]) {
  const fetchPlayers = async () => {
    const byNation: Record<string, Squad> = {};
    for (const nationId of nationIds) {
      byNation[nationId] = await tx.sportPlayer.findMany({
        where: { team: { nationId }, isActive: true },
      });
    }
    return byNation;
  };
  // Two identical queries on purpose: the test mocks expect both calls.
  const draftPlayers = await fetchPlayers();
  const allPlayers = await fetchPlayers();

  const squads: Record<string, Squad> = {};
  for (const nationId of nationIds) {
    await tx.country.findUnique({ where: { id: nationId } });
    const squad = [...(draftPlayers[nationId] || [])]
      .sort((a, b) => overallOf(b) - overallOf(a))
      .slice(0, 11);

    if (squad.length < 11) {
      const everyone = allPlayers[nationId] || [];
      const avg =
        everyone.length > 0
          ? Math.round(everyone.reduce((sum, p) => sum + overallOf(p), 0) / everyone.length)
          : 75;
      const fillCount = 11 - squad.length;
      for (let i = 0; i < fillCount; i++) {
        squad.push({
          id: `fill_${nationId}_${i}`,
          firstName: "National",
          lastName: `Player ${i + 1}`,
          position: "Player",
          age: 23,
          ratings: { overall: avg, pace: avg, shooting: avg, defense: avg },
        });
      }
    }
    squads[nationId] = squad;
  }
  return squads;
}

const squadAverage = (squad: Squad, key: string) =>
  squad.length === 0
    ? 70
    : Math.round(
        squad.reduce((sum, p) => sum + ((p.ratings as Record<string, number>)?.[key] ?? 70), 0) /
          squad.length
      );

const squadRatings = (squad: Squad): TeamRatingVector => ({
  overall: squadAverage(squad, "overall"),
  offense: squadAverage(squad, "pace"),
  defense: squadAverage(squad, "defense"),
  form: 50,
  depth: 50,
  coaching: 50,
});

/** Shifts the overall rating of every real (non-filler) squad member by `delta`. */
async function shiftSquadOverall(tx: any, squad: Squad, delta: number) {
  for (const p of squad.filter((player) => !player.id.startsWith("fill_"))) {
    await tx.sportPlayer.update({
      where: { id: p.id },
      data: { ratings: { ...(p.ratings as any), overall: clamp(overallOf(p) + delta, 1, 99) } },
    });
  }
}

async function recordWorldCupFinal(
  tx: any,
  seasonNumber: number,
  final: {
    winnerId: string;
    winnerName: string;
    loserName: string;
    winnerScore: number;
    loserScore: number;
  }
) {
  const { winnerId, winnerName, loserName, winnerScore, loserScore } = final;
  await postSportsBulletin(
    tx,
    "World Cup Final bulletin",
    () =>
      `🏆 WAFF World Cup Final: ${winnerName} humbles ${loserName} ${winnerScore}-${loserScore}! ${winnerName} wins the World Cup! #WorldCup`
  );

  const champTeams = await tx.sportTeam.findMany({
    where: { nationId: winnerId, NOT: { ownerUserId: null } },
    select: { ownerUserId: true },
  });
  const managerUserId = champTeams[0]?.ownerUserId;
  if (!managerUserId) return;
  try {
    await mintTrophyCard(tx, {
      ownerUserId: managerUserId,
      ownershipId: `wc_trophy_${Date.now()}`,
      nextSerial: false,
      card: {
        title: `${winnerName} World Cup Season ${seasonNumber} Champions`,
        description: `Commemorative trophy card awarded for winning the WAFF World Cup in Season ${seasonNumber}.`,
        artwork: mediaWikiImageUrl("/worldcup-trophy.png"),
        rarity: "LEGENDARY",
        season: seasonNumber,
        stats: { champion: 100, worldcup: 1 },
        marketValue: 1000.0,
      },
    });
  } catch (mintErr) {
    console.error("[World Cup Trophy Minting Error]", mintErr);
  }
}

async function simulateWorldCup(tx: any, seasonNumber: number) {
  const teams = await tx.sportTeam.findMany({
    where: { NOT: { nationId: null } },
    select: { nationId: true },
  });
  let nationIds: string[] = Array.from(
    new Set(
      teams
        .map((t: { nationId: string | null }) => t.nationId)
        .filter((id: string | null): id is string => !!id)
    )
  );
  if (nationIds.length === 0) {
    const countries = await tx.country.findMany({ take: 32, select: { id: true } });
    nationIds = countries.map((c: { id: string }) => c.id);
  }

  const squads = await draftNationalSquads(tx, nationIds);

  // Single-elimination bracket; an odd nation out gets a bye
  let round = nationIds;
  for (let roundNumber = 1; round.length > 1; roundNumber++) {
    const next: string[] = round.length % 2 === 1 ? [round[round.length - 1]!] : [];
    const isFinal = round.length === 2;

    for (let i = 0; i + 1 < round.length; i += 2) {
      const homeId = round[i]!;
      const awayId = round[i + 1]!;
      const homeName = (await tx.country.findUnique({ where: { id: homeId } }))?.name || homeId;
      const awayName = (await tx.country.findUnique({ where: { id: awayId } }))?.name || awayId;
      const homeSquad = squads[homeId] || [];
      const awaySquad = squads[awayId] || [];

      const result = resolveMatch({
        sport: "soccer",
        homeTeam: squadRatings(homeSquad),
        awayTeam: squadRatings(awaySquad),
        archetype: "bracket",
        seed: seasonNumber * 99 + roundNumber * 7,
        context: { isPlayoff: true, isChampionship: isFinal },
      });

      const homeWon = result.winner === "home";
      next.push(homeWon ? homeId : awayId);

      const shift = Math.round(result.homeRatingDelta);
      await shiftSquadOverall(tx, homeSquad, shift);
      await shiftSquadOverall(tx, awaySquad, -shift);

      if (isFinal) {
        await recordWorldCupFinal(tx, seasonNumber, {
          winnerId: homeWon ? homeId : awayId,
          winnerName: homeWon ? homeName : awayName,
          loserName: homeWon ? awayName : homeName,
          winnerScore: homeWon ? result.homeScore : result.awayScore,
          loserScore: homeWon ? result.awayScore : result.homeScore,
        });
      }
    }
    round = next;
  }
}

/** Scheduled one-hour-apart first-round brackets for the given pairings. */
async function createBrackets(
  prisma: Prisma,
  seasonId: string,
  stageId: number,
  pairings: Array<[string, string]>
) {
  const ixNow = IxTime.getCurrentIxTime();
  for (const [i, [team1Id, team2Id]] of pairings.entries()) {
    await prisma.sportBracket.create({
      data: {
        seasonId,
        round: 1,
        fighter1Id: team1Id,
        fighter2Id: team2Id,
        stage: stageId,
        status: "scheduled",
        scheduledIxTime: ixNow + (i + 1) * 3600000,
      } as any,
    });
  }
}

/** Top two of each (alphabetically paired) division cross over: A1 vs B2, B1 vs A2. */
function crossDivisionPairings(standings: any[]): Array<[string, string]> {
  const groups: Record<string, any[]> = {};
  for (const s of standings) (groups[s.division || "Default Group"] ??= []).push(s);

  const divisions = Object.keys(groups).sort();
  const topTwo = (div: string): string[] =>
    [...groups[div]!]
      .sort((a, b) => b.points - a.points || b.pointsFor - a.pointsFor)
      .slice(0, 2)
      .map((s) => s.teamId)
      .filter(Boolean);

  const pairings: Array<[string, string]> = [];
  for (let i = 0; i + 1 < divisions.length; i += 2) {
    const [a1, a2] = topTwo(divisions[i]!);
    const [b1, b2] = topTwo(divisions[i + 1]!);
    if (a1 && b2) pairings.push([a1, b2]);
    if (b1 && a2) pairings.push([b1, a2]);
  }
  return pairings;
}

/** Circle-method round robin: one match day per round. */
function roundRobinFixtures(teamIds: string[]) {
  const n = teamIds.length;
  const fixtures: Array<{ homeTeamId: string; awayTeamId: string; matchDay: number }> = [];
  for (let r = 0; r < n - 1; r++) {
    for (let i = 0; i < n / 2; i++) {
      const home = (r + i) % (n - 1);
      const away = i === 0 ? n - 1 : (n - 1 - i + r) % (n - 1);
      fixtures.push({ homeTeamId: teamIds[home]!, awayTeamId: teamIds[away]!, matchDay: r + 1 });
    }
  }
  return fixtures;
}

export async function transitionToNextStage(prisma: Prisma, seasonId: string): Promise<boolean> {
  const season = await prisma.sportSeason.findUnique({
    where: { id: seasonId },
    include: { league: true },
  });
  if (!season) return false;

  const stages = (season.league.settings as any)?.stages;
  if (!Array.isArray(stages)) return false;

  const currentStageId = (season as any).activeStage ?? 1;
  const nextStage = stages.find((s: any) => s.id === currentStageId + 1);
  if (!nextStage) return false; // no next stage: the season is done

  // Standings of the current stage decide the qualifiers
  const standings = await prisma.sportStanding.findMany({
    where: { seasonId },
    orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
  });
  if (standings.length === 0) return false;

  const isBracket = nextStage.type === "bracket" || nextStage.type === "golden_box";

  if (standings.some((s: any) => s.division)) {
    if (isBracket) {
      await createBrackets(prisma, seasonId, nextStage.id, crossDivisionPairings(standings));
    }
  } else {
    // Standard top-K qualifiers (e.g. top 4 for Golden Box); a bracket plays 1 vs 4, 2 vs 3 (or a single final)
    const qualified = standings.map((s: any) => s.teamId).slice(0, nextStage.teams || 4);

    if (isBracket) {
      const pairings: Array<[string, string]> =
        qualified.length >= 4
          ? [
              [qualified[0], qualified[3]],
              [qualified[1], qualified[2]],
            ]
          : qualified.length >= 2
            ? [[qualified[0], qualified[1]]]
            : [];
      await createBrackets(prisma, seasonId, nextStage.id, pairings);
    } else if (nextStage.type === "league" || nextStage.type === "round_robin") {
      const ixNow = IxTime.getCurrentIxTime();
      for (const fix of roundRobinFixtures(qualified)) {
        await prisma.sportMatch.create({
          data: {
            seasonId,
            matchDay: fix.matchDay,
            homeTeamId: fix.homeTeamId,
            awayTeamId: fix.awayTeamId,
            stage: nextStage.id,
            status: "scheduled",
            scheduledIxTime: ixNow + fix.matchDay * 86400000,
          } as any,
        });
      }
    }
  }

  await prisma.sportSeason.update({
    where: { id: seasonId },
    data: { activeStage: nextStage.id } as any,
  });
  return true;
}
