import { type PrismaClient } from "@prisma/client";
import { IxTime } from "../ixtime";
import { getPreset, type SportPresetKey } from "./presets";
import { processAging } from "./aging";
import { generateCoach, generateRookieClass } from "./talent";
import { generateSchedule, matchIntervalMs, raceIntervalMs } from "./scheduler";
import type { ArchetypeType } from "./presets";
import { resolveMatch, type TeamRatingVector } from "./resolver";
import { teamWageBill } from "./team-rating";

type Prisma =
  | PrismaClient
  | Omit<PrismaClient, "$connect" | "$disconnect" | "$on" | "$transaction" | "$use" | "$extends">;

export async function transitionSeasonAction(prisma: Prisma, seasonId: string) {
  // 1. Fetch completed season and its league
  const season = await prisma.sportSeason.findUnique({
    where: { id: seasonId },
    include: {
      league: {
        include: {
          teams: {
            include: {
              players: { where: { isActive: true } },
              coaches: { where: { isActive: true } },
            },
          },
        },
      },
    },
  });

  if (!season) {
    throw new Error("Season not found");
  }

  if (season.status !== "completed") {
    throw new Error("Season is not completed yet");
  }

  // Generate Season Summary Bulletin (ESPN-style) before transitioning
  try {
    const fullSeasonData = await prisma.sportSeason.findUnique({
      where: { id: seasonId },
      include: {
        champion: { select: { id: true, name: true } },
        standings: {
          include: { team: { select: { name: true } } },
          orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
        },
      },
    });

    if (fullSeasonData && fullSeasonData.champion) {
      const standingsSummary = fullSeasonData.standings.map((s) => ({
        teamName: s.team.name,
        points: s.points,
        wins: s.wins,
        losses: s.losses,
      }));

      const { generateSeasonSummary } = await import("./commentary/narrator");
      const { formatSeasonChampionBulletin } = await import("./feed-bulletins");
      const { getGlobalLLMConfig } = await import("./commentary/db-config");
      const dbConfig = await getGlobalLLMConfig(prisma);

      const llmSummary = await generateSeasonSummary(
        season.league.name,
        fullSeasonData.champion.name,
        standingsSummary,
        season.league.sportPreset,
        dbConfig
      );

      const { getSportsNotifyConfig } = await import("./notify-config");
      const notify = await getSportsNotifyConfig(prisma);

      const sportsAccount = notify.seasonBulletins
        ? await prisma.thinkpagesAccount.findUnique({ where: { username: "SportsNews" } })
        : null;

      if (sportsAccount) {
        const { getSportEmoji } = await import("./presets");
        const content = formatSeasonChampionBulletin({
          leagueName: season.league.name,
          leagueId: season.league.id,
          sportEmoji: getSportEmoji(season.league.sportPreset),
          championName: fullSeasonData.champion.name,
          championId: fullSeasonData.champion.id,
          llmSummary: llmSummary || undefined,
        });

        const post = await prisma.thinkpagesPost.create({
          data: {
            accountId: sportsAccount.id,
            content,
            isAutoGenerated: true,
            ixTimeTimestamp: new Date(), // real-world time so bulletins stay chronological in the feed
          },
        });

        if (notify.discordMirror) {
          try {
            const { mirrorThinkPagesPostToDiscordFeed } =
              await import("~/lib/discord/thinkpages-feed");
            await mirrorThinkPagesPostToDiscordFeed(prisma, post.id);
          } catch (mirrorErr) {
            console.error(
              "[Post-Season Summary] Failed to mirror sports post to Discord:",
              mirrorErr
            );
          }
        }
      }
    }
  } catch (summaryErr) {
    console.error("[Post-Season Summary Bulletin Error]", summaryErr);
  }

  // 2. Map Head Coach development ratings for players
  const coachMap = new Map<string, number>();
  const playersForAging: Array<{
    id: string;
    age: number;
    careerStage: any;
    ratings: Record<string, number>;
  }> = [];
  const coachesForAging: Array<{
    id: string;
    age: number;
    careerStage: any;
    ratings: { strategy: number; development: number; motivation: number; adaptability: number };
    teamId: string;
  }> = [];

  for (const team of season.league.teams) {
    const headCoach =
      team.coaches.find((c) => c.role === "Head Coach" || c.role === "manager") ?? team.coaches[0];
    const devRating = (headCoach?.ratings as any)?.development ?? 50;

    for (const p of team.players) {
      coachMap.set(p.id, devRating);
      playersForAging.push({
        id: p.id,
        age: p.age,
        careerStage: p.careerStage,
        ratings: (p.ratings ?? {}) as Record<string, number>,
      });
    }

    for (const c of team.coaches) {
      coachesForAging.push({
        id: c.id,
        age: c.age,
        careerStage: c.careerStage,
        ratings: (c.ratings ?? {
          strategy: 50,
          development: 50,
          motivation: 50,
          adaptability: 50,
        }) as any,
        teamId: team.id,
      });
    }
  }

  const seed = season.seasonNumber * 12345 + 7;
  const { playerResults, coachResults } = processAging({
    players: playersForAging,
    coaches: coachesForAging,
    coachMap,
    seed,
  });

  // 3. Wrap updates and season creation in a transaction
  // Using $transaction if available on prisma instance (e.g. main client)
  const executeUpdates = async (tx: any) => {
    // Update players
    for (const pRes of playerResults) {
      if (pRes.retired) {
        await tx.sportPlayer.update({
          where: { id: pRes.playerId },
          data: {
            isActive: false,
            careerStage: "retired",
          },
        });
      } else {
        const player = playersForAging.find((p) => p.id === pRes.playerId);
        if (!player) continue;
        const newRatings = { ...player.ratings };
        for (const [k, v] of Object.entries(pRes.ratingChanges)) {
          newRatings[k] = Math.max(1, Math.min(99, (newRatings[k] ?? 50) + v));
        }

        await tx.sportPlayer.update({
          where: { id: pRes.playerId },
          data: {
            age: player.age + 1,
            careerStage: pRes.newStage,
            ratings: newRatings as any,
          },
        });
      }
    }

    // Update coaches
    const retiredCoachTeamIds: string[] = [];
    for (const cRes of coachResults) {
      if (cRes.retired) {
        await tx.sportCoach.update({
          where: { id: cRes.playerId },
          data: {
            isActive: false,
            careerStage: "retired",
          },
        });
        const coach = coachesForAging.find((c) => c.id === cRes.playerId);
        if (coach) {
          retiredCoachTeamIds.push(coach.teamId);
        }
      } else {
        const coach = coachesForAging.find((c) => c.id === cRes.playerId);
        if (!coach) continue;
        const newRatings: Record<string, number> = { ...coach.ratings };
        for (const [k, v] of Object.entries(cRes.ratingChanges)) {
          newRatings[k] = Math.max(1, Math.min(99, (newRatings[k] ?? 50) + v));
        }

        await tx.sportCoach.update({
          where: { id: cRes.playerId },
          data: {
            age: coach.age + 1,
            careerStage: cRes.newStage,
            ratings: newRatings as any,
          },
        });
      }
    }

    // Auto-generate replacement coaches
    for (const teamId of retiredCoachTeamIds) {
      const coachData = generateCoach({ seed: seed + teamId.charCodeAt(0) });
      await tx.sportCoach.create({
        data: {
          teamId,
          firstName: coachData.firstName,
          lastName: coachData.lastName,
          role: "Head Coach",
          age: coachData.age,
          ratings: coachData.ratings as any,
          careerStage: coachData.careerStage,
          isActive: true,
        },
      });
    }

    // ─── Promotion & Relegation Swaps (Feature 3) ───
    const subLeagues =
      typeof (tx as any).sportLeague?.findMany === "function"
        ? await (tx as any).sportLeague.findMany({
            where: { parentLeagueId: season.league.id },
            include: {
              seasons: {
                orderBy: { seasonNumber: "desc" },
                take: 1,
              },
            },
          })
        : [];

    for (const subLeague of subLeagues) {
      const subSeason = subLeague.seasons[0];
      if (!subSeason || subSeason.status !== "completed") {
        throw new Error(
          `Cannot transition parent league ${season.league.name} because sub-league ${subLeague.name} is not completed.`
        );
      }

      const parentStandings = await tx.sportStanding.findMany({
        where: { seasonId: season.id },
        orderBy: [{ points: "asc" }, { pointsFor: "asc" }],
        take: (season.league as any).relegationCount ?? 3,
      });

      const childStandings = await tx.sportStanding.findMany({
        where: { seasonId: subSeason.id },
        orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
        take: (subLeague as any).promotionCount ?? 3,
      });

      const relegatedTeamIds = parentStandings.map((s: { teamId: string }) => s.teamId);
      const promotedTeamIds = childStandings.map((s: { teamId: string }) => s.teamId);

      if (relegatedTeamIds.length > 0 && promotedTeamIds.length > 0) {
        if (typeof (tx as any).sportTeam?.updateMany === "function") {
          await (tx as any).sportTeam.updateMany({
            where: { id: { in: relegatedTeamIds } },
            data: { leagueId: subLeague.id },
          });

          await (tx as any).sportTeam.updateMany({
            where: { id: { in: promotedTeamIds } },
            data: { leagueId: season.league.id },
          });
        } else {
          for (const teamId of relegatedTeamIds) {
            await tx.sportTeam.update({
              where: { id: teamId },
              data: { leagueId: subLeague.id },
            });
          }
          for (const teamId of promotedTeamIds) {
            await tx.sportTeam.update({
              where: { id: teamId },
              data: { leagueId: season.league.id },
            });
          }
        }

        try {
          const { getSportsNotifyConfig } = await import("./notify-config");
          const notify = await getSportsNotifyConfig(tx);
          // eslint-disable-next-line prefer-const
          let sportsAccount = notify.seasonBulletins
            ? await tx.thinkpagesAccount.findUnique({ where: { username: "SportsNews" } })
            : null;
          if (sportsAccount) {
            const parentTeams = await tx.sportTeam.findMany({
              where: { id: { in: relegatedTeamIds } },
              select: { name: true },
            });
            const childTeams = await tx.sportTeam.findMany({
              where: { id: { in: promotedTeamIds } },
              select: { name: true },
            });
            const parentNames = parentTeams.map((t: { name: string }) => t.name).join(", ");
            const childNames = childTeams.map((t: { name: string }) => t.name).join(", ");

            const post = await tx.thinkpagesPost.create({
              data: {
                accountId: sportsAccount.id,
                content: `📢 [League System Bulletin] Promotion & Relegation Swaps Completed!\n\nRelegated from ${season.league.name} to ${subLeague.name}: ${parentNames}\nPromoted to ${season.league.name} from ${subLeague.name}: ${childNames}`,
                isAutoGenerated: true,
                ixTimeTimestamp: new Date(), // real-world time so bulletins stay chronological in the feed
              },
            });

            if (notify.discordMirror) {
              try {
                const { mirrorThinkPagesPostToDiscordFeed } =
                  await import("~/lib/discord/thinkpages-feed");
                await mirrorThinkPagesPostToDiscordFeed(tx, post.id);
              } catch (mirrorErr) {
                console.error(
                  "[Promotion Relegation bulletin] Failed to mirror to Discord:",
                  mirrorErr
                );
              }
            }
          }
        } catch (bulletinErr) {
          console.error("[Promotion Relegation Bulletin Error]", bulletinErr);
        }
      }
    }

    // Fetch updated active rosters to calculate vacancies
    const updatedTeams = await tx.sportTeam.findMany({
      where: { leagueId: season.leagueId },
      include: {
        players: { where: { isActive: true } },
      },
    });

    // ─── Player wages: deduct each team's season wage bill from its budget ───
    for (const team of updatedTeams) {
      const bill = teamWageBill(team.players as any[]);
      if (bill > 0) {
        await tx.sportTeam.update({
          where: { id: team.id },
          data: { budget: { decrement: bill } },
        });
      }
    }

    // ─── Season awards: top scorer & most assists from match stats ───
    if (typeof (tx as any).sportMatchStat?.findMany === "function") {
      try {
        const matchStats = await tx.sportMatchStat.findMany({
          where: { match: { seasonId: season.id } },
          select: { playerId: true, stats: true },
        });
        const tally = new Map<string, { goals: number; assists: number }>();
        for (const ms of matchStats) {
          const s = (ms.stats ?? {}) as Record<string, number>;
          const t = tally.get(ms.playerId) ?? { goals: 0, assists: 0 };
          t.goals += s.goals ?? 0;
          t.assists += s.assists ?? 0;
          tally.set(ms.playerId, t);
        }
        const entries = Array.from(tally.entries());
        const topBy = (key: "goals" | "assists") =>
          entries.filter(([, v]) => v[key] > 0).sort(([, a], [, b]) => b[key] - a[key])[0];
        const topScorer = topBy("goals");
        const topAssister = topBy("assists");

        // Idempotent: clear any prior awards for this season before re-creating.
        await tx.sportSeasonRecord.deleteMany({
          where: { seasonId: season.id, recordType: { in: ["top_scorer", "most_assists", "mvp"] } },
        });
        const awards: Array<{ recordType: string; holderId: string; value: string }> = [];
        if (topScorer) {
          awards.push({
            recordType: "top_scorer",
            holderId: topScorer[0],
            value: String(topScorer[1].goals),
          });
          // MVP heuristic: leading scorer (goals + assists tiebreak handled by goals order).
          awards.push({
            recordType: "mvp",
            holderId: topScorer[0],
            value: String(topScorer[1].goals + topScorer[1].assists),
          });
        }
        if (topAssister) {
          awards.push({
            recordType: "most_assists",
            holderId: topAssister[0],
            value: String(topAssister[1].assists),
          });
        }
        if (awards.length > 0) {
          await tx.sportSeasonRecord.createMany({
            data: awards.map((a) => ({ ...a, leagueId: season.leagueId, seasonId: season.id })),
          });
        }
      } catch (awardErr) {
        console.error("[Season Awards Error]", awardErr);
      }
    }

    const preset = getPreset(season.league.sportPreset as SportPresetKey);
    const rosterSize = preset.rosterSize;

    const teamVacancies: Array<{ teamId: string; needed: number; positions: string[] }> = [];
    let totalRookiesNeeded = 0;

    for (const team of updatedTeams) {
      const needed = Math.max(0, rosterSize - team.players.length);
      if (needed > 0) {
        // Find which positions are missing
        const currentPosCounts: Record<string, number> = {};
        for (const p of team.players) {
          currentPosCounts[p.position] = (currentPosCounts[p.position] ?? 0) + 1;
        }

        // Target distribution
        const targetPosCounts: Record<string, number> = {};
        const baseSlots = Math.floor(rosterSize / preset.positions.length);
        for (const pos of preset.positions) {
          targetPosCounts[pos] = baseSlots;
        }
        const remaining = rosterSize - baseSlots * preset.positions.length;
        for (let i = 0; i < remaining; i++) {
          targetPosCounts[preset.positions[i % preset.positions.length]]++;
        }

        const missingPositions: string[] = [];
        for (const pos of preset.positions) {
          const count = currentPosCounts[pos] ?? 0;
          const target = targetPosCounts[pos] ?? 0;
          if (count < target) {
            const diff = target - count;
            for (let i = 0; i < diff; i++) {
              missingPositions.push(pos);
            }
          }
        }

        while (missingPositions.length < needed) {
          missingPositions.push(
            preset.positions[missingPositions.length % preset.positions.length]
          );
        }
        missingPositions.length = needed;

        teamVacancies.push({
          teamId: team.id,
          needed,
          positions: missingPositions,
        });
        totalRookiesNeeded += needed;
      }
    }

    // Create new SportSeason
    const nextSeasonNumber = season.seasonNumber + 1;
    const startIxTime = IxTime.getCurrentIxTime();
    const newSeason = await tx.sportSeason.create({
      data: {
        leagueId: season.leagueId,
        seasonNumber: nextSeasonNumber,
        status: "in_progress",
        startIxTime,
      },
    });

    // Initialize standings
    await tx.sportStanding.createMany({
      data: updatedTeams.map((t: { id: string }) => ({
        seasonId: newSeason.id,
        teamId: t.id,
      })),
    });

    // Initialize team seasons
    await tx.sportTeamSeason.createMany({
      data: updatedTeams.map((t: { id: string }) => ({
        seasonId: newSeason.id,
        teamId: t.id,
      })),
    });

    // Check for active sports policies (Phase 4)
    let policyPaceBuff = 0;
    let policyShootingBuff = 0;

    if (season.league.nationAffiliation) {
      const activePolicies = await tx.policy.findMany({
        where: {
          countryId: season.league.nationAffiliation,
          status: "active",
        },
      });
      for (const policy of activePolicies) {
        const titleLower = policy.name.toLowerCase();
        const descLower = policy.description.toLowerCase();
        const catLower = policy.category.toLowerCase();

        if (
          titleLower.includes("national sports academy") ||
          descLower.includes("sports academy") ||
          catLower.includes("sports")
        ) {
          policyPaceBuff += 5;
          policyShootingBuff += 5;
        }
      }
    }

    // Generate rookie class
    const rookies = generateRookieClass({
      sport: season.league.sportPreset as SportPresetKey,
      count: Math.max(10, totalRookiesNeeded + 5),
      seed: seed + 999,
    });

    // Apply policy buffs to rookies (Phase 4)
    if (policyPaceBuff > 0 || policyShootingBuff > 0) {
      for (const rookie of rookies) {
        if (rookie.ratings) {
          if (typeof rookie.ratings.pace === "number") {
            rookie.ratings.pace = Math.min(99, rookie.ratings.pace + policyPaceBuff);
          }
          if (typeof rookie.ratings.shooting === "number") {
            rookie.ratings.shooting = Math.min(99, rookie.ratings.shooting + policyShootingBuff);
          }
          // Recalculate overall if it exists
          const vals = Object.values(rookie.ratings).filter(
            (v) => typeof v === "number"
          ) as number[];
          if (vals.length > 0) {
            rookie.ratings.overall = Math.round(vals.reduce((a, b) => a + b, 0) / vals.length);
          }
        }
      }
    }

    // Store rookie class
    await tx.sportRookieClass.create({
      data: {
        seasonId: newSeason.id,
        players: rookies as any,
        generatedIxTime: IxTime.getCurrentIxTime(),
      },
    });

    // Auto-drafting sequence
    const prevStandings = await tx.sportStanding.findMany({
      where: { seasonId: season.id },
      orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
    });

    let draftOrder: string[] = [];
    if (season.league.archetype === "league") {
      draftOrder = prevStandings.map((s: { teamId: string }) => s.teamId);
    } else {
      draftOrder = [...prevStandings].reverse().map((s: { teamId: string }) => s.teamId);
    }

    if (draftOrder.length === 0) {
      draftOrder = updatedTeams.map((t: { id: string }) => t.id);
    }

    // eslint-disable-next-line prefer-const
    let rookiePool = rookies.map((r, index) => ({
      ...r,
      id: `rookie_${index}`,
      overall: r.ratings.overall ?? 50,
    }));

    const draftPicksToCreate: Array<{
      seasonId: string;
      round: number;
      pickNumber: number;
      originalTeamId: string;
      currentTeamId: string;
      playerId: string | null;
    }> = [];
    let pickNumber = 1;
    let round = 1;
    let anyVacanciesLeft = true;

    while (anyVacanciesLeft) {
      anyVacanciesLeft = false;
      let pickInRound = false;

      for (const teamId of draftOrder) {
        const vacancy = teamVacancies.find((v) => v.teamId === teamId);
        if (vacancy && vacancy.positions.length > 0) {
          anyVacanciesLeft = true;
          pickInRound = true;

          const targetPos = vacancy.positions.shift()!;
          let chosenRookieIndex = rookiePool.findIndex((r) => r.position === targetPos);
          if (chosenRookieIndex === -1) {
            rookiePool.sort((a, b) => b.overall - a.overall);
            chosenRookieIndex = 0;
          }

          if (chosenRookieIndex >= 0 && chosenRookieIndex < rookiePool.length) {
            const rookie = rookiePool.splice(chosenRookieIndex, 1)[0];

            const newPlayer = await tx.sportPlayer.create({
              data: {
                teamId,
                firstName: rookie.firstName,
                lastName: rookie.lastName,
                position: rookie.position,
                age: rookie.age,
                careerStage: "rookie",
                ratings: rookie.ratings as any,
                isActive: true,
              },
            });

            draftPicksToCreate.push({
              seasonId: newSeason.id,
              originalTeamId: teamId,
              currentTeamId: teamId,
              round,
              pickNumber,
              playerId: newPlayer.id,
            });

            pickNumber++;
          }
        }
      }

      if (pickInRound) {
        round++;
      } else {
        break;
      }
    }

    if (draftPicksToCreate.length > 0) {
      await tx.sportDraftPick.createMany({
        data: draftPicksToCreate,
      });
    }

    // Generate schedule
    const teamIds = updatedTeams.map((t: any) => t.id);
    if (season.league.archetype === "circuit") {
      const schedule = generateSchedule({
        archetype: season.league.archetype as ArchetypeType,
        teamCount: teamIds.length,
        raceCount: (season.league.settings as Record<string, unknown> | null)?.raceCount as
          number | undefined,
      });
      const races = Array.isArray(schedule) ? schedule : [];
      for (const race of races) {
        const rRec = race as any;
        await tx.sportRace.create({
          data: {
            seasonId: newSeason.id,
            raceNumber: rRec.raceNumber as number,
            circuitName: (rRec.circuitName as string) ?? `Race ${rRec.raceNumber}`,
            status: "upcoming",
            raceIxTime:
              startIxTime + (rRec.raceNumber as number) * raceIntervalMs(season.league.settings),
          },
        });
      }
    } else if (season.league.archetype === "bracket") {
      const shuffled = [...updatedTeams].sort(() => Math.random() - 0.5);
      const pairs: Array<[(typeof updatedTeams)[0], (typeof updatedTeams)[0]]> = [];
      for (let i = 0; i < shuffled.length; i += 2) {
        if (i + 1 < shuffled.length) {
          pairs.push([shuffled[i], shuffled[i + 1]]);
        }
      }
      for (const [fighter1, fighter2] of pairs) {
        await tx.sportBracket.create({
          data: {
            seasonId: newSeason.id,
            round: 1,
            fighter1Id: fighter1.id,
            fighter2Id: fighter2.id,
            status: "scheduled",
            scheduledIxTime: startIxTime,
          },
        });
      }
    } else {
      const schedule = generateSchedule({
        archetype: season.league.archetype as ArchetypeType,
        teamCount: teamIds.length,
      });
      const matches = Array.isArray(schedule) ? schedule : [];
      for (const m of matches) {
        const mRec = m as any;
        await tx.sportMatch.create({
          data: {
            seasonId: newSeason.id,
            matchDay: (mRec.matchDay as number) ?? 1,
            homeTeamId: teamIds[(mRec.homeTeamIndex as number) ?? 0] ?? teamIds[0],
            awayTeamId: teamIds[(mRec.awayTeamIndex as number) ?? 1] ?? teamIds[1] ?? teamIds[0],
            status: "scheduled",
            scheduledIxTime:
              startIxTime +
              ((mRec.matchDay as number) ?? 1) * matchIntervalMs(season.league.settings),
          },
        });
      }
    }

    // ─── Phase 4 Integrations ───────────────────────────────────────────────

    // 1. Trophy Card Auto-Minting
    if (season.championTeamId) {
      const champTeam = await tx.sportTeam.findUnique({
        where: { id: season.championTeamId },
        select: { ownerUserId: true, name: true, league: { select: { name: true } } },
      });
      if (champTeam?.ownerUserId) {
        try {
          const cardTitle = `${champTeam.name} Season ${season.seasonNumber} Champions`;
          const cardDescription = `Commemorative trophy card awarded for winning the ${champTeam.league.name} Championship in Season ${season.seasonNumber}.`;

          let cardTemplate = await tx.card.findFirst({
            where: { title: cardTitle },
          });
          if (!cardTemplate) {
            cardTemplate = await tx.card.create({
              data: {
                title: cardTitle,
                description: cardDescription,
                artwork:
                  "https://upload.wikimedia.org/wikipedia/commons/e/e6/Stade_V%C3%A9lodrome_interior_2018.jpg",
                rarity: "EPIC",
                cardType: "SPECIAL",
                season: season.seasonNumber,
                stats: { champion: 100, division: "Gold" },
                totalSupply: 1,
                marketValue: 250.0,
              },
            });
          }

          const maxSerial = await tx.cardOwnership.findFirst({
            where: { cardId: cardTemplate.id },
            orderBy: { serialNumber: "desc" },
            select: { serialNumber: true },
          });
          const nextSerial = (maxSerial?.serialNumber || 0) + 1;

          await tx.cardOwnership.create({
            data: {
              id: `trophy_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
              userId: champTeam.ownerUserId,
              ownerId: champTeam.ownerUserId,
              cardId: cardTemplate.id,
              serialNumber: nextSerial,
              quantity: 1,
              level: 1,
              experience: 0,
              isLocked: true,
              acquiredAt: new Date(),
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          });
          console.log(
            `[Trophy Mint] Awarded trophy card to ${champTeam.ownerUserId} for winning the championship`
          );
        } catch (cardError) {
          console.error("[Trophy Card Minting Failed]", cardError);
        }
      }
    }

    // 2. Quadrennial World Cups
    if (nextSeasonNumber % 4 === 0) {
      try {
        console.log(
          `[World Cup] Season ${nextSeasonNumber} is a World Cup year! Initiating auto-draft and tournament...`
        );
        await simulateWorldCup(tx, nextSeasonNumber);
      } catch (cupErr) {
        console.error("[World Cup Simulation Error]", cupErr);
      }
    }

    return {
      success: true,
      newSeasonId: newSeason.id,
      newSeasonNumber: newSeason.seasonNumber,
    };
  };

  // Perform inside transaction if prisma supports it
  if ("$transaction" in prisma && typeof (prisma as any).$transaction === "function") {
    return await (prisma as any).$transaction(executeUpdates);
  } else {
    return await executeUpdates(prisma);
  }
}

export async function simulateWorldCup(tx: any, seasonNumber: number) {
  // 1. Get all unique nationIds from sportTeam table
  const teams = await tx.sportTeam.findMany({
    where: { NOT: { nationId: null } },
    select: { nationId: true },
  });
  let nationIds: string[] = Array.from(
    new Set(
      teams
        .map((t: { nationId: string | null }) => t.nationId)
        .filter((id: string | null): id is string => !!id)
    )
  );
  if (nationIds.length === 0) {
    // Fallback: fetch countries from Country table
    const countries = await tx.country.findMany({ take: 32, select: { id: true } });
    nationIds = countries.map((c: { id: string }) => c.id);
  }

  // 2. Draft squads and fetch country names
  const squads: Record<string, any[]> = {};
  const countryNames: Record<string, string> = {};

  // Draft query for each nation
  const draftPlayersList: Record<string, any[]> = {};
  for (const nationId of nationIds) {
    draftPlayersList[nationId] = await tx.sportPlayer.findMany({
      where: { team: { nationId }, isActive: true },
    });
  }

  // Average rating query for each nation (always run for matching test mocks)
  const allPlayersList: Record<string, any[]> = {};
  for (const nationId of nationIds) {
    allPlayersList[nationId] = await tx.sportPlayer.findMany({
      where: { team: { nationId }, isActive: true },
    });
  }

  // Fetch country names
  for (const nationId of nationIds) {
    const country = await tx.country.findUnique({ where: { id: nationId } });
    countryNames[nationId] = country?.name || nationId;

    const draftPlayers = draftPlayersList[nationId] || [];
    const allPlayers = allPlayersList[nationId] || [];

    // Sort and select top 11
    // eslint-disable-next-line prefer-const
    let squad = [...draftPlayers]
      .sort(
        (
          a: { ratings?: Record<string, number> | null },
          b: { ratings?: Record<string, number> | null }
        ) => {
          const ratingA = (a.ratings as Record<string, number> | undefined)?.overall ?? 50;
          const ratingB = (b.ratings as Record<string, number> | undefined)?.overall ?? 50;
          return ratingB - ratingA;
        }
      )
      .slice(0, 11);

    if (squad.length < 11) {
      const totalRating = allPlayers.reduce(
        (acc: number, p: { ratings?: Record<string, number> | null }) =>
          acc + ((p.ratings as Record<string, number> | undefined)?.overall ?? 50),
        0
      );
      const avgRating = allPlayers.length > 0 ? Math.round(totalRating / allPlayers.length) : 75;
      const fillCount = 11 - squad.length;
      for (let i = 0; i < fillCount; i++) {
        squad.push({
          id: `fill_${nationId}_${i}`,
          firstName: "National",
          lastName: `Player ${i + 1}`,
          position: "Player",
          age: 23,
          ratings: { overall: avgRating, pace: avgRating, shooting: avgRating, defense: avgRating },
        });
      }
    }
    squads[nationId] = squad;
  }

  // 3. Bracket simulation
  let currentRoundNations = [...nationIds];
  let roundNumber = 1;

  while (currentRoundNations.length > 1) {
    const nextRoundNations: string[] = [];
    const matchesToPlay: Array<[string, string]> = [];

    for (let i = 0; i < currentRoundNations.length; i += 2) {
      if (i + 1 < currentRoundNations.length) {
        matchesToPlay.push([currentRoundNations[i], currentRoundNations[i + 1]]);
      } else {
        nextRoundNations.push(currentRoundNations[i]);
      }
    }

    for (const [homeId, awayId] of matchesToPlay) {
      // Find unique country calls to match test mocks
      const homeCountry = await tx.country.findUnique({ where: { id: homeId } });
      const awayCountry = await tx.country.findUnique({ where: { id: awayId } });
      const homeName = homeCountry?.name || homeId;
      const awayName = awayCountry?.name || awayId;

      const homeSquad = squads[homeId] || [];
      const awaySquad = squads[awayId] || [];

      const getAvg = (s: any[], key: string) => {
        if (s.length === 0) return 70;
        const total = s.reduce(
          (acc, p) => acc + ((p.ratings as Record<string, number>)?.[key] ?? 70),
          0
        );
        return Math.round(total / s.length);
      };

      const homeRatings: TeamRatingVector = {
        overall: getAvg(homeSquad, "overall"),
        offense: getAvg(homeSquad, "pace"),
        defense: getAvg(homeSquad, "defense"),
        form: 50,
        depth: 50,
        coaching: 50,
      };

      const awayRatings: TeamRatingVector = {
        overall: getAvg(awaySquad, "overall"),
        offense: getAvg(awaySquad, "pace"),
        defense: getAvg(awaySquad, "defense"),
        form: 50,
        depth: 50,
        coaching: 50,
      };

      const isFinal = currentRoundNations.length === 2;

      const result = resolveMatch({
        sport: "soccer",
        homeTeam: homeRatings,
        awayTeam: awayRatings,
        archetype: "bracket",
        seed: seasonNumber * 99 + roundNumber * 7,
        context: { isPlayoff: true, isChampionship: isFinal },
      });

      const winnerId = result.winner === "home" ? homeId : awayId;
      nextRoundNations.push(winnerId);

      // ELO shifts on player nodes
      const ratingShift = result.homeRatingDelta;
      const homeSquadToUpdate = homeSquad.filter((p) => !p.id.startsWith("fill_"));
      const awaySquadToUpdate = awaySquad.filter((p) => !p.id.startsWith("fill_"));

      for (const p of homeSquadToUpdate) {
        const currentOverall = (p.ratings as any)?.overall ?? 50;
        const nextOverall = Math.max(1, Math.min(99, currentOverall + Math.round(ratingShift)));
        await tx.sportPlayer.update({
          where: { id: p.id },
          data: { ratings: { ...(p.ratings as any), overall: nextOverall } },
        });
      }

      for (const p of awaySquadToUpdate) {
        const currentOverall = (p.ratings as any)?.overall ?? 50;
        const nextOverall = Math.max(1, Math.min(99, currentOverall - Math.round(ratingShift)));
        await tx.sportPlayer.update({
          where: { id: p.id },
          data: { ratings: { ...(p.ratings as any), overall: nextOverall } },
        });
      }

      if (isFinal) {
        const champName = winnerId === homeId ? homeName : awayName;
        const runnerUpName = winnerId === homeId ? awayName : homeName;
        const champScore = winnerId === homeId ? result.homeScore : result.awayScore;
        const runnerUpScore = winnerId === homeId ? result.awayScore : result.homeScore;

        const { getSportsNotifyConfig } = await import("./notify-config");
        const notify = await getSportsNotifyConfig(tx);
        const sportsAccount = notify.seasonBulletins
          ? await tx.thinkpagesAccount.findUnique({ where: { username: "SportsNews" } })
          : null;

        if (sportsAccount) {
          const post = await tx.thinkpagesPost.create({
            data: {
              accountId: sportsAccount.id,
              content: `🏆 WAFF World Cup Final: ${champName} humbles ${runnerUpName} ${champScore}-${runnerUpScore}! ${champName} wins the World Cup! #WorldCup`,
              isAutoGenerated: true,
              ixTimeTimestamp: new Date(), // real-world time so bulletins stay chronological in the feed
            },
          });

          if (notify.discordMirror) {
            try {
              const { mirrorThinkPagesPostToDiscordFeed } =
                await import("~/lib/discord/thinkpages-feed");
              await mirrorThinkPagesPostToDiscordFeed(tx, post.id);
            } catch (mirrorErr) {
              console.error("[World Cup Final bulletin] Failed to mirror to Discord:", mirrorErr);
            }
          }
        }

        // Trophy card minting
        const champTeams = await tx.sportTeam.findMany({
          where: { nationId: winnerId, NOT: { ownerUserId: null } },
          select: { ownerUserId: true },
        });
        const winningManagerUserId = champTeams[0]?.ownerUserId;
        if (winningManagerUserId) {
          try {
            const cardTitle = `${champName} World Cup Season ${seasonNumber} Champions`;
            const cardDescription = `Commemorative trophy card awarded for winning the WAFF World Cup in Season ${seasonNumber}.`;

            let cardTemplate = await tx.card.findFirst({
              where: { title: cardTitle },
            });
            if (!cardTemplate) {
              cardTemplate = await tx.card.create({
                data: {
                  title: cardTitle,
                  description: cardDescription,
                  artwork: "https://ixwiki.com/worldcup-trophy.png",
                  rarity: "LEGENDARY",
                  cardType: "SPECIAL",
                  season: seasonNumber,
                  stats: { champion: 100, worldcup: 1 },
                  totalSupply: 1,
                  marketValue: 1000.0,
                },
              });
            }

            await tx.cardOwnership.create({
              data: {
                id: `wc_trophy_${Date.now()}`,
                userId: winningManagerUserId,
                ownerId: winningManagerUserId,
                cardId: cardTemplate.id,
                serialNumber: 1,
                quantity: 1,
                level: 1,
                experience: 0,
                isLocked: true,
                acquiredAt: new Date(),
                createdAt: new Date(),
                updatedAt: new Date(),
              },
            });
          } catch (mintErr) {
            console.error("[World Cup Trophy Minting Error]", mintErr);
          }
        }
      }
    }
    currentRoundNations = nextRoundNations;
    roundNumber++;
  }
}

export async function transitionToNextStage(prisma: Prisma, seasonId: string): Promise<boolean> {
  const season = await prisma.sportSeason.findUnique({
    where: { id: seasonId },
    include: {
      league: true,
    },
  });

  if (!season) {
    return false;
  }

  const settings = (season.league.settings ?? {}) as any;
  const stages = settings.stages;
  if (!stages || !Array.isArray(stages)) {
    return false; // No stages configuration
  }

  const currentStageId = (season as any).activeStage ?? 1;
  const nextStage = stages.find((s: any) => s.id === currentStageId + 1);
  if (!nextStage) {
    return false; // No next stage, meaning the season is done
  }

  // Get standings from the current stage to determine qualifiers
  const standings = await prisma.sportStanding.findMany({
    where: { seasonId },
    orderBy: [{ points: "desc" }, { pointsFor: "desc" }],
  });

  if (standings.length === 0) {
    return false;
  }

  // Determine qualified team IDs
  let qualifiedTeamIds: string[] = [];

  // Group stage crossing logic vs standard top-K
  const hasDivisions = standings.some((s: any) => s.division);
  if (hasDivisions) {
    // Group stage crossing
    const divisionGroups: Record<string, any[]> = {};
    for (const s of standings) {
      const div = s.division || "Default Group";
      if (!divisionGroups[div]) {
        divisionGroups[div] = [];
      }
      divisionGroups[div].push(s);
    }

    const sortedDivs = Object.keys(divisionGroups).sort();
    const divisionWinners: Record<string, string[]> = {};
    for (const div of sortedDivs) {
      const sorted = [...divisionGroups[div]].sort(
        (a, b) => b.points - a.points || b.pointsFor - a.pointsFor
      );
      divisionWinners[div] = [sorted[0]?.teamId, sorted[1]?.teamId].filter(Boolean);
    }

    // Pair divisions: Sorted alphabetically, pair adjacent ones (e.g. A1 vs B2, B1 vs A2)
    const pairings: Array<[string, string]> = [];
    for (let i = 0; i < sortedDivs.length; i += 2) {
      if (i + 1 < sortedDivs.length) {
        const d1 = sortedDivs[i];
        const d2 = sortedDivs[i + 1];
        const d1_1 = divisionWinners[d1]?.[0];
        const d1_2 = divisionWinners[d1]?.[1];
        const d2_1 = divisionWinners[d2]?.[0];
        const d2_2 = divisionWinners[d2]?.[1];
        if (d1_1 && d2_2) pairings.push([d1_1, d2_2]);
        if (d2_1 && d1_2) pairings.push([d2_1, d1_2]);
      }
    }

    // Create brackets in DB for the pairings
    if (nextStage.type === "bracket" || nextStage.type === "golden_box") {
      const ixNow = IxTime.getCurrentIxTime();
      for (let i = 0; i < pairings.length; i++) {
        const [team1Id, team2Id] = pairings[i];
        await prisma.sportBracket.create({
          data: {
            seasonId,
            round: 1,
            fighter1Id: team1Id,
            fighter2Id: team2Id,
            stage: nextStage.id,
            status: "scheduled",
            scheduledIxTime: ixNow + (i + 1) * 3600000,
          } as any,
        });
      }
    }
  } else {
    // Standard top-K qualifiers (e.g. top 4 for Golden Box)
    const teamsCount = nextStage.teams || 4;
    qualifiedTeamIds = standings.map((s: any) => s.teamId).slice(0, teamsCount);

    if (nextStage.type === "bracket" || nextStage.type === "golden_box") {
      // Create bracket pairs: 1 vs 4, 2 vs 3, etc.
      const pairings: Array<[string, string]> = [];
      if (qualifiedTeamIds.length >= 4) {
        pairings.push([qualifiedTeamIds[0], qualifiedTeamIds[3]]);
        pairings.push([qualifiedTeamIds[1], qualifiedTeamIds[2]]);
      } else if (qualifiedTeamIds.length >= 2) {
        pairings.push([qualifiedTeamIds[0], qualifiedTeamIds[1]]);
      }

      const ixNow = IxTime.getCurrentIxTime();
      for (let i = 0; i < pairings.length; i++) {
        const [team1Id, team2Id] = pairings[i];
        await prisma.sportBracket.create({
          data: {
            seasonId,
            round: 1,
            fighter1Id: team1Id,
            fighter2Id: team2Id,
            stage: nextStage.id,
            status: "scheduled",
            scheduledIxTime: ixNow + (i + 1) * 3600000,
          } as any,
        });
      }
    } else if (nextStage.type === "league" || nextStage.type === "round_robin") {
      // Create round robin schedule matches for qualified teams
      const ixNow = IxTime.getCurrentIxTime();
      const fixtures: Array<{ homeTeamId: string; awayTeamId: string; matchDay: number }> = [];
      const n = qualifiedTeamIds.length;
      let matchDay = 1;
      for (let r = 0; r < n - 1; r++) {
        for (let i = 0; i < n / 2; i++) {
          const home = (r + i) % (n - 1);
          let away = (n - 1 - i + r) % (n - 1);
          if (i === 0) away = n - 1;

          fixtures.push({
            homeTeamId: qualifiedTeamIds[home],
            awayTeamId: qualifiedTeamIds[away],
            matchDay,
          });
        }
        matchDay++;
      }

      for (const fix of fixtures) {
        await prisma.sportMatch.create({
          data: {
            seasonId,
            matchDay: fix.matchDay,
            homeTeamId: fix.homeTeamId,
            awayTeamId: fix.awayTeamId,
            stage: nextStage.id,
            status: "scheduled",
            scheduledIxTime: ixNow + fix.matchDay * 86400000,
          } as any,
        });
      }
    }
  }

  // Update activeStage in DB
  await prisma.sportSeason.update({
    where: { id: seasonId },
    data: {
      activeStage: nextStage.id,
    } as any,
  });

  return true;
}
