import { z } from "zod";
import type { PrismaClient } from "@prisma/client";
import { createTRPCRouter, publicProcedure } from "~/server/api/trpc";
import { getRecentChanges as getWikiBridgeRecentChanges } from "~/lib/wiki-os/adapters/mediawiki/bridge";
import { getForumTrendingThreads } from "~/server/modules/forum";
import { TRENDING_CONFIG, topicRank } from "~/lib/thinkpages/trending";

type TrendingItem = {
  id: string;
  title: string;
  source: "thinkpages" | "forum" | "wiki" | "ixstats" | "crisis";
  score: number;
  engagement: { views: number; replies: number; likes: number; reposts: number };
  author?: string;
  url?: string;
  excerpt?: string;
  timestamp: string;
  isNew?: boolean;
};

const HOUR_MS = 60 * 60 * 1000;
const NO_ENGAGEMENT = { views: 0, replies: 0, likes: 0, reposts: 0 };

/** Time decay: content from 0h ago = 1.0x, 48h ago = 0.1x */
function timeDecay(ts: Date | string, now: number) {
  const time = new Date(ts).getTime();
  return Math.max(0.1, 1 - (now - (isNaN(time) ? now : time)) / (48 * HOUR_MS));
}

/** One failing source must not take the others down. */
async function collect(label: string, load: () => Promise<TrendingItem[]>) {
  try {
    return await load();
  } catch (error) {
    console.error(`[UnifiedTrending] ${label} failed:`, error);
    return [];
  }
}

const SPORTS_BULLETIN = /<!--\s*sports-bulletin:([\s\S]*?)-->/i;

interface SportsBulletin {
  sportEmoji?: string;
  league?: { id?: string; name?: string };
  isChampionBulletin?: boolean;
  isPlayoffBulletin?: boolean;
  championName?: string;
  championId?: string;
  roundName?: string;
  matchDay?: number;
  llmSummary?: string;
}

/** Title, excerpt and link for a bulletin embedded in a ThinkPages post. */
function describeBulletin(data: SportsBulletin, fallbackUrl: string) {
  const emoji = data.sportEmoji || "⚽";
  const leagueName = data.league?.name || "League";
  const leagueUrl = data.league?.id ? `/myleague/${data.league.id}` : fallbackUrl;
  const summary = (fallback: string) =>
    data.llmSummary ? data.llmSummary.slice(0, 95) + "..." : fallback;
  if (data.isChampionBulletin) {
    return {
      title: `${emoji} ${leagueName} Champion Crowned!`,
      excerpt: `Congratulations to ${data.championName || "the champions"}!`,
      url: data.championId ? `/myclub/${data.championId}` : fallbackUrl,
    };
  }
  if (data.isPlayoffBulletin) {
    return {
      title: `${emoji} ${leagueName} ${data.roundName || "Playoff"}`,
      excerpt: summary("Playoff round results and highlights"),
      url: leagueUrl,
    };
  }
  return {
    title: `${emoji} ${leagueName} ${data.matchDay ? `— Matchday ${data.matchDay}` : ""}`,
    excerpt: summary("Latest matchday results and table movers"),
    url: leagueUrl,
  };
}

type TrendingPost = {
  id: string;
  content: string;
  account: { username: string; displayName: string | null } | null;
};

function describePost(post: TrendingPost) {
  const cleanContent = post.content.replace(/<!--\s*sports-bulletin:[\s\S]*?-->/gi, "").trim();
  const previewText = cleanContent || "Sports News Bulletin";
  const url = `/thinkpages/post/${post.id}`;
  const excerpt = previewText.length > 100 ? previewText.slice(0, 97) + "..." : previewText;
  const username = post.account?.username;
  const bulletin = post.content.match(SPORTS_BULLETIN)?.[1];

  if (bulletin) {
    try {
      return describeBulletin(JSON.parse(bulletin.trim()) as SportsBulletin, url);
    } catch {
      return { title: `⚽ ${post.account?.displayName || "Sports News"}`, excerpt, url };
    }
  }
  const firstLine = username === "SportsNews" ? cleanContent.split("\n")[0] || "" : null;
  const title =
    firstLine === null
      ? `@${username ?? "unknown"}`
      : firstLine
        ? firstLine.replace(/\*\*/g, "").slice(0, 40)
        : "⚽ Sports Bulletin";
  return { title, excerpt, url };
}

async function thinkpagesItems(db: PrismaClient): Promise<TrendingItem[]> {
  // Scored by the thinkpages-trending cron (engagement-decay over real reactions, replies,
  // reposts and daily distinct views); posts with no engagement from other users do not appear.
  const posts = await db.thinkpagesPost.findMany({
    where: { visibility: "public", trendingScore: { gt: 0 } },
    orderBy: { trendingScore: "desc" },
    take: 30,
    include: { account: { select: { username: true, displayName: true, verified: true } } },
  });
  return posts.map((post): TrendingItem => ({
    id: `tp-${post.id}`,
    ...describePost(post),
    source: "thinkpages",
    score: post.trendingScore,
    engagement: {
      views: post.impressions,
      replies: post.replyCount,
      likes: post.likeCount,
      reposts: post.repostCount,
    },
    author: post.account?.displayName ?? post.account?.username,
    timestamp: (post.isAutoGenerated ? post.ixTimeTimestamp : post.createdAt).toISOString(),
  }));
}

async function forumItems(now: number): Promise<TrendingItem[]> {
  const threads = await getForumTrendingThreads(25);
  return threads.map((thread): TrendingItem => ({
    id: `forum-${thread.threadId}`,
    title: thread.title,
    source: "forum",
    // Views are significant, replies = comments
    score: (thread.replyCount * 2 + thread.viewCount * 0.05) * timeDecay(thread.timestamp, now),
    engagement: { ...NO_ENGAGEMENT, views: thread.viewCount, replies: thread.replyCount },
    author: thread.author,
    url: thread.url,
    timestamp: thread.timestamp.toISOString(),
  }));
}

const plural = (n: number, word: string) => `${n} ${word}${n > 1 ? "s" : ""}`;

async function wikiItems(now: number): Promise<TrendingItem[]> {
  // Trending pages from recent changes, aggregated by title
  const pageMap = new Map<
    string,
    {
      title: string;
      editCount: number;
      editors: Set<string>;
      totalBytesChanged: number;
      isNew: boolean;
      latestEdit: Date;
    }
  >();
  for (const rc of await getWikiBridgeRecentChanges(100)) {
    const editDate = new Date(rc.timestamp);
    const validDate = isNaN(editDate.getTime()) ? new Date() : editDate;
    const page = pageMap.get(rc.title) ?? {
      title: rc.title,
      editCount: 0,
      editors: new Set<string>(),
      totalBytesChanged: 0,
      isNew: false,
      latestEdit: validDate,
    };
    page.editCount++;
    page.editors.add(rc.user);
    page.totalBytesChanged += Math.abs(rc.newLen - rc.oldLen);
    page.isNew ||= rc.type === "new";
    if (validDate > page.latestEdit) page.latestEdit = validDate;
    pageMap.set(rc.title, page);
  }
  return [...pageMap.values()]
    .sort((a, b) => b.editCount - a.editCount)
    .slice(0, 25)
    .map((page): TrendingItem => {
      const editors = page.editors.size;
      // Edits = activity signal, multiple editors = collaborative interest, byte changes proxy
      // for content depth; new pages get a bonus
      const raw =
        page.editCount * 5 +
        editors * 10 +
        Math.min(page.totalBytesChanged / 500, 20) +
        (page.isNew ? 15 : 0);
      const activity = `${plural(page.editCount, "edit")} by ${plural(editors, "editor")}`;
      return {
        id: `wiki-${page.title}`,
        title: page.title,
        source: "wiki",
        score: raw * timeDecay(page.latestEdit, now),
        engagement: NO_ENGAGEMENT,
        url: `/wiki/${encodeURIComponent(page.title.replace(/ /g, "_"))}`,
        excerpt: page.isNew
          ? `New page — ${activity}`
          : `${activity} (${page.totalBytesChanged > 0 ? "+" : ""}${page.totalBytesChanged} bytes)`,
        timestamp: page.latestEdit.toISOString(),
        isNew: page.isNew,
      };
    });
}

const ACTIVITY_BASE_SCORE: Record<string, number> = {
  diplomatic: 25,
  economic: 20,
  achievement: 15,
  meta: 10,
};

async function activityItems(db: PrismaClient, now: number): Promise<TrendingItem[]> {
  const activities = await db.activityFeed.findMany({
    where: { createdAt: { gte: new Date(now - 48 * HOUR_MS) }, visibility: "public" },
    // Activity rows have no view tracking (only ThinkPages posts do), so take the newest.
    orderBy: { createdAt: "desc" },
    take: 40,
    select: {
      id: true,
      title: true,
      type: true,
      likes: true,
      comments: true,
      shares: true,
      views: true,
      createdAt: true,
    },
  });
  return activities.map((a): TrendingItem => {
    const raw =
      (ACTIVITY_BASE_SCORE[a.type] ?? 5) + a.shares * 3 + a.comments * 2 + a.likes + a.views * 0.01;
    return {
      id: `ix-${a.id}`,
      title: a.title,
      source: "ixstats",
      score: raw * timeDecay(a.createdAt, now),
      engagement: { views: a.views, replies: a.comments, likes: a.likes, reposts: a.shares },
      timestamp: a.createdAt.toISOString(),
    };
  });
}

const CRISIS_BASE_SCORE: Record<string, number> = { critical: 60, high: 45, medium: 30 };

async function crisisItems(db: PrismaClient, now: number): Promise<TrendingItem[]> {
  const crises = await db.crisisEvent.findMany({
    where: { responseStatus: { in: ["pending", "in_progress", "monitoring"] } },
    orderBy: [{ severity: "desc" }, { timestamp: "desc" }],
    take: 10,
  });
  return crises.map((crisis): TrendingItem => ({
    id: `crisis-${crisis.id}`,
    title: crisis.title,
    source: "crisis",
    score:
      (CRISIS_BASE_SCORE[crisis.severity] ?? 20) * Math.max(0.4, timeDecay(crisis.timestamp, now)),
    engagement: { ...NO_ENGAGEMENT, views: crisis.casualties ?? 0 },
    excerpt: crisis.description ?? "Active international crisis requiring resolution.",
    timestamp: crisis.timestamp.toISOString(),
  }));
}

export const activitiesTrendingRouter = createTRPCRouter({
  /**
   * Trending hashtags, as written to `TrendingTopic` by the thinkpages-trending cron job over
   * its engagement window. Empty when nothing qualifies (no fallback content).
   */
  getTrendingTopics: publicProcedure
    .input(
      z
        .object({
          limit: z.number().min(1).max(10).default(5),
        })
        .default({ limit: 5 })
    )
    .query(async ({ ctx, input }) => {
      try {
        const rows = await ctx.db.trendingTopic.findMany({
          where: { isActive: true },
          select: {
            id: true,
            hashtag: true,
            postCount: true,
            engagement: true,
            peakTimestamp: true,
          },
          take: TRENDING_CONFIG.maxTopics,
        });
        const risingSince = Date.now() - TRENDING_CONFIG.risingHours * 60 * 60 * 1000;
        return (rows ?? [])
          .sort((a, b) => topicRank(b) - topicRank(a) || a.hashtag.localeCompare(b.hashtag))
          .slice(0, input.limit)
          .map((topic) => ({
            id: topic.id,
            hashtag: topic.hashtag,
            title: `#${topic.hashtag}`,
            category: "Hashtag",
            postCount: topic.postCount,
            engagement: topic.engagement,
            // "up" while the topic hit a new high recently; otherwise holding steady.
            trend: (topic.peakTimestamp.getTime() >= risingSince ? "up" : "steady") as
              "up" | "steady",
          }));
      } catch (error) {
        console.error("Error fetching trending topics:", error);
        return [];
      }
    }),

  /**
   * Unified trending — cross-platform trending topics scored by engagement.
   * Aggregates: ThinkPages posts, forum threads, wiki page activity, IxStats activities.
   * Scoring: weighted engagement with time decay (newer content ranks higher).
   */
  getUnifiedTrending: publicProcedure
    .input(z.object({ limit: z.number().min(1).max(100).default(50) }))
    .query(async ({ ctx, input }) => {
      const now = Date.now();
      const sources = await Promise.all([
        collect("ThinkPages", () => thinkpagesItems(ctx.db)),
        collect("Forum", () => forumItems(now)),
        collect("Wiki", () => wikiItems(now)),
        collect("IxStats activities", () => activityItems(ctx.db, now)),
        collect("Crisis events", () => crisisItems(ctx.db, now)),
      ]);
      const items = sources.flat().sort((a, b) => b.score - a.score);
      return { items: items.slice(0, input.limit), generatedAt: new Date().toISOString() };
    }),
});
